import type {CapabilityDescriptor,JsonSchema} from '../../app-contracts/src/index.ts';
import {DATASET_BINDING_SCHEMA,SOURCE_CONTEXT_SCHEMA,SOURCE_REFS_SCHEMA} from './source-binding-schema.ts';
const string:JsonSchema={type:'string',minLength:1},integer:JsonSchema={type:'integer',minimum:1},hash:JsonSchema={type:'string',pattern:'^[a-f0-9]{64}$'},date:JsonSchema={type:'string',format:'date-time'},nullableString:JsonSchema={type:['string','null']};
const object=(properties:Record<string,JsonSchema>,required=Object.keys(properties),additionalProperties=false):JsonSchema=>({type:'object',properties,required,additionalProperties});
const array=(items:JsonSchema):JsonSchema=>({type:'array',items});
export const AUTHORING_FILE_SCHEMA=object({path:string,sha256:hash,bytes:{type:'integer',minimum:0}});
export const AUTHORING_ASSERTION_SCHEMA=object({id:string,required:{type:'boolean'},expected:string,actual:nullableString,status:{enum:['PASS','FAIL','NOT_RUN','BLOCKED']},evidenceRefs:array(AUTHORING_FILE_SCHEMA)});
const buildProperties={schemaVersion:{const:1},receiptId:string,attemptId:string,sourceRevision:integer,sourceInputDigest:hash,lockfileDigest:hash,command:{type:'array',minItems:1,items:string},cwd:string,toolchain:{type:'object',minProperties:1,additionalProperties:{type:'string'}},exitCode:{type:'integer'},startedAt:date,finishedAt:date,logRef:AUTHORING_FILE_SCHEMA,distDigest:{anyOf:[hash,{type:'null'}]},archiveBuildId:{anyOf:[hash,{type:'null'}]},fileManifestRef:{anyOf:[AUTHORING_FILE_SCHEMA,{type:'null'}]},inputUnchanged:{type:'boolean'},verdict:{enum:['PASS','FAIL']}} satisfies Record<string,JsonSchema>;
/** Equivalent to the A.2 template's conditional PASS gate; the local compiler supports oneOf. */
export const AUTHORING_BUILD_RECEIPT_SCHEMA:JsonSchema={oneOf:[object({...buildProperties,verdict:{const:'PASS'},exitCode:{const:0},inputUnchanged:{const:true},distDigest:hash,archiveBuildId:hash,fileManifestRef:AUTHORING_FILE_SCHEMA}),object({...buildProperties,verdict:{const:'FAIL'}})]};
const viewportProperties={id:string,contentWidthCssPx:integer,heightCssPx:integer,deviceScaleFactor:{type:'number',exclusiveMinimum:0},screenshot:AUTHORING_FILE_SCHEMA,pageErrors:array(string),unhandledRejections:array(string),failedRequests:array(string),bridgeReady:{type:'boolean'},assertionIds:array(string)} satisfies Record<string,JsonSchema>;
const previewProperties={schemaVersion:{const:1},receiptId:string,attemptId:string,buildReceiptId:string,buildId:hash,protocol:{const:'dsh.apps.component.v2'},mode:{enum:['fixture','live_readonly']},runnerVersion:string,startedAt:date,finishedAt:date,viewportResults:{type:'array',minItems:1,items:object(viewportProperties)},assertionResults:{type:'array',minItems:1,items:AUTHORING_ASSERTION_SCHEMA},verdict:{enum:['PASS','FAIL','INCOMPLETE']}} satisfies Record<string,JsonSchema>;
const requiredPassAssertion:JsonSchema={oneOf:[object({...(AUTHORING_ASSERTION_SCHEMA.properties as Record<string,JsonSchema>),required:{const:true},status:{const:'PASS'}}),object({...(AUTHORING_ASSERTION_SCHEMA.properties as Record<string,JsonSchema>),required:{const:false}})]};
export const AUTHORING_PREVIEW_RECEIPT_SCHEMA:JsonSchema={oneOf:[object({...previewProperties,verdict:{const:'PASS'},viewportResults:{type:'array',minItems:2,items:object({...viewportProperties,pageErrors:{type:'array',maxItems:0,items:string},unhandledRejections:{type:'array',maxItems:0,items:string},bridgeReady:{const:true}})},assertionResults:{type:'array',minItems:1,items:requiredPassAssertion}}),object({...previewProperties,verdict:{enum:['FAIL','INCOMPLETE']}})]};
const state:JsonSchema={enum:['editing','building','build_failed','previewing','preview_failed','publish_ready','mounting','mounted','failed_mount','cancelled','superseded','interrupted']};
const draft=object({schemaVersion:{const:1},draftId:string,ownerSessionId:string,viewId:string,workspacePath:string,sourceRevision:integer,epoch:integer,status:{enum:[...(state.enum as string[]),'closed','discarded']},createdAt:date,updatedAt:date,sourceComponentId:string,selectedSourceRevision:integer,baseRevisionAtOpen:integer},['schemaVersion','draftId','ownerSessionId','viewId','workspacePath','sourceRevision','epoch','status','createdAt','updatedAt']);
const attempt=object({attemptId:string,draftId:string,epoch:integer,sourceRevision:integer,state,startedAt:date,expectedViewRevision:integer,invocationRefs:array(string),evidenceRefs:array(AUTHORING_FILE_SCHEMA),terminalReason:nullableString,buildReceiptId:string,previewReceiptId:string,publicationId:string,requestHash:hash},['attemptId','draftId','epoch','sourceRevision','state','startedAt','expectedViewRevision','invocationRefs','evidenceRefs','terminalReason']);
const source=object({buildId:hash,directory:string,entry:string,files:array(string)},['buildId','directory','entry','files'],true);
const view=object({viewId:string,ownerSessionId:nullableString,title:string,design:{},bindings:array(DATASET_BINDING_SCHEMA),sourceRefs:SOURCE_REFS_SCHEMA,context:SOURCE_CONTEXT_SCHEMA,source,createdAt:date,updatedAt:date,sourceComponentId:string,baseRevision:integer,viewRevision:integer,activeBuildId:nullableString,lastGoodBuildId:nullableString,previousGoodBuildId:nullableString,pendingPublicationId:nullableString,validationStatus:{enum:['draft_unpublished','legacy_unverified','verified']}},['viewId','ownerSessionId','title','design','bindings','createdAt','updatedAt','viewRevision','activeBuildId','lastGoodBuildId','previousGoodBuildId','pendingPublicationId','validationStatus'],true);
export const AUTHORING_PUBLICATION_SCHEMA=object({publicationId:string,viewId:string,ownerSessionId:string,attemptId:string,attemptEpoch:integer,expectedViewRevision:integer,candidateBuildId:hash,priorActiveBuildId:nullableString,state:{enum:['prepared','mounting','mounted','failed_mount','cancelled','superseded','interrupted']},readyDeadlineAt:{type:['string','null'],format:'date-time'},mountStartedAt:{type:['string','null'],format:'date-time'},evidenceRefs:array(AUTHORING_FILE_SCHEMA),createdAt:date,updatedAt:date,buildReceiptId:string,previewReceiptId:string,source,frameInstanceId:string,documentNonce:string,committedViewRevision:integer,terminalReason:string},['publicationId','viewId','ownerSessionId','attemptId','attemptEpoch','expectedViewRevision','candidateBuildId','priorActiveBuildId','state','readyDeadlineAt','evidenceRefs','createdAt','updatedAt','buildReceiptId','previewReceiptId','source']);
export const AUTHORING_DISPLAY_SCHEMA=object({displayId:string,generation:integer,ownerSessionId:string,viewId:string,publicationId:string,attemptId:string,attemptEpoch:integer,buildId:hash,expectedViewRevision:integer,state:{enum:['opening','ready','failed','retired']},view,errors:array(object({phase:{type:'string',minLength:1,maxLength:80},code:{type:'string',minLength:1,maxLength:160},message:{type:'string',minLength:1,maxLength:4096},at:date},['phase','code','message'])),createdAt:date,updatedAt:date,readyAt:date,frameInstanceId:string,documentNonce:string},['displayId','generation','ownerSessionId','viewId','publicationId','attemptId','attemptEpoch','buildId','expectedViewRevision','state','view','errors','createdAt','updatedAt']);
const beginProperties={mode:{enum:['new','edit','open_saved']},viewId:string,componentId:string,revision:integer,workspacePath:string,newCopy:{type:'boolean'},title:string,bindings:array(DATASET_BINDING_SCHEMA),sourceRefs:SOURCE_REFS_SCHEMA,context:SOURCE_CONTEXT_SCHEMA,invocationId:string,attemptId:string} satisfies Record<string,JsonSchema>;
const begin:JsonSchema={oneOf:[object({...beginProperties,mode:{const:'new'}},['mode']),object({...beginProperties,mode:{const:'edit'}},['mode','viewId']),object({...beginProperties,mode:{const:'open_saved'}},['mode','componentId'])]};
const attemptProperties={attemptId:string,epoch:integer};
const saveProperties={viewId:string,expectedViewRevision:integer,userRequest:string,mode:{enum:['save_as','update']},componentId:string,expectedRevision:integer,title:string} satisfies Record<string,JsonSchema>;
const {componentId:_componentId,expectedRevision:_expectedRevision,...saveAsProperties}=saveProperties;
const inspectSummary=object({lastConfirmedDisplay:{type:['object','null']},preparedBuild:{type:['object','null']},currentDisplay:{type:['object','null']},blockedStage:string,nextAction:object({action:string,reason:string,target:{type:'object'},errorCodes:array(string)}),requiresRebuild:{type:['boolean','null']}});
const definitions:{name:string;input:JsonSchema;output:JsonSchema;query?:boolean;mutation?:boolean}[]=[
  {name:'begin',input:begin,output:object({draft,attempt,view})},
  {name:'record_build',input:object({...attemptProperties,reportRef:AUTHORING_FILE_SCHEMA}),output:AUTHORING_BUILD_RECEIPT_SCHEMA},
  {name:'record_preview',input:object({...attemptProperties,buildReceiptId:string,reportRef:AUTHORING_FILE_SCHEMA}),output:AUTHORING_PREVIEW_RECEIPT_SCHEMA},
  {name:'publish',input:object({...attemptProperties,viewId:string,expectedViewRevision:integer,buildId:hash,buildReceiptId:string,previewReceiptId:string,publicationId:string},['attemptId','epoch','viewId','expectedViewRevision','buildId','buildReceiptId','previewReceiptId']),output:AUTHORING_PUBLICATION_SCHEMA},
  {name:'inspect',query:true,input:{oneOf:[object({attemptId:string,displayId:string},['attemptId']),object({publicationId:string,displayId:string},['publicationId'])]},output:object({summary:inspectSummary,draft,attempt,publication:{anyOf:[AUTHORING_PUBLICATION_SCHEMA,{type:'null'}]},view,latestDisplay:{anyOf:[AUTHORING_DISPLAY_SCHEMA,{type:'null'}]},displays:array(AUTHORING_DISPLAY_SCHEMA),display:AUTHORING_DISPLAY_SCHEMA,workspaceAvailable:{type:'boolean'},missingEvidence:array(string)},['summary','draft','attempt','publication','view','latestDisplay','displays','workspaceAvailable','missingEvidence'])},
  {name:'cancel',input:object({attemptId:string,expectedEpoch:integer,reason:string}),output:object({status:{enum:['cancelled','already_published']},activeBuildId:nullableString,viewRevision:integer,publication:AUTHORING_PUBLICATION_SCHEMA},['status','activeBuildId','viewRevision'])},
  {name:'save_component',mutation:true,input:{oneOf:[object({...saveAsProperties,mode:{const:'save_as'}},['viewId','expectedViewRevision','userRequest','mode']),object({...saveProperties,mode:{const:'update'}},['viewId','expectedViewRevision','userRequest','mode','componentId','expectedRevision'])]},output:object({componentId:string,revision:integer,title:string,view:{type:'object'},userRequest:string,savedAt:date},['componentId','revision','title','view','userRequest','savedAt'],true)},
];
export const APP_AUTHORING_DESCRIPTORS:readonly CapabilityDescriptor[]=definitions.map(item=>({capabilityId:`apps.authoring.${item.name}`,version:'1.0.0',title:item.name,description:item.mutation?'Explicitly save a confirmed authoring view using component/view CAS and the existing idempotent mutation ledger.':'Versioned local authoring metadata. Candidates, mounting, confirmed display and explicit saved assets are distinct; this action owns no domain mutation or another Agent loop.',effect:item.mutation?'mutation':item.query?'query':'compute',inputSchema:item.input,outputSchema:item.output,execution:{mode:'sync',timeoutMs:30000,concurrency:item.mutation?'exclusive':'declared_safe',lockScope:'connection',idempotency:item.mutation?'runtime_dedup':'not_applicable',completionEvidence:'response'},discovery:{defaultVisible:false,keywords:['authoring','component','source','receipt']},aliases:[]}));
