import type {CapabilityDescriptor,JsonSchema} from '../../app-contracts/src/index.ts';
import {DATASET_BINDING_SCHEMA,SOURCE_CONTEXT_SCHEMA,SOURCE_REFS_SCHEMA,SOURCE_REF_SCHEMA} from './source-binding-schema.ts';
import {DATA_SOURCE_DRAFT_SCHEMA,DATA_SOURCE_SCHEMA,DATA_SOURCE_VALIDATION_SCHEMA} from './data-sources.ts';
const string:JsonSchema={type:'string',minLength:1},integer:JsonSchema={type:'integer',minimum:1};
const binding=DATASET_BINDING_SCHEMA;
const bindings:JsonSchema={type:'array',items:binding};
// Historical field labels and query spelling are presentation metadata only.
const legacyBinding:JsonSchema={type:'object',properties:{id:string,datasetKey:string,fieldMap:{type:'object',additionalProperties:{type:'string'}},query:{type:'object',properties:{tool:string,params:{type:'object'}},required:['tool','params'],additionalProperties:false}},required:['id','fieldMap'],additionalProperties:false};
const source:JsonSchema={type:'object',properties:{buildId:string,directory:string,entry:string,files:{type:'array',items:string},thumbnail:string,preview:{type:'object',properties:{screenshotPath:string,reportPath:string,width:{type:'number'},height:{type:'number'},capturedAt:string},required:['screenshotPath','reportPath'],additionalProperties:false}},required:['buildId','directory','entry','files'],additionalProperties:false};
const view:JsonSchema={type:'object',properties:{viewId:string,ownerSessionId:{type:['string','null']},title:string,design:{},bindings,sourceRefs:SOURCE_REFS_SCHEMA,context:SOURCE_CONTEXT_SCHEMA,source,createdAt:string,updatedAt:string,panelState:{enum:['open','closed']},closedAt:string,sourceComponentId:string,baseRevision:integer,baseRevisionAtOpen:integer,selectedSourceRevision:integer,viewRevision:integer,activeBuildId:{type:['string','null']},lastGoodBuildId:{type:['string','null']},previousGoodBuildId:{type:['string','null']},pendingPublicationId:{type:['string','null']},validationStatus:{enum:['draft_unpublished','legacy_unverified','verified','failed']},initialData:{type:'array',items:{type:'object',properties:{bindingId:string,datasetId:string,status:{enum:['ready','failed','unavailable','empty']}},required:['bindingId','datasetId','status'],additionalProperties:false}}},required:['viewId','ownerSessionId','title','design','bindings','createdAt','updatedAt'],additionalProperties:false};
const component:JsonSchema={type:'object',properties:{componentId:string,revision:integer,title:string,view,userRequest:string,savedAt:string,legacyTemplate:{},revisions:{type:'array',items:{type:'object',properties:{revision:integer,title:string,savedAt:string,buildId:string},required:['revision','title','savedAt'],additionalProperties:false}}},required:['componentId','revision','title','view','userRequest','savedAt'],additionalProperties:false};
const entry:JsonSchema={type:'object',properties:{assetId:string,kind:{const:'entry'},entryKind:{enum:['data','component']},componentId:string,title:string,binding,legacyBinding,legacyFieldOrder:{type:'array',items:string},userRequest:string,pinned:{type:'boolean'},order:{type:'integer'}},required:['assetId','kind','title','userRequest','pinned','order'],oneOf:[{required:['binding']},{required:['componentId']}],additionalProperties:false};
const template:JsonSchema={type:'object',properties:{assetId:string,kind:{const:'template'},title:string,description:{type:'string'},design:{},bindings,sourceRefs:SOURCE_REFS_SCHEMA,context:SOURCE_CONTEXT_SCHEMA,source,userRequest:string,savedAt:string},required:['assetId','kind','title','design','bindings','userRequest'],additionalProperties:false};
const outputs:Record<string,JsonSchema>={renderView:view,updateView:view,openComponent:view,openSource:view,saveComponent:component,saveEntry:entry,saveTemplate:template,listSaved:{type:'object',properties:{components:{type:'array',items:component},assets:{type:'array',items:{oneOf:[entry,template]}}},required:['components','assets'],additionalProperties:false},manageSaved:{oneOf:[component,entry,template,{type:'object',properties:{deleted:{const:true},id:string},required:['deleted','id'],additionalProperties:false}]}};
const definitions:{name:string;alias:string;effect:CapabilityDescriptor['effect'];properties:Record<string,JsonSchema>;required:string[]}[]=[
 {name:'renderView',alias:'render_view',effect:'compute',properties:{title:string,design:{},bindings,sourceRefs:SOURCE_REFS_SCHEMA,context:SOURCE_CONTEXT_SCHEMA,viewId:string,legacyViewId:string,templateId:string,directory:string,legacyBindings:{type:'array',items:legacyBinding},requiredBindingIds:{type:'array',items:string},legacyNeedsSpecification:{type:'boolean'}},required:['title']},
 {name:'updateView',alias:'update_view',effect:'compute',properties:{viewId:string,title:string,design:{},bindings,sourceRefs:SOURCE_REFS_SCHEMA,context:SOURCE_CONTEXT_SCHEMA},required:['viewId']},
 {name:'openComponent',alias:'open_component',effect:'compute',properties:{componentId:string,revision:integer,directory:string,context:SOURCE_CONTEXT_SCHEMA,newCopy:{type:'boolean'}},required:['componentId']},
 {name:'openSource',alias:'open_source_component',effect:'compute',properties:{directory:string,title:string,viewId:string,bindings,sourceRefs:SOURCE_REFS_SCHEMA,context:SOURCE_CONTEXT_SCHEMA,legacyBindings:{type:'array',items:legacyBinding}},required:['directory']},
 {name:'saveComponent',alias:'save_component',effect:'mutation',properties:{viewId:string,userRequest:string,title:string,mode:{enum:['save_as','update']},componentId:string,expectedRevision:integer,legacyComponentId:string,legacyTemplate:{}},required:['viewId','userRequest','mode']},
 {name:'saveEntry',alias:'save_entry',effect:'mutation',properties:{title:string,binding,legacyBinding,legacyFieldOrder:{type:'array',items:string},userRequest:string},required:['title','binding','userRequest']},
 {name:'saveTemplate',alias:'save_template',effect:'mutation',properties:{viewId:string,name:string,description:{type:'string'},userRequest:string},required:['viewId','name','userRequest']},
 {name:'listSaved',alias:'list_saved',effect:'query',properties:{},required:[]},
 {name:'manageSaved',alias:'manage_saved',effect:'mutation',properties:{kind:{enum:['component','entry','template']},id:string,action:{enum:['rename','delete','pin','reorder']},name:string,order:{type:'integer'},pinned:{type:'boolean'},expectedRevision:integer},required:['kind','id','action']},
];
outputs.listDataSources={type:'object',properties:{sources:{type:'array',items:DATA_SOURCE_SCHEMA}},required:['sources'],additionalProperties:false};
outputs.validateDataSource=DATA_SOURCE_VALIDATION_SCHEMA;
outputs.registerDataSource=DATA_SOURCE_SCHEMA;
outputs.resolveDataSource={type:'object',properties:{binding,sourceRef:SOURCE_REF_SCHEMA,fieldMap:{type:'object',additionalProperties:{type:'string'}},fieldMeta:{type:'object'},rowsPath:{type:'string'}},required:['binding','sourceRef','fieldMap','fieldMeta','rowsPath'],additionalProperties:false};
outputs.listMaterials={type:'object',properties:{materials:{type:'array',items:{type:'object'}},fieldRoles:{type:'array',items:{type:'object',properties:{key:string,label:string,description:string,format:{enum:['text','currency','percent','integer','datetime','image']},unit:string},required:['key','label','description','format'],additionalProperties:false}}},required:['materials','fieldRoles'],additionalProperties:false};
definitions.push(
 {name:'listMaterials',alias:'list_materials',effect:'query',properties:{},required:[]},
 {name:'listDataSources',alias:'list_data_sources',effect:'query',properties:{appId:string},required:[]},
 {name:'resolveDataSource',alias:'resolve_data_source',effect:'compute',properties:{id:string,revision:integer,bindingId:string,context:SOURCE_CONTEXT_SCHEMA,params:{type:'object'}},required:['id','revision','bindingId']},
 {name:'validateDataSource',alias:'validate_data_source',effect:'compute',properties:{definition:DATA_SOURCE_DRAFT_SCHEMA,expectedRevision:{type:'integer',minimum:0},context:SOURCE_CONTEXT_SCHEMA,params:{type:'object'}},required:['definition']},
 {name:'registerDataSource',alias:'register_data_source',effect:'mutation',properties:{definition:DATA_SOURCE_DRAFT_SCHEMA,expectedRevision:{type:'integer',minimum:0},context:SOURCE_CONTEXT_SCHEMA,params:{type:'object'}},required:['definition']},
);
export const APP_PRESENTATION_DESCRIPTORS:readonly CapabilityDescriptor[]=definitions.map(item=>({capabilityId:`apps.presentation.${item.alias}`,version:'1.0.0',title:item.name,description:`Shared component ${item.name}. Builds and drafts remain separate from explicit saved assets.`,effect:item.effect,inputSchema:{type:'object',properties:item.properties,required:item.required,additionalProperties:false},outputSchema:outputs[item.name],execution:{mode:'sync',timeoutMs:['validateDataSource','registerDataSource','renderView','openComponent','openSource'].includes(item.name)?150000:30000,concurrency:'exclusive',lockScope:'connection',idempotency:item.effect==='mutation'?'runtime_dedup':'not_applicable',completionEvidence:'response'},discovery:{defaultVisible:false,keywords:['component','presentation','source']},aliases:[`hallmark_${item.alias}`]}));
