import type {CapabilityDescriptor,JsonSchema} from '../../app-contracts/src/index.ts';
const string:JsonSchema={type:'string',minLength:1},integer:JsonSchema={type:'integer',minimum:1};
const binding:JsonSchema={type:'object',properties:{bindingId:string,appId:string,connectionId:string,capabilityId:string,capabilityMajor:integer,input:{},projection:{type:'array',items:string},datasetId:string,refresh:{type:'object',properties:{mode:{enum:['manual','scheduled']},scheduleId:string},required:['mode'],additionalProperties:false}},required:['bindingId','appId','connectionId','capabilityId','capabilityMajor','input','projection','refresh'],additionalProperties:false};
const bindings:JsonSchema={type:'array',items:binding};
// Historical field labels and query spelling are presentation metadata only.
const legacyBinding:JsonSchema={type:'object',properties:{id:string,datasetKey:string,fieldMap:{type:'object',additionalProperties:{type:'string'}},query:{type:'object',properties:{tool:string,params:{type:'object'}},required:['tool','params'],additionalProperties:false}},required:['id','fieldMap'],additionalProperties:false};
const source:JsonSchema={type:'object',properties:{buildId:string,directory:string,entry:string,files:{type:'array',items:string},thumbnail:string,preview:{type:'object',properties:{screenshotPath:string,reportPath:string,width:{type:'number'},height:{type:'number'},capturedAt:string},required:['screenshotPath','reportPath'],additionalProperties:false}},required:['buildId','directory','entry','files'],additionalProperties:false};
const view:JsonSchema={type:'object',properties:{viewId:string,ownerSessionId:{type:['string','null']},title:string,design:{},bindings,source,createdAt:string,updatedAt:string,sourceComponentId:string,baseRevision:integer,baseRevisionAtOpen:integer,selectedSourceRevision:integer,viewRevision:integer,activeBuildId:{type:['string','null']},lastGoodBuildId:{type:['string','null']},previousGoodBuildId:{type:['string','null']},pendingPublicationId:{type:['string','null']},validationStatus:{enum:['draft_unpublished','legacy_unverified','verified','failed']},initialData:{type:'array',items:{type:'object',properties:{bindingId:string,datasetId:string,status:{enum:['ready','failed','unavailable','empty']}},required:['bindingId','datasetId','status'],additionalProperties:false}}},required:['viewId','ownerSessionId','title','design','bindings','createdAt','updatedAt'],additionalProperties:false};
const component:JsonSchema={type:'object',properties:{componentId:string,revision:integer,title:string,view,userRequest:string,savedAt:string,legacyTemplate:{},revisions:{type:'array',items:{type:'object',properties:{revision:integer,title:string,savedAt:string,buildId:string},required:['revision','title','savedAt'],additionalProperties:false}}},required:['componentId','revision','title','view','userRequest','savedAt'],additionalProperties:false};
const entry:JsonSchema={type:'object',properties:{assetId:string,kind:{const:'entry'},entryKind:{enum:['data','component']},componentId:string,title:string,binding,legacyBinding,legacyFieldOrder:{type:'array',items:string},userRequest:string,pinned:{type:'boolean'},order:{type:'integer'}},required:['assetId','kind','title','userRequest','pinned','order'],oneOf:[{required:['binding']},{required:['componentId']}],additionalProperties:false};
const template:JsonSchema={type:'object',properties:{assetId:string,kind:{const:'template'},title:string,description:{type:'string'},design:{},bindings,source,userRequest:string,savedAt:string},required:['assetId','kind','title','design','bindings','userRequest'],additionalProperties:false};
const outputs:Record<string,JsonSchema>={renderView:view,updateView:view,openComponent:view,openSource:view,saveComponent:component,saveEntry:entry,saveTemplate:template,listSaved:{type:'object',properties:{components:{type:'array',items:component},assets:{type:'array',items:{oneOf:[entry,template]}}},required:['components','assets'],additionalProperties:false},manageSaved:{oneOf:[component,entry,template,{type:'object',properties:{deleted:{const:true},id:string},required:['deleted','id'],additionalProperties:false}]}};
const definitions:{name:string;alias:string;effect:CapabilityDescriptor['effect'];properties:Record<string,JsonSchema>;required:string[]}[]=[
 {name:'renderView',alias:'render_view',effect:'compute',properties:{title:string,design:{},bindings,viewId:string,legacyViewId:string,templateId:string,directory:string,legacyBindings:{type:'array',items:legacyBinding},requiredBindingIds:{type:'array',items:string},legacyNeedsSpecification:{type:'boolean'}},required:['title']},
 {name:'updateView',alias:'update_view',effect:'compute',properties:{viewId:string,title:string,design:{},bindings},required:['viewId']},
 {name:'openComponent',alias:'open_component',effect:'compute',properties:{componentId:string,revision:integer,directory:string},required:['componentId']},
 {name:'openSource',alias:'open_source_component',effect:'compute',properties:{directory:string,title:string,viewId:string,bindings,legacyBindings:{type:'array',items:legacyBinding}},required:['directory']},
 {name:'saveComponent',alias:'save_component',effect:'mutation',properties:{viewId:string,userRequest:string,title:string,mode:{enum:['save_as','update']},componentId:string,expectedRevision:integer,legacyComponentId:string,legacyTemplate:{}},required:['viewId','userRequest','mode']},
 {name:'saveEntry',alias:'save_entry',effect:'mutation',properties:{title:string,binding,legacyBinding,legacyFieldOrder:{type:'array',items:string},userRequest:string},required:['title','binding','userRequest']},
 {name:'saveTemplate',alias:'save_template',effect:'mutation',properties:{viewId:string,name:string,description:{type:'string'},userRequest:string},required:['viewId','name','userRequest']},
 {name:'listSaved',alias:'list_saved',effect:'query',properties:{},required:[]},
 {name:'manageSaved',alias:'manage_saved',effect:'mutation',properties:{kind:{enum:['component','entry','template']},id:string,action:{enum:['rename','delete','pin','reorder']},name:string,order:{type:'integer'},pinned:{type:'boolean'},expectedRevision:integer},required:['kind','id','action']},
];
export const APP_PRESENTATION_DESCRIPTORS:readonly CapabilityDescriptor[]=definitions.map(item=>({capabilityId:`apps.presentation.${item.alias}`,version:'1.0.0',title:item.name,description:`Shared component ${item.name}. Builds and drafts remain separate from explicit saved assets.`,effect:item.effect,inputSchema:{type:'object',properties:item.properties,required:item.required,additionalProperties:false},outputSchema:outputs[item.name],execution:{mode:'sync',timeoutMs:30000,concurrency:'exclusive',lockScope:'connection',idempotency:item.effect==='mutation'?'runtime_dedup':'not_applicable',completionEvidence:'response'},discovery:{defaultVisible:false,keywords:['component','presentation','source']},aliases:[`hallmark_${item.alias}`]}));
