import assert from 'node:assert/strict';import{readdirSync,readFileSync,writeFileSync}from'node:fs';import{join}from'node:path';
const [directory,out]=process.argv.slice(2),median=x=>{const a=[...x].sort((a,b)=>a-b),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;},results=[];
for(const shape of ['small','product','posting']){
 const records=readdirSync(directory).filter(f=>f.startsWith(shape+'-c')&&f.endsWith('.json')).map(file=>({file,data:JSON.parse(readFileSync(join(directory,file)))}));assert.equal(records.length,20);assert.equal(new Set(records.map(r=>r.data.contentDigest)).size,1,'Per-turn content hash matches across all arms/processes');
 const byArm=arm=>records.filter(r=>r.file.endsWith('-'+arm+'.json'));for(const arm of ['baseline','integration']){assert.equal(byArm(arm).length,10);assert.equal(new Set(byArm(arm).map(r=>JSON.stringify(r.data.sourceHashes))).size,1);}
 const stats=arm=>{const rows=byArm(arm);return{processes:rows.length,samplesPerProcess:8,medianProcessMs:median(rows.map(r=>median(r.data.samplesMs))),minProcessMs:Math.min(...rows.map(r=>median(r.data.samplesMs))),maxProcessMs:Math.max(...rows.map(r=>median(r.data.samplesMs))),medianCpuMs:median(rows.map(r=>(r.data.resources.cpuMicros.user+r.data.resources.cpuMicros.system)/1000)),medianPeakRSSMiB:median(rows.map(r=>r.data.resources.maxRSSKiB/1024)),processMedians:rows.map(r=>({file:r.file,ms:median(r.data.samplesMs)}))};};
 const baseline=stats('baseline'),integration=stats('integration'),cycles=[];
 for(let i=1;i<=5;i++){const a=records.filter(r=>r.file.includes('-c'+i+'-')),b=median(a.filter(r=>r.file.endsWith('-baseline.json')).map(r=>median(r.data.samplesMs))),c=median(a.filter(r=>r.file.endsWith('-integration.json')).map(r=>median(r.data.samplesMs)));cycles.push({cycle:i,baselineMs:b,integrationMs:c,reductionPercent:(b-c)/b*100});}
 for(const {data:d}of records){assert.equal(d.mode,'timing');assert.equal(d.samplesMs.length,8);assert.equal(d.upstream,0);assert.equal(d.providerCalls,20);assert.equal(d.schedulerRefreshes,10);}
 results.push({shape,n:records[0].data.n,legacyRows:records[0].data.legacyRows,noiseRows:records[0].data.noiseRows,baseline,integration,medianReductionPercent:(baseline.medianProcessMs-integration.medianProcessMs)/baseline.medianProcessMs*100,cycles,parityContentDigest:records[0].data.contentDigest,allCyclesImproved:cycles.every(c=>c.reductionPercent>0)});
}
const summary={method:'Independent processes, five ABBA cycles per shape; median of process medians. Each measured sample is one complete direct Runtime.invoke plus one scheduler.tick -> presentation.refreshBinding -> second Runtime.invoke. Each process has2warmup+8measured turns.',results};if(out)writeFileSync(out,JSON.stringify(summary,null,2));console.log(JSON.stringify(summary,null,2));
