import {test} from 'node:test';
import assert from 'node:assert/strict';
import {fork} from 'node:child_process';
import {createServer} from 'node:http';
import {createHash} from 'node:crypto';
import {DatabaseSync} from 'node:sqlite';
import {cpSync,existsSync,mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {fileURLToPath} from 'node:url';
import {AppStore} from '../../packages/store/index.ts';
import {composeAppsRuntime} from '../../packages/service/src/apps-main.ts';
import {createAppsServer} from '../../packages/service/src/apps-server.ts';
import {AppsClient,HttpRuntimeTransport} from '../../packages/app-sdk/src/index.ts';
import {HallmarkStorePort} from '../../packages/app-hallmark/src/index.ts';
import {canonicalJson} from '../../packages/app-contracts/src/index.ts';
import {exportLegacyDatabase,migrationDryRun,createConsistentBackup,verifyBackup,migrateOffline,rollbackBaseline,assessRollback,validateCutoverEvidence} from '../../packages/app-migration/src/index.ts';
import type {MigrationOptions} from '../../packages/app-migration/src/index.ts';

type Data=Record<string,any>;
const hash=(value:unknown)=>createHash('sha256').update(canonicalJson(value)).digest('hex');
const fileHash=(path:string)=>createHash('sha256').update(readFileSync(path)).digest('hex');
const helper=fileURLToPath(new URL('./fixtures/schema2-service.mjs',import.meta.url)),token='c'.repeat(64),at='2026-10-05T00:00:00Z';
async function listen(server:ReturnType<typeof createServer>){await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address();assert.ok(address&&typeof address!=='string');return `http://127.0.0.1:${address.port}`;}
async function close(server:ReturnType<typeof createServer>){server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
function writer(directory:string,backend:string,tokenFile:string){
 const process=fork(helper,[directory,backend,tokenFile],{execArgv:[],silent:true}),messages:Data[]=[],waiting=new Map<string,Array<(value:Data)=>void>>();let stderr='';
 process.stderr?.on('data',chunk=>{stderr+=chunk.toString();});process.stdout?.resume();
 process.on('message',message=>{const value=message as Data;messages.push(value);for(const receive of waiting.get(value.event)??[])receive(value);waiting.delete(value.event);});
 const exit=new Promise<{code:number|null;signal:NodeJS.Signals|null}>(resolve=>process.once('exit',(code,signal)=>resolve({code,signal})));
 const wait=(event:string)=>new Promise<Data>((resolve,reject)=>{const prior=messages.find(row=>row.event===event);if(prior)return resolve(prior);const timer=setTimeout(()=>reject(new Error(`WRITER_EVENT_TIMEOUT:${event}:${stderr.slice(0,1000)}`)),15000);const receive=(value:Data)=>{clearTimeout(timer);resolve(value);};waiting.set(event,[...(waiting.get(event)??[]),receive]);});
 return {process,messages,wait,exit,send:(action:string)=>process.send({action})};
}
async function request(url:string,path:string,input?:unknown){const response=await fetch(new URL(path,url),{method:input===undefined?'GET':'POST',headers:{authorization:`Bearer ${token}`,...(input===undefined?{}:{'content-type':'application/json'})},...(input===undefined?{}:{body:JSON.stringify(input)}),redirect:'error',signal:AbortSignal.timeout(15000)});return {status:response.status,data:await response.json() as Data};}
function emit(branch:string,report:Data){const root=process.env.APPS_MIGRATION_EVIDENCE_DIR;if(!root)return;const directory=join(resolve(root),'TODO-024','full-rehearsal');mkdirSync(directory,{recursive:true});writeFileSync(join(directory,`${branch}.json`),JSON.stringify({status:'PASS',kind:'actual_isolated_schema2_service_and_schema3_runtime_copy_rehearsal',executedAt:new Date().toISOString(),nodeVersion:process.version,...report},null,2));}

for(const branch of ['A-no-new-write','B-success-and-unknown'] as const)test(`isolated copied service full stop/drain/backup/migrate/cutover/rollback rehearsal ${branch}`,async()=>{
 const root=mkdtempSync(join(tmpdir(),'dsh-apps-cutover-')),source=join(root,'legacy-copy'),target=join(root,'apps-target'),tokenFile=join(root,'fixture-key');mkdirSync(source);writeFileSync(tokenFile,token,{mode:0o600});
 const project=join(source,'project');mkdirSync(join(project,'dist'),{recursive:true});writeFileSync(join(project,'package.json'),'{"name":"isolated-copied-component","private":true}');writeFileSync(join(project,'src.tsx'),'export default () => "original copied source";');writeFileSync(join(project,'dist','index.html'),'<div>Copied source artifact</div>');
 const database=join(source,'app.db'),fixtureBaselineDirectory=join(root,'synthetic-fixture-baseline');mkdirSync(fixtureBaselineDirectory);const fixtureBaselineDatabase=join(fixtureBaselineDirectory,'app.db'),seed=new AppStore(fixtureBaselineDatabase),originalOperationId='copied-original-operation';
 seed.put('session_apps','s',{sessionId:'s',appId:'hallmark',active:true,activatedAt:at});seed.put('operations',originalOperationId,{operationId:originalOperationId,kind:'update_price',sessionId:'s',clientKey:'copied-original-intent',storeId:'shop',targets:['A'],input:{storeId:'shop',offerIds:['A'],price:100,currency:'RUB',valueSource:'user',clientOperationKey:'copied-original-intent',userRequest:'Original copied historical intent',fingerprint:'copied-historical-hash'},state:'succeeded',hallmarkRefs:[{taskId:'task',requestId:'copied-original-request'}],items:[{target:'A',state:'succeeded'}],createdAt:at,updatedAt:at});seed.close();cpSync(fixtureBaselineDatabase,database,{errorOnExist:true,force:false});const fixtureBaselineHash=fileHash(fixtureBaselineDatabase);assert.equal(fileHash(database),fixtureBaselineHash);
 const businessRequests:Data[]=[];let holdNextRefresh=false,markRefreshStarted:()=>void=()=>{},releaseRefresh:()=>void=()=>{};
 const refreshStarted=new Promise<void>(resolve=>{markRefreshStarted=resolve;}),refreshRelease=new Promise<void>(resolve=>{releaseRefresh=resolve;});
 const upstream=createServer(async(req,res)=>{const chunks:Uint8Array[]=[];for await(const chunk of req)chunks.push(chunk);const body=Buffer.concat(chunks).toString(),input=body?JSON.parse(body):{},route=new URL(req.url??'/','http://127.0.0.1').pathname;businessRequests.push({method:req.method,route,...(body?{input}:{})});
  const send=(value:unknown)=>{res.writeHead(200,{'content-type':'application/json'});res.end(JSON.stringify(value));};
  if(route==='/api/health')return send({service:'hallmark-control'});if(route==='/api/stores')return send([{id:'shop',shopName:'Copied fixture shop'}]);
  if(route==='/api/store-products'||route==='/api/store-products/sync'){if(route.endsWith('/sync')&&holdNextRefresh){holdNextRefresh=false;markRefreshStarted();await refreshRelease;}return send({stores:[{id:'shop',lastSuccessAt:at}],products:[{storeId:'shop',offerId:'A',productId:1,price:100,stock:2,originalField:{preserved:true}}]});}
  if(route==='/api/tasks')return send([{id:'task',kind:'listing',storeId:'shop',status:'active'}]);if(route==='/api/tasks/task')return send({id:'task',kind:'listing',storeId:'shop',status:'active'});
  if(route==='/api/tasks/task/platform'){assert.ok(['/v1/product/import/prices','/v5/product/info/prices'].includes(input.path));return send({requestId:input.requestId,taskId:'task',storeId:'shop',path:input.path,method:input.method,body:input.body,startedAt:at,outcome:input.path==='/v1/product/import/prices'?'outcome_unknown':'response_received',httpStatus:200,response:input.path==='/v1/product/import/prices'?{result:[{updated:true}]}:{result:{items:[{offer_id:'A',product_id:1,price:{price:'50',currency_code:'RUB'}}]}},originalRaw:{retained:true}});}
  res.writeHead(404);res.end('{}');
 });
 const backend=await listen(upstream),old=writer(source,backend,tokenFile);let instance:ReturnType<typeof composeAppsRuntime>|undefined,candidateServer:ReturnType<typeof createServer>|undefined,restored:ReturnType<typeof writer>|undefined,second:ReturnType<typeof writer>|undefined;
 try {
  const oldReady=await old.wait('ready');assert.equal(oldReady.schemaVersion,2);const health=await request(oldReady.url,'/health');assert.equal(health.status,200);
  second=writer(source,backend,tokenFile);const refused=await second.wait('writer-rejected');assert.equal(refused.code,'RUNTIME_WRITER_ALREADY_ACTIVE');assert.equal(refused.databaseOpened,false);assert.equal((await second.exit).code,3);
  const opened=await request(oldReady.url,'/tools/hallmark_open_source_component',{sessionId:'s',arguments:{directory:project,title:'Copied saved source',bindings:[{id:'data',datasetKey:'store_products:shop',fieldMap:{offerId:'商品标识'}}]}});assert.equal(opened.data.status,'ok',JSON.stringify(opened));
  const viewId=opened.data.data.viewId,save=await request(oldReady.url,'/tools/hallmark_save_component',{sessionId:'s',arguments:{viewId,userRequest:'保存复制环境组件'},userRequest:'保存复制环境组件'});assert.equal(save.data.status,'ok',JSON.stringify(save));const componentId=save.data.data.component.id,buildId=save.data.data.component.spec.source.buildId;
  const options:MigrationOptions={sourceDatabase:database,sourceDirectory:source,targetDirectory:target,connection:{appId:'hallmark',connectionId:'copied-backend',displayName:'Isolated mock backend',config:{baseUrl:backend},configRevision:1,enabled:true},offlineConfirmed:true};
  assert.throws(()=>migrationDryRun(options),/SOURCE_WRITER_ACTIVE_OR_UNREVIEWED/);
  holdNextRefresh=true;const inFlight=request(oldReady.url,'/refresh',{sessionId:'s',datasetKey:'store_products:shop'});await refreshStarted;old.send('freeze');const frozen=await old.wait('frozen');assert.equal(frozen.activeRequests,1);assert.equal(old.messages.some(row=>row.event==='drained'),false);
  const afterFreeze=await request(oldReady.url,'/sessions/s/app',{active:false});assert.equal(afterFreeze.status,503);assert.equal(afterFreeze.data.error.code,'COPY_WRITER_FROZEN');
  releaseRefresh();const completed=await inFlight;assert.equal(completed.data.status,'ok',JSON.stringify(completed));const drained=await old.wait('drained');assert.equal(drained.activeRequests,0);old.send('stop');const stopped=await old.wait('stopped');assert.equal(stopped.writerLeaseReleased,true);assert.equal((await old.exit).code,0);assert.equal(existsSync(join(source,'runtime-writer.json')),false);await assert.rejects(request(oldReady.url,'/health'));await assert.rejects(request(oldReady.serviceUrl,'/health'));
  const before=exportLegacyDatabase(database),logicalBefore=hash(before.collections),sourceHash=fileHash(database),dry=migrationDryRun(options);assert.equal(dry.status,'ready',JSON.stringify(dry));assert.equal(Object.keys(dry.counts).length,11);for(const count of Object.values(dry.counts))assert.equal(count.source,count.mapped+count.quarantined);assert.deepEqual(dry.unresolvedOperationIds,[]);assert.ok(dry.assets.some(asset=>asset.relativePath.includes(buildId)));
  const backupDirectory=join(root,'verified-backup'),backup=await createConsistentBackup(options,backupDirectory,dry);assert.equal(verifyBackup(backupDirectory).backupId,backup.backupId);const migrated=await migrateOffline(options);assert.equal(migrated.status,'migrated');assert.equal(fileHash(database),sourceHash);assert.equal(hash(exportLegacyDatabase(database).collections),logicalBefore);
  instance=composeAppsRuntime(target,{connections:[{appId:'notes',connectionId:'copied-notes',displayName:'Isolated copied Notes',config:{backend:'local-notes'},configRevision:1,enabled:true}],legacyHallmarkConnectionId:'copied-backend'});
  assert.throws(()=>composeAppsRuntime(target,{connections:[]}),/RUNTIME_WRITER_ALREADY_ACTIVE/);
  for(const [appId,connectionId] of [['apps','presentation'],['notes','copied-notes']])instance.runtime.bind({sessionId:'s',appId,connectionId,enabled:true,boundAt:new Date().toISOString()});
  candidateServer=createAppsServer({...instance,token});const candidateUrl=await listen(candidateServer),transport=new HttpRuntimeTransport(candidateUrl,token),sdk=new AppsClient(transport,{kind:'agent',sessionId:'s',nativeCallId:'isolated-cutover-rehearsal'});
  assert.equal(instance.runtime.identity().databaseSchemaVersion,3);const libraryDescriptor=(await transport.describe('apps.presentation.list_saved'))!,library=await sdk.invoke({appId:'apps',connectionId:'presentation'},libraryDescriptor,{});assert.equal(library.status,'ok',JSON.stringify(library));assert.ok('data' in library);assert.equal((library.data as Data).components[0].componentId,componentId);assert.equal((library.data as Data).components[0].view.ownerSessionId,null);assert.equal(instance.presentation.sources!.verify(buildId).valid,true);assert.equal(instance.presentation.sources!.readFile(buildId,'index.html')!.bytes.toString(),'<div>Copied source artifact</div>');assert.equal(instance.store.get<Data>('operations',originalOperationId)!.operationId,originalOperationId);
  const datasetAlias=instance.store.get<Data>('legacy_aliases','dataset:store_products:shop')!,dataset=instance.store.get<Data>('datasets',datasetAlias.datasetId)!;assert.equal(dataset.payload.products[0].originalField.preserved,true);assert.equal(dataset.sourceDataTime,at);
  const productionGates=validateCutoverEvidence({oldWriterStopped:true,runtimeWriterCount:1,gateStates:{G0:'NOT_RUN',G1:'NOT_RUN',G2:'NOT_RUN',G3:'NOT_RUN',G4:'NOT_RUN'},unresolvedOperationIds:[],migrationStatus:migrated.status});assert.equal(productionGates.allowed,false);
  const cutoverAt=new Date().toISOString(),baseline=rollbackBaseline(instance.store),cutover={scope:'isolated copied environment route switched from stopped schema2 endpoint to schema3 endpoint',oldPid:oldReady.pid,oldUrl:oldReady.url,newPid:process.pid,newUrl:candidateUrl,oldWriterStopped:true,runtimeWriterCount:1,databaseSchemaVersion:3,runtimeIdentity:instance.runtime.identity(),historicalOperationIds:baseline.operationIds,componentId,buildId,savedLibraryVerified:true,sourceManifestAndDistVerified:true,sourceFieldAndOriginalDataTimeVerified:at,productionGateAssessment:productionGates,productionCutover:'NOT_RUN'};
  let delta:Data;
  if(branch==='A-no-new-write'){
   delta=assessRollback(instance.store,baseline,cutoverAt);assert.equal(delta.branch,'A');assert.equal(delta.legacyRestoreAllowed,true);assert.equal(delta.incrementalExport.operations.length,0);
   await close(candidateServer);candidateServer=undefined;await instance.close();instance=undefined;assert.equal(existsSync(join(target,'runtime-writer.json')),false);
   const restoreDirectory=join(root,'restored-legacy-copy');mkdirSync(restoreDirectory);cpSync(join(backupDirectory,'app.db'),join(restoreDirectory,'app.db'),{errorOnExist:true,force:false});cpSync(join(backupDirectory,'assets'),restoreDirectory,{recursive:true,errorOnExist:true,force:false});assert.equal(hash(exportLegacyDatabase(join(restoreDirectory,'app.db')).collections),logicalBefore);
   restored=writer(restoreDirectory,backend,tokenFile);const ready=await restored.wait('ready'),restoredLibrary=await request(ready.url,'/tools/hallmark_list_saved',{sessionId:'s',arguments:{}});assert.equal(restoredLibrary.data.status,'ok');assert.equal(restoredLibrary.data.data.components[0].id,componentId);restored.send('freeze');await restored.wait('drained');restored.send('stop');await restored.wait('stopped');assert.equal((await restored.exit).code,0);
   delta.actualLegacyCopyRestart={pid:ready.pid,url:ready.url,schemaVersion:ready.schemaVersion,restoredFromVerifiedBackup:true,allOriginalCollectionContentMatches:true,savedComponentReadable:true,cleanlyStopped:true};
  }else{
   const noteDescriptor=(await transport.describe('notes.notes.create'))!,success=await sdk.invoke({appId:'notes',connectionId:'copied-notes'},noteDescriptor,{id:'copied-success-note',title:'Actual successful copied mutation',content:'Local Runtime evidence'},{idempotencyKey:'copied-success-intent',invocationId:'copied-success-invocation'});assert.equal(success.status,'ok',JSON.stringify(success));
   const priceDescriptor=(await transport.describe('hallmark.api.products.update_price'))!,unknown=await sdk.invoke({appId:'hallmark',connectionId:'copied-backend'},priceDescriptor,{storeId:'shop',offerIds:['A'],price:100,currency:'RUB',valueSource:'user',userRequest:'明确测试夹具 A 价格 100 RUB'},{idempotencyKey:'copied-unknown-intent',invocationId:'copied-unknown-invocation'});assert.equal(unknown.status,'unknown',JSON.stringify(unknown));assert.ok('error' in unknown);assert.equal(unknown.error.retryPolicy,'inspect_only');
   delta=assessRollback(instance.store,baseline,cutoverAt);assert.equal(delta.branch,'B');assert.equal(delta.legacyRestoreAllowed,false);assert.equal(delta.incrementalExport.operations.length,2);assert.deepEqual(delta.incrementalExport.operations.map((row:Data)=>row.operationId).sort(),[success.operation!.operationId,unknown.operation!.operationId].sort());assert.equal(delta.incrementalExport.operations.find((row:Data)=>row.operationId===success.operation!.operationId).state,'succeeded');assert.deepEqual(delta.unresolvedOperationIds,[unknown.operation!.operationId]);
   const port=new HallmarkStorePort(instance.store,'copied-backend'),originalEvidence=port.get<Data>('operations',unknown.operation!.operationId)!;assert.equal(originalEvidence.operationId,unknown.operation!.operationId);assert.equal(originalEvidence.items[0].write.raw.outcome,'outcome_unknown');assert.equal(businessRequests.filter(row=>row.input?.path==='/v1/product/import/prices').length,1);
   const providerEvidence=instance.store.list<Data>('provider_records').filter(row=>row.namespace==='operations'&&[success.operation!.operationId,unknown.operation!.operationId].includes(row.recordId));assert.equal(providerEvidence.length,2);
   await close(candidateServer);candidateServer=undefined;await instance.close();instance=undefined;assert.equal(existsSync(join(target,'runtime-writer.json')),false);
   writeFileSync(join(source,'writer-freeze.json'),JSON.stringify({reason:'incremental reconciliation required',unresolvedOperationIds:delta.unresolvedOperationIds,successfulOperationId:success.operation!.operationId}));restored=writer(source,backend,tokenFile);const denied=await restored.wait('writer-rejected');assert.equal(denied.code,'ROLLBACK_INCREMENTAL_RECONCILIATION_REQUIRED');assert.equal(denied.databaseOpened,false);assert.equal((await restored.exit).code,3);
   const retained=new DatabaseSync(join(target,'apps.db'),{readOnly:true});try{const operations=retained.prepare('SELECT value_json FROM operations').all().map(row=>JSON.parse(String(row.value_json)) as Data);assert.equal(operations.find(row=>row.operationId===success.operation!.operationId)!.state,'succeeded');assert.equal(operations.find(row=>row.operationId===unknown.operation!.operationId)!.state,'unknown');assert.equal(operations.length,baseline.operationIds.length+2);}finally{retained.close();}
   delta.retainedProviderEvidence=providerEvidence;delta.completeOriginalUnknownEvidence=originalEvidence;delta.actualLegacyCopyRestart={blocked:true,code:denied.code,databaseOpened:false};delta.runtimeFrozenAndLeaseReleased=true;
  }
  assert.equal(delta.externalBusinessReversed,false);assert.equal(hash(exportLegacyDatabase(database).collections),logicalBefore);
  assert.equal(fileHash(fixtureBaselineDatabase),fixtureBaselineHash);
  emit(branch,{originalDatabaseOrServicesTouched:false,realBusinessMutation:'NOT_RUN',fixtureBaseline:{database:fixtureBaselineDatabase,schemaVersion:2,databaseSha256:fixtureBaselineHash,byteCopiedBeforeServiceStart:true,unmodifiedAfterRehearsal:true},fixtureBusinessMutationPosts:businessRequests.filter(row=>row.input?.path==='/v1/product/import/prices').length,oldService:{...oldReady,supervisor:'test-only admission/lease wrapper around actual schema2 service',concurrentWriterRejected:refused,admissionFrozen:frozen,newWriteAfterFreeze:{httpStatus:afterFreeze.status,errorCode:afterFreeze.data.error.code},inFlightFinished:completed.data.status,drained,stopped,exitCode:0,portsClosed:true},inspection:{sourceSchemaVersion:before.schemaVersion,sourceDatabaseSha256:sourceHash,sourceCollectionsSha256:logicalBefore,sourceCollectionCounts:dry.counts,unresolvedOperationIds:dry.unresolvedOperationIds},backup,migration:migrated,cutover,rollback:delta,fixtureBackendRoutes:businessRequests.map(row=>({method:row.method,route:row.route,...(row.input?.path?{platformPath:row.input.path}:{})})),externalBusinessReversed:false});
 } finally {
  releaseRefresh();if(candidateServer)await close(candidateServer);await instance?.close();for(const child of [old,second,restored])if(child?.process.connected){child.send('stop');await child.exit;}await close(upstream);const checked=resolve(root);assert.ok(checked.startsWith(resolve(tmpdir())+sep)&&checked.includes('dsh-apps-cutover-'));rmSync(checked,{recursive:true,force:true});
 }
});
