import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { existsSync,mkdirSync,mkdtempSync,readFileSync,writeFileSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname,join,resolve,sep } from 'node:path';
import { AppStore } from '../../packages/store/index.ts';
import { RuntimeStore } from '../../packages/app-runtime/src/store.ts';
import type { RuntimeOperation } from '../../packages/app-runtime/src/store.ts';
import { RuntimeWriterLease } from '../../packages/app-runtime/src/lease.ts';
import { SourceComponentStore } from '../../packages/source-components/src/index.ts';
import { composeAppsRuntime } from '../../packages/service/src/apps-main.ts';
import { projectLegacyPresentationResult,createLegacyPresentationAdapter } from '../../packages/service/src/apps-legacy-presentation.ts';
import { canonicalJson } from '../../packages/app-contracts/src/index.ts';
import { exportLegacyDatabase,migrationDryRun,migrateOffline,createConsistentBackup,verifyBackup,gcDryRun,applyGC,rollbackBaseline,assessRollback,validateCutoverEvidence } from '../../packages/app-migration/src/index.ts';
import type { MigrationOptions } from '../../packages/app-migration/src/index.ts';

const digest=(path:string)=>createHash('sha256').update(readFileSync(path)).digest('hex');
const at='2026-10-06T01:00:00Z';
const originalBinding={id:'products',datasetKey:'store_products:shop',query:{tool:'hallmark_list_store_products',params:{storeId:'shop'}},fieldMap:{name:'title',offerId:'商品标识'}};
const originalTemplate={id:'original-template',name:'Original saved design',description:'Immutable resolved template snapshot',theme:{accent:'fixture'},layout:{type:'column',children:[]},widgetStyles:[],contentRules:{bindingIds:['products']},version:1};
function emit(name:string,value:unknown):void{const root=process.env.APPS_MIGRATION_EVIDENCE_DIR;if(root){const todo=name.slice(0,8),directory=join(resolve(root),todo,todo==='TODO-023'?'migration':todo==='TODO-024'?'rollback':'operations');mkdirSync(directory,{recursive:true});writeFileSync(join(directory,`${name}.json`),JSON.stringify({kind:'synthetic_fixture',executedAt:new Date().toISOString(),status:'PASS',evidence:value},null,2));}}
function fixture(){
 const root=mkdtempSync(join(tmpdir(),'dsh-apps-migration-')),source=join(root,'source'),target=join(root,'target');mkdirSync(source);
 const project=join(source,'project');mkdirSync(join(project,'dist'),{recursive:true});writeFileSync(join(project,'package.json'),'{"name":"synthetic-component","private":true}');writeFileSync(join(project,'src.tsx'),'export default () => "original source";');writeFileSync(join(project,'dist','index.html'),'<div>Version one</div>');
 const sources=new SourceComponentStore(join(source,'source-components')),first=sources.capture(project).source;writeFileSync(join(project,'dist','index.html'),'<div>Version two</div>');const second=sources.capture(project).source;
 const database=join(source,'app.db'),store=new AppStore(database),bindings=[originalBinding],spec=(viewId:string,build=second)=>({id:viewId,title:'Synthetic source component',kind:'source',source:build,layout:{type:'column',children:[]},widgets:[],bindings});
 store.put('session_apps','s',{sessionId:'s',appId:'hallmark',active:true,activatedAt:at});
 const operation={operationId:'legacy-price',kind:'update_price',sessionId:'s',clientKey:'original-intent',storeId:'shop',targets:['A'],input:{storeId:'shop',offerIds:['A'],price:100,currency:'RUB',valueSource:'user',clientOperationKey:'original-intent',userRequest:'把 A 价格改为 100 RUB',fingerprint:'original-hash'},state:'succeeded',hallmarkRefs:[{taskId:'task',requestId:'original-request'}],items:[{target:'A',state:'succeeded'}],createdAt:at,updatedAt:at};store.put('operations',operation.operationId,operation);
 const spill=join(source,'data','spill','source.json');mkdirSync(dirname(spill),{recursive:true});writeFileSync(spill,'{"source":"complete data"}');
 store.updateSnapshotSuccess('store_products:shop',{products:[{storeId:'shop',offerId:'A',price:100,originalField:{preserved:true}}]},null,{provenance:{source:'hallmark_snapshot',fetchedAt:at},sourceSpill:{path:spill,bytes:26,summary:{kind:'products'},cursor:'0'}});
 store.put('internal_tasks','shop:store_operation',{storeId:'shop',purpose:'store_operation',taskId:'task'});store.put('result_sets','expired',{resultSetId:'expired',expiresAt:'2026-10-06T02:00:00Z',payload:{products:[],unable:[],total:0}});
 store.put('queries','q',{id:'q',datasetKey:'query:q',tool:'hallmark_list_store_products',params:{storeId:'shop'},userRequest:'保存查询'});
 store.put('views','draft:draft',{kind:'component-draft',spec:spec('draft')});store.put('views','owner:draft',{kind:'component-owner',owner:{sessionId:'s',viewId:'draft',title:'Draft',createdAt:at,updatedAt:at,widgetTypes:[]}});
 const component={id:'component',title:'Saved source',spec:spec('component'),template:originalTemplate,revision:2,revisions:[{revision:1,title:'Earlier',savedAt:at,buildId:first.buildId},{revision:2,title:'Saved source',savedAt:at,buildId:second.buildId}],userRequest:'保存组件',savedAt:at};store.put('components','component',component);
 store.put('settings','source-revision:component:1',{...component,revision:1,spec:spec('component',first),revisions:[component.revisions[0]]});store.put('settings','queried_store:shop',{storeId:'shop',lastQueriedAt:at});
 store.put('templates','template',{id:'template',name:'Saved template',description:'Fixture',theme:{},layout:{type:'column',children:[]},widgetStyles:[],contentRules:{bindingIds:['products']},version:1,kind:'source',source:second,bindings,userRequest:'保存模板'});
 store.put('entries','component-entry',{id:'component-entry',appId:'hallmark',kind:'component',viewId:'component',title:'Entry',pinned:true,order:0,userRequest:'保存组件'});store.put('entries','data-entry',{id:'data-entry',appId:'hallmark',kind:'data',title:'Data',binding:bindings[0],pinned:false,order:1,userRequest:'保存数据入口'});
 store.close();writeFileSync(join(source,'pending-closures.json'),JSON.stringify({version:1,intents:[{sessionId:'s',requestedAt:at}]}));
 const options:MigrationOptions={sourceDatabase:database,sourceDirectory:source,targetDirectory:target,connection:{appId:'hallmark',connectionId:'explicit-backend',displayName:'Synthetic original backend',config:{baseUrl:'http://127.0.0.1:3000'},configRevision:1,enabled:true},offlineConfirmed:true};
 return {root,source,target,database,options,first,second,cleanup:()=>{const verified=resolve(root);assert.ok(verified.startsWith(resolve(tmpdir())+sep)&&verified.includes('dsh-apps-migration-'));rmSync(verified,{recursive:true,force:true});}};
}

test('dry-run covers all 11 collections, 26 aliases and both immutable builds without touching source/target',()=>{
 const f=fixture();try{const before=digest(f.database),report=migrationDryRun(f.options);assert.equal(report.status,'ready',JSON.stringify(report.records.filter(row=>row.state==='quarantined')));assert.equal(Object.keys(report.counts).length,11);for(const count of Object.values(report.counts))assert.equal(count.source,count.mapped+count.quarantined);assert.equal(report.legacyTools.length,26);assert.ok(report.assets.some(file=>file.relativePath.includes(f.first.buildId)));assert.ok(report.assets.some(file=>file.relativePath.includes(f.second.buildId)));assert.ok(report.assets.some(file=>file.relativePath==='pending-closures.json'));assert.equal(digest(f.database),before);assert.equal(existsSync(f.target),false);emit('TODO-023-dry-run',report);}finally{f.cleanup();}
});
test('consistent SQLite backup includes committed WAL and complete assets; tampering is detected',async()=>{
 const f=fixture();try{const writer=new AppStore(f.database);writer.put('settings','queried_store:wal',{storeId:'wal',lastQueriedAt:at});const directory=join(f.root,'backup'),manifest=await createConsistentBackup(f.options,directory);assert.equal(manifest.verified,true);assert.ok(exportLegacyDatabase(join(directory,'app.db')).collections.settings.some(row=>row.id==='queried_store:wal'));writer.close();assert.equal(verifyBackup(directory).backupId,manifest.backupId);const file=manifest.files[0];writeFileSync(file.sourcePath,'tampered');assert.throws(()=>verifyBackup(directory),/BACKUP_HASH_MISMATCH/);emit('TODO-023-backup',{manifest,tamperingDetected:true,walRecordIncluded:true});}finally{f.cleanup();}
});
test('apply maps history, ownership, closure intent, datasets and original operations; repeat is reentrant',async()=>{
 const f=fixture();try{const before=digest(f.database),report=await migrateOffline(f.options),repeated=await migrateOffline(f.options);assert.equal(repeated.migrationId,report.migrationId);assert.equal(report.status,'migrated');assert.equal(digest(f.database),before);const target=new RuntimeStore(join(f.target,'apps.db'));try{assert.equal(target.list<any>('session_app_bindings')[0].enabled,false);assert.equal(target.get<any>('operations','legacy-price').operationId,'legacy-price');assert.equal(target.list('component_versions').length,2);assert.equal(target.get<any>('views','draft').ownerSessionId,'s');const alias=target.get<any>('legacy_aliases','dataset:store_products:shop');assert.equal(alias.canonicalBinding.connectionId,'explicit-backend');assert.equal(target.get<any>('datasets',alias.datasetId).sourceDataTime,null);assert.equal(target.get<any>('datasets',alias.datasetId).freshness,'stale');assert.equal(target.get<any>('component_versions','component:1').view.source.buildId,f.first.buildId);assert.equal(target.get<any>('saved_assets','entry:component-entry').componentId,'component');assert.equal(target.get<any>('saved_assets','entry:data-entry').binding.datasetId,alias.datasetId);assert.ok(existsSync(join(f.target,'source-components','builds',f.first.buildId,'project','src.tsx')));assert.ok(target.get<any>('legacy_aliases','operation:legacy-price'));emit('TODO-023-apply',{report,counts:Object.fromEntries(['operations','invocations','datasets','components','component_versions','views','saved_assets'].map(table=>[table,target.list(table).length])),sourceUnchanged:true});}finally{target.close();}}finally{f.cleanup();}
});
test('unknown connections/settings/tables/tools and orphan ownership are quarantined; apply is blocked',async()=>{
 const f=fixture();try{const unknown=migrationDryRun({...f.options,connection:undefined});assert.equal(unknown.status,'needs_migration');assert.equal(unknown.counts.operations.quarantined,1);const original=new AppStore(f.database);original.put('settings','future-setting',{uninterpreted:true});original.put('queries','future-query',{id:'future-query',datasetKey:'query:future-query',tool:'hallmark_future_tool',params:{}});original.put('views','draft:orphan',{kind:'component-draft',spec:{id:'orphan',title:'Orphan',layout:{type:'column',children:[]},widgets:[],bindings:[]}});original.db.exec('CREATE TABLE future_table(id TEXT); INSERT INTO future_table VALUES (\'opaque\')');original.close();const report=migrationDryRun(f.options);assert.equal(report.status,'needs_migration');assert.equal(report.counts.future_table.quarantined,1);assert.ok(report.records.some(row=>row.reason==='VIEW_OWNER_UNKNOWN'));assert.ok(report.records.some(row=>row.reason==='UNKNOWN_SETTING_QUARANTINED'));assert.ok(report.records.some(row=>row.sourceId==='future-query'&&row.reason?.startsWith('DATASET_RECIPE_NEEDS_MIGRATION')));await assert.rejects(migrateOffline(f.options),/MIGRATION_REQUIRES_RESOLUTION/);assert.equal(existsSync(f.target),false);emit('TODO-023-quarantine',{unknownConnection:unknown,unsupported:report});}finally{f.cleanup();}
});

test('unsupported legacy entry metadata and component shapes are quarantined before strict saved library can be produced',async()=>{
 const f=fixture();try{const source=new AppStore(f.database),entry=source.get<any>('entries','data-entry')!,component=source.get<any>('components','component')!;source.put('entries','data-entry',{...entry,binding:{...entry.binding,inventedFutureBindingField:true}});source.put('components','component',{...component,title:42});source.close();const before=digest(f.database),report=migrationDryRun(f.options),quarantine=report.records.find(row=>row.sourceCollection==='entries'&&row.sourceId==='data-entry')!,invalidComponent=report.records.find(row=>row.sourceCollection==='components'&&row.sourceId==='component')!;assert.equal(report.status,'needs_migration');assert.equal(quarantine.state,'quarantined');assert.match(quarantine.reason!,/^SAVED_ASSET_SCHEMA_NEEDS_MIGRATION:/);assert.equal(quarantine.targets.some(target=>target.collection==='saved_assets'),false);assert.equal(invalidComponent.state,'quarantined');assert.match(invalidComponent.reason!,/^SAVED_COMPONENT_SCHEMA_NEEDS_MIGRATION:/);assert.equal(invalidComponent.targets.some(target=>target.collection==='components'),false);await assert.rejects(migrateOffline(f.options),/MIGRATION_REQUIRES_RESOLUTION/);assert.equal(existsSync(f.target),false);assert.equal(digest(f.database),before);emit('TODO-023-metadata-quarantine',{report,unsupportedMetadataRetainedInSource:true,strictLibraryBlocked:true,sourceUnchanged:true});}finally{f.cleanup();}
});
test('missing source/dist files and missing historical revision block apply without overwriting source',async()=>{
 const f=fixture();try{const old=new AppStore(f.database);old.delete('settings','source-revision:component:1');old.close();const historical=migrationDryRun(f.options);assert.equal(historical.status,'needs_migration');assert.ok(historical.records.some(row=>row.reason==='HISTORICAL_REVISION_MISSING'));const file=join(f.source,'source-components','builds',f.first.buildId,'project','src.tsx');writeFileSync(file,'corrupted archive');const report=migrationDryRun(f.options);assert.equal(report.status,'needs_migration');assert.ok(report.assetErrors.some(error=>error.includes('HASH_MISMATCH')));await assert.rejects(migrateOffline(f.options),/MIGRATION_REQUIRES_RESOLUTION/);assert.equal(existsSync(f.target),false);emit('TODO-023-asset-failure',{report,historicalRevisionMissingDetected:true});}finally{f.cleanup();}
});
test('writer lease and migration target reject concurrent or in-place takeover',async()=>{
 const f=fixture();try{assert.throws(()=>migrationDryRun({...f.options,targetDirectory:f.source}),/SEPARATE_TARGET_DIRECTORY_REQUIRED/);assert.throws(()=>migrationDryRun({...f.options,offlineConfirmed:false}),/OFFLINE_CONFIRMATION_REQUIRED/);const owner=new RuntimeWriterLease(f.target);try{await assert.rejects(migrateOffline(f.options),/RUNTIME_WRITER_ALREADY_ACTIVE/);}finally{owner.release();}emit('TODO-024-single-writer',{inPlaceRejected:true,offlineProofRequired:true,concurrentRuntimeWriterRejected:true});}finally{f.cleanup();}
});
test('rollback branch A allows only no delta; branch B exports writes/assets/bindings and freezes unknown',()=>{
 const f=fixture(),store=new RuntimeStore(':memory:');try{
  const baseline=rollbackBaseline(store),clean=assessRollback(store,baseline,at);assert.equal(clean.branch,'A');assert.equal(clean.legacyRestoreAllowed,true);
  const request:any={protocolVersion:'1.0',invocationId:'new',traceId:'trace',appId:'notes',connectionId:'one',capabilityId:'notes.notes.create',capabilityVersion:'1.0.0',input:{title:'T',content:'C'},source:{kind:'agent',sessionId:'s',nativeCallId:'n'},deadlineAt:new Date().toISOString(),idempotencyKey:'new'};
  const op:RuntimeOperation={operationId:'new-write',appId:'notes',connectionId:'one',capabilityId:'notes.notes.create',capabilityVersion:'1.0.0',idempotencyKey:'new',requestHash:'hash',request,state:'unknown',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
  store.put('operations',op.operationId,op);
  const success:RuntimeOperation={...op,operationId:'successful-write',idempotencyKey:'success',request:{...request,invocationId:'success-invocation',idempotencyKey:'success'},state:'succeeded',result:{status:'ok',invocationId:'success-invocation',traceId:'trace',operation:{operationId:'successful-write',state:'succeeded'},data:{resource:{appId:'notes',connectionId:'one',resourceType:'note',resourceId:'created-note',revision:'1'}}}};
  store.put('operations',success.operationId,success);store.put('saved_assets','entry:new',{kind:'entry',assetId:'new',title:'saved'});
  const incremental=assessRollback(store,baseline,at);assert.equal(incremental.branch,'B');assert.equal(incremental.legacyRestoreAllowed,false);assert.equal(incremental.incrementalExport.operations.length,2);
  assert.deepEqual(incremental.incrementalExport.operations.map(row=>row.operationId).sort(),['new-write','successful-write']);assert.deepEqual(incremental.unresolvedOperationIds,['new-write']);assert.deepEqual(incremental.incrementalExport.operations.find(row=>row.operationId==='successful-write')?.result,success.result);
  assert.equal(incremental.incrementalExport.savedAssets.length,1);assert.equal(incremental.externalBusinessReversed,false);const gates={G0:'VERIFIED',G1:'VERIFIED',G2:'VERIFIED',G3:'VERIFIED',G4:'VERIFIED'},single=validateCutoverEvidence({oldWriterStopped:true,runtimeWriterCount:1,gateStates:gates,unresolvedOperationIds:[],migrationStatus:'migrated'}),dual=validateCutoverEvidence({oldWriterStopped:false,runtimeWriterCount:2,gateStates:gates,unresolvedOperationIds:['new-write'],migrationStatus:'migrated'});assert.equal(single.allowed,true);assert.equal(dual.allowed,false);emit('TODO-024-rollback',{noDelta:clean,newWrites:incremental,mode:'simulation',realCutover:'NOT_RUN'});emit('TODO-024-cutover',{mode:'simulation',singleWriterAndAllGates:single,dualWriterAndUnknown:dual,realCutover:'NOT_RUN',realGates:'NOT_RUN'});
 }finally{store.close();f.cleanup();}
});

test('real Runtime composition reads migrated library, historical source and cached data with preserved ownership',async()=>{
 const f=fixture();let instance:ReturnType<typeof composeAppsRuntime>|undefined;
 try{
  const source=new AppStore(f.database),storedTemplate=source.get<any>('templates','template')!;source.put('templates','template',{...storedTemplate,savedAt:at});source.close();
  await migrateOffline(f.options);instance=composeAppsRuntime(f.target,{connections:[]});
  const original=instance.store.get<any>('components','component');assert.equal(original.view.ownerSessionId,null);assert.deepEqual(original.legacyTemplate,originalTemplate);assert.deepEqual(instance.store.get<any>('component_versions','component:1').legacyTemplate,originalTemplate);assert.equal(instance.store.get<any>('views','draft').ownerSessionId,'s');assert.equal(instance.store.list<any>('session_app_bindings').find(row=>row.appId==='hallmark').enabled,false);
  const sources=instance.presentation.sources!;assert.equal(sources.verify(f.first.buildId).valid,true);assert.equal(sources.manifest(f.first.buildId)?.buildId,f.first.buildId);assert.equal(sources.readFile(f.first.buildId,'index.html')?.bytes.toString(),'<div>Version one</div>');assert.equal(sources.readFile(f.second.buildId,'index.html')?.bytes.toString(),'<div>Version two</div>');
  assert.throws(()=>instance!.presentation.ownedView('viewer','draft'),/another session/);const cached=instance.presentation.getData('s','draft');assert.equal((cached.bindings[0].payload as any).products[0].originalField.preserved,true);assert.equal(cached.bindings[0].freshness,'stale');assert.equal(cached.bindings[0].sourceDataTime,null);
  instance.runtime.bind({sessionId:'viewer',appId:'apps',connectionId:'presentation',enabled:true,boundAt:new Date().toISOString()});
  const invoke=(capabilityId:string,input:any)=>instance!.runtime.invoke({protocolVersion:'1.0',invocationId:`library:${capabilityId}`,traceId:'library',appId:'apps',connectionId:'presentation',capabilityId,capabilityVersion:'1.0.0',input,source:{kind:'agent',sessionId:'viewer',nativeCallId:'library'},deadlineAt:new Date(Date.now()+10000).toISOString()});
  const library=await invoke('apps.presentation.list_saved',{});assert.equal(library.status,'ok',JSON.stringify(library));if(library.status==='ok'){assert.equal((library.data as any).components.length,1);assert.equal((library.data as any).assets.length,3);assert.equal((library.data as any).components[0].view.ownerSessionId,null);const dataEntry=(library.data as any).assets.find((asset:any)=>asset.assetId==='data-entry');assert.deepEqual(dataEntry.legacyBinding,originalBinding);assert.deepEqual(dataEntry.legacyFieldOrder,['name','offerId']);assert.equal(dataEntry.binding.connectionId,'explicit-backend');const projected=projectLegacyPresentationResult('hallmark_list_saved',library,instance.runtime).data as any;assert.deepEqual(projected.entries.map((entry:any)=>entry.id),['component-entry','data-entry']);assert.deepEqual(projected.entries[1].binding,originalBinding);}
  const legacyLibrary=projectLegacyPresentationResult('hallmark_list_saved',library,instance.runtime).data as any;assert.deepEqual(legacyLibrary.components[0].template,originalTemplate);assert.equal(legacyLibrary.templates[0].savedAt,at);assert.equal(instance.store.get<any>('saved_assets','template:template').savedAt,at);
  const opened=await invoke('apps.presentation.open_component',{componentId:'component',revision:1});assert.equal(opened.status,'ok',JSON.stringify(opened));assert.ok(opened.status==='ok');const view=opened.data as any;assert.equal(view.source.buildId,f.first.buildId);assert.equal(view.ownerSessionId,'viewer');assert.equal(readFileSync(join(view.source.directory,'src.tsx'),'utf8'),'export default () => "original source";');assert.equal(readFileSync(join(view.source.directory,'dist','index.html'),'utf8'),'<div>Version one</div>');assert.equal((instance.presentation.getData('viewer',view.viewId).bindings[0].payload as any).products[0].originalField.preserved,true);
  assert.equal(instance.store.get<any>('components','component').view.ownerSessionId,null);assert.equal(instance.store.get<any>('views','draft').ownerSessionId,'s');assert.equal(instance.store.list('operations').length,1);
  const legacy=createLegacyPresentationAdapter(instance.presentation,instance.runtime),openedEntry=await legacy.handle('/ui/open-entry','POST',{entryId:'data-entry'},'viewer') as any;assert.deepEqual(openedEntry.bindings[0].query,originalBinding.query);assert.deepEqual(openedEntry.widgets[0].columns,[{field:'name',label:'title'},{field:'offerId',label:'商品标识'}]);
  const saved=await instance.runtime.invoke({protocolVersion:'1.0',invocationId:'library:explicit-save',traceId:'library',appId:'apps',connectionId:'presentation',capabilityId:'apps.presentation.save_component',capabilityVersion:'1.0.0',input:{viewId:view.viewId,mode:'update',componentId:'component',expectedRevision:2,userRequest:'保存打开的历史版本',title:'Restored historical source'},source:{kind:'agent',sessionId:'viewer',nativeCallId:'library-save'},deadlineAt:new Date(Date.now()+10000).toISOString(),idempotencyKey:'library-explicit-save'});assert.equal(saved.status,'ok',JSON.stringify(saved));assert.ok(saved.status==='ok');assert.equal((saved.data as any).revision,3);assert.equal((saved.data as any).view.source.buildId,f.first.buildId);const entries=instance.store.list<any>('saved_assets').filter(asset=>asset.kind==='entry'&&asset.componentId==='component');assert.equal(entries.length,1);assert.equal(entries[0].assetId,'component-entry');assert.equal(entries[0].pinned,true);assert.equal(entries[0].order,0);assert.equal(instance.store.list('saved_assets').length,3);assert.equal(instance.store.list('component_versions').length,3);assert.equal(instance.store.get<any>('views','draft').ownerSessionId,'s');assert.deepEqual(instance.store.get<any>('saved_assets','entry:data-entry').legacyBinding,originalBinding);
  emit('TODO-023-composition',{libraryStatus:library.status,sourceManifestVerified:true,historicalSourceRead:true,cachedDataPreserved:true,originalOwnerPreserved:true,openingCreatesExplicitNewOwner:true,legacyFieldMapAndQueryPreserved:true,legacyColumnOrderPreserved:true,legacyResolvedTemplateSnapshotPreserved:true,originalTemplateSavedAtPreserved:at,explicitHistoricalSaveCreatesRevision:3,componentEntryAssetIdPreserved:'component-entry',componentEntryPinAndOrderPreserved:true,duplicateComponentEntryCreated:false,businessMutationCount:0});
 }finally{await instance?.close();f.cleanup();}
});
test('GC dry-run retains saved history and referenced builds, applies only unchanged unreferenced plans',()=>{
 const f=fixture(),store=new RuntimeStore(':memory:');try{const saved='b'.repeat(64),orphan='a'.repeat(64);for(const buildId of [saved,orphan]){const path=join(f.target,'source-components','builds',buildId);mkdirSync(path,{recursive:true});writeFileSync(join(path,'asset.txt'),'fixture bytes');store.put('builds',buildId,{buildId,createdAt:'2000-01-01T00:00:00Z'});}store.put('component_versions','saved:1',{componentId:'saved',revision:1,view:{viewId:'saved-view',source:{buildId:saved}}});const plan=gcDryRun(store,f.target);assert.deepEqual(plan.candidates.map(row=>row.id),[orphan]);assert.equal(existsSync(plan.candidates[0].path!),true);const stale=structuredClone(plan);store.put('artifact_refs','new',{ownerKind:'view',ownerId:'new',targetKind:'build',targetId:orphan});assert.throws(()=>applyGC(store,stale),/GC_PLAN_STALE/);store.delete('artifact_refs','new');const fresh=gcDryRun(store,f.target),result=applyGC(store,fresh);assert.equal(result.deleted.length,1);assert.equal(existsSync(join(f.target,'source-components','builds',orphan)),false);assert.equal(existsSync(join(f.target,'source-components','builds',saved)),true);assert.equal(store.list('component_versions').length,1);emit('TODO-025-gc',{dryRun:plan,result,savedHistoryRetained:true,stalePlanRejected:true});}finally{store.close();f.cleanup();}
});

test('GC retains assets referenced by operation, Provider and migration evidence',()=>{
 const f=fixture(),store=new RuntimeStore(':memory:');
 try{
  const retained='c'.repeat(64);mkdirSync(join(f.target,'source-components','builds',retained),{recursive:true});store.put('builds',retained,{buildId:retained,createdAt:'2000-01-01T00:00:00Z'});store.put('migration_records','evidence',{legacyValue:{source:{buildId:retained}}});
  const before=gcDryRun(store,f.target);assert.equal(before.candidates.length,0);assert.ok(before.retained.some(row=>row.id===retained&&row.reason==='asset_reference'));store.delete('migration_records','evidence');const planned=gcDryRun(store,f.target);assert.equal(planned.candidates.length,1);
  store.put('provider_records','evidence',{value:{source:{buildId:retained},state:'unknown'}});assert.throws(()=>applyGC(store,planned),/GC_PLAN_STALE/);assert.equal(gcDryRun(store,f.target).candidates.length,0);assert.equal(store.list('provider_records').length,1);assert.ok(existsSync(join(f.target,'source-components','builds',retained)));emit('TODO-025-evidence-retention',{migrationReferenceRetained:true,newProviderEvidenceInvalidatesPlan:true,unresolvedEvidencePreserved:true});
 }finally{store.close();f.cleanup();}
});
