import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,readFileSync,writeFileSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {RuntimeStore} from '../../packages/app-runtime/src/store.ts';
import {schema4DryRun,migrateSchema4,verifySchema4Backup,restoreSchema3Backup} from '../../packages/app-migration/src/schema4.ts';

test('schema3 migration is offline, separate, complete, reentrant and recoverable without invented validation',async()=>{
 const root=mkdtempSync(join(tmpdir(),'apps-schema4-')),source=join(root,'source'),target=join(root,'target');mkdirSync(source);let store=new RuntimeStore(join(source,'apps.db'),{schemaVersion:3});
 try{store.put('views','owned',{viewId:'owned',ownerSessionId:'owner',title:'legacy',source:{buildId:'a'.repeat(64)}});store.put('views','unknown',{viewId:'unknown',ownerSessionId:null,title:'owner unknown'});store.put('component_versions','saved:1',{componentId:'saved',revision:1,view:{viewId:'saved-view'}});store.close();mkdirSync(join(source,'authoring-evidence'));writeFileSync(join(source,'authoring-evidence','historic.log'),'retain me');const bytes=readFileSync(join(source,'apps.db'));assert.throws(()=>new RuntimeStore(join(source,'apps.db')),/OFFLINE_MIGRATION_REQUIRED/);const options={sourceDirectory:source,targetDirectory:target,offlineConfirmed:true};const dry=schema4DryRun(options);assert.equal(dry.sourceSchemaVersion,3);assert.equal(dry.files.length,1);const report=await migrateSchema4(options);assert.equal(report.status,'migrated');assert.deepEqual(readFileSync(join(source,'apps.db')),bytes);verifySchema4Backup(report.backupDirectory!);assert.equal((await migrateSchema4(options)).migrationId,report.migrationId);store=new RuntimeStore(join(target,'apps.db'));assert.equal(store.schemaVersion,4);assert.equal(store.get<any>('views','owned').validationStatus,'legacy_unverified');assert.equal(store.get<any>('views','unknown').ownerSessionId,null);assert.equal(store.list('build_receipts').length,0);assert.equal(store.list('preview_receipts').length,0);assert.equal(store.list('component_versions').length,1);store.close();const restored=join(root,'restore');restoreSchema3Backup(report.backupDirectory!,restored);store=new RuntimeStore(join(restored,'apps.db'),{schemaVersion:3});assert.equal(store.get<any>('views','owned').validationStatus,undefined);assert.equal(readFileSync(join(restored,'authoring-evidence','historic.log'),'utf8'),'retain me');}finally{store.close();assert.ok(resolve(root).startsWith(resolve(tmpdir())));rmSync(root,{recursive:true,force:true});}
});
test('active source writer blocks schema migration and new receipt collections preserve immutable evidence',()=>{
 const root=mkdtempSync(join(tmpdir(),'apps-schema4-')),source=join(root,'source');mkdirSync(source);const old=new RuntimeStore(join(source,'apps.db'),{schemaVersion:3});old.close();writeFileSync(join(source,'runtime-writer.json'),JSON.stringify({pid:process.pid,ownerId:'actual-running-test'}));assert.throws(()=>schema4DryRun({sourceDirectory:source,targetDirectory:join(root,'target'),offlineConfirmed:true}),/SOURCE_WRITER_STILL_ACTIVE/);const current=new RuntimeStore(':memory:');try{for(const table of ['build_receipts','preview_receipts']){current.put(table,'receipt',{receiptId:'receipt'});assert.throws(()=>current.put(table,'receipt',{receiptId:'receipt'}),/IMMUTABLE_EVIDENCE/);assert.throws(()=>current.delete(table,'receipt'),/EVIDENCE_DELETE_FORBIDDEN/);}}finally{current.close();assert.ok(resolve(root).startsWith(resolve(tmpdir())));rmSync(root,{recursive:true,force:true});}
});
