/** Reusable chat component workspace. Every rule is scoped to these three exported UI surfaces. */
export const CHAT_STYLES = `
.hm-root.hm-chat-workspace,.hm-root.hm-chat-trigger{--hm-accent:#2563eb;--hm-on-accent:#fff;--hm-bg:var(--dsw-alias-bg-base,#fff);--hm-text:var(--dsw-alias-label-primary,#172033);--hm-muted:var(--dsw-alias-label-secondary,#667085);--hm-line:var(--dsw-alias-border-l2,#e4e8ef);--hm-surface:var(--dsw-alias-bg-layer-1,#fff);--hm-soft:color-mix(in srgb,var(--hm-accent) 7%,var(--hm-bg));--hm-positive:#138a50;color:var(--hm-text)}
body[data-ds-dark-theme] .hm-root.hm-chat-workspace,body[data-ds-dark-theme] .hm-root.hm-chat-trigger{--hm-accent:#7aaaff;--hm-on-accent:#101f38;--hm-positive:#5edda0}
.hm-root.hm-session-components.hm-chat-workspace{padding:0;height:100%;min-height:0;min-width:0;overflow:auto;background:var(--hm-bg);scrollbar-color:var(--hm-line) var(--hm-bg);container-type:inline-size}
.hm-chat-workspace .hm-chat-workspace-header{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:12px;padding:19px 18px 18px;border-bottom:1px solid var(--hm-line);background:var(--hm-surface)}
.hm-chat-workspace .hm-chat-brand{display:flex;align-items:center;gap:11px;min-width:0}.hm-chat-workspace .hm-chat-brand-mark{display:flex;align-items:center;justify-content:center;width:39px;height:42px;flex:none;border-radius:10px;color:var(--hm-accent);background:var(--hm-soft);font-size:29px;font-weight:750;line-height:1}.hm-chat-workspace .hm-chat-brand-name{display:block;margin-bottom:2px;color:var(--hm-muted);font-size:11px;line-height:1.2}.hm-chat-workspace .hm-chat-brand h3{font-size:16px;font-weight:650;line-height:1.5;letter-spacing:-.015em}
.hm-chat-workspace button.hm-chat-refresh{flex:none;padding:7px 9px;border-radius:8px;border-color:var(--hm-line);background:var(--hm-bg);font-size:11px;color:var(--hm-muted);gap:5px}.hm-chat-workspace button.hm-chat-refresh:hover:not(:disabled){color:var(--hm-accent);border-color:color-mix(in srgb,var(--hm-accent) 40%,var(--hm-line));background:var(--hm-soft)}
.hm-chat-workspace .hm-chat-workspace-body{padding:18px;min-width:0}.hm-chat-workspace .hm-chat-workspace-body>.hm-error{margin-bottom:16px;background:var(--hm-surface);font-size:12px;overflow-wrap:anywhere}.hm-chat-workspace .hm-chat-workspace-body>.hm-skeleton{padding:9px 2px}.hm-chat-workspace .hm-chat-workspace-body>.hm-skeleton span{background:var(--hm-soft);border:0;border-radius:5px}.hm-chat-workspace .hm-chat-workspace-body>.hm-skeleton span:last-child{background:none;height:auto;color:var(--hm-muted)}
.hm-chat-workspace .hm-chat-list-heading{display:flex;justify-content:space-between;align-items:center;gap:12px;margin:0 1px 12px;color:var(--hm-muted);font-size:11px}.hm-session-components.hm-chat-workspace .hm-session-view-list{gap:10px;margin:0}.hm-session-components.hm-chat-workspace .hm-session-view-list button.hm-chat-component-card{display:flex;align-items:center;justify-content:flex-start;gap:12px;min-height:91px;padding:15px 13px;border:1px solid var(--hm-line);border-radius:11px;background:var(--hm-surface);text-align:left;box-shadow:0 2px 4px #17203303;transition:background 120ms,border-color 120ms,box-shadow 120ms}.hm-session-components.hm-chat-workspace .hm-session-view-list button.hm-chat-component-card:hover:not(:disabled){background:var(--hm-soft);border-color:color-mix(in srgb,var(--hm-accent) 38%,var(--hm-line));box-shadow:0 3px 10px #17203308}.hm-session-components.hm-chat-workspace .hm-session-view-list button.hm-chat-component-card:disabled{opacity:.72}
.hm-chat-workspace .hm-chat-card-icon{display:flex;align-items:center;justify-content:center;width:39px;height:42px;flex:none;border-radius:9px;background:var(--hm-soft);color:var(--hm-accent)}.hm-chat-workspace .hm-chat-card-copy{display:grid;gap:7px;min-width:0;flex:1}.hm-session-components.hm-chat-workspace .hm-chat-card-copy strong{font-size:13px;font-weight:600;line-height:1.55;overflow-wrap:anywhere}.hm-chat-workspace .hm-chat-card-meta{display:flex;align-items:center;flex-wrap:wrap;gap:7px 12px;font-size:10px;color:var(--hm-muted)}.hm-chat-workspace .hm-chat-card-status{display:inline-flex;align-items:center;gap:5px;white-space:nowrap}.hm-chat-workspace .hm-chat-card-status::before{content:'';width:5px;height:5px;flex:none;border-radius:50%;background:var(--hm-muted)}.hm-chat-workspace .hm-chat-card-status[data-state=ready]::before{background:var(--hm-positive)}.hm-chat-workspace .hm-chat-card-meta time{white-space:nowrap}.hm-chat-workspace .hm-chat-card-open{flex:none;color:var(--hm-accent)}.hm-chat-workspace .hm-chat-component-card:disabled .hm-chat-card-icon,.hm-chat-workspace .hm-chat-component-card:disabled .hm-chat-card-open{color:var(--hm-muted)}.hm-chat-workspace .hm-chat-list-note{margin:16px 2px 0;color:var(--hm-muted);font-size:11px;line-height:1.8}
.hm-session-components.hm-chat-workspace .hm-sidebar-toolbar{display:flex;align-items:center;justify-content:space-between;flex-wrap:wrap;gap:9px;margin:0 0 15px}.hm-chat-workspace .hm-sidebar-toolbar>button{padding:7px 9px;min-height:32px;border-radius:8px;font-size:11px;gap:5px}.hm-chat-workspace .hm-sidebar-toolbar>button.hm-chat-back{padding-left:1px;border-color:transparent;background:transparent;color:var(--hm-muted)}.hm-chat-workspace .hm-chat-back>svg{transform:rotate(180deg)}.hm-chat-workspace .hm-sidebar-toolbar>button.hm-chat-back:hover{color:var(--hm-accent)}.hm-chat-workspace .hm-sidebar-toolbar>button.hm-chat-open-workspace{background:var(--hm-accent);border-color:var(--hm-accent);color:var(--hm-on-accent)}.hm-chat-workspace .hm-sidebar-toolbar>button.hm-chat-open-workspace:hover{background:color-mix(in srgb,var(--hm-accent) 90%,#000)}
.hm-chat-workspace .hm-chat-detail{min-width:0}.hm-chat-workspace .hm-chat-detail>.hm-view{padding:15px;margin:0;border-radius:11px;background:var(--hm-surface);min-width:0}.hm-chat-workspace .hm-chat-detail>.hm-view>.hm-head{display:flex;align-items:flex-start;flex-direction:column;gap:12px;margin-bottom:17px}.hm-chat-workspace .hm-chat-detail>.hm-view>.hm-head h3{font-size:15px;line-height:1.65;overflow-wrap:anywhere}.hm-chat-workspace .hm-chat-detail .hm-actions{gap:7px}.hm-chat-workspace .hm-chat-detail .hm-actions>button{font-size:11px;padding:5px 8px;min-height:29px}.hm-chat-workspace .hm-chat-detail .hm-footer{font-size:10px;line-height:1.7;color:var(--hm-muted)}.hm-chat-workspace .hm-chat-detail .hm-empty{background:var(--hm-surface);padding:19px;font-size:12px;line-height:1.8;overflow-wrap:anywhere}.hm-chat-workspace .hm-chat-detail .hm-empty p{color:var(--hm-muted)}
.hm-chat-workspace .hm-chat-empty{display:flex;flex-direction:column;align-items:center;text-align:center;gap:12px;padding:34px 12px 26px;min-height:340px}.hm-chat-workspace .hm-chat-empty-art{position:relative;width:100px;height:86px;margin:7px 0 9px}.hm-chat-workspace .hm-chat-empty-sheet{position:absolute;inset:1px 16px 7px 0;display:flex;align-items:center;justify-content:center;background:var(--hm-soft);border:1px solid color-mix(in srgb,var(--hm-accent) 19%,var(--hm-line));border-radius:15px;color:var(--hm-accent);transform:rotate(-5deg)}.hm-chat-workspace .hm-chat-empty-chart{position:absolute;right:0;bottom:0;display:flex;align-items:center;justify-content:center;width:44px;height:44px;background:var(--hm-surface);border:1px solid var(--hm-line);border-radius:12px;color:var(--hm-accent);box-shadow:0 4px 10px #17203308}.hm-chat-workspace .hm-chat-empty h3{font-size:16px;font-weight:600;line-height:1.6}.hm-chat-workspace .hm-chat-empty>p{max-width:280px;font-size:12px;line-height:1.9;color:var(--hm-muted)}.hm-chat-workspace .hm-chat-prompt-example{margin-top:8px;padding:13px 15px;border:1px solid var(--hm-line);border-radius:10px;background:var(--hm-surface);text-align:left;max-width:100%;font-size:11px;line-height:1.8;user-select:text}.hm-chat-workspace .hm-chat-prompt-example>span{display:flex;align-items:center;gap:6px;color:var(--hm-muted)}.hm-chat-workspace .hm-chat-prompt-example>p{margin-top:5px;color:var(--hm-text);overflow-wrap:anywhere}
.hm-root.hm-session-button.hm-chat-trigger>button{display:inline-flex;align-items:center;gap:6px;padding:6px 9px;font-size:12px;line-height:1.4;color:var(--hm-accent);background:var(--hm-soft);border:1px solid color-mix(in srgb,var(--hm-accent) 13%,var(--hm-line));border-radius:8px}.hm-root.hm-session-button.hm-chat-trigger>button:hover{background:color-mix(in srgb,var(--hm-accent) 12%,var(--hm-bg));border-color:color-mix(in srgb,var(--hm-accent) 36%,var(--hm-line))}.hm-root.hm-session-button.hm-chat-trigger .hm-button-notice{font-size:11px;line-height:1.7;box-shadow:0 4px 15px #17203312;overflow-wrap:anywhere}.hm-chat-tab-title{display:inline-flex;align-items:center;gap:7px;font:inherit;color:inherit;min-width:0}.hm-chat-tab-title>svg{flex:none;color:#2563eb}body[data-ds-dark-theme] .hm-chat-tab-title>svg{color:#7aaaff}
@container(max-width:350px){.hm-chat-workspace .hm-chat-workspace-header{padding:16px 13px;gap:10px}.hm-chat-workspace .hm-chat-workspace-body{padding:14px 12px}.hm-chat-workspace .hm-chat-brand{gap:8px}.hm-chat-workspace .hm-chat-brand-mark{width:34px;height:38px;font-size:26px}.hm-chat-workspace .hm-chat-brand h3{font-size:15px}.hm-chat-workspace button.hm-chat-refresh{padding:6px 7px;font-size:10px}.hm-session-components.hm-chat-workspace .hm-session-view-list button.hm-chat-component-card{padding:12px 10px;gap:10px}.hm-chat-workspace .hm-chat-card-icon{width:33px;height:36px}.hm-chat-workspace .hm-chat-card-open{width:14px;height:14px}.hm-chat-workspace .hm-chat-detail>.hm-view{padding:12px}.hm-chat-workspace .hm-chat-empty{padding:28px 4px 20px}.hm-chat-workspace .hm-chat-empty>p{max-width:245px}}
@container(max-width:260px){.hm-chat-workspace .hm-chat-workspace-header{align-items:flex-start}.hm-chat-workspace .hm-chat-refresh{margin-left:auto}.hm-chat-workspace .hm-chat-card-icon{display:none}.hm-chat-workspace .hm-sidebar-toolbar{align-items:flex-start}.hm-chat-workspace .hm-chat-prompt-example{padding:11px}.hm-chat-workspace .hm-chat-empty h3{font-size:14px}}
@media(prefers-reduced-motion:reduce){.hm-chat-workspace button,.hm-chat-trigger>button{transition:none}}
.hm-chat-workspace .hm-chat-manage-toggle{width:auto;display:inline-flex;align-items:center;gap:5px;font-size:11px;padding:5px 8px;min-height:28px;border-radius:7px}.hm-chat-workspace .hm-chat-manage-toggle[aria-pressed=true]{color:var(--hm-accent);background:var(--hm-soft)}
.hm-chat-workspace .hm-chat-management-help{margin:0 0 12px;color:var(--hm-muted);font-size:11px;line-height:1.8;overflow-wrap:anywhere}.hm-chat-workspace .hm-chat-card-management{padding:10px 11px;background:var(--hm-surface);border:1px solid var(--hm-line);border-top:0;border-radius:0 0 10px 10px;margin-top:-7px;position:relative}
.hm-chat-workspace .hm-chat-management-actions{display:flex;flex-wrap:wrap;gap:7px;align-items:center}.hm-session-components.hm-chat-workspace .hm-chat-management-actions button{width:auto;min-height:29px;padding:5px 9px;display:inline-flex;font-size:11px;border-radius:7px;line-height:1.5}.hm-chat-workspace button.hm-chat-remove{color:var(--hm-danger,#c5343a)}
.hm-chat-workspace .hm-chat-management-editor{font-size:12px;line-height:1.7;min-width:0;overflow-wrap:anywhere}.hm-chat-workspace .hm-chat-management-editor label{display:grid;gap:6px;color:var(--hm-muted);font-size:11px}.hm-chat-workspace .hm-chat-management-editor input{box-sizing:border-box;width:100%;min-width:0;margin:0 0 9px;background:var(--hm-bg);color:var(--hm-text);font:inherit;font-size:12px}.hm-chat-workspace .hm-chat-management-editor p{margin:0 0 8px}.hm-chat-workspace .hm-chat-management-editor .hm-chat-management-error{color:var(--hm-danger,#c5343a);margin:9px 0 0}.hm-chat-workspace .hm-chat-management-notice{color:var(--hm-accent);font-size:11px;line-height:1.8;margin:0 0 12px;padding:8px 10px;background:var(--hm-soft);border-radius:7px}
`;
