import { test } from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { AppsRuntime, RuntimeStore } from '../../packages/app-runtime/src/index.ts';
import { NotesProvider } from '../../packages/app-notes/src/index.ts';
import type { InvocationRequest, CapabilityResult } from '../../packages/app-contracts/src/index.ts';
function fixture(){const store=new RuntimeStore(':memory:'),provider=new NotesProvider({store}),runtime=new AppsRuntime(store);runtime.register(provider);for(const connectionId of ['one','two']){runtime.addConnection({appId:'notes',connectionId,displayName:connectionId,config:{backend:'local-notes'},configRevision:1,enabled:true});runtime.bind({sessionId:'s',appId:'notes',connectionId,enabled:true,boundAt:new Date().toISOString()});}const invoke=(action:string,input:any,extra:Partial<InvocationRequest>={})=>runtime.invoke({protocolVersion:'1.0',invocationId:randomUUID(),traceId:randomUUID(),appId:'notes',connectionId:'one',capabilityId:`notes.notes.${action}`,capabilityVersion:'1.0.0',input,source:{kind:'agent',sessionId:'s',nativeCallId:randomUUID()},deadlineAt:new Date(Date.now()+30000).toISOString(),...extra});return {store,runtime,provider,invoke};}
function data(result:CapabilityResult):any{assert.ok('data' in result,JSON.stringify(result));return result.data;}
test('Notes completes list/get/create/update with generic note ResourceRef and connection isolation',async()=>{const f=fixture();try{const created=await f.invoke('create',{id:'N-1',title:'原始标题',content:'内容'},{idempotencyKey:'create'});assert.equal(created.status,'ok');assert.deepEqual(data(created).resource,{appId:'notes',connectionId:'one',resourceType:'note',resourceId:'N-1',revision:'1'});assert.equal(data(await f.invoke('get',{id:'N-1'})).note.content,'内容');assert.equal(data(await f.invoke('list',{})).total,1);assert.equal(data(await f.invoke('list',{}, {connectionId:'two'})).total,0);const updated=await f.invoke('update',{id:'N-1',content:'已编辑'},{idempotencyKey:'update',expectedResourceRevision:'1'});assert.equal(data(updated).note.revision,'2');assert.equal(data(updated).note.title,'原始标题');assert.equal(data(await f.invoke('get',{id:'N-1'})).note.content,'已编辑');assert.equal(f.store.list('operations').length,2);}finally{await f.runtime.dispose();f.store.close();}});
test('CAS lets only one update at the same expected revision succeed',async()=>{const f=fixture();try{await f.invoke('create',{id:'n',title:'T',content:'C'},{idempotencyKey:'c'});const results=await Promise.all([f.invoke('update',{id:'n',content:'A'},{idempotencyKey:'a',expectedResourceRevision:'1'}),f.invoke('update',{id:'n',content:'B'},{idempotencyKey:'b',expectedResourceRevision:'1'})]);assert.equal(results.filter(result=>result.status==='ok').length,1);const failed=results.find(result=>result.status==='failed')!;assert.ok('error' in failed);assert.equal(failed.error.code,'REVISION_CONFLICT');assert.equal(data(await f.invoke('get',{id:'n'})).note.revision,'2');}finally{await f.runtime.dispose();f.store.close();}});
test('same intent and inspect reuse original evidence without creating another note or operation',async()=>{const f=fixture();try{const input={title:'T',content:'C'},first=await f.invoke('create',input,{idempotencyKey:'same'}),retry=await f.invoke('create',input,{idempotencyKey:'same'});assert.equal(first.operation?.operationId,retry.operation?.operationId);assert.equal(data(first).note.id,data(retry).note.id);const inspected=await f.provider.inspect(first.operation!.operationId,{request:{protocolVersion:'1.0',invocationId:'inspect',traceId:'trace',appId:'notes',connectionId:'one',capabilityId:'notes.notes.create',capabilityVersion:'1.0.0',input,source:{kind:'recovery',operationId:first.operation!.operationId},deadlineAt:new Date(Date.now()+10000).toISOString()},signal:new AbortController().signal});assert.equal(inspected.status,'ok');assert.equal(inspected.invocationId,'inspect');assert.equal(data(await f.invoke('list',{})).total,1);assert.equal(f.store.list('operations').length,1);}finally{await f.runtime.dispose();f.store.close();}});
test('ordinary query errors preserve note ID case and writes require existing revision',async()=>{const f=fixture();try{await f.invoke('create',{id:'CaseSensitive',title:'T',content:'C'},{idempotencyKey:'c'});const missing=await f.invoke('get',{id:'casesensitive'});assert.equal(missing.status,'failed');if('error' in missing)assert.equal(missing.error.code,'RESOURCE_NOT_FOUND');const noRevision=await f.invoke('update',{id:'CaseSensitive',content:'X'},{idempotencyKey:'u'});assert.equal(noRevision.status,'needs_clarification');assert.equal(data(await f.invoke('get',{id:'CaseSensitive'})).note.content,'C');}finally{await f.runtime.dispose();f.store.close();}});
