import {test} from 'node:test';
import assert from 'node:assert/strict';
import {AppStore} from '../../packages/store/index.ts';
import {AppCore} from '../../packages/core/src/index.ts';
import {PresentationManager} from '../../packages/presentation/src/index.ts';
import type {CoreOptions} from '../../packages/core/src/types.ts';
const ok=(raw:any)=>({status:'ok' as const,raw,provenance:{source:'hallmark_snapshot' as const,fetchedAt:'2026-10-05T10:00:00Z'}});
function setup(){const store=new AppStore(':memory:');store.put('session_apps','s',{active:true,appId:'hallmark'});const writes:any[]=[];let rows:any[]=[];
 const client:CoreOptions['client']={getStores:async()=>ok([{id:'shop',shopName:'Shop'}]),getStoreProducts:async()=>ok({stores:[{id:'shop'}],products:[{storeId:'shop',offerId:'123',productId:44,profit:{costMinor:20,actualMargin:0.1}}]}),syncStoreProducts:async()=>ok({}),getTargetMargin:async()=>ok({}),searchCollectedItems:async()=>({...ok([{id:'1'},{id:'2'}]),matches:[{id:'2'}]}),getCollectedItem:async()=>({...ok({content:'x'.repeat(10000),id:'item',truncated:false}),spill:{path:'synthetic.json',bytes:10000,cursor:'0',summary:{kind:'object'}}}),platformCall:async(id,input)=>{writes.push(input);return ok({outcome:'response_received',response:{result:[{updated:true}]}});},platformRead:async()=>ok({response:{result:{items:rows}}})};
 const broker={getStoreTask:async()=>ok({taskId:'t'}),getListingTask:async()=>ok({taskId:'l'}),requestId:(kind:string,id:string,n:number)=>`${kind}-${id}-${n}`};const core=new AppCore({store,client,broker,presentation:new PresentationManager(store)});return {store,core,writes,setRows:(value:any[])=>rows=value};}
const request='指定商品调价100RUB',ctx={sessionId:'s',userRequest:request},args={storeId:'shop',offerIds:['123'],price:100,currency:'RUB',valueSource:'user',userRequest:request,clientOperationKey:'p'};
test('missing source dataTime stays unknown on first read, cached read, computed result and refresh',async()=>{const f=setup();for(let i=0;i<2;i++){const result=await f.core.invoke('hallmark_list_store_products',{storeId:'shop'},ctx);assert.equal(result.status,'ok');assert.equal(Object.hasOwn(result.provenance!,'dataTime'),false);assert.equal(f.store.get('snapshots','store_products:shop')!.dataTime,null);}
 const filtered=await f.core.invoke('hallmark_filter_products',{storeId:'shop',maxMargin:0.2},ctx);assert.equal((filtered.data as any).dataTime,null);assert.equal(Object.hasOwn(filtered.provenance!,'dataTime'),false);
 const refreshed=await f.core.refreshDataset('store_products:shop',ctx);assert.equal((refreshed.data as any).snapshot.dataTime,null);assert.equal(Object.hasOwn(refreshed.provenance!,'dataTime'),false);assert.ok((refreshed.data as any).snapshot.lastSuccessAt);assert.equal(refreshed.provenance?.fetchedAt,'2026-10-05T10:00:00Z');f.store.close();});
test('offerId numeric text cannot be verified by another productId of the same numeric value',async()=>{const f=setup();f.setRows([{offer_id:'different',product_id:123,price:{price:'100',currency_code:'RUB'}}]);const result=await f.core.invoke('hallmark_update_price',args,ctx);assert.equal(result.status,'unknown');f.store.close();});
test('productId cannot be verified by another offerId with the same numeric text',async()=>{const f=setup();f.setRows([{offer_id:'44',product_id:123,price:{price:'100',currency_code:'RUB'}}]);const {offerIds,...input}=args;const result=await f.core.invoke('hallmark_update_price',{...input,productIds:['44']},ctx);assert.equal(result.status,'unknown');f.store.close();});
test('price equality without returned currency remains unknown',async()=>{const f=setup();f.setRows([{offer_id:'123',price:{price:'100'}}]);assert.equal((await f.core.invoke('hallmark_update_price',args,ctx)).status,'unknown');f.store.close();});
test('requested oldPrice also requires readback equality',async()=>{const f=setup();f.setRows([{offer_id:'123',price:{price:'100',currency_code:'RUB',old_price:'500'}}]);assert.equal((await f.core.invoke('hallmark_update_price',{...args,oldPrice:200},ctx)).status,'unknown');f.store.close();});
test('stock warehouse and product IDs must be canonical positive integer strings before any dispatch',async()=>{const f=setup();const result=await f.core.invoke('hallmark_update_stock',{...args,price:undefined,currency:undefined,stock:0,warehouseId:'001'} as any,ctx);assert.equal(result.status,'failed');const {price,currency,...base}=args;assert.equal((await f.core.invoke('hallmark_update_stock',{...base,stock:0,warehouseId:'001'},ctx)).status,'needs_clarification');assert.equal(f.writes.length,0);assert.equal(f.store.list('operations').length,0);f.store.close();});
test('activity price is explicitly unsupported, never ordinary-price write or readback',async()=>{const f=setup();assert.equal((await f.core.invoke('hallmark_update_price',{...args,actionId:1},ctx)).error?.code,'ACTION_PRICE_NOT_SUPPORTED');assert.equal(f.writes.length,0);f.store.close();});
test('blank rule source and userRequest mismatch cannot dispatch',async()=>{const f=setup();assert.equal((await f.core.invoke('hallmark_update_price',{...args,valueSource:'rule:   '},ctx)).status,'needs_clarification');assert.equal((await f.core.invoke('hallmark_update_price',{...args,userRequest:'other'},ctx)).error?.code,'USER_REQUEST_MISMATCH');assert.equal(f.writes.length,0);f.store.close();});
test('unverified named rules never authorize price, stock or listing assignments',async()=>{const f=setup();const price=await f.core.invoke('hallmark_update_price',{...args,valueSource:'rule:invented-auto-margin'},ctx);assert.equal(price.status,'needs_clarification');assert.deepEqual(price.clarification?.missing,['ruleEvidence']);const {price:ignoredPrice,currency,...base}=args;const stock=await f.core.invoke('hallmark_update_stock',{...base,stock:0,warehouseId:'12',valueSource:'rule:invented-stock'},ctx);assert.equal(stock.status,'needs_clarification');assert.deepEqual(stock.clarification?.missing,['ruleEvidence']);let assignments=0;f.core.options.broker.getListingTask=async()=>{assignments++;return ok({taskId:'listing'});};const listing=await f.core.invoke('hallmark_list_product',{storeId:'shop',collectedItemId:'item',skuScope:['sku'],importItems:[{offer_id:'sku',price:'100'}],clientOperationKey:'listing-rule',userRequest:request,valueSource:'rule:invented-listing'},ctx);assert.equal(listing.status,'needs_clarification');assert.deepEqual(listing.clarification?.missing,['ruleEvidence']);assert.equal(f.writes.length,0);assert.equal(assignments,0);assert.equal(f.store.list('operations').length,0);f.store.close();});
test('search honors matches and returns bounded paged candidate metadata',async()=>{const f=setup();const result=await f.core.invoke('hallmark_search_collected_items',{query:'2',limit:1},ctx);assert.deepEqual((result.data as any).items,[{id:'2'}]);assert.equal((result.data as any).total,1);f.core.options.client.searchCollectedItems=async()=>ok(Array.from({length:250},(_,i)=>({id:String(i),unknownSourceField:'retained'})));const first=await f.core.invoke('hallmark_search_collected_items',{limit:100},ctx);assert.equal((first.data as any).items.length,100);assert.equal((first.data as any).cursor,'100');const second=await f.core.invoke('hallmark_search_collected_items',{limit:100,cursor:'100'},ctx);assert.equal((second.data as any).items[0].id,'100');assert.equal((second.data as any).items[0].unknownSourceField,'retained');f.store.close();});
test('spill never duplicates source raw into tool result',async()=>{const f=setup();const result=await f.core.invoke('hallmark_get_collected_item',{itemId:'item'},ctx);assert.equal(Object.hasOwn(result.data as any,'raw'),false);assert.equal((result.data as any).spill.path,'synthetic.json');f.store.close();});
test('unknown dataset store does not publish a successful empty snapshot',async()=>{const f=setup();const result=await f.core.refreshDatasetBackground('store_products:missing');assert.equal(result.status,'failed');assert.equal(result.error?.code,'STORE_NOT_FOUND');assert.equal(f.store.get('snapshots','store_products:missing')?.payload,undefined);f.store.close();});
