import {test} from 'node:test';
import assert from 'node:assert/strict';
import {AppStore} from '../../packages/store/index.ts';
import {AppCore} from '../../packages/core/src/index.ts';
import {PresentationManager,bindingDatasetKey} from '../../packages/presentation/src/index.ts';
import type {CoreOptions} from '../../packages/core/src/types.ts';
const ok=(raw:any)=>({status:'ok' as const,raw});
function setup(){
 const store=new AppStore(':memory:');store.put('session_apps','s',{appId:'hallmark',active:true});const calls:any[]=[];
 const client:CoreOptions['client']={getStores:async()=>ok([{id:'shop',shopName:'Shop'}]),getStoreProducts:async()=>ok({stores:[{id:'shop',lastSuccessAt:'2026-10-05T00:00:00Z'}],products:[{storeId:'shop',offerId:'A',productId:1,profit:{actualMargin:0.1,costMinor:10}},{storeId:'shop',offerId:'B',productId:2,profit:{actualMargin:null,costMinor:null}}]}),syncStoreProducts:async()=>ok({}),getTargetMargin:async()=>ok({}),searchCollectedItems:async()=>ok([]),getCollectedItem:async()=>ok({}),platformCall:async(id,input)=>{calls.push({write:true,...input});return ok({outcome:'response_received',response:{result:[{updated:true}]}});},platformRead:async(id,input)=>{calls.push({write:false,...input});return input.path==='/v3/product/info/list'?ok({response:{items:[{id:1,offer_id:'A',sku:33}]}}):ok({response:{result:[{offer_id:'A',warehouse_id:12,present:0}]}});}};
 const broker={getStoreTask:async()=>ok({taskId:'t'}),getListingTask:async()=>ok({taskId:'l'}),requestId:(kind:string,id:string,n:number)=>`${kind}-${id}-${n}`};const presentation=new PresentationManager(store);const core=new AppCore({store,client,broker,presentation});return {store,core,calls,presentation};
}
test('stock zero is valid, warehouse explicit and readback verifies exact warehouse',async()=>{const f=setup(),request='Shop 的商品1 在仓12库存改为0';const result=await f.core.invoke('hallmark_update_stock',{storeId:'shop',productIds:['1'],warehouseId:'12',stock:0,valueSource:'user',clientOperationKey:'stock',userRequest:request},{sessionId:'s',userRequest:request});assert.equal(result.status,'ok');assert.deepEqual(f.calls[0].body,{stocks:[{product_id:1,warehouse_id:12,stock:0}]});assert.equal(f.calls[1].path,'/v3/product/info/list');assert.equal(f.calls[2].path,'/v2/product/info/stocks-by-warehouse/fbs');assert.deepEqual(f.calls[2].body,{sku:[33],limit:100});f.store.close();});
test('saved query data binds to its refreshed snapshot without changing design',async()=>{const f=setup();const binding={id:'data',query:{tool:'hallmark_filter_products',params:{storeId:'shop',maxMargin:0.15}},fieldMap:{}};f.presentation.saveEntry(binding,'利润筛选','保存筛选');const key=bindingDatasetKey(binding);assert.ok(f.core.getRefreshCandidates().includes(key));const result=await f.core.refreshDatasetBackground(key);assert.equal(result.status,'ok');const snapshot=f.store.get('snapshots',key)!;assert.equal(snapshot.payload.products.length,1);assert.equal(snapshot.payload.unable.length,1);assert.ok(snapshot.metricBasis);assert.equal(f.calls.length,0);f.store.close();});
test('arbitrary saved write query cannot enter isolated refresh code',async()=>{const f=setup();f.store.put('queries','bad',{tool:'hallmark_update_price',params:{storeId:'shop',price:1}});const result=await f.core.refreshDatasetBackground('query:bad');assert.equal(result.status,'unavailable');assert.equal(result.error?.code,'DATASET_NOT_SUPPORTED');assert.equal(f.calls.length,0);f.store.close();});
test('interrupted refresh recovery marks snapshot and operation failed without replaying or overwriting successful data',async()=>{const f=setup();const datasetKey='store_products:shop';const original=f.store.updateSnapshotSuccess(datasetKey,{products:[{offerId:'old',source:'preserved'}]},'2026-10-05T00:00:00Z');f.store.updateSnapshotState(datasetKey,'refreshing');const timestamp=new Date().toISOString();f.store.put('operations','refresh-crash',{operationId:'refresh-crash',kind:'refresh',sessionId:'background',storeId:'shop',targets:[],input:{datasetKey},state:'running',hallmarkRefs:[],items:[],createdAt:timestamp,updatedAt:timestamp});let remoteCalls=0;f.core.options.client.syncStoreProducts=async()=>{remoteCalls++;return ok({});};f.core.options.client.getStoreProducts=async()=>{remoteCalls++;return ok({});};const results=await f.core.recoverOperations();assert.equal(results.length,1);assert.equal(results[0].status,'failed');assert.equal(results[0].error?.code,'REFRESH_INTERRUPTED');const recovered=f.store.get('snapshots',datasetKey)!;assert.equal(recovered.state,'failed');assert.deepEqual(recovered.payload,original.payload);assert.equal(recovered.dataTime,original.dataTime);assert.equal(recovered.lastSuccessAt,original.lastSuccessAt);assert.equal(recovered.version,original.version);assert.equal(recovered.lastError.code,'REFRESH_INTERRUPTED');assert.equal(f.store.get('operations','refresh-crash')!.state,'failed');assert.equal(remoteCalls,0);assert.equal(f.calls.length,0);assert.deepEqual(await f.core.recoverOperations(),[]);f.store.close();});
test('recovery of an interrupted batch retains explicit unsent items, never claims full success',async()=>{const f=setup();f.store.put('operations','crash',{operationId:'crash',kind:'update_price',sessionId:'s',storeId:'shop',targets:['A','B'],input:{},state:'running',hallmarkRefs:[],items:[{target:'A',state:'succeeded'}],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const results=await f.core.recoverOperations();assert.equal(results[0].status,'partial');const op=results[0].data as any;assert.equal(op.items.length,2);assert.equal(op.items[1].error.code,'NOT_SENT_AFTER_INTERRUPTION');assert.equal(f.calls.length,0);f.store.close();});
