import {after, test} from 'node:test';
import assert from 'node:assert/strict';
import {createHash, randomUUID} from 'node:crypto';
import {existsSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {createServer} from 'node:http';
import {createConnection} from 'node:net';
import {tmpdir} from 'node:os';
import {dirname, join, resolve} from 'node:path';
import {AppsRuntime, RuntimeStore} from '../../packages/app-runtime/src/index.ts';
import {RuntimeWriterLease} from '../../packages/app-runtime/src/lease.ts';
import {AppsPresentationService} from '../../packages/app-presentation/src/index.ts';
import {createAppsServer} from '../../packages/service/src/apps-server.ts';
import {SourceComponentStore} from '../../packages/source-components/src/index.ts';
import {AppsClient, HttpRuntimeTransport} from '../../packages/app-sdk/src/index.ts';
import {AppsHost, HttpAppsHostTransport} from '../../packages/plugin-apps/src/index.ts';
import type {AppProvider, CapabilityDescriptor, CapabilityResult, InvocationRequest} from '../../packages/app-contracts/src/index.ts';
import {validateResult} from '../../packages/app-contracts/src/index.ts';

type Fault='none'|'drop-response'|'drop-response-and-inspection'|'operation-only-inspection'|'drop-read'|'handshake'|'describe'|'connections'|'corrupt-output'|'protocol-rejection'|'mismatched-inspection'|'drop-component';
const evidence:unknown[]=[];
const sha=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
const evidenceRoot=process.env.APPS_TRANSPORT_ERROR_EVIDENCE_DIR?resolve(process.env.APPS_TRANSPORT_ERROR_EVIDENCE_DIR):null;
function save(name:string,value:unknown){if(!evidenceRoot)return;const path=join(evidenceRoot,name);mkdirSync(dirname(path),{recursive:true});writeFileSync(path,JSON.stringify(value,null,2)+'\n',{flag:'wx'});}
after(()=>save('cases.json',{scope:'ISOLATED_REGRESSION',modelClass:'NONE',actualDesktop:false,actualBusiness:false,results:evidence}));
const cap=(effect:'query'|'mutation'):CapabilityDescriptor=>({capabilityId:`transportfixture.rows.${effect}`,version:'1.0.0',title:'Real HTTP transport regression',description:'Isolated Runtime and fault proxy, not real business',effect,inputSchema:{type:'object',properties:{value:{type:'string'}},required:['value'],additionalProperties:false},outputSchema:{type:'object',properties:{value:{type:'string'}},required:['value'],additionalProperties:false},execution:{mode:'sync',timeoutMs:3000,concurrency:effect==='mutation'?'exclusive':'declared_safe',lockScope:'connection',idempotency:effect==='mutation'?'runtime_dedup':'not_applicable',completionEvidence:'response'},discovery:{defaultVisible:false,keywords:[]},aliases:[]});
const listen=(server:ReturnType<typeof createServer>)=>new Promise<number>((done,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',()=>{const address=server.address();assert.ok(address&&typeof address!=='string');assert.ok(![36994,4180,4280].includes(address.port));done(address.port);});});
const probeClosed=(port:number)=>new Promise<{port:number;connected:false;error:string}>((done,reject)=>{const socket=createConnection({host:'127.0.0.1',port});socket.setTimeout(1000);socket.once('connect',()=>{socket.destroy();reject(new Error(`Fixture port ${port} still accepts connections`));});socket.once('timeout',()=>{socket.destroy();reject(new Error(`Fixture port ${port} did not refuse probe`));});socket.once('error',error=>{socket.destroy();done({port,connected:false,error:(error as NodeJS.ErrnoException).code??error.message});});});
async function fixture(label:string){
  const parent=evidenceRoot??tmpdir();mkdirSync(parent,{recursive:true});const directory=mkdtempSync(join(parent,`transport-${label}-`)),lease=new RuntimeWriterLease(directory),store=new RuntimeStore(join(directory,'apps.db')),logs:unknown[]=[],runtime=new AppsRuntime(store,{log:row=>logs.push(row)}),providerEvents:unknown[]=[],http:Record<string,any>[]=[];
  const descriptors=[cap('query'),cap('mutation')];let providerCalls=0,pending=0,fault:Fault='none';
  const provider:AppProvider={manifest:{manifestVersion:1,appId:'transportfixture',displayName:'Transport fixture',providerPackage:'transport-regression',providerVersion:'1.0.0',runtimeProtocolMajor:1,resourceTypes:['row']},descriptors,async execute(context){providerCalls++;pending++;try{const value=(context.request.input as {value:string}).value,receipt={request:context.request,operationId:context.operationId??null,value,at:new Date().toISOString()};providerEvents.push(receipt);save(`${label}/accepted-${context.request.invocationId}.json`,receipt);if(value==='reject')return {invocationId:context.request.invocationId,traceId:context.request.traceId,status:'failed',error:{code:'BUSINESS_REJECTED',message:'Synthetic source explicitly rejected the requested value.',retryPolicy:'never'}};return {invocationId:context.request.invocationId,traceId:context.request.traceId,status:'ok',data:{value}};}finally{pending--; }},async dispose(){}};
  runtime.register(provider);runtime.addConnection({appId:'transportfixture',connectionId:'C1',displayName:'Synthetic C1',config:{},configRevision:1,enabled:true});runtime.bind({sessionId:'fixture-session',appId:'transportfixture',connectionId:'C1',enabled:true,boundAt:new Date().toISOString()});
  const snapshot=()=>Object.fromEntries(store.collections.map(table=>[table,store.db.prepare(`SELECT id,value_json,created_at,updated_at FROM ${table} ORDER BY id`).all()])),stateBefore=snapshot();
  const token=randomUUID()+randomUUID(),sources=new SourceComponentStore(join(directory,'source-archive')),presentation=new AppsPresentationService({store,runtime,sources}),backend=createAppsServer({runtime,presentation,token}),backendPort=await listen(backend),backendURL=`http://127.0.0.1:${backendPort}`;
  const proxy=createServer(async(req,res)=>{
    let body='';for await(const part of req)body+=part;const row:Record<string,any>={at:new Date().toISOString(),method:req.method,path:req.url,body:body?JSON.parse(body):null,fault};http.push(row);
    try{
      if((fault==='handshake'&&req.url==='/v1/runtime')||(fault==='describe'&&req.url?.startsWith('/v1/capabilities/'))||(fault==='connections'&&req.url?.startsWith('/v1/connections'))||(fault==='drop-response-and-inspection'&&req.method==='GET'&&req.url?.startsWith('/v1/invocations/'))){row.droppedBeforeForward=true;req.socket.destroy();return;}
      if(fault==='protocol-rejection'&&req.method==='POST'&&req.url==='/v1/invocations'){body=JSON.stringify({...row.body,protocolVersion:'2.0'});row.forwardedBody=JSON.parse(body);}
      const forwarded=await fetch(new URL(req.url!,backendURL),{method:req.method,headers:{Authorization:`Bearer ${token}`,...(body?{'Content-Type':'application/json'}:{})},...(body?{body}:{}),signal:AbortSignal.timeout(4000)});const value=await forwarded.json();row.backendStatus=forwarded.status;row.backendBody=structuredClone(value);
      if(req.method==='POST'&&req.url==='/v1/invocations'&&['drop-response','drop-response-and-inspection','operation-only-inspection','drop-read','mismatched-inspection'].includes(fault)||req.method==='POST'&&req.url==='/v1/component-bridge'&&fault==='drop-component'){row.acceptedThenResponseLost=true;req.socket.destroy();return;}
      if(fault==='mismatched-inspection'&&req.method==='GET'&&req.url?.startsWith('/v1/invocations/')){value.invocationId='another-invocation';value.result.invocationId='another-invocation';row.corruptedInspectionIdentity=true;}
      if(fault==='operation-only-inspection'&&req.method==='GET'&&req.url?.startsWith('/v1/invocations/')){delete value.result;row.omittedResultRetainedActualOperationId=true;}
      if(req.method==='POST'&&req.url==='/v1/invocations'&&fault==='corrupt-output'){value.data={wrong:true};row.corruptedAfterRuntimeAccepted=true;}
      res.writeHead(forwarded.status,{'Content-Type':'application/json'});res.end(JSON.stringify(value));
    }catch(error){row.error=error instanceof Error?error.message:String(error);if(!res.headersSent&&!res.destroyed){res.writeHead(502,{'Content-Type':'application/json'});res.end(JSON.stringify({error:'PROXY_FAILURE'}));}}
  });
  const port=await listen(proxy),url=`http://127.0.0.1:${port}`,transport=new HttpAppsHostTransport(url,token),agent={id:'fixture-session'},tools=new Map(),host=new AppsHost({agents:{get:id=>id===agent.id?agent:undefined},tools:{register:tool=>{tools.set(tool.name,tool);return()=>tools.delete(tool.name);}}},transport);await host.start();host.attachApp('transportfixture');
  const sdk=new AppsClient(new HttpRuntimeTransport(url,token),{kind:'script',sessionId:agent.id,runId:'transport-regression',stepKey:label},{traceId:'trace-'+label});
  async function close(){await host.dispose();proxy.closeAllConnections();await new Promise<void>(done=>proxy.close(()=>done()));backend.closeAllConnections();await new Promise<void>(done=>backend.close(()=>done()));await runtime.dispose();const state=snapshot();store.close();lease.release();const ports=await Promise.all([probeClosed(port),probeClosed(backendPort)]),leaseExists=existsSync(lease.path);assert.equal(leaseExists,false);assert.equal(pending,0);assert.equal(tools.size,0);assert.equal(proxy.listening,false);assert.equal(backend.listening,false);const row={label,directory,port,backendPort,providerCalls,pending,tools:tools.size,http,providerEvents,logs,stateBefore,state,cleanup:{ports,proxyListening:proxy.listening,backendListening:backend.listening,leasePath:lease.path,leaseExists,leaseReleased:!leaseExists}};evidence.push(row);save(label+'/trace.json',row);}
  return {label,store,runtime,host,transport,sdk,http,descriptors,setFault(value:Fault){fault=value;},providerCalls:()=>providerCalls,async component(effect:'query'|'mutation',invalidBuild=false){const project=join(directory,'component-project');mkdirSync(join(project,'dist'),{recursive:true});writeFileSync(join(project,'package.json'),'{"name":"transport-component-fixture","version":"1.0.0","type":"module"}',{flag:'wx'});writeFileSync(join(project,'package-lock.json'),'{"lockfileVersion":3}',{flag:'wx'});writeFileSync(join(project,'Component.tsx'),'export default function Component(){return null;}',{flag:'wx'});writeFileSync(join(project,'dist/index.html'),'<html><body>Isolated bridge transport regression</body></html>',{flag:'wx'});const view=presentation.openSource(agent.id,project,{bindings:[{bindingId:'rows',appId:'transportfixture',connectionId:'C1',capabilityId:cap('query').capabilityId,capabilityMajor:1,input:{value:'component-binding'},projection:[],refresh:{mode:'manual'}}]}),request={channel:'dsh.apps.component.v2',protocolVersion:'2.0',sessionId:agent.id,viewId:view.viewId,buildId:invalidBuild?'not-the-real-build':view.source!.buildId,frameInstanceId:'regression-frame',requestId:randomUUID(),method:'invokeCapability',params:{appId:'transportfixture',connectionId:'C1',capabilityId:cap(effect).capabilityId,capabilityVersion:'1.0.0',input:{value:'component'},deadlineAt:new Date(Date.now()+3000).toISOString(),...(effect==='mutation'?{idempotencyKey:'component-'+randomUUID()}:{})}};const response=await host.ui(new Request('http://localhost/api/dsh-apps',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'componentBridge',request})}));const packet=await response.json();save(label+'/component-result.json',{request,httpStatus:response.status,packet});return {request,response,packet};},async invoke(entry:'host'|'sdk',effect:'query'|'mutation',value='accepted') {const descriptor=cap(effect),invocationId=label+'-'+randomUUID(),traceId=entry==='sdk'?'trace-'+label:'trace-'+invocationId;const result=entry==='sdk'?await sdk.invoke({appId:'transportfixture',connectionId:'C1'},descriptor,{value},{invocationId,...(effect==='mutation'?{idempotencyKey:invocationId}:{})}):await host.call('apps_invoke',{appId:'transportfixture',connectionId:'C1',capabilityId:descriptor.capabilityId,capabilityVersion:descriptor.version,input:{value},invocationId,traceId,...(effect==='mutation'?{idempotencyKey:invocationId}:{})},agent.id);save(label+'/result-'+invocationId+'.json',{entry,effect,result,invocationId,traceId});return {result:result as CapabilityResult,invocationId,traceId};},close};
}

for(const entry of ['sdk','host'] as const){
  test(`${entry}: lost response with actual operation-only readback is unknown and resolves through inspection without resubmitting`,async()=>{const f=await fixture(entry+'-operation-only');try{f.setFault('operation-only-inspection');const {result,invocationId,traceId}=await f.invoke(entry,'mutation');assert.equal(result.status,'unknown');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.equal(result.operation?.operationId,f.store.list<{operationId:string}>('operations')[0].operationId);assert.equal(result.operation?.state,'unknown');assert.ok('error'in result);assert.equal(result.error.retryPolicy,'inspect_only');assert.deepEqual(validateResult(result),[]);const inspected=await f.transport.inspect(result.operation!.operationId);assert.equal(inspected.status,'ok');assert.equal(inspected.operation?.operationId,result.operation!.operationId);assert.equal(f.providerCalls(),1);assert.equal(f.http.filter(row=>row.path==='/v1/invocations'&&row.method==='POST').length,1);assert.equal(f.http.filter(row=>row.path?.endsWith('/inspect')).length,1);}finally{await f.close();}});
  test(`${entry}: accepted mutation lost response and unavailable readback keeps original identity unavailable/inspect_only without inventing operationId or resubmitting`,async()=>{const f=await fixture(entry+'-lost-unavailable');try{f.setFault('drop-response-and-inspection');const {result,invocationId,traceId}=await f.invoke(entry,'mutation');assert.equal(f.providerCalls(),1);assert.equal(f.http.filter(row=>row.method==='POST'&&row.path==='/v1/invocations').length,1);assert.equal(f.store.list<{state:string}>('operations')[0].state,'succeeded');assert.equal(result.status,'unavailable');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.ok('error'in result);assert.equal(result.error.retryPolicy,'inspect_only');assert.equal(result.operation,undefined,'Unavailable readback must not invent an operation ID');assert.deepEqual(validateResult(result),[]);assert.ok(f.http.some(row=>row.method==='GET'&&row.path===`/v1/invocations/${invocationId}`));}finally{await f.close();}});
  test(`${entry}: accepted mutation response loss recovers the actual original result with one POST`,async()=>{const f=await fixture(entry+'-lost-recovered');try{f.setFault('drop-response');const {result,invocationId}=await f.invoke(entry,'mutation');assert.equal(result.status,'ok');assert.equal(result.invocationId,invocationId);assert.ok(result.operation);assert.equal(result.operation.operationId,f.store.list<{operationId:string}>('operations')[0].operationId);assert.equal(f.providerCalls(),1);assert.equal(f.http.filter(row=>row.path==='/v1/invocations'&&row.method==='POST').length,1);}finally{await f.close();}});
  test(`${entry}: query response loss is unavailable/read_retry and never repeated automatically`,async()=>{const f=await fixture(entry+'-read-lost');try{f.setFault('drop-read');const {result,invocationId,traceId}=await f.invoke(entry,'query');assert.equal(result.status,'unavailable');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.ok('error'in result);assert.equal(result.error.retryPolicy,'read_retry');assert.equal(f.providerCalls(),1);assert.equal(f.store.list('operations').length,0);assert.equal(f.http.filter(row=>row.path==='/v1/invocations').length,1);}finally{await f.close();}});
  test(`${entry}: handshake network failure occurs before any mutation submission`,async()=>{const f=await fixture(entry+'-handshake-offline');try{f.setFault('handshake');const {result,invocationId,traceId}=await f.invoke(entry,'mutation');assert.equal(result.status,'unavailable');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.equal(result.operation,undefined);assert.equal(f.providerCalls(),0);assert.equal(f.http.filter(row=>row.path==='/v1/invocations').length,0);assert.equal(f.store.list('operations').length,0);}finally{await f.close();}});
  test(`${entry}: explicit business rejection remains failed/never with original operation identity`,async()=>{const f=await fixture(entry+'-explicit-rejection');try{const {result,invocationId,traceId}=await f.invoke(entry,'mutation','reject');assert.equal(result.status,'failed');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.ok('error'in result);assert.equal(result.error.code,'BUSINESS_REJECTED');assert.equal(result.error.retryPolicy,'never');assert.equal(result.operation?.state,'failed');assert.equal(f.providerCalls(),1);}finally{await f.close();}});
  test(`${entry}: explicit non2xx Runtime protocol rejection preserves failed/never and zero Provider`,async()=>{const f=await fixture(entry+'-protocol-rejected');try{f.setFault('protocol-rejection');const {result,invocationId,traceId}=await f.invoke(entry,'mutation');assert.equal(result.status,'failed');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.ok('error'in result);assert.equal(result.error.code,'INCOMPATIBLE_PROTOCOL');assert.equal(result.error.retryPolicy,'never');assert.equal(f.providerCalls(),0);assert.equal(f.store.list('operations').length,0);}finally{await f.close();}});
  test(`${entry}: response loss with mismatched original-invocation readback never adopts another identity or result`,async()=>{const f=await fixture(entry+'-mismatched-readback');try{f.setFault('mismatched-inspection');const {result,invocationId,traceId}=await f.invoke(entry,'mutation');assert.equal(result.status,'unavailable');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.ok('error'in result);assert.equal(result.error.retryPolicy,'inspect_only');assert.equal(result.operation,undefined);assert.equal(f.providerCalls(),1);assert.equal(f.http.filter(row=>row.path==='/v1/invocations').length,1);}finally{await f.close();}});
}
for(const stage of ['describe','connections'] as const){test(`Host ${stage} network failure is pre-submission unavailable with preserved identity and zero Provider`,async()=>{const f=await fixture('host-pre-'+stage);try{f.setFault(stage);const {result,invocationId,traceId}=await f.invoke('host','mutation');assert.equal(result.status,'unavailable');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.ok('error'in result);assert.equal(result.error.retryPolicy,'read_retry');assert.equal(result.operation,undefined);assert.equal(f.providerCalls(),0);assert.equal(f.http.filter(row=>row.path==='/v1/invocations').length,0);}finally{await f.close();}});}
test('Host output schema corruption after real mutation dispatch remains unknown/inspect_only with actual operation ID',async()=>{const f=await fixture('host-corrupt-output');try{f.setFault('corrupt-output');const {result,invocationId,traceId}=await f.invoke('host','mutation');assert.equal(result.status,'unknown');assert.equal(result.invocationId,invocationId);assert.equal(result.traceId,traceId);assert.ok('error'in result);assert.equal(result.error.code,'OUTPUT_SCHEMA_INVALID');assert.equal(result.error.retryPolicy,'inspect_only');assert.equal(result.operation?.operationId,f.store.list<{operationId:string}>('operations')[0].operationId);assert.equal(result.operation?.state,'unknown');assert.equal(f.providerCalls(),1);assert.deepEqual(validateResult(result),[]);}finally{await f.close();}});
test('Host transport throw after real HTTP mutation accepts reads back original invocation rather than making failed/never',async()=>{const f=await fixture('host-throw-after-post');try{const original=f.transport.invoke.bind(f.transport);f.transport.invoke=async(request,signal)=>{await original(request,signal);throw new Error('Real response discarded by caller transport');};const {result,invocationId}=await f.invoke('host','mutation');assert.equal(result.status,'ok');assert.equal(result.invocationId,invocationId);assert.equal(f.providerCalls(),1);assert.equal(f.http.filter(row=>row.path==='/v1/invocations').length,1);assert.ok(f.http.some(row=>row.path===`/v1/invocations/${invocationId}`));}finally{await f.close();}});
test('Host invalid input remains deterministic failed/never without Provider dispatch',async()=>{const f=await fixture('host-invalid-input');try{const descriptor=cap('mutation'),result=await f.host.call('apps_invoke',{appId:'transportfixture',connectionId:'C1',capabilityId:descriptor.capabilityId,capabilityVersion:descriptor.version,input:{value:123},invocationId:'invalid-input',traceId:'invalid-input-trace',idempotencyKey:'invalid-input'},'fixture-session') as CapabilityResult;assert.equal(result.status,'failed');assert.ok('error'in result);assert.equal(result.error.code,'INPUT_SCHEMA_INVALID');assert.equal(result.error.retryPolicy,'never');assert.equal(f.providerCalls(),0);assert.equal(f.store.list('operations').length,0);}finally{await f.close();}});
for(const effect of ['query','mutation'] as const){test(`component proxy ${effect} accepted once then response loss retains original bridge identity and honest retry policy`,async()=>{const f=await fixture('component-lost-'+effect);try{f.setFault('drop-component');const {request,response,packet}=await f.component(effect);assert.equal(response.status,200);assert.equal(packet.channel,request.channel);for(const key of ['protocolVersion','sessionId','viewId','buildId','frameInstanceId','requestId'] as const)assert.equal(packet[key],request[key]);assert.equal(packet.error.retryPolicy,effect==='mutation'?'inspect_only':'read_retry');assert.equal(packet.error.details.requestId,request.requestId);assert.equal(packet.error.details.method,'invokeCapability');assert.equal(packet.error.details.params.capabilityId,request.params.capabilityId);if(effect==='mutation')assert.equal(packet.error.details.params.idempotencyKey,request.params.idempotencyKey);assert.equal(packet.result,undefined);assert.equal(f.providerCalls(),1);assert.equal(f.http.filter(row=>row.path==='/v1/component-bridge').length,1);}finally{await f.close();}});}
test('component proxy explicit stale-build backend rejection preserves same tuple and never policy with zero Provider',async()=>{const f=await fixture('component-known-rejection');try{const {request,packet}=await f.component('mutation',true);assert.equal(packet.requestId,request.requestId);assert.equal(packet.error.code,'BRIDGE_IDENTITY_STALE');assert.equal(packet.error.retryPolicy,'never');assert.equal(f.providerCalls(),0);assert.equal(f.store.list('operations').length,0);}finally{await f.close();}});
test('Direct HTTP transport cancellation before submission returns cancelled/never with zero HTTP POST or Provider dispatch',async()=>{const f=await fixture('direct-before-submit');try{const descriptor=cap('mutation'),request:InvocationRequest={protocolVersion:'1.0',appId:'transportfixture',connectionId:'C1',invocationId:randomUUID(),traceId:randomUUID(),capabilityId:descriptor.capabilityId,capabilityVersion:descriptor.version,input:{value:'cancelled-before-submit'},source:{kind:'script',sessionId:'fixture-session',runId:'direct-transport',stepKey:'cancelled'},deadlineAt:new Date(Date.now()+3000).toISOString(),idempotencyKey:randomUUID()},before=f.http.length,result=await f.transport.invoke(request,AbortSignal.abort());save(f.label+'/cancelled-result.json',{request,result});assert.equal(result.status,'cancelled');assert.equal(result.invocationId,request.invocationId);assert.equal(result.traceId,request.traceId);assert.ok('error'in result);assert.equal(result.error.code,'CANCELLED_BEFORE_DISPATCH');assert.equal(result.error.retryPolicy,'never');assert.equal(result.operation,undefined);assert.equal(f.http.length,before);assert.equal(f.providerCalls(),0);assert.equal(f.store.list('operations').length,0);}finally{await f.close();}});
