import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { createWorkspaceState, workspaceReducer } from '../../packages/dsh-plugin/client/workspace-tabs.ts';
test('workbench is pinned, cannot close and missing active targets are ignored',()=>{
  const state=createWorkspaceState();assert.equal(state.tabs.length,1);assert.equal(state.tabs[0].kind,'workbench');assert.equal(state.tabs[0].pinned,true);assert.equal(workspaceReducer(state,{type:'close',id:state.activeId}),state);assert.equal(workspaceReducer(state,{type:'activate',id:'missing'}),state);
});
test('opening existing view deduplicates by app/view ID and selects its real title',()=>{
  let state=createWorkspaceState();state=workspaceReducer(state,{type:'open-view',appId:'hallmark',viewId:'real-view-7',title:'利润筛选'});assert.equal(state.tabs.length,2);const id=state.activeId;state=workspaceReducer(state,{type:'activate',id:state.tabs[0].id});state=workspaceReducer(state,{type:'open-view',appId:'hallmark',viewId:'real-view-7',title:'利润筛选更新'});assert.equal(state.tabs.length,2);assert.equal(state.activeId,id);assert.equal(state.tabs[1].title,'利润筛选更新');assert.equal(state.tabs[1].viewId,'real-view-7');
});
test('closing inactive preserves selection; closing active falls back to workbench, not another view',()=>{
  let state=createWorkspaceState();const pinned=state.activeId;state=workspaceReducer(state,{type:'open-view',appId:'hallmark',viewId:'a',title:'商品'});const inactive=state.activeId;state=workspaceReducer(state,{type:'open-view',appId:'hallmark',viewId:'b',title:'利润'});const active=state.activeId;state=workspaceReducer(state,{type:'close',id:inactive});assert.equal(state.activeId,active);assert.equal(state.tabs.length,2);state=workspaceReducer(state,{type:'close',id:active});assert.equal(state.activeId,pinned);assert.equal(state.tabs.length,1);
});
test('drafts are unique temporary tabs and metadata for unsupported apps grants no workspace authority',()=>{
  let state=createWorkspaceState();state=workspaceReducer(state,{type:'new-draft',appId:'hallmark'});const first=state.activeId;state=workspaceReducer(state,{type:'new-draft',appId:'hallmark'});assert.notEqual(state.activeId,first);state=workspaceReducer(state,{type:'close',id:first});state=workspaceReducer(state,{type:'new-draft',appId:'hallmark'});assert.equal(state.draftSequence,3);assert.equal(new Set(state.tabs.map(tab=>tab.id)).size,state.tabs.length);assert.equal(workspaceReducer(state,{type:'new-draft',appId:'other-app'}),state);assert.equal(workspaceReducer(state,{type:'open-view',appId:'other-app',viewId:'x',title:'Not Hallmark'}),state);const other=createWorkspaceState('other-app');assert.equal(other.tabs.length,0);assert.equal(workspaceReducer(other,{type:'new-draft',appId:'other-app'}),other);
});
test('dock renders accessible real actions and mounted hidden panes retain draft without implicit saves',()=>{
  const dock=readFileSync(new URL('../../packages/dsh-plugin/client/workspace-dock.tsx',import.meta.url),'utf8');const page=readFileSync(new URL('../../packages/dsh-plugin/client/page.tsx',import.meta.url),'utf8');const workbench=readFileSync(new URL('../../packages/dsh-plugin/client/workbench.tsx',import.meta.url),'utf8');const reducer=readFileSync(new URL('../../packages/dsh-plugin/client/workspace-tabs.ts',import.meta.url),'utf8');assert.ok(dock.includes('aria-label="工作区标签"'));for(const key of ['ArrowLeft','ArrowRight','Home','End','Delete'])assert.ok(dock.includes(key));assert.ok(dock.includes('关闭 ${tab.title} 标签'));assert.ok(dock.includes('新建组件设计标签'));assert.ok(page.indexOf('<WorkspaceDockTabs')<page.indexOf('<header className="hm-page-header">'));assert.ok(page.includes("hidden={tab.id!==workspace.activeId"));assert.ok(page.includes("initialTab={tab.kind==='draft'?'builder':'common'}"));assert.ok(workbench.includes('const prefix=useId()'));assert.ok(workbench.includes('onOpenView({viewId:opened.id,title:opened.title})'));assert.ok(!workbench.includes("from './index.tsx'"));assert.ok(!reducer.includes('fetch('));assert.ok(!reducer.includes('saveComponent('));
});
