import React,{useEffect,useMemo,useRef,useState} from 'react';
import {flexRender,getCoreRowModel,getFilteredRowModel,getPaginationRowModel,getSortedRowModel,useReactTable} from '@tanstack/react-table';
import type {ColumnDef,SortingState} from '@tanstack/react-table';
import type {BindingData,DataBinding,WidgetSpec} from '../../../presentation/src/types.ts';
import type {ViewInteractions} from '../material-interactions.ts';
import type {Row} from '../model.ts';
import {safeImageURL} from '../model.ts';
import {materialColumns,materialDisplay,materialFieldMeta,materialLabel,materialRows,materialValue} from './material-format.ts';
import {tablePageSize} from './table-format.ts';
import {ProcurementCell} from './procurement-cells.tsx';

export function MaterialImage({value,name}:{value:unknown;name:string}){
  const src=safeImageURL(value),[failed,setFailed]=useState<string>();
  return src&&failed!==src?<img className="hm-material-image" src={src} alt={name} loading="lazy" referrerPolicy="no-referrer" onError={()=>setFailed(src)}/>:<span className="hm-material-image hm-material-image-empty" role="img" aria-label="暂无商品图片"><svg viewBox="0 0 24 24" width="20" height="20" aria-hidden="true" fill="none" stroke="currentColor"><rect x="3" y="3" width="18" height="18" rx="3"/><circle cx="8" cy="8" r="1.5"/><path d="m4 18 5-5 3 3 4-5 5 7"/></svg><small>暂无图片</small></span>;
}
export function ProductList({widget,binding,data,interactions}:{widget:WidgetSpec;binding?:DataBinding;data?:BindingData;interactions?:ViewInteractions}){
  const procurement=widget.options?.materialId==='product-procurement';
  const rows=useMemo(()=>materialRows(data?.payload,widget),[data?.payload,widget.options?.rowsPath]);
  const control=interactions?.bindings?.[widget.bindingId??''];
  const fullDataset=control?.fullDataset===true;
  const serverSearch=!fullDataset&&control?.operations?.search==='server'&&!!control.onQueryChange,serverSort=!fullDataset&&control?.operations?.sort==='server'&&!!control.onQueryChange;
  const [search,setSearch]=useState(()=>control?.appliedSearch??''),searchDraft=useRef(false);
  const [sorting,setSorting]=useState<SortingState>(()=>{const sort=widget.options?.sort as {field:string;direction:string}|undefined;return sort?[{id:sort.field,desc:sort.direction==='desc'}]:[];});
  useEffect(()=>{if((serverSearch||fullDataset)&&typeof control?.appliedSearch==='string'&&!searchDraft.current)setSearch(control.appliedSearch);},[serverSearch,fullDataset,control?.appliedSearch]);
  const pageSize=tablePageSize(widget.options?.pageSize),[pagination,setPagination]=useState({pageIndex:0,pageSize});
  useEffect(()=>setPagination({pageIndex:0,pageSize}),[pageSize]);
  useEffect(()=>{if(!fullDataset)setPagination(current=>({...current,pageIndex:0}));},[data?.datasetKey,fullDataset]);
  const specs=materialColumns(widget,['product.image','product.name','price.current']);
  const columns=useMemo<ColumnDef<Row>[]>(()=>specs.map(column=>({id:column.field,header:materialLabel(column,widget),accessorFn:row=>{const value=materialValue(row,column.field,widget,binding);return procurement&&['currency','percent','integer'].includes(materialFieldMeta(column.field,widget).format??'')&&(value==null||value===''||!Number.isFinite(Number(value)))?undefined:value;},enableSorting:materialFieldMeta(column.field,widget).format!=='image'&&(!procurement||!['product.url','purchase.url'].includes(column.field)),sortUndefined:'last',sortDescFirst:false,sortingFn:(a,b,id)=>{const x=a.getValue(id),y=b.getValue(id);const numeric=materialFieldMeta(id,widget).format;return ['currency','percent','integer'].includes(numeric??'')?Number(x)-Number(y):String(x).localeCompare(String(y),'zh-CN',{numeric:true});},cell:({row})=>column.field==='product.image'?<MaterialImage value={materialValue(row.original,column.field,widget,binding)} name={materialDisplay(row.original,'product.name',widget,binding)}/>:procurement?<ProcurementCell row={row.original} role={column.field} widget={widget} binding={binding} image={column.field==='product.name'&&!specs.some(spec=>spec.field==='product.image')?<MaterialImage value={materialValue(row.original,'product.image',widget,binding)} name={materialDisplay(row.original,'product.name',widget,binding)}/>:undefined}/>:<span title={materialDisplay(row.original,column.field,widget,binding)}>{materialDisplay(row.original,column.field,widget,binding)}</span>})),[JSON.stringify(specs),widget.fields,widget.options?.fieldMeta,widget.options?.currency,binding,procurement]);
  const query=(nextSort=sorting)=>{searchDraft.current=false;control?.onQueryChange?.({search, ...(nextSort[0]?{sort:{field:nextSort[0].id,direction:nextSort[0].desc?'desc':'asc'}}:{})});};
  const table=useReactTable({data:rows,columns,state:{sorting,pagination,globalFilter:search},onSortingChange:update=>{const next=typeof update==='function'?update(sorting):update;setSorting(next);setPagination(current=>({...current,pageIndex:0}));if(serverSort)query(next);},onPaginationChange:setPagination,manualSorting:serverSort,manualFiltering:serverSearch,enableSortingRemoval:false,getColumnCanGlobalFilter:column=>fullDataset&&procurement?column.id===specs[0]?.field:fullDataset||materialFieldMeta(column.id,widget).format!=='image',globalFilterFn:(row,columnId,value)=>(fullDataset&&procurement?[row.original.sku,row.original.offerId,...['product.name','product.id','sku.id','sku.specification','purchase.specification'].map(role=>materialDisplay(row.original,role,widget,binding))]:[materialDisplay(row.original,columnId,widget,binding),materialDisplay(row.original,'product.id',widget,binding)]).join(' ').normalize('NFKC').toLocaleLowerCase().includes(String(value).normalize('NFKC').toLocaleLowerCase().trim()),getCoreRowModel:getCoreRowModel(),getFilteredRowModel:getFilteredRowModel(),getSortedRowModel:getSortedRowModel(),getPaginationRowModel:getPaginationRowModel(),autoResetPageIndex:false});
  const pages=Math.max(1,table.getPageCount());
  useEffect(()=>{if(pagination.pageIndex>=pages)setPagination(current=>({...current,pageIndex:pages-1}));},[pages,pagination.pageIndex]);
  const total=control?.pagination?.total,loaded=control?.pagination?.loadedCount??rows.length;
  const select=(row:Row)=>{const id=materialValue(row,'product.id',widget,binding);if(id!==undefined&&id!==null)interactions?.onSelect?.({widgetId:widget.id,field:'product.id',value:String(id),row});};
  return <div className={`hm-native-product-list${procurement?' hm-product-procurement':''}`} data-density={widget.options?.density??'comfortable'}>
    <div className="hm-material-toolbar"><form onSubmit={event=>{event.preventDefault();if(serverSearch)query();}}>{procurement?<svg className="hm-procurement-search-icon" viewBox="0 0 20 20" width="18" height="18" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><circle cx="8.5" cy="8.5" r="5.5"/><path d="m13 13 4 4"/></svg>:null}<input type="search" aria-label={serverSearch||fullDataset?'搜索全部商品':'搜索已加载商品'} placeholder={procurement?'搜索名称 / SKU / 货号 / 规格':'搜索商品名称或编号'} value={search} onChange={event=>{searchDraft.current=!fullDataset;setSearch(event.target.value);setPagination(current=>({...current,pageIndex:0}));if(fullDataset)control?.onQueryChange?.({search:event.target.value});}}/>{serverSearch?<button type="submit" disabled={control?.pagination?.loading}>搜索</button>:null}</form>{widget.options?.example===true||data?.provenance.example===true?<span className="hm-material-example">示例</span>:null}</div>
    <p className="hm-material-scope">{fullDataset?`${procurement?'全店在售':'当前范围共'} ${rows.length} 件 · 搜索与排序覆盖全部商品`:<>{procurement?'在售商品 · ':''}搜索：{serverSearch?'全部商品':'已加载范围'} · 排序：{serverSort?'全部商品':'已加载范围'}{!serverSearch||!serverSort?`（仅在已加载 ${loaded}${total!==undefined?` / 共 ${total}`:''} 条中）`:''}</>}</p>
    <div className="hm-material-scroll"><table className="hm-material-table"><thead>{table.getHeaderGroups().map(group=><tr key={group.id}>{group.headers.map(header=><th key={header.id} scope="col" aria-sort={header.column.getIsSorted()==='asc'?'ascending':header.column.getIsSorted()==='desc'?'descending':'none'} title={materialFieldMeta(header.id,widget).description}>{header.column.getCanSort()?<button type="button" onClick={header.column.getToggleSortingHandler()}>{flexRender(header.column.columnDef.header,header.getContext())}<span aria-hidden="true">{header.column.getIsSorted()==='asc'?' ↑':header.column.getIsSorted()==='desc'?' ↓':' ↕'}</span></button>:flexRender(header.column.columnDef.header,header.getContext())}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map(row=>{const id=materialValue(row.original,'product.id',widget,binding),selectable=!!interactions?.onSelect&&id!=null,selected=id!=null&&interactions?.selectedByWidget?.[widget.id]===String(id);return <tr key={row.id} aria-selected={selected} tabIndex={selectable?0:undefined} onClick={selectable?()=>select(row.original):undefined} onKeyDown={selectable?event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();select(row.original);}}:undefined} className={selectable?'hm-material-selectable':undefined}>{row.getVisibleCells().map(cell=><td key={cell.id} data-field={cell.column.id}>{flexRender(cell.column.columnDef.cell,cell.getContext())}</td>)}</tr>;})}</tbody></table></div>
    {!table.getFilteredRowModel().rows.length?<div className="hm-material-empty" role="status">{search&&!serverSearch?fullDataset?procurement?'全店商品中没有匹配记录':'全部商品中没有匹配记录':'已加载商品中没有匹配记录':'暂无商品数据'}</div>:null}
    <div className="hm-material-pagination"><span>{fullDataset?`${search?`匹配 ${table.getFilteredRowModel().rows.length} 件 / `:''}共 ${rows.length} 件`:`${table.getFilteredRowModel().rows.length} 条已加载记录`}</span><div>{fullDataset?<label>每页 <select aria-label="每页商品数" value={pagination.pageSize} onChange={event=>{table.setPageSize(Number(event.target.value));table.setPageIndex(0);}}>{[...new Set([10,20,50,pageSize])].sort((a,b)=>a-b).map(size=><option key={size} value={size}>{size} 条</option>)}</select></label>:null}<button type="button" disabled={!table.getCanPreviousPage()} onClick={()=>table.previousPage()}>上一页</button><span aria-live="polite">{pagination.pageIndex+1} / {pages}</span><button type="button" disabled={!table.getCanNextPage()} onClick={()=>table.nextPage()}>下一页</button>{fullDataset?<label>跳至 <select aria-label="跳转页码" value={pagination.pageIndex} onChange={event=>table.setPageIndex(Number(event.target.value))}>{Array.from({length:pages},(_,index)=><option key={index} value={index}>第 {index+1} 页</option>)}</select></label>:null}{!fullDataset&&control?.pagination?.hasMore?<button type="button" onClick={control.onPage} disabled={!control.onPage||control.pagination.loading}>{control.pagination.loading?'正在加载…':'下一批'}</button>:null}</div></div>
  </div>;
}
