import test from 'node:test';
import assert from 'node:assert/strict';
import {AppsRuntime,RuntimeStore} from '../../packages/app-runtime/src/index.ts';
import {NotesProvider} from '../../packages/app-notes/src/index.ts';
import {AppsPresentationService} from '../../packages/app-presentation/src/index.ts';
import {createAppsServer} from '../../packages/service/src/apps-server.ts';
import {AppsHost,type AppsPluginContext} from '../../packages/plugin-apps/src/index.ts';
import {HttpAppsHostTransport} from '../../packages/plugin-apps/src/transport.ts';
import {NativeAppsReferences,APPS_REFERENCE_SOURCE,type NativeAppsTransport,type NativeAppsInputState,type NativeBindingReceipt} from '../../packages/plugin-apps/client/native-apps.ts';
const tick=()=>new Promise<void>(resolve=>setImmediate(resolve));
test('original-session Apps reference traverses actual Host proxy and HTTP Runtime; restart uses readonly restore and deletion preserves another bound reference',async()=>{
  const store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store);runtime.register(new NotesProvider({store}));const presentation=new AppsPresentationService({store,runtime});runtime.register(presentation.provider());for(const [appId,connectionId] of [['notes','N1'],['notes','N2'],['apps','presentation']])runtime.addConnection({appId,connectionId,displayName:connectionId,enabled:true,config:{},configRevision:1});
  const server=createAppsServer({runtime,presentation,token:'x'.repeat(64)});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const port=(server.address() as {port:number}).port,transport=new HttpAppsHostTransport(`http://127.0.0.1:${port}`,'x'.repeat(64)),A={id:'A'},B={id:'B'},agents=new Map([['A',A],['B',B]]),ctx={agents:{get:(id:string)=>agents.get(id),list:()=>[A,B]}} as unknown as AppsPluginContext,host=new AppsHost(ctx,transport),requests:string[]=[],posts:unknown[]=[];
  async function request(value:unknown){posts.push(value);const response=await host.ui(new Request('http://dsh/api/dsh-apps',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(value)})),payload=await response.json();if(!response.ok)throw new Error(JSON.stringify(payload));return payload;}
  const browser:NativeAppsTransport={async apps(){return [{appId:'notes',displayName:'笔记'}];},async bind(input){return await request({action:'nativeBinding',...input}) as NativeBindingReceipt;},async inspect(sessionId,bindRequestId,referenceId){requests.push('GET');const query=new URLSearchParams({resource:'nativeBinding',sessionId,bindRequestId,referenceId}),response=await host.ui(new Request(`http://dsh/api/dsh-apps?${query}`));assert.equal(response.status,200);return await response.json() as NativeBindingReceipt|null;},async serialize(referenceId){return await request({action:'serializeNativeReference',referenceId}) as {text:string};}};
  let manager=new NativeAppsReferences(browser);
  const input=(refs:string[],draftRev:number):NativeAppsInputState=>({phase:'plain',draftRev,draft:'中文原文',attachmentIds:['existing'],occurrences:refs.map((ref,index)=>({source:APPS_REFERENCE_SOURCE,ref,occurrenceId:`occ-${index}`,label:'笔记'}))});
  const wait=async(check:()=>boolean)=>{for(let i=0;i<100&&!check();i++)await new Promise(resolve=>setTimeout(resolve,5));assert.ok(check());};
  try{
    const candidates=await manager.source.candidates({sessionId:'A'},{query:'笔',signal:new AbortController().signal}),ref1=manager.source.onPick({candidate:candidates[0],session:{sessionId:'A'},action:'pick'})!.insert.ref,ref2=manager.source.onPick({candidate:candidates[0],session:{sessionId:'A'},action:'pick'})!.insert.ref,token={};assert.equal(posts.length,0);
    manager.observe('A',input([ref1,ref2],1),token);await wait(()=>manager.states('A').every(row=>row.status==='needs_connection'));assert.equal(runtime.sessionBindings('A').length,0);await manager.choose(ref1,'N2');await manager.choose(ref2,'N2');assert.equal(runtime.sessionBindings('A').find(row=>row.appId==='notes')?.connectionId,'N2');assert.equal(runtime.sessionBindings('B').length,0);
    const text=await manager.source.codec.serialize(ref1,new AbortController().signal);assert.match(text,/"sessionId":"A"/);assert.match(text,/"connectionId":"N2"/);const mutationsBefore=posts.length;manager.dispose();manager=new NativeAppsReferences(browser);const reopened={};manager.observe('A',input([ref1,ref2],5),reopened);await wait(()=>manager.states('A').every(row=>row.status==='bound'));assert.equal(posts.length,mutationsBefore);assert.equal(requests.length,2);manager.observe('A',input([ref2],6),reopened);await wait(()=>posts.length===mutationsBefore+1);await tick();assert.equal((posts.at(-1) as {enabled:boolean}).enabled,false);assert.equal(runtime.sessionBindings('A').find(row=>row.appId==='notes')?.enabled,true);assert.equal(store.list('invocations').length,0);assert.equal(store.list('operations').length,0);
    const forged={...JSON.parse(ref2),sessionId:'unknown'},bad=await host.ui(new Request('http://dsh/api/dsh-apps',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'serializeNativeReference',referenceId:JSON.stringify(forged)})}));assert.equal(bad.status,400);
    const cross=await host.ui(new Request(`http://dsh/api/dsh-apps?${new URLSearchParams({resource:'nativeBinding',sessionId:'B',bindRequestId:JSON.parse(ref2).bindRequestId,referenceId:ref2})}`));assert.equal(cross.status,400);assert.equal(runtime.sessionBindings('B').length,0);
  }finally{manager.dispose();await host.dispose();server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));await runtime.dispose();store.close();}
});
