import test from 'node:test';import assert from 'node:assert/strict';import {mkdirSync,mkdtempSync,rmSync} from 'node:fs';import {resolve,join} from 'node:path';import {spawnSync} from 'node:child_process';import {build} from 'esbuild';
async function fixture(contents:string){mkdirSync('artifacts',{recursive:true});const directory=mkdtempSync(resolve('artifacts/native-frame-handshake-')),entry=join(directory,'fixture.mjs');try{await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents},banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outfile:entry,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime','react-test-renderer']});const result=spawnSync(process.execPath,[entry],{encoding:'utf8',timeout:10000});assert.equal(result.status,0,result.error?.message??result.stderr);assert.match(result.stdout,/FRAME_HANDSHAKE_PASS/);}finally{rmSync(directory,{recursive:true,force:true});}}
const setup=`
import React from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';import {AppsSourceFrame} from './packages/dsh-plugin/client/component-frame.tsx';import {COMPONENT_CHANNEL} from './packages/component-runtime/src/apps-client.ts';globalThis.IS_REACT_ACT_ENVIRONMENT=true;const listeners=new Set(),posts=[],retiredA=[],retiredB=[],authorizedA=[],authorizedB=[],child={postMessage:message=>posts.push(message)};globalThis.window={location:{origin:'http://fixture'},addEventListener(type,fn){if(type==='message')listeners.add(fn);},removeEventListener(type,fn){if(type==='message')listeners.delete(fn);}};let finishA,rejectA;const handlersA={getData:()=>({}),getContext:()=>({}),extensions:{uiStateV1:()=>({})},authorizeFrame(identity,nonce){authorizedA.push({identity,nonce});return new Promise((resolve,reject)=>{finishA=resolve;rejectA=reject;});},retireFrame(identity,nonce){retiredA.push({identity,nonce});}},handlersB={getData:()=>({}),getContext:()=>({}),extensions:{uiStateV1:()=>({})},authorizeFrame(identity,nonce){authorizedB.push({identity,nonce});return Promise.resolve(['uiStateV1']);},retireFrame(identity,nonce){retiredB.push({identity,nonce});}};const draw=(sessionId,handlers)=> <AppsSourceFrame sessionId={sessionId} viewId='V' buildId={sessionId+'-build'} title='Frame' url='/fixture' data={{}} context={{}} handlers={handlers}/>;const nodeMock=node=>node.type==='iframe'?{contentWindow:child}:null;const hello=(requestId,extra={})=>({source:child,origin:'http://fixture',data:{channel:COMPONENT_CHANNEL,type:'hello',protocolVersion:'2.0',requestId,documentNonce:'same-document',clientFeatures:['uiStateV1'],...extra}});const receive=()=>[...listeners][0];const flush=()=>new Promise(resolve=>setTimeout(resolve,0));
`;
test('pending same-document hello retries share one authorization but invalid envelopes retain protocol validation',()=>fixture(setup+`
let tree;await act(async()=>{tree=create(draw('A',handlersA),{createNodeMock:nodeMock});});const first=receive()(hello('one'));await flush();assert.equal(authorizedA.length,1);const duplicate=receive()(hello('two'));await receive()(hello('wrong-protocol',{protocolVersion:'3.0'}));await receive()(hello('wrong-features',{clientFeatures:'invalid'}));assert.equal(authorizedA.length,1);assert.deepEqual(posts.map(row=>row.error?.code),['UNSUPPORTED_PROTOCOL','INVALID_BRIDGE_MESSAGE']);finishA(['uiStateV1']);await Promise.all([first,duplicate]);const valid=posts.filter(row=>row.type==='hello');assert.equal(valid.length,2);assert.equal(valid[0].frameInstanceId,valid[1].frameInstanceId);assert.deepEqual(valid.map(row=>row.requestId).sort(),['one','two']);assert.equal(retiredA.length,0);await act(async()=>tree.unmount());assert.equal(retiredA.length,1);assert.equal(listeners.size,0);console.log('FRAME_HANDSHAKE_PASS');
`));
test('A to B owner change retires a late A authorization using A handlers and never posts A into B document',()=>fixture(setup+`
let tree;await act(async()=>{tree=create(draw('A',handlersA),{createNodeMock:nodeMock});});const old=receive()(hello('old'));await flush();assert.equal(authorizedA.length,1);await act(async()=>tree.update(draw('B',handlersB)));await receive()(hello('current'));assert.equal(authorizedB.length,1);assert.equal(posts.length,1);assert.equal(posts[0].sessionId,'B');finishA(['uiStateV1']);await old;assert.equal(posts.length,1);assert.deepEqual(retiredA,[authorizedA[0]]);assert.equal(retiredB.length,0);await act(async()=>tree.unmount());assert.deepEqual(retiredB,[authorizedB[0]]);assert.equal(listeners.size,0);console.log('FRAME_HANDSHAKE_PASS');
`));
test('an unknown late A authorization is retired without poisoning the same nonce in B or retrying A',()=>fixture(setup+`
let finishB;handlersB.authorizeFrame=(identity,nonce)=>{authorizedB.push({identity,nonce});return new Promise(resolve=>finishB=resolve);};let tree;await act(async()=>{tree=create(draw('A',handlersA),{createNodeMock:nodeMock});});const old=receive()(hello('old'));await flush();await act(async()=>tree.update(draw('B',handlersB)));const current=receive()(hello('current'));await flush();rejectA(Error('authorization response lost'));await old;assert.deepEqual(retiredA,[authorizedA[0]]);assert.equal(retiredB.length,0);assert.equal(posts.length,0);finishB(['uiStateV1']);await current;assert.equal(posts.length,1);assert.equal(posts[0].sessionId,'B');assert.equal(authorizedA.length,1);assert.equal(authorizedB.length,1);await act(async()=>tree.unmount());assert.deepEqual(retiredB,[authorizedB[0]]);console.log('FRAME_HANDSHAKE_PASS');
`));
