import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {mkdirSync,mkdtempSync,readFileSync,writeFileSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {build} from 'esbuild';

/** Real production React, real loopback HTTP; the Window/document seat is a fixture, not DSH. */
async function fixture(label:string,contents:string){
  const parent=resolve(process.env.APPS_SIDEBAR_RECOVERY_EVIDENCE_DIR??'artifacts/native-sidebar-recovery');mkdirSync(parent,{recursive:true});
  const directory=mkdtempSync(join(parent,label+'-')),entry=join(directory,'fixture.mjs'),source=setup+contents;
  writeFileSync(join(directory,'fixture.tsx'),source,{flag:'wx'});
  await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:source},banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outfile:entry,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime','react-test-renderer']});
  const result=spawnSync(process.execPath,[entry],{encoding:'utf8',timeout:12000,maxBuffer:4*1024*1024});
  writeFileSync(join(directory,'stdout.txt'),result.stdout??'',{flag:'wx'});writeFileSync(join(directory,'stderr.txt'),result.stderr??'',{flag:'wx'});
  const sha=(path:string)=>createHash('sha256').update(readFileSync(path)).digest('hex');
  writeFileSync(join(directory,'command.json'),JSON.stringify({label,command:[process.execPath,entry],cwd:process.cwd(),exitCode:result.status,error:result.error?.message??null,sourceSha256:sha(join(directory,'fixture.tsx')),executedBundleSha256:sha(entry),stdoutSha256:sha(join(directory,'stdout.txt')),stderrSha256:sha(join(directory,'stderr.txt')),scope:'ISOLATED_PRODUCTION_REACT_HTTP_FIXTURE',actualDesktop:false,renderReadySimulated:false,actualBusiness:false},null,2)+'\n',{flag:'wx'});
  assert.equal(result.status,0,result.error?.message??result.stderr);assert.match(result.stdout,/SIDEBAR_RECOVERY_PASS/);
}
const setup=`
import React from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';import {createServer} from 'node:http';import {createConnection} from 'node:net';
import {AppsSidebarPane} from './packages/plugin-apps/client/sidebar.tsx';import {AppsNativeView} from './packages/plugin-apps/client/view.tsx';import {COMPONENT_CHANNEL} from './packages/component-runtime/src/apps-client.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
const actualFetch=globalThis.fetch,previousWindow=globalThis.window,http=[],fetchEvents=[],stages=[],events=new Map(),posts=[],nodes=[],releases=[],modes=new Map();let owner='A',tree,failure;
const sourceFor=id=>({buildId:id+'-active-build',entry:'index.html',protocol:'dsh.apps.component.v2'}),viewFor=id=>({viewId:'V',ownerSessionId:id,title:id+' owned component',design:{},bindings:[],source:sourceFor(id),viewRevision:1,pendingPublicationId:null,validationStatus:'verified'});
const server=createServer(async(req,res)=>{let body='';for await(const chunk of req)body+=chunk;const url=new URL(req.url,'http://fixture'),sessionId=url.searchParams.get('sessionId')??'A',resource=url.searchParams.get('resource'),row={method:req.method,path:req.url,sessionId,resource,body:body?JSON.parse(body):null};http.push(row);res.once('close',()=>row.closed=true);const reply=(status,value)=>{row.status=status;row.response=value;row.delivered=!res.destroyed;if(!res.destroyed){res.writeHead(status,{'Content-Type':'application/json'});res.end(JSON.stringify(value));}};
 if(url.pathname==='/api/hallmark-app'){reply(200,{sessionId,views:[]});return;}
 if(resource==='views'){const mode=modes.get(sessionId)??'ok';row.mode=mode;if(mode==='hold'){releases.push(()=>reply(200,{views:[viewFor(sessionId)]}));return;}reply(mode==='error'?503:200,mode==='error'?{error:{code:'CATALOG_UNAVAILABLE',message:'Isolated catalogue temporarily unavailable'}}:{views:mode==='legacy'?[]:[viewFor(sessionId)]});return;}
 if(resource==='view'){reply(200,viewFor(sessionId));return;}if(resource==='viewData'){reply(200,{viewId:'V',bindings:[]});return;}if(resource==='hostCapabilities'){reply(200,{adapterReady:false});return;}if(resource==='componentFeatures'){reply(200,{features:['uiStateV1']});return;}
 if(row.body?.operation==='negotiateFrame'){reply(200,{features:row.body.params.clientFeatures});return;}if(row.body?.operation==='retireFrame'){reply(200,{retired:true});return;}reply(404,{error:{code:'FIXTURE_ROUTE_NOT_FOUND',message:'No fixture route'}});
});
await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(0,'127.0.0.1',resolve);});const port=server.address().port;assert.ok(![36994,4180,4280].includes(port));const origin='http://127.0.0.1:'+port;
globalThis.fetch=(input,init)=>{const row={url:String(input),abortedBefore:init?.signal?.aborted??false};fetchEvents.push(row);init?.signal?.addEventListener('abort',()=>row.aborted=true,{once:true});return actualFetch(new URL(String(input),origin),init);};
const parent={location:{origin},addEventListener(type,fn){const listeners=events.get(type)??new Set();listeners.add(fn);events.set(type,listeners);},removeEventListener(type,fn){events.get(type)?.delete(fn);},dispatchEvent(event){for(const listener of [...events.get(event.type)??[]])listener(event);return true;}};globalThis.window=parent;
const mountedListeners=new Set(),sidebar={mounted:{getSnapshot:()=>owner,subscribe:fn=>{mountedListeners.add(fn);return()=>mountedListeners.delete(fn);}},openTab(){assert.fail('The pane recovery must not issue another native open or publish');}};
const controller=new AbortController(),info=(revision,signal=controller.signal)=>({tab:{navigation:{params:{viewId:'V'},revision},signal,visible:true,actions:{openTab(){}}}}),draw=(sessionId='A',revision=1,signal=controller.signal)=><AppsSidebarPane sessionId={sessionId} sidebarRight={sidebar} useTabInfo={()=>info(revision,signal)}/>;
const nodeMock=node=>{if(node.type!=='iframe')return null;const child={postMessage:message=>posts.push(message)},element={contentWindow:child};nodes.push(element);return element;};
const settle=(ms=12)=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,ms));}),until=async(predicate,message)=>{for(let n=0;n<80&&!predicate();n++)await settle();assert.ok(predicate(),message);};
const catalog=()=>http.filter(row=>row.resource==='views'),snapshot=label=>stages.push({label,iframeCount:tree.root.findAllByType('iframe').length,appsViewCount:tree.root.findAllByType(AppsNativeView).length,catalog:catalog().map(row=>({sessionId:row.sessionId,status:row.status,mode:row.mode}))});
const render=async()=>{await act(async()=>{tree=create(draw(),{createNodeMock:nodeMock});});},update=async(sessionId='A',revision=2,signal=controller.signal)=>{await act(async()=>tree.update(draw(sessionId,revision,signal)));};
try {
`;
const finish=`
}catch(error){failure=error instanceof Error?error.stack:String(error);}
finally{if(tree)await act(async()=>tree.unmount());for(const release of releases)release();await new Promise(resolve=>setTimeout(resolve,25));server.closeAllConnections();await new Promise(resolve=>server.close(resolve));globalThis.fetch=actualFetch;globalThis.window=previousWindow;assert.equal(mountedListeners.size,0);for(const listeners of events.values())assert.equal(listeners.size,0);}
const portProbe=await new Promise((resolve,reject)=>{const socket=createConnection({host:'127.0.0.1',port});socket.setTimeout(1000);socket.once('connect',()=>{socket.destroy();reject(Error('Fixture port still listening'));});socket.once('timeout',()=>{socket.destroy();reject(Error('Fixture port did not refuse connection'));});socket.once('error',error=>{socket.destroy();resolve({port,connected:false,error:error.code});});});
console.log(JSON.stringify({scope:'ISOLATED_PRODUCTION_REACT_HTTP_FIXTURE',actualDesktop:false,renderReadySimulated:false,actualBusiness:false,http,fetchEvents,stages,iframeNodeCreations:nodes.length,posts,cleanup:{listening:server.listening,mountedListeners:mountedListeners.size,messageListeners:[...events.values()].reduce((count,set)=>count+set.size,0),portProbe},failure},null,2));if(failure){console.error(failure);process.exitCode=1;}else console.log('SIDEBAR_RECOVERY_PASS');
`;

for(const mode of ['error','legacy'] as const)test(`same-view native navigation revision recovers an earlier HTTP ${mode==='error'?'503':'legacy catalogue'} decision into the production Apps iframe`,()=>fixture('recover-'+mode,`
modes.set('A','${mode}');await render();await until(()=>catalog().length===1&&catalog()[0].status!==undefined,'Initial catalogue response recorded');await settle();snapshot('before-reopen');assert.equal(tree.root.findAllByType(AppsNativeView).length,0);assert.equal(tree.root.findAllByType('iframe').length,0);
modes.set('A','ok');await update('A',2);await until(()=>tree.root.findAllByType('iframe').length===1,'The same view reopened by native revision must recover an Apps iframe');snapshot('after-reopen');assert.equal(catalog().length,2);assert.equal(catalog()[0].status,${mode==='error'?503:200});assert.equal(catalog()[1].status,200);assert.equal(tree.root.findAllByType(AppsNativeView).length,1);assert.ok(tree.root.findByType('iframe').props.src.includes('A-active-build'));assert.equal(http.some(row=>row.body?.operation==='publish'),false);
`+finish));

test('same-view native navigation rechecks catalogue without replacing its already negotiated production iframe document',()=>fixture('preserve-granted-frame',`
await render();await until(()=>tree.root.findAllByType('iframe').length===1,'Initial iframe');const original=tree.root.findByType('iframe'),originalNode=nodes[0],receiver=[...events.get('message')??[]][0];assert.ok(receiver);await act(async()=>{await receiver({source:originalNode.contentWindow,origin,data:{channel:COMPONENT_CHANNEL,type:'hello',protocolVersion:'2.0',requestId:'hello-original',documentNonce:'original-document',clientFeatures:['uiStateV1']}});});assert.equal(http.filter(row=>row.body?.operation==='negotiateFrame').length,1);assert.equal(posts.filter(row=>row.type==='hello').length,1);const frameInstanceId=posts.find(row=>row.type==='hello').frameInstanceId;snapshot('granted-original');
modes.set('A','hold');await update('A',2);await until(()=>releases.length===1,'A native reopen must recheck the owned catalogue');assert.equal(tree.root.findByType('iframe'),original);assert.equal(nodes.length,1);assert.equal(http.filter(row=>row.body?.operation==='retireFrame').length,0);snapshot('pending-recheck-preserves-original');await act(async()=>releases.shift()());await until(()=>catalog()[1].status===200,'Reopened catalogue settles');await settle();assert.equal(tree.root.findByType('iframe'),original);assert.equal(nodes.length,1);assert.equal(http.filter(row=>row.body?.operation==='negotiateFrame').length,1);assert.equal(http.filter(row=>row.body?.operation==='retireFrame').length,0);assert.equal(posts.find(row=>row.type==='hello').frameInstanceId,frameInstanceId);snapshot('settled-original-document');
`+finish));

test('a same-view catalogue HTTP 503 preserves the negotiated iframe and shows the read failure until a later navigation succeeds',()=>fixture('preserve-granted-frame-error',`
await render();await until(()=>tree.root.findAllByType('iframe').length===1,'Initial iframe');const original=tree.root.findByType('iframe'),originalNode=nodes[0],receiver=[...events.get('message')??[]][0];await act(async()=>{await receiver({source:originalNode.contentWindow,origin,data:{channel:COMPONENT_CHANNEL,type:'hello',protocolVersion:'2.0',requestId:'hello-original',documentNonce:'original-document',clientFeatures:['uiStateV1']}});});assert.equal(http.filter(row=>row.body?.operation==='negotiateFrame').length,1);const frameInstanceId=posts.find(row=>row.type==='hello').frameInstanceId;
modes.set('A','error');await update('A',2);await until(()=>catalog().length===2&&catalog()[1].status===503,'The reopened catalogue returns a real HTTP 503');await settle();assert.equal(tree.root.findAllByType('iframe').length,1,'A catalogue refresh failure must retain the last successfully loaded iframe');assert.equal(tree.root.findByType('iframe'),original);assert.equal(nodes.length,1);assert.equal(http.filter(row=>row.body?.operation==='negotiateFrame').length,1);assert.equal(http.filter(row=>row.body?.operation==='retireFrame').length,0);assert.equal(posts.find(row=>row.type==='hello').frameInstanceId,frameInstanceId);assert.match(JSON.stringify(tree.toJSON()),/Isolated catalogue temporarily unavailable/);snapshot('503-original-frame-and-visible-warning');
modes.set('A','ok');await update('A',3);await until(()=>catalog().length===3&&catalog()[2].status===200,'A later native navigation retries the original catalogue');await settle();assert.equal(tree.root.findByType('iframe'),original);assert.equal(nodes.length,1);assert.equal(http.filter(row=>row.body?.operation==='negotiateFrame').length,1);assert.equal(http.filter(row=>row.body?.operation==='retireFrame').length,0);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/Isolated catalogue temporarily unavailable/);snapshot('later-navigation-clears-warning-keeps-document');
`+finish));

test('an owner switch aborts the old A catalogue and its late response cannot replace the B Apps iframe',()=>fixture('owner-switch',`
modes.set('A','hold');await render();await until(()=>releases.length===1,'A read is in flight');await act(async()=>{owner='B';for(const listener of mountedListeners)listener();tree.update(draw('B',1));});await until(()=>tree.root.findAllByType('iframe').length===1,'B owned iframe');assert.ok(tree.root.findByType('iframe').props.src.includes('B-active-build'));snapshot('B-before-A-late');await act(async()=>releases.shift()());await settle();assert.ok(tree.root.findByType('iframe').props.src.includes('B-active-build'));assert.equal(tree.root.findAllByType('iframe').length,1);assert.equal(http.some(row=>row.resource==='view'&&row.sessionId==='A'),false);assert.ok(fetchEvents.some(row=>row.url.includes('sessionId=A')&&row.aborted));snapshot('B-after-A-late');
`+finish));

test('an aborted native tab cancels its in-flight catalogue and a late owned response creates no Apps view or iframe',()=>fixture('abort-tab',`
modes.set('A','hold');await render();await until(()=>releases.length===1,'A read is in flight');await act(async()=>controller.abort());await act(async()=>releases.shift()());await settle();assert.equal(tree.root.findAllByType('iframe').length,0);assert.equal(tree.root.findAllByType(AppsNativeView).length,0);assert.ok(fetchEvents.some(row=>row.url.includes('resource=views')&&row.aborted));assert.equal(http.some(row=>row.resource==='view'),false);snapshot('aborted-no-frame');
`+finish));
