import test from 'node:test';import assert from 'node:assert/strict';import {mkdirSync,mkdtempSync,rmSync} from 'node:fs';import {resolve,join} from 'node:path';import {spawnSync} from 'node:child_process';import {build} from 'esbuild';
test('message publication is fixed while a later view candidate exists; confirmed failed mount reloads only its owned active view',async()=>{
 mkdirSync('artifacts',{recursive:true});const directory=mkdtempSync(resolve('artifacts/native-publication-')),entry=join(directory,'fixture.mjs');
 try{await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
 import React from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';import {AppsNativeView} from './packages/plugin-apps/client/view.tsx';
 globalThis.IS_REACT_ACT_ENVIRONMENT=true;const listeners=new Map(),parent={location:{origin:'http://native.fixture'},addEventListener(type,listener){const set=listeners.get(type)??new Set();set.add(listener);listeners.set(type,set);},removeEventListener(type,listener){listeners.get(type)?.delete(listener);},dispatchEvent(){return true;}},child={postMessage(){}};globalThis.window=parent;
 const source=buildId=>({buildId,entry:'index.html',protocol:'dsh.apps.component.v2'}),publication={publicationId:'original-P',viewId:'V',ownerSessionId:'A',attemptId:'attempt',attemptEpoch:1,candidateBuildId:'original-build',source:source('original-build'),state:'mounted',committedViewRevision:5,readyDeadlineAt:new Date(Date.now()+60000).toISOString()},base={viewId:'V',ownerSessionId:'A',title:'原消息组件',viewRevision:5,bindings:[],source:source('original-build'),pendingPublicationId:'later-P'},calls=[];let mode='history',failed=false;
 const json=value=>new Response(JSON.stringify(value),{headers:{'content-type':'application/json'}});globalThis.fetch=async(url,options)=>{const query=new URL(url,'http://native.fixture'),body=options?.body?JSON.parse(options.body):undefined;calls.push({resource:query.searchParams.get('resource'),publicationId:query.searchParams.get('publicationId'),buildId:query.searchParams.get('buildId'),body});if(query.searchParams.get('resource')==='hostCapabilities')return json({adapterReady:false});if(query.searchParams.get('resource')==='componentFeatures')return json({features:[]});if(query.searchParams.get('resource')==='viewData')return json({viewId:'V',bindings:[]});if(query.searchParams.get('resource')==='view'){if(mode==='history')return json({...base,publication});if(failed)return json({...base,pendingPublicationId:null,source:source('last-good-build')});return json({...base,pendingPublicationId:'original-P',source:source('original-build'),publication:{...publication,state:'mounting'}});}if(body?.operation==='inspect'){assert.equal(body.params.publicationId,'original-P');return json({publication:{...publication,state:failed?'failed_mount':'mounting'}});}if(body?.operation==='failMount'){assert.equal(body.params.publicationId,'original-P');failed=true;return json({...publication,state:'failed_mount'});}throw Error('Unexpected UI request '+url);};
 const render=async props=>{let tree;await act(async()=>{tree=create(<AppsNativeView sessionId='A' viewId='V' {...props}/>,{createNodeMock:node=>node.type==='iframe'?{contentWindow:child}:null});});for(let n=0;n<100&&!tree.root.findAllByType('iframe').length;n++)await act(async()=>{await new Promise(resolve=>setTimeout(resolve,5));});assert.equal(tree.root.findAllByType('iframe').length,1);return tree;};
 let tree=await render({expectedBuildId:'original-build',expectedViewRevision:5,expectedPublicationId:'original-P'});assert.ok(tree.root.findByType('iframe').props.src.includes('original-build'));assert.equal(calls[0].publicationId,'original-P');assert.equal(calls[0].buildId,'original-build');assert.equal(calls.some(item=>item.body?.operation==='inspect'),false);await act(async()=>tree.unmount());
 mode='pending';calls.length=0;tree=await render({expectedBuildId:'original-build',expectedPublicationId:'original-P'});await act(async()=>tree.root.findByType('iframe').props.onError());for(let n=0;n<100&&!tree.root.findAllByType('iframe')[0]?.props.src.includes('last-good-build');n++)await act(async()=>{await new Promise(resolve=>setTimeout(resolve,5));});assert.ok(tree.root.findByType('iframe').props.src.includes('last-good-build'));assert.equal(calls.filter(item=>item.body?.operation==='failMount').length,1);assert.equal(calls.some(item=>item.body?.operation==='inspect'&&item.body.params.publicationId==='later-P'),false);const reload=calls.find(item=>item.resource==='view'&&!item.publicationId);assert.ok(reload);await act(async()=>tree.unmount());assert.equal(listeners.get('message')?.size??0,0);console.log('FIXED_PUBLICATION_AND_OWNED_FALLBACK_PASS');
 `},banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outfile:entry,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime','react-test-renderer']});const result=spawnSync(process.execPath,[entry],{encoding:'utf8',timeout:15000});assert.equal(result.status,0,result.error?.message??result.stderr);assert.match(result.stdout,/FIXED_PUBLICATION_AND_OWNED_FALLBACK_PASS/);}finally{rmSync(directory,{recursive:true,force:true});}
});
