import test from 'node:test';
import assert from 'node:assert/strict';
import {NativeAppsReferences,APPS_REFERENCE_SOURCE,type NativeBindingReceipt,type NativeBindingRequest,type NativeAppsInputState,type NativeAppsTransport,type NativeCandidate} from '../../packages/plugin-apps/client/native-apps.ts';
const tick=()=>new Promise<void>(done=>setImmediate(done));
function fixture(delayed=false){const requests:NativeBindingRequest[]=[],resolvers:((value:NativeBindingReceipt)=>void)[]=[];const transport:NativeAppsTransport={async apps(){return [{appId:'notes',displayName:'笔记'},{appId:'hallmark',displayName:'店铺'}];},bind(input){requests.push(input);if(delayed)return new Promise(done=>resolvers.push(done));return Promise.resolve({...input,status:'bound',connectionId:input.connectionId??'N1'});},async serialize(referenceId){return {text:referenceId};}};const manager=new NativeAppsReferences(transport);return {manager,requests,resolvers,transport};}
async function pick(manager:NativeAppsReferences,sessionId='A'){const rows=await manager.source.candidates({sessionId},{query:'笔',signal:new AbortController().signal});assert.equal(rows.length,1);const inserted=manager.source.onPick({candidate:rows[0],session:{sessionId},action:'pick'});assert.ok(inserted);return inserted.insert;}
const state=(ref?:string,draftRev=1,phase='plain'):NativeAppsInputState=>({phase,draftRev,draft:ref?'original text @笔记':'original text',attachmentIds:['existing-attachment'],occurrences:ref?[{occurrenceId:'occ',source:APPS_REFERENCE_SOURCE,ref}]:[]});
test('Runtime candidates preserve appId distinct from Chinese labels and pick is synchronous with no binding/send',async()=>{const f=fixture();try{const insert=await pick(f.manager);assert.equal(insert.source,APPS_REFERENCE_SOURCE);assert.equal(insert.label,'笔记');assert.equal(JSON.parse(insert.ref).appId,'notes');assert.equal(f.requests.length,0);assert.equal(f.manager.states('A')[0].status,'pending');}finally{f.manager.dispose();}});
test('native insertion receipt gates async Host binding; rejected CAS never binds',async()=>{const f=fixture();try{const insert=await pick(f.manager),token={};f.manager.observe('A',state(undefined),token);await tick();assert.equal(f.requests.length,0);f.manager.observe('A',state(insert.ref,2),token);await tick();assert.equal(f.requests.length,1);assert.equal(f.manager.states('A')[0].status,'bound');assert.equal(f.requests[0].sessionId,'A');}finally{f.manager.dispose();}});
test('remove before commit advances epoch and ignores late bound response, cancelling only the intended tuple',async()=>{const f=fixture(true);try{const insert=await pick(f.manager),token={};f.manager.observe('A',state(insert.ref),token);f.manager.observe('A',state(undefined,2),token);assert.equal(f.requests.length,2);assert.equal(f.requests[0].enabled,true);assert.equal(f.requests[1].enabled,false);assert.equal(f.requests[1].epoch,1);f.resolvers[0]({...f.requests[0],status:'bound',connectionId:'N1'});f.resolvers[1]({...f.requests[1],status:'cancelled'});await tick();assert.equal(f.manager.states('A').length,0);}finally{f.manager.dispose();}});
test('source projects original session, A/B coexist, remount and session cleanup do not disable persistent binding',async()=>{const f=fixture();try{const a=await pick(f.manager),b=await pick(f.manager,'B'),tokenA={},tokenB={};f.manager.observe('A',state(a.ref),tokenA);f.manager.observe('B',state(b.ref),tokenB);await tick();f.manager.release('A',tokenA);f.manager.observe('A',state(undefined,5),{});await tick();assert.deepEqual(f.requests.map(item=>[item.sessionId,item.enabled]),[['A',true],['B',true]]);assert.equal(f.manager.states('B')[0].status,'bound');}finally{f.manager.dispose();}});
test('manual source serialization prevents send-cleared chips from disabling the original bound connection',async()=>{const f=fixture();try{const insert=await pick(f.manager),token={};f.manager.observe('A',state(insert.ref),token);await tick();await f.manager.source.codec.serialize(insert.ref,new AbortController().signal);f.manager.observe('A',state(undefined,2),token);await tick();assert.equal(f.requests.length,1);assert.equal(f.manager.states('A')[0].manualSubmission,true);f.manager.observe('A',state(insert.ref,3),token);f.manager.observe('A',state(undefined,4),token);await tick();assert.equal(f.requests[1].enabled,false);}finally{f.manager.dispose();}});
test('pending or failed references cannot silently serialize clipboard text',async()=>{const f=fixture();try{const insert=await pick(f.manager);await assert.rejects(f.manager.source.codec.serialize(insert.ref,new AbortController().signal),/绑定尚未确认/);assert.equal(f.requests.length,0);}finally{f.manager.dispose();}});
test('connection ambiguity stays unbound until explicit choice and source disposal aborts owned work',async()=>{const f=fixture();f.transport.bind=async input=>{f.requests.push(input);return input.connectionId?{...input,status:'bound'}:{...input,status:'needs_connection',connections:[{connectionId:'N1',displayName:'一'},{connectionId:'N2',displayName:'二'}]};};try{const insert=await pick(f.manager);f.manager.observe('A',state(insert.ref),{});await tick();assert.equal(f.manager.states('A')[0].status,'needs_connection');await f.manager.choose(insert.ref,'N2');assert.equal(f.manager.states('A')[0].connectionId,'N2');assert.equal(f.requests[1].epoch,1);assert.equal(f.requests[1].connectionId,'N2');}finally{f.manager.dispose();}assert.equal(f.manager.states('A').length,0);assert.deepEqual(await f.manager.source.candidates({sessionId:'A'},{query:'',signal:new AbortController().signal}),[]);});
test('forged candidate session never inserts or binds and unsupported native state remains closed',async()=>{const f=fixture();try{const candidate:NativeCandidate={name:'notes',label:'笔记',description:'',section:'Apps',value:JSON.stringify({sessionId:'B',appId:'notes',displayName:'笔记'})};assert.equal(f.manager.source.onPick({candidate,session:{sessionId:'A'},action:'pick'}),undefined);const insert=await pick(f.manager);f.manager.observe('A',state(insert.ref),{},'cannot verify native session');await tick();assert.equal(f.requests.length,0);}finally{f.manager.dispose();}});
test('reopened original Composer restores by GET only and deletion uses persisted epoch without enabling again',async()=>{const f=fixture(),ref=JSON.stringify({kind:'dsh-apps-native-reference',version:1,sessionId:'A',appId:'notes',bindRequestId:'old-request',epoch:0}),reads:string[]=[];f.transport.inspect=async(sessionId,bindRequestId,referenceId)=>{reads.push(bindRequestId);return {sessionId,bindRequestId,referenceId,appId:'notes',epoch:4,enabled:true,connectionId:'N2',status:'bound'};};try{const token={};f.manager.observe('A',state(ref),token);await tick();assert.deepEqual(reads,['old-request']);assert.equal(f.requests.length,0);assert.equal(f.manager.states('A')[0].epoch,4);f.manager.observe('A',state(undefined,2),token);await tick();assert.equal(f.requests.length,1);assert.equal(f.requests[0].enabled,false);assert.equal(f.requests[0].connectionId,'N2');assert.equal(f.requests[0].epoch,5);}finally{f.manager.dispose();}});
test('delete while readonly restore is pending waits for current epoch, and missing records never replay enable',async()=>{const f=fixture(),ref=JSON.stringify({kind:'dsh-apps-native-reference',version:1,sessionId:'A',appId:'notes',bindRequestId:'old-request',epoch:0});let resolveRead!:(receipt:NativeBindingReceipt|null)=>void;f.transport.inspect=()=>new Promise(resolve=>{resolveRead=resolve;});try{const token={};f.manager.observe('A',state(ref),token);f.manager.observe('A',state(undefined,2),token);assert.equal(f.requests.length,0);resolveRead({sessionId:'A',bindRequestId:'old-request',referenceId:ref,appId:'notes',epoch:7,enabled:true,connectionId:'N1',status:'bound'});await tick();assert.equal(f.requests.length,1);assert.equal(f.requests[0].epoch,8);assert.equal(f.requests[0].enabled,false);}finally{f.manager.dispose();}const g=fixture();g.transport.inspect=async()=>null;try{g.manager.observe('A',state(ref),{});await tick();assert.equal(g.requests.length,0);assert.equal(g.manager.states('A')[0].status,'failed');}finally{g.manager.dispose();}});
test('failed manual serialization restores deletion observation without clearing original draft or attachments',async()=>{const f=fixture();try{const inserted=await pick(f.manager),token={};f.manager.observe('A',state(inserted.ref),token);await tick();f.transport.serialize=async()=>{throw new Error('offline');};await assert.rejects(f.manager.source.codec.serialize(inserted.ref,new AbortController().signal),/offline/);assert.equal(f.manager.states('A')[0].manualSubmission,false);const input=state(undefined,2);f.manager.observe('A',input,token);await tick();assert.equal(f.requests.at(-1)?.enabled,false);assert.equal(input.draft,'original text');assert.deepEqual(input.attachmentIds,['existing-attachment']);}finally{f.manager.dispose();}});
test('native undo restores a removed chip as visibly unavailable without replaying enable',async()=>{const f=fixture();try{const inserted=await pick(f.manager),token={};f.manager.observe('A',state(inserted.ref),token);await tick();f.manager.observe('A',state(undefined,2),token);await tick();assert.equal(f.requests.length,2);f.manager.observe('A',state(inserted.ref,3),token);await tick();assert.equal(f.requests.length,2);assert.equal(f.manager.states('A')[0].status,'failed');assert.match(f.manager.states('A')[0].message!,/已解除/);await assert.rejects(f.manager.source.codec.serialize(inserted.ref,new AbortController().signal),/绑定尚未确认/);}finally{f.manager.dispose();}});
