import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {join,resolve} from 'node:path';
import {spawnSync} from 'node:child_process';
import {build} from 'esbuild';
async function fixture(contents:string){
  mkdirSync('artifacts',{recursive:true});const directory=mkdtempSync(resolve('artifacts/native-candidate-surface-')),entry=join(directory,'fixture.mjs');
  try{await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents},banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outfile:entry,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime','react-test-renderer']});const result=spawnSync(process.execPath,[entry],{encoding:'utf8',timeout:15000});assert.equal(result.status,0,result.error?.message??result.stderr);assert.match(result.stdout,/CANDIDATE_SURFACE_PASS/);}finally{rmSync(directory,{recursive:true,force:true});}
}
const setup=`
import React,{useState} from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';
import combined from './bundles/apps/client/index.tsx';import {AppsNativeView,AppsToolView} from './packages/plugin-apps/client/view.tsx';import {AppsSidebarPane} from './packages/plugin-apps/client/sidebar.tsx';import {AppsWorkspace} from './packages/plugin-apps/client/workspace.tsx';import {watchOwnedAppsViews,NativePublicationObserver,announceAppsPublication,CandidateFrameLease} from './packages/plugin-apps/client/native-publication.tsx';import {COMPONENT_CHANNEL} from './packages/component-runtime/src/apps-client.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;const events=new Map(),posts=[],child={postMessage:value=>posts.push(value)},parent={location:{origin:'http://native.fixture'},addEventListener(type,fn){const rows=events.get(type)??new Set();rows.add(fn);events.set(type,rows);},removeEventListener(type,fn){events.get(type)?.delete(fn);},dispatchEvent(event){for(const fn of [...events.get(event.type)??[]])fn(event);return true;}};globalThis.window=parent;
const source={buildId:'candidate-build',entry:'index.html',protocol:'dsh.apps.component.v2'},pubBase={publicationId:'P',viewId:'V',ownerSessionId:'A',attemptId:'attempt',attemptEpoch:1,candidateBuildId:source.buildId,source,state:'mounting',readyDeadlineAt:new Date(Date.now()+60000).toISOString()};let publication={...pubBase},view={viewId:'V',ownerSessionId:'A',title:'Bill 商品',design:{},bindings:[],source:{...source,buildId:'last-good'},viewRevision:2,pendingPublicationId:'P',validationStatus:'draft_unpublished'},authorizeGate;const calls=[],authorizations=[],failures=[];
const json=value=>new Response(JSON.stringify(value),{headers:{'content-type':'application/json'}});
globalThis.fetch=async(url,options)=>{const query=new URL(url,'http://native.fixture'),resource=query.searchParams.get('resource'),body=options?.body?JSON.parse(options.body):undefined;calls.push({resource,sessionId:query.searchParams.get('sessionId'),publicationId:query.searchParams.get('publicationId'),body});if(resource==='apps')return json({apps:[{appId:'hallmark',displayName:'Hallmark',runtimeState:'ready',hostProjectionState:'attached'}]});if(resource==='connections'||resource==='bindings')return json([]);if(resource==='diagnostics')return json({invocations:[]});if(resource==='saved')return json({components:[],assets:[]});if(resource==='hostCapabilities')return json({adapterReady:false});if(resource==='componentFeatures')return json({features:['renderReadyV1','uiStateV1']});if(resource==='views')return json({views:[view]});if(resource==='viewData')return json({viewId:'V',bindings:[]});if(resource==='view')return json(query.searchParams.has('publicationId')?{...view,source:publication.source,publication}:{...view});if(body?.operation==='inspect')return json({publication});if(body?.operation==='authorizeFrame'){authorizations.push(body);if(authorizeGate)await authorizeGate;publication={...publication,frameInstanceId:body.params.frameInstanceId,documentNonce:body.params.documentNonce};return json({features:body.params.clientFeatures});}if(body?.operation==='negotiateFrame')return json({features:body.params.clientFeatures});if(body?.operation==='retireFrame')return json({retired:true});if(body?.operation==='failMount'){failures.push(body);publication={...publication,state:'failed_mount'};view={...view,pendingPublicationId:null};return json(publication);}if(body?.action==='componentExtension'){publication={...publication,state:'mounted',committedViewRevision:3};view={...view,source,pendingPublicationId:null,validationStatus:'verified',viewRevision:3};return json({...body.request,result:{publication,view}});}if(body?.action==='componentBridge')return json({...body.request,result:body.request.method==='getData'?{viewId:'V',bindings:[]}:{} });throw Error('Unexpected UI request '+url);};
const settle=async(ms=15)=>act(async()=>{await new Promise(resolve=>setTimeout(resolve,ms));});const until=async(predicate)=>{for(let n=0;n<100&&!predicate();n++)await settle();assert.ok(predicate());};const nodeMock=node=>node.type==='iframe'?{contentWindow:child}:null;const hello=(requestId='hello',nonce='document')=>({source:child,origin:parent.location.origin,data:{channel:COMPONENT_CHANNEL,type:'hello',protocolVersion:'2.0',requestId,documentNonce:nonce,clientFeatures:['renderReadyV1','uiStateV1']}});const receiver=()=>[...events.get('message')??[]][0];
`;

test('always-mounted native root discovers and confirms one right-pane candidate with no ToolView mounted',()=>fixture(setup+`
const registrations=new Map(),cleanups=[];let opened=0,setNavigation;const mountedListeners=new Set(),sidebar={mounted:{getSnapshot:()=> 'A',subscribe:fn=>{mountedListeners.add(fn);return()=>mountedListeners.delete(fn);}},openTab(kind,options){opened++;setNavigation({params:options?.params,revision:opened});}},controller=new AbortController();
combined.apply({get:name=>name==='sidebarRight'?sidebar:name==='sidebarRightTabs'?{register:()=>()=>{}}:name==='layout'?{selectPanel(){}}:name==='uiWorkspace'?{openSession(){}}:undefined,slots:{register(options,component){registrations.set(options.name+':'+(options.key??options.id),component);return()=>{};},inject(name,effect){const rows=effect();cleanups.push(...(typeof rows==='function'?[rows]:rows));}}});const Root=registrations.get('sidebar.panellist:hallmark-apps'),Pane=registrations.get('sidebar.right.pane.tab:dsh-plugin-hallmark/session-components');assert.ok(Root&&Pane);
function Shell(){const [navigation,set]=useState();setNavigation=set;return <><Root usePanelInfo={selector=>selector({activePanelId:null})} useSessions={selector=>selector({byId:{A:{id:'A',retainedBy:{mainView:1}}}})}/>{navigation?<Pane sessionId='A' useTabInfo={()=>({tab:{navigation,signal:controller.signal,visible:true,actions:{openTab:sidebar.openTab}}})}/>:null}</>;}
let tree;await act(async()=>{tree=create(<Shell/>,{createNodeMock:nodeMock});});await until(()=>tree.root.findAllByType('iframe').length===1);assert.equal(tree.root.findAllByType(AppsToolView).length,0);assert.equal(opened,1);await settle(1050);assert.equal(opened,1);assert.equal(tree.root.findAllByType('iframe').length,1);
let release;authorizeGate=new Promise(resolve=>release=resolve);const first=receiver()(hello('one')),second=receiver()(hello('two'));await until(()=>authorizations.length===1);assert.equal(authorizations[0].params.publicationId,'P');assert.equal(authorizations[0].sessionId,'A');assert.equal(tree.root.findAllByType('button').find(button=>button.children.join('')==='重新读取').props.disabled,true);release();await act(async()=>{await Promise.all([first,second]);});assert.equal(posts.length,2);assert.equal(posts[0].frameInstanceId,posts[1].frameInstanceId);assert.deepEqual(posts.map(post=>post.requestId).sort(),['one','two']);const {sessionId,viewId,buildId,protocolVersion,frameInstanceId}=posts[0],identity={sessionId,viewId,buildId,protocolVersion,frameInstanceId,channel:COMPONENT_CHANNEL};await act(async()=>{await receiver()({source:child,origin:parent.location.origin,data:{...identity,type:'extension',requestId:'ready',feature:'renderReadyV1',action:'ready',params:{publicationId:'P',attemptId:'attempt',attemptEpoch:1,checks:{rendered:true,bridgeReady:true,dataRead:true,unhandledErrors:[],assertionResults:[{id:'native-fixture',required:true,status:'PASS',evidenceRefs:[]}]}}}});});assert.equal(failures.length,0);assert.equal(view.viewRevision,3);assert.equal(tree.root.findAllByType('iframe').length,1);assert.match(JSON.stringify(tree.toJSON()),/已发布 · 尚未保存/);await settle(1050);assert.equal(opened,1);await act(async()=>tree.unmount());cleanups.reverse().forEach(off=>off());assert.equal(events.get('message')?.size??0,0);console.log('CANDIDATE_SURFACE_PASS');
`));

test('single-flight discovery aborts stale A replies before B ownership and ignores expired publications without writes',()=>fixture(setup+`
let current='A',releaseA,reads=0;globalThis.fetch=async(url,options)=>{const query=new URL(url,'http://native.fixture');assert.equal(options?.method,undefined);reads++;if(query.searchParams.get('sessionId')==='A')return await new Promise(resolve=>releaseA=()=>resolve(json({views:[view]})));return json({views:[{...view,ownerSessionId:'B',viewId:'B-view'}]});};const seen=[];const stopA=watchOwnedAppsViews('A',rows=>seen.push(...rows),()=>current==='A',undefined,5);await until(()=>!!releaseA);await settle(20);assert.equal(reads,1);current='B';stopA();const stopB=watchOwnedAppsViews('B',rows=>seen.push(...rows),()=>current==='B',undefined,5);releaseA();await until(()=>seen.length>0);assert.ok(seen.every(row=>row.ownerSessionId==='B'));stopB();
publication={...pubBase,readyDeadlineAt:new Date(Date.now()-1000).toISOString()};let opened=0;globalThis.fetch=async(url,options)=>{assert.equal(options?.method,undefined);const q=new URL(url,'http://native.fixture');return json(q.searchParams.get('resource')==='views'?{views:[view]}:{...view,publication});};let tree;await act(async()=>{tree=create(<NativePublicationObserver sidebarRight={{mounted:{getSnapshot:()=> 'A',subscribe:()=>()=>{}},openTab(){opened++;}}}/>);});await settle(1100);assert.equal(opened,0);assert.equal(authorizations.length,0);assert.equal(failures.length,0);await act(async()=>tree.unmount());console.log('CANDIDATE_SURFACE_PASS');
`));

test('hidden right pane cannot claim a candidate and Apps page discovers it without a manual tab click',()=>fixture(setup+`
const sidebar={mounted:{getSnapshot:()=> 'A',subscribe:()=>()=>{}},openTab(){}};const signal=new AbortController().signal;const info=visible=>({tab:{navigation:{params:{viewId:'V'},revision:1},signal,visible,actions:{openTab(){}}}});let tree;const draw=(rightVisible,mainVisible)=> <><AppsSidebarPane sessionId='A' sidebarRight={sidebar} useTabInfo={()=>info(rightVisible)}/><AppsWorkspace currentSessionId='A' usePanelInfo={selector=>selector({activePanelId:mainVisible?'hallmark-apps':null})}/></>;
await act(async()=>{tree=create(draw(false,true),{createNodeMock:nodeMock});});await until(()=>tree.root.findAllByType('iframe').length===1);assert.equal(tree.root.findAllByType(AppsNativeView).length,1);assert.equal(tree.root.findAllByType('iframe')[0].props.src.includes('candidate-build'),true);await act(async()=>{await receiver()(hello());});assert.equal(authorizations.length,1);await act(async()=>tree.update(draw(true,true)));await settle();assert.equal(tree.root.findAllByType(AppsNativeView).length,2);assert.equal(tree.root.findAllByType('iframe').length,1);await act(async()=>tree.update(draw(true,false)));await settle();assert.equal(tree.root.findAllByType('iframe').length,0);assert.equal(authorizations.length,1);assert.match(JSON.stringify(tree.toJSON()),/此候选已在另一展示视图检查/);
publication={...pubBase,publicationId:'P2',attemptId:'attempt-2',attemptEpoch:2};view={...view,pendingPublicationId:'P2'};await act(async()=>announceAppsPublication('A','V','P2'));await until(()=>tree.root.findAllByType('iframe').length===1);window.dispatchEvent(new CustomEvent('apps-authoring-published',{detail:{sessionId:'A',viewId:'V',publicationId:'P',buildId:'candidate-build'}}));await settle();assert.equal(tree.root.findAllByType('button').find(button=>button.children.join('')==='重新读取').props.disabled,true);await act(async()=>{await receiver()(hello('new','document-two'));});assert.equal(authorizations.length,2);assert.equal(authorizations[1].params.publicationId,'P2');await act(async()=>tree.unmount());console.log('CANDIDATE_SURFACE_PASS');
`));

test('fixed ToolView cards have no frame and timeout inspection preserves a publication already confirmed by its original frame',()=>fixture(setup+`
let tree;await act(async()=>{tree=create(<AppsToolView sessionId='A' phase='result' block={{meta:{apps:{sessionId:'A',viewId:'V',publicationId:'P',buildId:'candidate-build',viewRevision:2}}}}/>);});await settle();assert.equal(tree.root.findAllByType('iframe').length,0);assert.equal(tree.root.findAllByType(AppsNativeView).length,0);assert.equal(tree.root.findByProps({'data-publication-id':'P'}).props['data-build-id'],'candidate-build');assert.match(JSON.stringify(tree.toJSON()),/打开此工作视图的当前版本；原发布记录保留/);await act(async()=>tree.unmount());
await act(async()=>{tree=create(<AppsNativeView sessionId='A' viewId='V'/>,{createNodeMock:nodeMock});});await until(()=>tree.root.findAllByType('iframe').length===1);const frame=tree.root.findByType('iframe');publication={...publication,state:'mounted',committedViewRevision:3};view={...view,source,pendingPublicationId:null,validationStatus:'verified',viewRevision:3};await act(async()=>{frame.props.onError();});await settle();assert.equal(failures.length,0);assert.equal(tree.root.findAllByType('iframe').length,1);assert.match(JSON.stringify(tree.toJSON()),/已发布 · 尚未保存/);await act(async()=>tree.unmount());console.log('CANDIDATE_SURFACE_PASS');
`));

test('candidate lease rejects old-owner release and keeps an authorized publication consumed while new publication remains independent',()=>fixture(setup+`
const leases=new CandidateFrameLease(),one={},two={};leases.acquire('P',one);leases.acquire('P',two);assert.equal(leases.owns('P',one),true);assert.equal(leases.owns('P',two),false);leases.release('P',two);assert.equal(leases.owns('P',one),true);leases.authorize('P',one);leases.release('P',one);leases.acquire('P',two);assert.equal(leases.owns('P',two),false);assert.throws(()=>leases.authorize('P',two),{code:'CANDIDATE_SURFACE_CHANGED'});leases.acquire('P2',two);leases.settle('P');assert.equal(leases.owns('P2',two),true);leases.authorize('P2',two);assert.throws(()=>leases.authorize('P',one),{code:'CANDIDATE_SURFACE_CHANGED'});console.log('CANDIDATE_SURFACE_PASS');
`));

test('failMount racing with renderReady reconciles the original publication and keeps the same confirmed iframe',()=>fixture(setup+`
const baseFetch=fetch;let inspects=0,writes=0;globalThis.fetch=async(url,options)=>{const body=options?.body?JSON.parse(options.body):undefined;if(body?.operation==='inspect'){inspects++;return json({publication});}if(body?.operation==='failMount'){writes++;publication={...publication,state:'mounted',committedViewRevision:3};view={...view,source,pendingPublicationId:null,validationStatus:'verified',viewRevision:3};return new Response(JSON.stringify({error:{code:'ALREADY_PUBLISHED'}}),{status:400});}return baseFetch(url,options);};let tree;await act(async()=>{tree=create(<AppsNativeView sessionId='A' viewId='V'/>,{createNodeMock:nodeMock});});await until(()=>tree.root.findAllByType('iframe').length===1);const original=tree.root.findByType('iframe');await act(async()=>original.props.onError());await until(()=>inspects===2);await settle();assert.equal(writes,1);assert.equal(view.viewRevision,3);assert.equal(tree.root.findByType('iframe'),original);assert.match(JSON.stringify(tree.toJSON()),/已发布 · 尚未保存/);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/原发布结果尚未确认/);assert.equal(authorizations.length,0);await act(async()=>tree.unmount());console.log('CANDIDATE_SURFACE_PASS');
`));

test('a delayed P1 mount failure cannot change P2 view, notice or frame authority in the same Session',()=>fixture(setup+`
const baseFetch=fetch;let releaseOld,oldInspects=0;globalThis.fetch=async(url,options)=>{const body=options?.body?JSON.parse(options.body):undefined;if(body?.operation==='inspect'&&body.params.publicationId==='P'){oldInspects++;return await new Promise(resolve=>releaseOld=()=>resolve(json({publication:{...pubBase,state:'failed_mount'}})));}return baseFetch(url,options);};let tree;await act(async()=>{tree=create(<AppsNativeView sessionId='A' viewId='V'/>,{createNodeMock:nodeMock});});await until(()=>tree.root.findAllByType('iframe').length===1);await act(async()=>tree.root.findByType('iframe').props.onError());await until(()=>!!releaseOld);publication={...pubBase,publicationId:'P2',attemptId:'attempt-2',attemptEpoch:2};view={...view,pendingPublicationId:'P2',title:'新的 P2 工作视图'};await act(async()=>announceAppsPublication('A','V','P2'));await until(()=>tree.root.findAllByType('iframe').length===1&&tree.root.findByType('iframe').props.title==='新的 P2 工作视图');releaseOld();await settle();assert.equal(oldInspects,1);assert.equal(failures.length,0);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/候选加载失败|重新读取此视图上一成功构建/);await act(async()=>{await receiver()(hello('P2','P2-document'));});assert.equal(authorizations.length,1);assert.equal(authorizations[0].params.publicationId,'P2');assert.equal(authorizations[0].params.attemptEpoch,2);await act(async()=>tree.unmount());console.log('CANDIDATE_SURFACE_PASS');
`));

test('sidebar ownership and permission failures never downgrade to the legacy read path',()=>fixture(setup+`
let legacyReads=0,mode='permission';globalThis.fetch=async(url,options)=>{const query=new URL(url,'http://native.fixture');if(query.pathname==='/api/hallmark-app'){legacyReads++;throw Error('Unexpected legacy fallback');}assert.equal(query.searchParams.get('resource'),'views');return mode==='permission'?new Response(JSON.stringify({error:{code:'INVALID_SESSION',message:'Session permission rejected'}}),{status:403}):json({views:[{...view,ownerSessionId:'B'}]});};const sidebar={mounted:{getSnapshot:()=> 'A',subscribe:()=>()=>{}},openTab(){}},signal=new AbortController().signal;const draw=()=> <AppsSidebarPane sessionId='A' sidebarRight={sidebar} useTabInfo={()=>({tab:{navigation:{params:{viewId:'V'},revision:1},signal,visible:true,actions:{openTab(){}}}})}/>;let tree;await act(async()=>{tree=create(draw());});await settle();assert.match(JSON.stringify(tree.toJSON()),/Session permission rejected/);assert.equal(legacyReads,0);assert.equal(tree.root.findAllByType('iframe').length,0);await act(async()=>tree.unmount());mode='foreign';await act(async()=>{tree=create(draw());});await settle();assert.match(JSON.stringify(tree.toJSON()),/会话归属不一致/);assert.equal(legacyReads,0);await act(async()=>tree.unmount());console.log('CANDIDATE_SURFACE_PASS');
`));

test('a late fixed publication GET cannot open A after the native mounted owner changes to B',()=>fixture(setup+`
let owner='A',finish,opened=0;const listeners=new Set(),sidebar={mounted:{getSnapshot:()=>owner,subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);}},openTab(){opened++;}};globalThis.fetch=async(url)=>{const query=new URL(url,'http://native.fixture');if(query.searchParams.get('resource')==='views')return json({views:query.searchParams.get('sessionId')==='A'?[view]:[]});return await new Promise(resolve=>finish=()=>resolve(json({...view,publication})));};let tree;await act(async()=>{tree=create(<NativePublicationObserver sidebarRight={sidebar}/>);});await until(()=>!!finish);await act(async()=>{owner='B';for(const fn of listeners)fn();});finish();await settle();assert.equal(opened,0);assert.equal(authorizations.length,0);await act(async()=>tree.unmount());console.log('CANDIDATE_SURFACE_PASS');
`));
