import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,rmSync} from 'node:fs';
import {resolve,join} from 'node:path';
import {spawnSync} from 'node:child_process';
import {build} from 'esbuild';
import {createAppsClient,COMPONENT_CHANNEL} from '../../packages/component-runtime/src/apps-client.ts';
import {ComponentHost} from '../../packages/component-runtime/src/host.ts';
const identity={protocolVersion:'2.0' as const,sessionId:'A',viewId:'view',buildId:'build',frameInstanceId:'frame'};
function browser(host:ComponentHost){const listeners=new Set<(event:MessageEvent)=>void>(),posts:unknown[]=[];const parent={postMessage(message:unknown){posts.push(message);void host.handle(message).then(value=>{if(value)for(const listener of listeners)listener({data:value,source:parent,origin:'http://fixture'} as MessageEvent);});}};const window={parent,location:{origin:'http://fixture'},addEventListener:(_event:string,listener:(event:MessageEvent)=>void)=>listeners.add(listener),removeEventListener:(_event:string,listener:(event:MessageEvent)=>void)=>listeners.delete(listener)} as unknown as Window;return {window,posts,listeners};}
test('extension intersection preserves the original method roster and blocks unnegotiated/oversized uiState before dispatch',async()=>{let read=0,ready=0;const host=new ComponentHost(identity,{getData:()=>({}),getContext:()=>({})},{extensionHandlers:{renderReadyV1:()=>{ready++;return {status:'mounted'};},uiStateV1:()=>{read++;return {status:'empty',snapshot:null};}}});const f=browser(host),client=createAppsClient({window:f.window,clientFeatures:['uiStateV1']});try{assert.deepEqual((await client.hello()).features,['uiStateV1']);assert.deepEqual(await client.readUiState(1),{status:'empty',snapshot:null});assert.equal(read,1);await assert.rejects(client.renderReady({publicationId:'p',attemptId:'a',attemptEpoch:1,checks:{rendered:true,bridgeReady:true,dataRead:true,unhandledErrors:[],assertionResults:[]}}),{code:'UNSUPPORTED_HOST_CAPABILITY'});assert.equal(ready,0);const before=f.posts.length;await assert.rejects(client.writeUiState({uiStateSchemaVersion:1,expectedStateRevision:0,value:'x'.repeat(65536),selectionEvidence:[]}),{code:'BRIDGE_MESSAGE_TOO_LARGE'});assert.equal(f.posts.length,before);assert.equal(read,1);}finally{client.dispose();host.dispose();}assert.equal(f.listeners.size,0);});
test('React imports/migrates declared UI state before committing data and ready, then writes after successful promotion',async()=>{mkdirSync('artifacts',{recursive:true});const directory=mkdtempSync(resolve('artifacts/native-ready-')),entry=join(directory,'fixture.mjs');try{await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';
import {useApps} from './packages/component-runtime/src/apps-react.tsx';import {ComponentHost} from './packages/component-runtime/src/host.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;const events=[],listeners=new Map();let restored,ready=false,tree;
const identity={protocolVersion:'2.0',sessionId:'A',viewId:'v',buildId:'b',frameInstanceId:'f'};
const host=new ComponentHost(identity,{getData:()=>({rows:[1]}),getContext:()=>({publication:{publicationId:'p',attemptId:'a',attemptEpoch:2}})},{extensionHandlers:{uiStateV1:request=>{events.push(request.action);if(request.action==='read')return {status:'incompatible',snapshot:{sessionId:'A',viewId:'v',sourceBuildId:'old',uiStateSchemaVersion:1,stateRevision:4,value:{count:2},capturedAt:'2026-10-07',selectionEvidence:[]},removedSelections:[]};assert.equal(ready,true);assert.equal(request.params.expectedStateRevision,4);assert.equal(request.params.uiStateSchemaVersion,2);return {stateRevision:5};},renderReadyV1:request=>{events.push('ready');assert.equal(restored.count,3);assert.deepEqual(tree.root.findByType('output').children,['1']);assert.equal(request.params.attemptEpoch,2);assert.equal(typeof request.params.documentNonce,'string');assert.equal(request.params.checks.rendered,true);assert.equal(request.params.checks.assertionResults[0].status,'PASS');ready=true;return {status:'mounted'};}}});
const parent={postMessage(message){void host.handle(message).then(data=>{if(data)for(const callback of listeners.get('message')??[])callback({data,source:parent,origin:'http://fixture'});});}};
globalThis.window={parent,location:{origin:'http://fixture'},addEventListener(type,callback){if(!listeners.has(type))listeners.set(type,new Set());listeners.get(type).add(callback);},removeEventListener(type,callback){listeners.get(type)?.delete(callback);}};
const contract={uiStateSchemaVersion:2,exportState:()=>({value:restored,selectionEvidence:[]}),importState(value){events.push('import');restored=value;},migrateState(snapshot){events.push('migrate');return {value:{count:snapshot.value.count+1},selectionEvidence:[]};}};
function Component(){const apps=useApps({uiState:contract,assertionResults:()=>[{id:'visible',required:true,expected:'one row',actual:'one row',status:'PASS',evidenceRefs:[]}]});return <output>{apps.data?.rows?.length??'loading'}</output>;}
await act(async()=>{tree=create(<Component/>);await new Promise(resolve=>setTimeout(resolve,10));});await act(async()=>{await new Promise(resolve=>setTimeout(resolve,10));});assert.deepEqual(events,['read','migrate','import','ready','write']);await act(async()=>tree.unmount());assert.equal(listeners.get('message').size,0);assert.equal(listeners.get('error').size,0);console.log('READY_IMPORT_BEFORE_WRITE_PASS');
`},banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outfile:entry,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime','react-test-renderer']});const result=spawnSync(process.execPath,[entry],{encoding:'utf8',timeout:10000});assert.equal(result.status,0,result.error?.message??result.stderr);assert.match(result.stdout,/READY_IMPORT_BEFORE_WRITE_PASS/);}finally{rmSync(directory,{recursive:true,force:true});}});
