import test from 'node:test';import assert from 'node:assert/strict';import {mkdirSync,mkdtempSync,rmSync} from 'node:fs';import {resolve,join} from 'node:path';import {spawnSync} from 'node:child_process';import {build} from 'esbuild';
test('Apps local library and workspace use existing shared Runtime actions, pin history/CAS, keep multiple views and never submit native text',async()=>{mkdirSync('artifacts',{recursive:true});const directory=mkdtempSync(resolve('artifacts/native-workspace-')),entry=join(directory,'fixture.mjs');try{await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {AppsToolView,AppsNativeView} from './packages/plugin-apps/client/view.tsx';
import {savedLibraryIntent} from './packages/plugin-apps/client/library-intent.ts';
import {AppsLibrary} from './packages/plugin-apps/client/library.tsx';import {AppsWorkspace} from './packages/plugin-apps/client/workspace.tsx';import {AppsSaveControls} from './packages/plugin-apps/client/save-controls.tsx';import {WorkbenchBoard} from './packages/plugin-apps/client/workbench-board.tsx';
import {AppsRuntime,RuntimeStore} from './packages/app-runtime/src/index.ts';import {AppsPresentationService} from './packages/app-presentation/src/index.ts';import {SourceComponentStore} from './packages/source-components/src/index.ts';import {createAppsServer} from './packages/service/src/apps-server.ts';import {AppsHost} from './packages/plugin-apps/src/index.ts';import {HttpAppsHostTransport} from './packages/plugin-apps/src/transport.ts';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;const events=new Map(),viewChanges=[];globalThis.window={addEventListener(type,fn){if(!events.has(type))events.set(type,new Set());events.get(type).add(fn);},removeEventListener(type,fn){events.get(type)?.delete(fn);},dispatchEvent(event){if(event.type==='hallmark-view-updated')viewChanges.push(event.detail);for(const fn of events.get(event.type)??[])fn(event);}};
const directory=mkdtempSync(join(tmpdir(),'apps-ui-')),store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),sources=new SourceComponentStore(join(directory,'sources')),presentation=new AppsPresentationService({store,runtime,sources});presentation.configureAuthoring();runtime.register(presentation.provider());runtime.addConnection({appId:'apps',connectionId:'presentation',displayName:'共享界面',enabled:true,config:{},configRevision:1});const seed=presentation.createView('seed',{title:'历史长标题'.repeat(30)}),component=presentation.saveComponent('seed',seed.viewId,'fixture explicit save',{mode:'save_as'});presentation.manageSaved({kind:'component',id:component.componentId,action:'rename',name:'当前标题'});const first=presentation.createView('A',{title:'工作视图一'}),second=presentation.createView('A',{title:'工作视图二'});presentation.createView('B',{title:'其他会话视图'});
const server=createAppsServer({runtime,presentation,token:'t'.repeat(64)});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const agents=new Map([['A',{id:'A'}],['B',{id:'B'}]]),host=new AppsHost({agents:{get:id=>agents.get(id),list:()=>[...agents.values()]}},new HttpAppsHostTransport('http://127.0.0.1:'+server.address().port,'t'.repeat(64))),nativeFetch=globalThis.fetch,requests=[];globalThis.fetch=async(url,options)=>{if(String(url).startsWith('/api/dsh-apps')){requests.push({url:String(url),body:options?.body?JSON.parse(options.body):undefined});return host.ui(new Request('http://native.fixture'+url,options));}return nativeFetch(url,options);};const settle=()=>new Promise(resolve=>setTimeout(resolve,40));let tree;const waitForUI=async(check,message)=>{const deadline=Date.now()+3000;while(!check()&&Date.now()<deadline)await act(async()=>{await settle();});assert.ok(check(),message);};const button=name=>tree.root.findAllByType('button').find(node=>node.children.join('')===name);const open=[];
try{
 await act(async()=>{tree=create(<AppsLibrary sessionId='A' onOpenView={view=>open.push(view)}/>);await settle();});assert.equal(store.list('operations').length,0);assert.ok(button('打开组件'));assert.equal(tree.root.findAllByProps({className:'apps-library-card'}).length,1);assert.equal(requests.filter(row=>row.url.includes('resource=componentHistory')).length,0);await act(async()=>{tree.root.findByProps({className:'apps-card-history'}).props.onToggle({currentTarget:{open:true}});await settle();});assert.equal(requests.filter(row=>row.url.includes('resource=componentHistory')).length,1);await act(async()=>tree.root.findByProps({className:'apps-card-history'}).props.onToggle({currentTarget:{open:false}}));await act(async()=>{tree.root.findByProps({className:'apps-card-history'}).props.onToggle({currentTarget:{open:true}});await settle();});assert.equal(requests.filter(row=>row.url.includes('resource=componentHistory')).length,1);await act(async()=>{button('打开此版本').props.onClick();await settle();});assert.equal(open[0].ownerSessionId,'A');assert.equal(open[0].selectedSourceRevision,1);assert.equal(open[0].baseRevisionAtOpen,2);assert.equal(store.get('components',component.componentId).revision,2);
 await act(async()=>button('重命名').props.onClick());await act(async()=>tree.root.findByProps({'aria-label':'组件新名称'}).props.onChange({target:{value:'明确重命名'}}));await act(async()=>{tree.root.findByType('form').props.onSubmit({preventDefault(){}});await settle();});const rename=requests.find(row=>row.body?.input?.action==='rename').body;assert.equal(rename.input.expectedRevision,2);assert.equal(store.get('components',component.componentId).revision,3);await waitForUI(()=>tree.root.findByProps({className:'apps-card-title'}).children.join('')==='明确重命名'&&tree.root.findByProps({'aria-label':'共享组件库'}).props['aria-busy']===false,'wait for refreshed revision before expanding its new history instance');await act(async()=>{tree.root.findByProps({className:'apps-card-history'}).props.onToggle({currentTarget:{open:true}});await settle();});assert.equal(requests.filter(row=>row.url.includes('resource=componentHistory')).length,2);assert.ok(tree.root.findByProps({className:'apps-history-list'}).findAllByType('span').some(node=>node.children.join('')==='版本 3 · 明确重命名'));assert.equal(store.get('component_versions',component.componentId+':1').title,seed.title);assert.equal(open[0].baseRevisionAtOpen,2);presentation.manageSaved({kind:'component',id:component.componentId,action:'rename',name:'保存后的新标题'});await act(async()=>{window.dispatchEvent(new CustomEvent('apps-library-changed'));await settle();});assert.equal(tree.root.findByProps({className:'apps-card-title'}).children.join(''),'保存后的新标题');await act(async()=>tree.unmount());
 await act(async()=>{tree=create(<AppsWorkspace currentSessionId='A'/>);await settle();});assert.ok(button('工作视图一'));assert.ok(button('工作视图二'));assert.equal(button('其他会话视图'),undefined);assert.equal(tree.root.findAllByType(AppsLibrary).length,0,'the default workbench contains cards, not a hidden component library');await act(async()=>{tree.root.findByType(WorkbenchBoard).props.onOpenSaved();await settle();});
 const tabIds=()=>tree.root.findAllByProps({className:'apps-tab-close'}).map(node=>node.props['aria-label']);const originalTabs=tabIds();
 await act(async()=>{tree.root.findByType(AppsLibrary).props.onOpenView(first);await settle();});assert.deepEqual(tabIds(),originalTabs,'opening an existing view activates its original tab without moving or duplicating it');assert.equal(button('工作视图一').props['aria-pressed'],true);
 await act(async()=>{tree.root.findByProps({'aria-label':'关闭工作视图一'}).props.onClick();await settle();});assert.equal(button('只隐藏展示视图'),undefined);assert.equal(button('关闭并保留'),undefined);
 assert.equal(presentation.getView(first.viewId).panelState,'closed','a view without an authoring draft must close persistently');assert.equal(tree.root.findAllByProps({'aria-label':'关闭工作视图一'}).length,0);assert.ok(tree.root.findByProps({'aria-label':'恢复工作视图一'}));assert.ok(button('工作视图二'));assert.equal(store.list('authoring_drafts').length,0);
 await act(async()=>{button('刷新列表').props.onClick();await settle();});assert.equal(tree.root.findAllByProps({'aria-label':'关闭工作视图一'}).length,0,'refresh keeps archived panels closed');
 await act(async()=>tree.unmount());await act(async()=>{tree=create(<AppsWorkspace currentSessionId='A'/>);await settle();});assert.equal(tree.root.findAllByProps({'aria-label':'关闭工作视图一'}).length,0,'remount reads the persisted closed state');assert.ok(tree.root.findByProps({'aria-label':'恢复工作视图一'}));
 const viewsBeforeRestore=store.list('views').length;await act(async()=>{tree.root.findByProps({'aria-label':'恢复工作视图一'}).props.onClick();await settle();});assert.equal(presentation.getView(first.viewId).panelState,'open');assert.equal(store.list('views').length,viewsBeforeRestore);assert.equal(tree.root.findAllByProps({'aria-label':'关闭工作视图一'}).length,1);assert.equal(button('工作视图一').props['aria-pressed'],true);assert.equal(requests.filter(row=>row.body?.operation==='restoreView').length,1);
 await act(async()=>{tree.root.findAllByType('button').find(node=>node.props['aria-label']==='新建组件工作副本').props.onClick();await settle();});const begin=requests.filter(row=>row.body?.capabilityId==='apps.authoring.begin').at(-1).body;assert.equal(begin.input.mode,'new');assert.equal(begin.sessionId,'A');assert.equal(store.list('components').length,1);assert.equal(store.list('authoring_drafts').length,1);await act(async()=>tree.unmount());
 await act(async()=>{tree=create(<AppsSaveControls sessionId='A' viewId={first.viewId}/>);await settle();});const saveBefore=requests.filter(row=>row.body?.capabilityId==='apps.authoring.save_component').length;assert.equal(button('保存到组件库').props.disabled,true);await act(async()=>tree.root.findByType('form').props.onSubmit({preventDefault(){}}));assert.equal(requests.filter(row=>row.body?.capabilityId==='apps.authoring.save_component').length,saveBefore);await act(async()=>tree.root.findByProps({'aria-label':'保存组件名称'}).props.onChange({target:{value:'我正在编辑的名称'}}));store.put('views',first.viewId,{...presentation.getView(first.viewId),validationStatus:'verified',viewRevision:2});await act(async()=>{window.dispatchEvent(new CustomEvent('apps-display-ready',{detail:{sessionId:'A',viewId:first.viewId}}));await settle();});assert.equal(button('保存到组件库').props.disabled,false);assert.equal(tree.root.findByProps({'aria-label':'保存组件名称'}).props.value,'我正在编辑的名称');await act(async()=>tree.unmount());assert.equal(requests.some(row=>['requestAgent','componentBridge'].includes(row.body?.action)),false);assert.equal(store.list('components').length,1);const draftView=presentation.createView('A',{title:'制作中的商品表',design:{kind:'source'}});
 await act(async()=>{tree=create(<AppsNativeView sessionId='A' viewId={draftView.viewId}/>);await settle();});assert.match(JSON.stringify(tree.toJSON()),/正在打磨，请稍候/);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/组件设计尚无对应展示器/);assert.equal(tree.root.findAllByType('iframe').length,0);await act(async()=>tree.unmount());
 const card=<AppsToolView sessionId='A' phase='result' block={{meta:{apps:{sessionId:'A',viewId:draftView.viewId}}}}/>,changesBeforeCards=viewChanges.length;
 await act(async()=>{tree=create(card);await settle();});assert.match(JSON.stringify(tree.toJSON()),/组件正在制作，尚未构建/);assert.equal(button('打开组件 ↗'),undefined);await act(async()=>tree.unmount());
 store.put('views',draftView.viewId,{...draftView,source:{buildId:'existing-build',directory,entry:'index.html',files:['index.html']}});
 await act(async()=>{tree=create(card);await settle();});assert.ok(button('打开组件 ↗'));await act(async()=>tree.unmount());
 assert.equal(viewChanges.length,changesBeforeCards,'Mounting or remounting a historical tool card must not invalidate the session catalogue');
 savedLibraryIntent.open();await act(async()=>{tree=create(<AppsWorkspace currentSessionId='A'/>);await settle();});assert.equal(tree.root.findAllByType(AppsLibrary).length,1,'sidebar library intent survives first-mount initialization');assert.equal(button('我的组件与模板').props['aria-pressed'],true);await act(async()=>tree.unmount());
 console.log('SHARED_WORKSPACE_HISTORY_CAS_PASS');
}finally{globalThis.fetch=nativeFetch;await host.dispose();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await runtime.dispose();store.close();rmSync(directory,{recursive:true,force:true});}
`},banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outfile:entry,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime','react-test-renderer']});const result=spawnSync(process.execPath,[entry],{encoding:'utf8',timeout:15000});assert.equal(result.status,0,result.error?.message??result.stderr);assert.match(result.stdout,/SHARED_WORKSPACE_HISTORY_CAS_PASS/);}finally{rmSync(directory,{recursive:true,force:true});}});
