import test from 'node:test';import assert from 'node:assert/strict';
import {AppsRuntime,RuntimeStore} from '../../packages/app-runtime/src/index.ts';import {AppsHost,type AppsPluginContext} from '../../packages/plugin-apps/src/index.ts';import type {AppsHostTransport} from '../../packages/plugin-apps/src/transport.ts';import type {AppsAuthoringGuidance} from '../../packages/plugin-apps/src/authoring-guidance.ts';
import {authoringInstructions} from '../../packages/plugin-apps/src/authoring-guidance.ts';

test('Agent guidance describes automatic display and retry of the same preview archive after failure',()=>{
  const instructions=authoringInstructions({cliPath:null,nodeExecutable:'node',nodeArgs:[],nodeEnvironment:{},starterPath:'starter',sdkDirectory:'sdk',buildRunnerPath:'build',previewRunnerPath:'preview',runtime:{url:'http://fixture',keyFile:'key-file-reference',archiveRoot:'archive',evidenceRoot:'evidence'}},'A');
  const flow=instructions.flow.join('\n');assert.match(flow,/成功仅表示组件已准备好/);assert.match(flow,/自动在右侧加载展示/);assert.match(flow,/无需要求用户再点击打开/);assert.match(flow,/不自行调用 UI startMount、openDisplay/);assert.match(flow,/UI自动为同publication\/build开启独立显示尝试/);assert.match(flow,/才可称已展示/);assert.match(flow,/重新打开同一构建/);assert.match(flow,/latestDisplay\/displays/);assert.match(flow,/旧frame不得恢复权限/);
  assert.equal(instructions.previewRequest.mode,'live_readonly');assert.equal(instructions.previewRequest.sessionId,'A');
  assert.equal(instructions.previewRequest.runtime.url,'http://fixture');assert.deepEqual(instructions.previewRequest.requiredMethods,['getData']);
  assert.equal('data' in instructions.previewRequest,false);
  assert.equal(instructions.resultReader.request.runtime.keyFile,'key-file-reference');
});

test('prepared authoring results produce a fixed original-chat card without claiming a committed view',async()=>{
  const store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),tools=new Map<string,import('../../packages/plugin-apps/src/index.ts').NativeGatewayTool>();
  const ctx={agents:{get:()=>undefined},tools:{register(tool:import('../../packages/plugin-apps/src/index.ts').NativeGatewayTool){tools.set(tool.name,tool);return()=>tools.delete(tool.name);}}} as unknown as AppsPluginContext;
  const host=new AppsHost(ctx,{identity:async()=>runtime.identity(),listApps:async()=>[]} as unknown as AppsHostTransport);await host.start();
  try{const publication={publicationId:'P1',viewId:'V',ownerSessionId:'A',state:'prepared',expectedViewRevision:4,readyDeadlineAt:null,source:{buildId:'candidate-build'}};
    assert.deepEqual(tools.get('apps_invoke')!.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.publish'},{invocationId:'I',traceId:'T',status:'ok',data:publication}),{apps:{viewId:'V',sessionId:'A',publicationId:'P1',buildId:'candidate-build'}});
  }finally{await host.dispose();await runtime.dispose();store.close();}
});
test('trusted original Agent summary receives frozen local authoring paths and exact session request templates without credential bytes',async()=>{const store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),A={id:'A'},B={id:'B'},agents=new Map([['A',A],['B',B]]);let text!:(context:{agent?:{id:string};scope?:object})=>string;const ctx={agents:{get:(id:string)=>agents.get(id)},tools:{register:()=>()=>{}},systemPrompt:{context(contribution:{text:typeof text}){text=contribution.text;return()=>{};}}} as unknown as AppsPluginContext,transport={identity:async()=>runtime.identity(),listApps:async()=>[],describe:async()=>undefined} as unknown as AppsHostTransport,guidance:AppsAuthoringGuidance={cliPath:'C:/Official/cli/bin/dsh.cmd',nodeExecutable:'C:/Official/DeepSeek Harness.exe',nodeArgs:['--expose-internals'],nodeEnvironment:{ELECTRON_RUN_AS_NODE:'1'},starterPath:'E:/candidate/source-starter/create-apps-source.mjs',sdkDirectory:'E:/candidate/sdk/component-runtime',buildRunnerPath:'E:/candidate/lib/apps-authoring-build.js',previewRunnerPath:'E:/candidate/lib/apps-authoring-preview.js',runtime:{url:'http://127.0.0.1:4181',keyFile:'E:/runtime/service-key',archiveRoot:'E:/runtime/source-components',evidenceRoot:'E:/runtime/authoring-evidence'}},host=new AppsHost(ctx,transport,undefined,{authoringGuidance:guidance});guidance.runtime.keyFile='mutated-after-construction';await host.start();try{const summary=text({scope:A}),payload=JSON.parse(summary.split('\n')[1]);assert.equal(payload.sessionId,'A');assert.equal(payload.developerDocs.index,'E:/candidate/authoring-docs/index.md');assert.equal(payload.checkRunner.windowsCommand[3],'E:/candidate/lib/apps-authoring-check.ps1');assert.equal(payload.buildRequest.sessionId,'A');assert.equal(payload.runtime.keyFile,'E:/runtime/service-key');assert.equal(payload.buildRequest.runtime.url,'http://127.0.0.1:4181');assert.equal(payload.buildRequest.archiveRoot,payload.runtime.archiveRoot);assert.equal(payload.previewRequest.evidenceRoot,payload.runtime.evidenceRoot);assert.ok(payload.flow.some((value:string)=>value.includes('markBuilding')));assert.ok(payload.flow.some((value:string)=>value.includes('onLoad不算')));assert.equal(text({agent:{id:'A'}}),'');assert.equal(text({agent:A,scope:B}),'');assert.equal(JSON.parse(text({scope:B}).split('\n')[1]).sessionId,'B');assert.ok(Buffer.byteLength(summary)<8192);assert.equal(summary.includes('mutated-after-construction'),false);assert.equal(store.list('invocations').length,0);}finally{await host.dispose();await runtime.dispose();store.close();}});
test('only documented authoring outputs project owned fixed view/publication/build identity and mounting never claims a committed revision',async()=>{const store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),tools=new Map<string,import('../../packages/plugin-apps/src/index.ts').NativeGatewayTool>(),ctx={agents:{get:()=>undefined},tools:{register(tool:import('../../packages/plugin-apps/src/index.ts').NativeGatewayTool){tools.set(tool.name,tool);return()=>{tools.delete(tool.name);};}}} as unknown as AppsPluginContext,transport={identity:async()=>runtime.identity(),listApps:async()=>[]} as unknown as AppsHostTransport,host=new AppsHost(ctx,transport);await host.start();try{const tool=tools.get('apps_invoke')!,base={invocationId:'i',traceId:'t',status:'ok'},view={viewId:'V',ownerSessionId:'A',viewRevision:4,source:{buildId:'old-build'}};assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.begin'},{...base,data:{draft:{},attempt:{},view}}),{apps:{viewId:'V',sessionId:'A',viewRevision:4,buildId:'old-build'}});const publication={publicationId:'P',viewId:'V',ownerSessionId:'A',state:'mounting',expectedViewRevision:4,source:{buildId:'candidate-build'}};assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.publish'},{...base,data:publication}),{apps:{viewId:'V',sessionId:'A',publicationId:'P',buildId:'candidate-build'}});assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.inspect'},{...base,data:{view,publication}}),{apps:{viewId:'V',sessionId:'A',publicationId:'P',buildId:'candidate-build'}});assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.publish'},{...base,data:{...publication,state:'mounted',committedViewRevision:5}}),{apps:{viewId:'V',sessionId:'A',publicationId:'P',buildId:'candidate-build',viewRevision:5}});assert.deepEqual(tool.output.presentationMeta({appId:'notes',capabilityId:'apps.authoring.publish'},{...base,data:publication}),{});assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.record_build'},{...base,data:publication}),{});}finally{await host.dispose();await runtime.dispose();store.close();}});
