import test from 'node:test';import assert from 'node:assert/strict';import {mkdirSync,mkdtempSync,rmSync} from 'node:fs';import {resolve,join} from 'node:path';import {spawnSync} from 'node:child_process';import {build} from 'esbuild';
test('lost shared-library mutation response locks original request, fast duplicate clicks dispatch once and inspection is owner-checked GET only',async()=>{
 mkdirSync('artifacts',{recursive:true});const directory=mkdtempSync(resolve('artifacts/native-recovery-')),entry=join(directory,'fixture.mjs');
 try{await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
 import React from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';import {AppsLibrary} from './packages/plugin-apps/client/library.tsx';import {appsPresentation,inspectPresentation,unconfirmedPresentation} from './packages/plugin-apps/client/api.ts';
 import {RuntimeStore,AppsRuntime} from './packages/app-runtime/src/index.ts';import {AppsPresentationService} from './packages/app-presentation/src/index.ts';import {createAppsServer} from './packages/service/src/apps-server.ts';import {AppsHost} from './packages/plugin-apps/src/index.ts';import {HttpAppsHostTransport} from './packages/plugin-apps/src/transport.ts';
 globalThis.IS_REACT_ACT_ENVIRONMENT=true;globalThis.window=new EventTarget();const store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),presentation=new AppsPresentationService({store,runtime}),seed=presentation.createView('A',{title:'原始组件'}),component=presentation.saveComponent('A',seed.viewId,'fixture explicit',{mode:'save_as'});runtime.register(presentation.provider());runtime.addConnection({appId:'apps',connectionId:'presentation',displayName:'共享界面',enabled:true,config:{},configRevision:1});const server=createAppsServer({runtime,presentation,token:'t'.repeat(64)});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const agents=new Map([['A',{id:'A'}],['B',{id:'B'}]]),host=new AppsHost({agents:{get:id=>agents.get(id)}},new HttpAppsHostTransport('http://127.0.0.1:'+server.address().port,'t'.repeat(64))),nativeFetch=globalThis.fetch,calls=[];let lose=true;
 globalThis.fetch=async(url,options)=>{if(!String(url).startsWith('/api/dsh-apps'))return nativeFetch(url,options);const body=options?.body?JSON.parse(options.body):undefined;calls.push({url:String(url),body});const result=await host.ui(new Request('http://native.fixture'+url,options));if(lose&&body?.capabilityId==='apps.presentation.manage_saved'){lose=false;throw Error('fixture response lost after shared store commit');}return result;};
 const button=name=>tree.root.findAllByType('button').find(node=>node.children.join('')===name),wait=()=>new Promise(resolve=>setTimeout(resolve,10));let tree;
 try{await act(async()=>{tree=create(<AppsLibrary sessionId='A'/>);});for(let n=0;n<100&&!button('重命名');n++)await act(async()=>{await wait();});await act(async()=>button('重命名').props.onClick());await act(async()=>tree.root.findByProps({'aria-label':'组件新名称'}).props.onChange({target:{value:'失联已保存名称'}}));const submit=()=>tree.root.findByType('form').props.onSubmit({preventDefault(){}});await act(async()=>{submit();submit();});for(let n=0;n<100&&!button('检查原调用');n++)await act(async()=>{await wait();});assert.ok(button('检查原调用'));assert.equal(calls.filter(item=>item.body).length,1);assert.equal(store.get('components',component.componentId).revision,2);assert.equal(button('保存名称').props.disabled,true);await act(async()=>submit());assert.equal(calls.filter(item=>item.body).length,1);const original=calls.find(item=>item.body).body;
 const input={kind:'component',id:component.componentId,action:'rename',expectedRevision:1,name:'失联已保存名称'};let cached;try{await appsPresentation('A','apps.presentation.manage_saved',input);}catch(error){cached=unconfirmedPresentation(error);}assert.equal(cached.requestId,original.requestId);assert.equal(calls.filter(item=>item.body).length,1);
 const foreign=await host.ui(new Request('http://native.fixture/api/dsh-apps?resource=presentationRequest&sessionId=B&requestId='+original.requestId));assert.equal(foreign.status,400);await assert.rejects(inspectPresentation({...cached,capabilityId:'apps.authoring.save_component'}),/身份不一致/);
 await act(async()=>button('检查原调用').props.onClick());for(let n=0;n<100&&button('检查原调用');n++)await act(async()=>{await wait();});assert.equal(button('检查原调用'),undefined);assert.equal(calls.filter(item=>item.body).length,1);assert.ok(calls.some(item=>item.url.includes('resource=presentationRequest')&&item.url.includes(original.requestId)));assert.equal(store.list('invocations').length,1);assert.equal(store.list('operations').length,1);assert.equal(store.get('components',component.componentId).revision,2);for(let n=0;n<100&&!tree.root.findAllByType('strong').some(node=>node.children.join('')==='失联已保存名称');n++)await act(async()=>{await wait();});assert.ok(tree.root.findAllByType('strong').some(node=>node.children.join('')==='失联已保存名称'));await act(async()=>tree.unmount());tree=undefined;console.log('ORIGINAL_UI_REQUEST_INSPECTION_NO_REPLAY_PASS');
 }finally{if(tree)await act(async()=>tree.unmount());globalThis.fetch=nativeFetch;await host.dispose();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));await runtime.dispose();store.close();}
 `},banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outfile:entry,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime','react-test-renderer']});const result=spawnSync(process.execPath,[entry],{encoding:'utf8',timeout:15000});assert.equal(result.status,0,result.error?.message??result.stderr);assert.match(result.stdout,/ORIGINAL_UI_REQUEST_INSPECTION_NO_REPLAY_PASS/);}finally{rmSync(directory,{recursive:true,force:true});}
});
