import {APP_AUTHORING_DESCRIPTORS} from '../../packages/app-presentation/src/authoring-descriptors.ts';
import test from 'node:test';import assert from 'node:assert/strict';
import {AppsRuntime,RuntimeStore} from '../../packages/app-runtime/src/index.ts';import {AppsHost,type AppsPluginContext} from '../../packages/plugin-apps/src/index.ts';import type {AppsHostTransport} from '../../packages/plugin-apps/src/transport.ts';import type {AppsAuthoringGuidance} from '../../packages/plugin-apps/src/authoring-guidance.ts';
import {authoringInstructions} from '../../packages/plugin-apps/src/authoring-guidance.ts';

test('Agent guidance describes automatic display and retry of the same preview archive after failure',()=>{
  const instructions=authoringInstructions({cliPath:null,nodeExecutable:'node',nodeArgs:[],nodeEnvironment:{},starterPath:'starter',sdkDirectory:'sdk',buildRunnerPath:'build',previewRunnerPath:'preview',runtime:{url:'http://fixture',keyFile:'key-file-reference',archiveRoot:'archive',evidenceRoot:'evidence'}},'A');
  const flow=instructions.flow.join('\n');assert.match(flow,/成功仅表示组件已准备好/);assert.match(flow,/自动在右侧加载展示/);assert.match(flow,/无需要求用户再点击打开/);assert.match(flow,/不自行调用 UI startMount、openDisplay/);assert.match(flow,/UI自动为同publication\/build开启独立显示尝试/);assert.match(flow,/才可称已展示/);assert.match(flow,/重新打开同一构建/);assert.match(flow,/latestDisplay\/displays/);assert.match(flow,/旧frame不得恢复权限/);
  assert.equal(instructions.previewRequest.mode,'live_readonly');assert.equal(instructions.previewRequest.sessionId,'A');
  assert.equal(instructions.previewRequest.runtime.url,'http://fixture');assert.deepEqual(instructions.previewRequest.requiredMethods,['getData']);
  assert.equal('data' in instructions.previewRequest,false);
  assert.equal(instructions.resultReader.request.runtime.keyFile,'key-file-reference');
});

test('Host keeps essential experience rules compact and returns full policy on authoring describe',async()=>{
  const agent={id:'original-session'},root='C:/Users/wubil/.dsh/profiles/desktop/node_modules/dsh-plugin-apps-bundle',directory='E:/project/deepseek_h/dsh-hallmark-app/artifacts/apps-a2-bill-runtime-restored';
  let summary!:(context:{agent?:{id:string};scope?:object})=>string;
  const ctx={agents:{get:(id:string)=>id===agent.id?agent:undefined},tools:{register:()=>()=>{}},systemPrompt:{context(contribution:{text:typeof summary}){summary=contribution.text;return()=>{};}}} as unknown as AppsPluginContext;
  const transport={identity:async()=>({transportMajor:1,catalogSchemaVersion:1}),describe:async()=>APP_AUTHORING_DESCRIPTORS.find(d=>d.capabilityId==='apps.authoring.begin'),listApps:async()=>[{appId:'hallmark',displayName:'Hallmark',providerState:'active'},{appId:'notes',displayName:'Notes',providerState:'active'}]} as unknown as AppsHostTransport;
  const guidance:AppsAuthoringGuidance={cliPath:'C:/Users/wubil/AppData/Local/Programs/DeepSeek Harness/resources/runtime/cli/bin/dsh.cmd',nodeExecutable:'C:/Users/wubil/AppData/Local/Programs/DeepSeek Harness/DeepSeek Harness.exe',nodeArgs:['--expose-internals'],nodeEnvironment:{ELECTRON_RUN_AS_NODE:'1'},starterPath:root+'/source-starter/create-apps-source.mjs',sdkDirectory:root+'/sdk/component-runtime',buildRunnerPath:root+'/lib/apps-authoring-build.js',previewRunnerPath:root+'/lib/apps-authoring-preview.js',runtime:{url:'http://127.0.0.1:36994',keyFile:directory+'/service-key',archiveRoot:directory+'/source-components',evidenceRoot:directory+'/authoring-evidence'}};
  const host=new AppsHost(ctx,transport,undefined,{authoringGuidance:guidance});
  await host.start();
  try{
    assert.equal(host.nativeSessionAdapter,'disabled');
    const text=summary({scope:agent}),payload=(await host.call('apps_describe',{capabilityId:'apps.authoring.begin'},agent.id) as any).authoringGuidance,rules=payload.userPreferences.rules.join('\n');assert.match(text,/15分钟/);assert.match(text,/完整体验规则/);assert.equal(text.includes(guidance.runtime.keyFile),false);assert.ok(Buffer.byteLength(text)<1500);
    assert.equal(payload.guidanceVersion,9);assert.equal(payload.userPreferences.policy,'component-experience-v1');assert.equal(payload.userPreferences.cacheTtlMs,15*60*1000);
    assert.equal(payload.developerDocs.userPreferences,root+'/authoring-docs/user-preferences.md');
    for(const pattern of [/蓝白/,/易懂中文/,/店铺选择/,/跨接口/,/添加信息/,/全量逻辑数据/,/后端组合/,/上次成功完整快照/,/手动刷新都在后台/,/临时失败保留旧快照和原时间/,/首次无快照/,/权限撤销/])assert.match(rules,pattern);
    assert.ok(Buffer.byteLength(text)<8192,`guidance grew to ${Buffer.byteLength(text)} bytes`);
    assert.equal(summary({agent:{id:agent.id}}),'');
  }finally{await host.dispose();}
});

test('prepared authoring results produce a fixed original-chat card without claiming a committed view',async()=>{
  const store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),tools=new Map<string,import('../../packages/plugin-apps/src/index.ts').NativeGatewayTool>();
  const ctx={agents:{get:()=>undefined},tools:{register(tool:import('../../packages/plugin-apps/src/index.ts').NativeGatewayTool){tools.set(tool.name,tool);return()=>tools.delete(tool.name);}}} as unknown as AppsPluginContext;
  const host=new AppsHost(ctx,{identity:async()=>runtime.identity(),listApps:async()=>[]} as unknown as AppsHostTransport);await host.start();
  try{const publication={publicationId:'P1',viewId:'V',ownerSessionId:'A',state:'prepared',expectedViewRevision:4,readyDeadlineAt:null,source:{buildId:'candidate-build'}};
    assert.deepEqual(tools.get('apps_invoke')!.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.publish'},{invocationId:'I',traceId:'T',status:'ok',data:publication}),{apps:{viewId:'V',sessionId:'A',publicationId:'P1',buildId:'candidate-build'}});
  }finally{await host.dispose();await runtime.dispose();store.close();}
});
test('on-demand guidance retains frozen paths and exact per-session templates while summaries enforce trusted identity',async()=>{const store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),A={id:'A'},B={id:'B'},agents=new Map([['A',A],['B',B]]);let text!:(context:{agent?:{id:string};scope?:object})=>string;const ctx={agents:{get:(id:string)=>agents.get(id)},tools:{register:()=>()=>{}},systemPrompt:{context(contribution:{text:typeof text}){text=contribution.text;return()=>{};}}} as unknown as AppsPluginContext,transport={identity:async()=>runtime.identity(),listApps:async()=>[],describe:async()=>APP_AUTHORING_DESCRIPTORS.find(d=>d.capabilityId==='apps.authoring.begin')} as unknown as AppsHostTransport,guidance:AppsAuthoringGuidance={cliPath:'C:/Official/cli/bin/dsh.cmd',nodeExecutable:'C:/Official/DeepSeek Harness.exe',nodeArgs:['--expose-internals'],nodeEnvironment:{ELECTRON_RUN_AS_NODE:'1'},starterPath:'E:/candidate/source-starter/create-apps-source.mjs',sdkDirectory:'E:/candidate/sdk/component-runtime',buildRunnerPath:'E:/candidate/lib/apps-authoring-build.js',previewRunnerPath:'E:/candidate/lib/apps-authoring-preview.js',runtime:{url:'http://127.0.0.1:4181',keyFile:'E:/runtime/service-key',archiveRoot:'E:/runtime/source-components',evidenceRoot:'E:/runtime/authoring-evidence'}},host=new AppsHost(ctx,transport,undefined,{authoringGuidance:guidance});guidance.runtime.keyFile='mutated-after-construction';await host.start();try{const summary=text({scope:A}),payload=(await host.call('apps_describe',{capabilityId:'apps.authoring.begin'},'A') as any).authoringGuidance;assert.equal(payload.sessionId,'A');assert.equal(payload.developerDocs.index,'E:/candidate/authoring-docs/index.md');assert.equal(payload.checkRunner.windowsCommand[3],'E:/candidate/lib/apps-authoring-check.ps1');assert.equal(payload.buildRequest.sessionId,'A');assert.equal(payload.runtime.keyFile,'E:/runtime/service-key');assert.equal(payload.buildRequest.runtime.url,'http://127.0.0.1:4181');assert.equal(payload.buildRequest.archiveRoot,payload.runtime.archiveRoot);assert.equal(payload.previewRequest.evidenceRoot,payload.runtime.evidenceRoot);assert.ok(payload.flow.some((value:string)=>value.includes('markBuilding')));assert.ok(payload.flow.some((value:string)=>value.includes('onLoad不算')));assert.equal(text({agent:{id:'A'}}),'');assert.equal(text({agent:A,scope:B}),'');assert.match(text({scope:B}),/Apps采用固定发现网关/);assert.equal(((await host.call('apps_describe',{capabilityId:'apps.authoring.begin'},'B')) as any).authoringGuidance.sessionId,'B');assert.ok(Buffer.byteLength(summary)<8192);assert.equal(summary.includes('mutated-after-construction'),false);assert.equal(store.list('invocations').length,0);}finally{await host.dispose();await runtime.dispose();store.close();}});
test('only documented authoring outputs project owned fixed view/publication/build identity and mounting never claims a committed revision',async()=>{const store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),tools=new Map<string,import('../../packages/plugin-apps/src/index.ts').NativeGatewayTool>(),ctx={agents:{get:()=>undefined},tools:{register(tool:import('../../packages/plugin-apps/src/index.ts').NativeGatewayTool){tools.set(tool.name,tool);return()=>{tools.delete(tool.name);};}}} as unknown as AppsPluginContext,transport={identity:async()=>runtime.identity(),listApps:async()=>[]} as unknown as AppsHostTransport,host=new AppsHost(ctx,transport);await host.start();try{const tool=tools.get('apps_invoke')!,base={invocationId:'i',traceId:'t',status:'ok'},view={viewId:'V',ownerSessionId:'A',viewRevision:4,source:{buildId:'old-build'}};assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.begin'},{...base,data:{draft:{},attempt:{},view}}),{apps:{viewId:'V',sessionId:'A',viewRevision:4,buildId:'old-build'}});const publication={publicationId:'P',viewId:'V',ownerSessionId:'A',state:'mounting',expectedViewRevision:4,source:{buildId:'candidate-build'}};assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.publish'},{...base,data:publication}),{apps:{viewId:'V',sessionId:'A',publicationId:'P',buildId:'candidate-build'}});assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.inspect'},{...base,data:{view,publication}}),{apps:{viewId:'V',sessionId:'A',publicationId:'P',buildId:'candidate-build'}});assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.publish'},{...base,data:{...publication,state:'mounted',committedViewRevision:5}}),{apps:{viewId:'V',sessionId:'A',publicationId:'P',buildId:'candidate-build',viewRevision:5}});assert.deepEqual(tool.output.presentationMeta({appId:'notes',capabilityId:'apps.authoring.publish'},{...base,data:publication}),{});assert.deepEqual(tool.output.presentationMeta({appId:'apps',capabilityId:'apps.authoring.record_build'},{...base,data:publication}),{});}finally{await host.dispose();await runtime.dispose();store.close();}});
