import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {join,resolve,sep} from 'node:path';
import {spawnSync} from 'node:child_process';
import {build} from 'esbuild';

test('procurement fees require explicit valid inputs and persist through workbench CAS before new results are shown',async()=>{
  const root=resolve('artifacts');mkdirSync(root,{recursive:true});const directory=mkdtempSync(join(root,'procurement-controls-')),entry=join(directory,'fixture.mjs');
  try{
    await build({stdin:{resolveDir:process.cwd(),loader:'tsx',contents:`
import React from 'react';import {create,act} from 'react-test-renderer';import assert from 'node:assert/strict';
import {ProcurementPlanControls,procurementResultSummary} from './packages/plugin-apps/client/procurement-plan.tsx';
import {WorkbenchBoard} from './packages/plugin-apps/client/workbench-board.tsx';
import {QueryParameters,widgetMaterialId} from './packages/plugin-apps/client/module-config.tsx';
import {createMaterialView,MATERIAL_CATALOG} from './packages/app-presentation/src/materials/catalog.ts';
import {MaterialLibrary} from './packages/plugin-apps/client/material-library.tsx';
import {WorkbenchInstanceView} from './packages/plugin-apps/client/workbench-board.tsx';
globalThis.IS_REACT_ACT_ENVIRONMENT=true;
let tree,applied=[];const platform={mode:'platform',label:'平台当前方案',fixedFeeYuan:3,logisticsYuanPerKg:12,commissionPercent:15};
const settle=async()=>{for(let i=0;i<10;i++)await new Promise(resolve=>setImmediate(resolve));};
const text=node=>typeof node==='string'?node:node?.children?.map(text).join('')??'',button=name=>tree.root.findAllByType('button').find(node=>text(node)===name),applyButton=()=>tree.root.findByProps({className:'apps-procurement-plan-apply'}),change=async(label,value)=>{await act(async()=>{tree.root.findByProps({'aria-label':label}).props.onChange({target:{value}});await settle();});},click=async name=>{await act(async()=>{button(name).props.onClick();await settle();});};
const render=plan=><ProcurementPlanControls params={{planMode:'platform',limit:10,query:'杯子'}} plan={plan} onApply={params=>applied.push(params)}/>;
await act(async()=>{tree=create(render(undefined));});await change('物流方案','custom');assert.equal(tree.root.findByProps({'aria-label':'固定费用'}).props.value,'');assert.equal(applyButton().props.disabled,true,'unknown platform costs are never invented');
await act(async()=>tree.update(render(platform)));assert.equal(tree.root.findByProps({'aria-label':'每公斤运费'}).props.value,'12');assert.equal(applied.length,0,'choosing a plan does not read until apply');assert.match(JSON.stringify(tree.toJSON()),/当前结果：平台当前方案/);assert.match(JSON.stringify(tree.toJSON()),/待应用/);
for(const [label,value] of [['固定费用','-1'],['固定费用','1000001'],['佣金比例','100'],['佣金比例','']]){await change(label,value);assert.equal(applyButton().props.disabled,true);await change(label,label==='佣金比例'?'15':'3');}
await change('固定费用','0');await click('应用试算');assert.deepEqual(applied.at(-1),{limit:10,query:'杯子',planMode:'custom',fixedFeeYuan:0,logisticsYuanPerKg:12,commissionPercent:15});await act(async()=>tree.unmount());
// New views use the application's rule set, with each product choosing its own matched logistics quote.
const application={mode:'application',label:'应用动态利润规则',settingsRevision:9,selectionNote:'按实际卖家价与计费重量匹配，重合方案取总费用最高者。'};
await act(async()=>{tree=create(<ProcurementPlanControls params={{query:'杯子'}} plan={application} onApply={params=>applied.push(params)}/>);});
assert.equal(tree.root.findByProps({'aria-label':'物流方案'}).props.value,'application');assert.equal(tree.root.findAllByProps({'aria-label':'物流渠道'}).length,0);assert.equal(tree.root.findAllByType('details').length,0);
assert.match(JSON.stringify(tree.toJSON()),/当前结果使用修订 9/);assert.match(JSON.stringify(tree.toJSON()),/重合方案取总费用最高/);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/接口提供物流渠道/);
await change('物流方案','custom');assert.equal(applyButton().props.disabled,true,'a dynamic rule set does not pretend to be a single uniform fee');await act(async()=>tree.unmount());
await act(async()=>{tree=create(<ProcurementPlanControls params={{planMode:'custom',query:'杯子',fixedFeeYuan:3,logisticsYuanPerKg:12,commissionPercent:15}} plan={platform} onApply={params=>applied.push(params)}/>);});
assert.match(JSON.stringify(tree.toJSON()),/尚未使用.*经营设置.*中的动态利润规则/);
await change('物流方案','application');assert.equal(tree.root.findAllByType('details').length,0);await click('应用试算');assert.deepEqual(applied.at(-1),{query:'杯子',planMode:'application'},'switching to application rules removes ad hoc fees');await act(async()=>tree.unmount());
await act(async()=>{tree=create(<ProcurementPlanControls params={{planMode:'delivery',deliveryMethodId:'old-channel',fixedFeeYuan:3,logisticsYuanPerKg:12,commissionPercent:15,query:'杯子',loadAll:true}} plan={{mode:'delivery',label:'历史渠道试算'}} onApply={params=>applied.push(params)}/>);});
assert.match(JSON.stringify(tree.toJSON()),/原渠道试算方式/);await click('改用应用动态规则');assert.deepEqual(applied.at(-1),{query:'杯子',loadAll:true,planMode:'application'},'explicit migration preserves the component scope and removes old channel fees');await act(async()=>tree.unmount());
const delivery={mode:'delivery',label:'自动匹配物流方案',deliveryMethodId:null,fixedFeeYuan:null,logisticsYuanPerKg:null,commissionPercent:null,choices:[{id:'d1',name:'渠道一',warehouseName:'仓库一',active:true},{id:'d2',name:'渠道二',active:true},{id:'closed',name:'停用渠道',active:false}]};let deliveryParams;
function Delivery(){const [params,setParams]=React.useState({planMode:'delivery',query:'杯子'});deliveryParams=params;return <ProcurementPlanControls params={params} plan={delivery} onApply={setParams}/>;}
await act(async()=>{tree=create(<Delivery/>);});assert.equal(tree.root.findByProps({'aria-label':'物流方案'}).props.value,'delivery');assert.equal(tree.root.findByProps({'aria-label':'物流渠道'}).findAllByType('option').find(node=>node.props.value==='closed').props.disabled,true);
await change('物流渠道','d1');assert.equal(tree.root.findByProps({'aria-label':'固定费用'}).props.value,'');assert.equal(tree.root.findByType('details').props.open,true,'unknown channel fees open by default');assert.equal(applyButton().props.disabled,false);await click('应用渠道');assert.deepEqual(deliveryParams,{query:'杯子',planMode:'delivery',deliveryMethodId:'d1'},'a real channel can be applied before its tariff is known');
await change('固定费用','3');assert.equal(applyButton().props.disabled,true,'partial tariff cannot masquerade as a complete quote');await change('每公斤运费','12');await change('佣金比例','15');for(const [label,value,reset] of [['固定费用','3.001','3'],['每公斤运费','100001','12'],['每公斤运费','1.0001','12'],['佣金比例','0.00001','15']]){await change(label,value);assert.equal(applyButton().props.disabled,true);await change(label,reset);}await click('应用试算');assert.equal(deliveryParams.deliveryMethodId,'d1');assert.equal(deliveryParams.fixedFeeYuan,3);
await change('物流渠道','d2');for(const label of ['固定费用','每公斤运费','佣金比例'])assert.equal(tree.root.findByProps({'aria-label':label}).props.value,'','tariffs never transfer to a different channel');await click('应用渠道');assert.deepEqual(deliveryParams,{query:'杯子',planMode:'delivery',deliveryMethodId:'d2'});await change('物流渠道','');await click('应用渠道');assert.deepEqual(deliveryParams,{query:'杯子',planMode:'delivery'});await act(async()=>tree.unmount());
// A saved channel is not a calculated result. Summaries come only from returned rows.
const missingProducts=[{referenceProfit:{margin:null,reason:'缺少精确来源的人民币采购价。'}},{referenceProfit:{margin:null,reason:'所选物流方案费用待补充。'}}];
assert.deepEqual(procurementResultSummary(missingProducts),{total:2,calculated:0,pending:2});assert.equal(procurementResultSummary(undefined),undefined);
let finishResults;
function Feedback(){const [params,setParams]=React.useState({planMode:'delivery',deliveryMethodId:'d1'}),[response,setResponse]=React.useState({plan:{...delivery,label:'渠道一',deliveryMethodId:'d1',reason:'所选物流方案费用待补充'},products:missingProducts}),[loading,setLoading]=React.useState(false),[stale,setStale]=React.useState(false);finishResults=(value,isStale=false)=>{setResponse(value);setLoading(false);setStale(isStale);};return <ProcurementPlanControls params={params} plan={response?.plan} resultSummary={procurementResultSummary(response?.products)} resultLoading={loading} resultStale={stale} onApply={async next=>{setParams(next);setResponse(undefined);setLoading(true);}}/>;}
await act(async()=>{tree=create(<Feedback/>);});assert.equal(tree.root.findByType('details').props.open,true);assert.equal(applyButton().props.disabled,true);assert.equal(text(applyButton()),'应用渠道');assert.match(JSON.stringify(tree.toJSON()),/渠道已应用，费用待补充/);assert.match(JSON.stringify(tree.toJSON()),/本批 0 件已算 · 2 件待补充/);assert.match(JSON.stringify(tree.toJSON()),/接口提供物流渠道，未提供运价/);
await change('固定费用','3');await change('每公斤运费','12');await change('佣金比例','15');assert.equal(text(applyButton()),'应用试算');assert.equal(tree.root.findByType('details').props.open,true,'editing the last fee does not collapse the form');assert.match(JSON.stringify(tree.toJSON()),/渠道已应用，费用待补充/,'draft fees do not change the actual result summary');await click('应用试算');assert.match(JSON.stringify(tree.toJSON()),/正在读取试算结果/);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/件已算|渠道已应用/,'a resolved save does not announce profit before the read resolves');
const returnedResults={plan:{...delivery,label:'渠道一',deliveryMethodId:'d1',fixedFeeYuan:3,logisticsYuanPerKg:12,commissionPercent:15},products:[{referenceProfit:{margin:0,reason:null}},missingProducts[0]]};await act(async()=>{finishResults(returnedResults);});assert.match(JSON.stringify(tree.toJSON()),/本批 1 件已算 · 1 件待补充/,'zero margin counts as a result and missing purchase cost remains pending');assert.match(JSON.stringify(tree.toJSON()),/参考利润率.*下方原因/);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/渠道已应用，费用待补充|正在读取试算结果/);await act(async()=>{finishResults(returnedResults,true);});assert.match(JSON.stringify(tree.toJSON()),/当前为缓存结果/);
await act(async()=>{finishResults({plan:{...returnedResults.plan,fixedFeeYuan:null,reason:'物流方案暂时无法确认，商品资料仍可查看。'},products:missingProducts});});assert.match(JSON.stringify(tree.toJSON()),/物流方案暂时无法确认/);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/渠道已应用/,'an unavailable lookup must not claim an applied channel');await act(async()=>tree.unmount());
const design=createMaterialView('product-list');design.widgets[0].options={...design.widgets[0].options,materialId:'product-procurement'};assert.equal(widgetMaterialId(design.widgets[0]),'product-procurement');
const source={kind:'data_source',id:'hallmark:connection:procurement',revision:1,title:'商品采购与利润',appId:'hallmark',connectionId:'connection',capabilityId:'hallmark.products.procurement',capabilityMajor:1,input:{},storeScoped:true,parameters:[...['planMode','fixedFeeYuan','logisticsYuanPerKg','commissionPercent','query','limit'].map(name=>({name,label:name,type:name==='query'||name==='planMode'?'string':'number'}))],rowsPath:'items',fields:[],operations:{search:{scope:'server',param:'query'},sort:{scope:'loaded'},pagination:{cursorParam:'cursor'}}};
await act(async()=>{tree=create(<QueryParameters source={source} params={{}} onChange={()=>{}}/>);});assert.deepEqual(tree.root.findAllByType('input').map(node=>node.props['aria-label']),[],'dedicated controls and table search replace generic duplicates');await act(async()=>tree.unmount());
const instance={instanceId:'test',title:'商品-采购对照表',materialId:'product-procurement',materialVersion:1,design,dataSources:{products:{id:source.id,revision:1,params:{planMode:'platform',query:'杯子'}}},position:{order:0}};
let board={appId:'hallmark',kind:'workbench',workbenchId:'board',revision:7,context:{storeId:'A'},instances:[instance]},holdRead=false,release;const requests=[];
globalThis.fetch=async(url,options)=>{const body=options?.body?JSON.parse(options.body):undefined;if(!body){const resource=new URL(url,'http://fixture').searchParams.get('resource');return Response.json(resource==='stores'?{stores:[{id:'A',name:'Bill',connectionId:'connection'},{id:'B',name:'Helen',connectionId:'connection'}]}:board);}requests.push(body);if(body.operation==='save'){assert.equal(body.params.expectedRevision,board.revision);board={...board,...body.params,revision:board.revision+1};return Response.json(board);}assert.equal(body.operation,'read');if(holdRead)await new Promise(resolve=>release=resolve);const params=board.instances[0].dataSources.products.params,plan=params.planMode==='custom'?{...params,mode:'custom',label:'自定义方案'}:platform,derived=structuredClone(design);derived.widgets[0].fields={'product.id':'id','product.name':'name','price.current':'price'};derived.widgets[0].options.rowsPath='items';return Response.json({instanceId:'test',view:{viewId:'view',design:derived},dataSources:{products:source},pages:{products:{hasMore:false,loadedCount:1}},data:{viewId:'view',bindings:[{bindingId:'products',datasetId:JSON.stringify(params)+board.context.storeId,payload:{items:[{id:'p1',name:board.context.storeId+' '+plan.label+'商品',price:10}],products:[{referenceProfit:{margin:params.planMode==='custom'?null:0.2}}],plan},state:'ready',lastSuccessAt:'2026-10-09T00:00:00Z',freshness:'fresh',provenance:[]}]}});};
await act(async()=>{tree=create(<WorkbenchBoard appId='hallmark' detailInstanceId='test' onAdd={()=>{}} onConfigure={()=>{}}/>);await settle();});assert.match(JSON.stringify(tree.toJSON()),/本批 1 件已算 · 0 件待补充/,'workbench detail forwards actual binding products');await change('物流方案','custom');await change('固定费用','4');holdRead=true;await click('应用试算');assert.equal(board.instances[0].dataSources.products.params.planMode,'custom');assert.equal(board.instances[0].dataSources.products.params.fixedFeeYuan,4);assert.equal(board.instances[0].dataSources.products.params.query,'杯子');assert.equal(board.revision,8);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/平台当前方案商品/,'changing applied scheme clears the old profit rows before new read resolves');assert.match(JSON.stringify(tree.toJSON()),/正在读取试算结果/);assert.doesNotMatch(JSON.stringify(tree.toJSON()),/件已算/,'workbench never announces old result counts during a changed scheme read');
holdRead=false;await act(async()=>{release();await settle();});assert.match(JSON.stringify(tree.toJSON()),/自定义方案商品/);assert.match(JSON.stringify(tree.toJSON()),/本批 0 件已算 · 1 件待补充/);await change('当前店铺','B');assert.equal(board.instances[0].dataSources.products.params.fixedFeeYuan,4,'scheme follows instance across store changes');assert.match(JSON.stringify(tree.toJSON()),/B 自定义方案商品/);
await change('物流方案','platform');await click('应用试算');assert.equal(board.instances[0].dataSources.products.params.planMode,'platform');assert.equal(Object.hasOwn(board.instances[0].dataSources.products.params,'fixedFeeYuan'),false);assert.match(JSON.stringify(tree.toJSON()),/B 平台当前方案商品/);assert.equal(requests.filter(item=>item.operation==='save').length,3);await act(async()=>tree.unmount());
// A missing catalog entry is initialized through the platform, then the real source is pinned.
source.fields=[{role:'product.id',path:'id',confirmed:true},{role:'product.name',path:'name',confirmed:true},{role:'price.current',path:'price',confirmed:true,currency:'CNY'}];source.validation={status:'unverified',checkedAt:'',sampleCount:0,issues:[]};let initialized=0,completed;
globalThis.fetch=async(url,options)=>{const body=options?.body?JSON.parse(options.body):undefined;if(!body){const resource=new URL(url,'http://fixture').searchParams.get('resource');return Response.json(resource==='stores'?{stores:[{id:'B',name:'Helen',connectionId:'connection'}]}:resource==='materials'?{materials:MATERIAL_CATALOG}:resource==='dataSources'?{dataSources:[]}:board);}if(body.operation==='initialize'){initialized++;return Response.json({dataSources:[source],issues:[]});}if(body.operation==='save'){board={...board,...body.params,revision:board.revision+1};return Response.json(board);}assert.equal(body.operation,'preview');const current=body.params.instance,params=current.dataSources.products.params,derived=structuredClone(current.design);derived.widgets[0].fields={'product.id':'id','product.name':'name','price.current':'price'};derived.widgets[0].options.rowsPath='items';return Response.json({instanceId:current.instanceId,view:{viewId:'preview',design:derived},dataSources:{products:source},pages:{products:{hasMore:false,loadedCount:1}},data:{viewId:'preview',bindings:[{bindingId:'products',datasetId:JSON.stringify(params),payload:{items:[{id:'p1',name:'真实商品',price:10}],plan:params.planMode==='custom'?{...params,mode:'custom',label:'自定义方案'}:platform},state:'ready',lastSuccessAt:'2026-10-09T00:00:00Z',freshness:'fresh',provenance:[]}]}});};
await act(async()=>{tree=create(<MaterialLibrary appId='hallmark' sessionId='chat' onComplete={value=>completed=value}/>);await settle();});await click('商品');assert.ok(tree.root.findByProps({'aria-label':'选择商品-采购对照表'}));await act(async()=>{tree.root.findByProps({'aria-label':'选择商品-采购对照表'}).props.onClick();await settle();});assert.equal(initialized,1);assert.equal(tree.root.findByType(WorkbenchInstanceView).props.instance.dataSources.products.id,source.id);assert.equal(tree.root.findAllByType('input').filter(node=>node.props['aria-label']==='query').length,0);
await change('物流方案','custom');await change('固定费用','5');await change('每公斤运费','12');await change('佣金比例','15');await click('应用试算');assert.equal(tree.root.findByType(WorkbenchInstanceView).props.instance.dataSources.products.params.fixedFeeYuan,5);await click('添加到工作台');assert.equal(completed.title,'商品-采购对照表');assert.equal(completed.dataSources.products.params.fixedFeeYuan,5);assert.equal(completed.dataSources.products.params.planMode,'custom');await act(async()=>tree.unmount());
console.log('PROCUREMENT_PLAN_CONTROLS_PASS');
`},banner:{js:"import {createRequire} from 'node:module';const require=createRequire(import.meta.url);"},outfile:entry,bundle:true,platform:'node',format:'esm',jsx:'automatic',external:['react','react/jsx-runtime','react-test-renderer']});
    const result=spawnSync(process.execPath,[entry],{encoding:'utf8',timeout:20000});assert.equal(result.status,0,result.error?.message??result.stderr);assert.match(result.stdout,/PROCUREMENT_PLAN_CONTROLS_PASS/);
  }finally{assert.ok(resolve(directory).startsWith(root+sep));rmSync(directory,{recursive:true,force:true});}
});
