import test from 'node:test';
import assert from 'node:assert/strict';
import fs,{mkdtempSync,mkdirSync,writeFileSync,readFileSync,rmSync,statSync,utimesSync} from 'node:fs';
import {syncBuiltinESMExports} from 'node:module';
import {join,resolve} from 'node:path';
import {tmpdir} from 'node:os';
import {createHash} from 'node:crypto';
import {SourceComponentStore} from '../../packages/source-components/src/index.ts';
import {FileVerificationCache} from '../../packages/source-components/src/file-verification-cache.ts';
import {queryRows} from '../../packages/app-presentation/src/store-query.ts';
import {RuntimeStore} from '../../packages/app-runtime/src/store.ts';
import {DataSourceLibrary} from '../../packages/app-presentation/src/data-sources.ts';
import {AppsAuthoringService} from '../../packages/app-presentation/src/authoring.ts';
import {AppsPresentationService} from '../../packages/app-presentation/src/index.ts';
import {AuthoringEvidenceRunner} from '../../packages/source-components/src/authoring-evidence.ts';
import {AUTHORING_BUILD_RECEIPT_SCHEMA} from '../../packages/app-presentation/src/authoring-descriptors.ts';
import {compileSchema} from '../../packages/app-contracts/src/index.ts';
import type {BuildReceipt,FileEvidenceRef,PreviewReceipt,AuthoringAttempt} from '../../packages/app-presentation/src/authoring-types.ts';
import type {DataSourceDraft,PresentationRuntime} from '../../packages/app-presentation/src/types.ts';
import type {CapabilityDescriptor,InvocationSource} from '../../packages/app-contracts/src/index.ts';

function fixture(t:{after:(fn:()=>void)=>void}){const root=mkdtempSync(join(tmpdir(),'backend-performance-'));t.after(()=>{assert.ok(resolve(root).startsWith(resolve(tmpdir())));rmSync(root,{recursive:true,force:true});});return root;}
function countReads<T>(path:string,work:()=>T){const original=fs.readFileSync;let calls=0,bytes=0;(fs as unknown as {readFileSync:typeof fs.readFileSync}).readFileSync=((file:Parameters<typeof readFileSync>[0],...args:unknown[])=>{const result=(original as (...input:unknown[])=>Buffer|string)(file,...args);if(String(file).startsWith(path)){calls++;bytes+=Buffer.byteLength(result);}return result;}) as typeof fs.readFileSync;syncBuiltinESMExports();try{return {result:work(),calls,bytes};}finally{fs.readFileSync=original;syncBuiltinESMExports();}}
function archive(t:{after:(fn:()=>void)=>void}){const root=fixture(t),project=join(root,'project');mkdirSync(join(project,'dist'),{recursive:true});writeFileSync(join(project,'dist','index.html'),'<main>source archive</main>');writeFileSync(join(project,'source.txt'),'a'.repeat(4096));const sources=new SourceComponentStore(join(root,'archive')),source=sources.capture(project).source;return {root,sources,source,project:join(sources.directory,'builds',source.buildId,'project')};}

test('archive verification reads each archived file once then uses stat-checked bounded reuse',t=>{const f=archive(t),cold=countReads(f.project,()=>f.sources.verify(f.source.buildId));assert.equal(cold.result.valid,true);assert.equal(cold.calls,2);const warm=countReads(f.project,()=>f.sources.verify(f.source.buildId));assert.equal(warm.result.valid,true);assert.equal(warm.calls,0);console.log(JSON.stringify({metric:'archive-verification',coldReads:cold.calls,coldBytes:cold.bytes,warmReads:warm.calls,warmBytes:warm.bytes}));});
test('warm archive verification detects same-size edits with restored mtime, added members and manifest changes',t=>{const f=archive(t);assert.equal(f.sources.verify(f.source.buildId).valid,true);const path=join(f.project,'source.txt'),before=statSync(path),original=readFileSync(path);writeFileSync(path,'b'.repeat(original.length));utimesSync(path,before.atime,before.mtime);assert.equal(f.sources.verify(f.source.buildId).valid,false);writeFileSync(path,original);assert.equal(f.sources.verify(f.source.buildId).valid,true);writeFileSync(join(f.project,'extra.txt'),'unexpected member');assert.equal(f.sources.verify(f.source.buildId).valid,false);rmSync(join(f.project,'extra.txt'));assert.equal(f.sources.verify(f.source.buildId).valid,true);const manifest=join(f.sources.directory,'builds',f.source.buildId,'manifest.json'),value=JSON.parse(readFileSync(manifest,'utf8'));value.fileManifest[0].sha256='0'.repeat(64);writeFileSync(manifest,JSON.stringify(value));assert.equal(f.sources.verify(f.source.buildId).valid,false);});
test('historical manifests remain valid and the archive cache evicts beyond 64 entries',t=>{const f=archive(t),manifest=join(f.sources.directory,'builds',f.source.buildId,'manifest.json'),value=JSON.parse(readFileSync(manifest,'utf8'));delete value.fileManifest;delete value.manifestVersion;writeFileSync(manifest,JSON.stringify(value));assert.equal(f.sources.verify(f.source.buildId).valid,true);const project=join(f.root,'project');for(let i=0;i<64;i++){writeFileSync(join(project,'dist','index.html'),`<main>version ${i}</main>`);const source=f.sources.capture(project).source;assert.equal(f.sources.verify(source.buildId).valid,true);}assert.equal(countReads(f.project,()=>f.sources.verify(f.source.buildId)).calls,2);});
test('evidence cache has entry and byte limits, returns independent bytes, and does not cache failures',t=>{const root=fixture(t),cache=new FileVerificationCache(2,12),refs=['one','two','three'].map((name,index)=>{const path=join(root,name),bytes=Buffer.from(String(index).repeat(6));writeFileSync(path,bytes);return {path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};});const read=(index:number)=>cache.read(refs[index].path,refs[index].sha256,refs[index].bytes);read(0).fill(0);assert.equal(read(0).toString(),'000000');read(1);read(2);assert.equal(countReads(root,()=>read(0)).calls,1);const oversized=join(root,'large');writeFileSync(oversized,'x'.repeat(13));const sha=createHash('sha256').update('x'.repeat(13)).digest('hex');cache.read(oversized,sha,13);assert.equal(countReads(root,()=>cache.read(oversized,sha,13)).calls,1);writeFileSync(refs[0].path,'badbad');assert.throws(()=>read(0),/FILE_HASH_MISMATCH/);writeFileSync(refs[0].path,'000000');assert.equal(read(0).toString(),'000000');});
test('receipt verification deduplicates shared files and rechecks evidence changes',t=>{const root=fixture(t),store=new RuntimeStore(':memory:');t.after(()=>store.close());const sources=new SourceComponentStore(join(root,'sources')),evidenceRoot=join(root,'evidence'),service=new AppsAuthoringService({store,sources,evidenceRoot,presentation:{} as never}),path=join(evidenceRoot,'shared.png');writeFileSync(path,'same evidence');const bytes=readFileSync(path),ref:FileEvidenceRef={path,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')};const attempt={evidenceRefs:[ref,ref]} as AuthoringAttempt,build={logRef:ref,fileManifestRef:ref} as BuildReceipt,preview={viewportResults:[{screenshot:ref},{screenshot:ref}],assertionResults:[{evidenceRefs:[ref,ref]}]} as unknown as PreviewReceipt,verify=()=>{(service as unknown as {verifyReceiptFiles(a:AuthoringAttempt,b:BuildReceipt,p:PreviewReceipt):void}).verifyReceiptFiles(attempt,build,preview);};assert.equal(countReads(evidenceRoot,verify).calls,1);assert.equal(countReads(evidenceRoot,verify).calls,0);const stat=statSync(path);writeFileSync(path,'evil evidence');utimesSync(path,stat.atime,stat.mtime);assert.throws(verify,{code:'EVIDENCE_HASH_MISMATCH'});});
test('exact indexed store queries parse matching rows only and preserve list ordering',t=>{const store=new RuntimeStore(':memory:');t.after(()=>store.close());store.put('provider_records','b',{namespace:'component_displays',value:{viewId:'target',generation:2}});store.put('provider_records','a',{namespace:'component_displays',value:{viewId:'target',generation:1}});for(let i=0;i<1000;i++)store.put('provider_records','unrelated:'+i,{namespace:'other',value:{viewId:'other'}});const expected=store.list<{namespace:string;value:{viewId:string;generation:number}}>('provider_records').filter(row=>row.namespace==='component_displays'&&row.value.viewId==='target').map(row=>row.value.generation),original=JSON.parse;let parsed=0;JSON.parse=((...args:Parameters<typeof JSON.parse>)=>{parsed++;return original(...args);}) as typeof JSON.parse;try{const rows=(store as unknown as {query<T>(collection:string,filters:Record<string,string>):T[]}).query<{value:{generation:number}}>('provider_records',{namespace:'component_displays','value.viewId':'target'});assert.equal(parsed,2);assert.deepEqual(rows.map(row=>row.value.generation),expected);console.log(JSON.stringify({metric:'exact-query',unrelatedRows:1000,parsedRows:parsed}));}finally{JSON.parse=original;}});
test('query whitelist rejects injected paths and fallback matches null and namespace filters',t=>{const store=new RuntimeStore(':memory:');t.after(()=>store.close());store.put('views','null',{ownerSessionId:null});store.put('views','absent',{});assert.deepEqual(store.query('views',{ownerSessionId:null}),[{ownerSessionId:null}]);for(const filters of [{}, {"ownerSessionId') OR 1=1 --":'foreign'}, {unknown:'value'}] as Record<string,string>[])assert.throws(()=>store.query('views',filters),/INVALID_RUNTIME_QUERY/);const stub={...store,list:()=>[{namespace:'component_displays',value:{viewId:'target'}},{namespace:'foreign',value:{viewId:'target'}}]} as never;assert.deepEqual(queryRows(stub,'provider_records',{namespace:'component_displays','value.viewId':'target'}),[{namespace:'component_displays',value:{viewId:'target'}}]);});

const descriptor:CapabilityDescriptor={
  capabilityId:'fixture.list',version:'1.0.0',title:'Fixture',description:'Fixture',effect:'query',
  inputSchema:{type:'object',additionalProperties:false},
  outputSchema:{type:'object',properties:{items:{type:'array',items:{type:'object',properties:{id:{type:'string'},name:{type:'string'}}}}},required:['items']},
  execution:{mode:'sync',timeoutMs:1000,concurrency:'declared_safe',lockScope:'connection',idempotency:'not_applicable',completionEvidence:'response'},
  discovery:{defaultVisible:false,keywords:[]},aliases:[],
};
const source:InvocationSource={kind:'agent',sessionId:'A',nativeCallId:'first-call'};
const definition:DataSourceDraft={id:'fixture',title:'Fixture',appId:'fixture',connectionId:'fixture',capabilityId:'fixture.list',capabilityMajor:1,input:{},parameters:[],rowsPath:'items',fields:[{path:'id',role:'product.id',confirmed:true}],operations:{search:{scope:'loaded'},sort:{scope:'loaded'}}};
test('only title/description registration reuses confirmed validation; semantic changes, stale and partial stay rejected',async t=>{const store=new RuntimeStore(':memory:');t.after(()=>store.close());let calls=0,status:'ok'|'partial'='ok',stale=false;const runtime:PresentationRuntime={describe:()=>structuredClone(descriptor),invoke:async request=>{calls++;return status==='partial'?{status:'partial',invocationId:request.invocationId,traceId:request.traceId,data:{items:[{id:'1',name:'Item'}]}} as never:{status:'ok',invocationId:request.invocationId,traceId:request.traceId,data:{items:[{id:'1',name:'Item'}],cache:{stale}}};}},library=new DataSourceLibrary({store,runtime});const first=await library.register({definition},source);stale=true;const renamed=await library.register({definition:{...definition,title:'Renamed',description:'Label only'},expectedRevision:first.revision},{...source,nativeCallId:'rename-call'});assert.equal(calls,1);assert.deepEqual(renamed.validation,first.validation);const changed={...definition,fields:[{path:'name',role:'product.name',confirmed:true}]};await assert.rejects(library.register({definition:changed,expectedRevision:renamed.revision},source),{code:'DATA_SOURCE_VALIDATION_FAILED'});assert.equal(calls,2);stale=false;status='partial';await assert.rejects(library.register({definition:changed,expectedRevision:renamed.revision},source),{code:'DATA_SOURCE_VALIDATION_FAILED'});assert.equal(calls,3);console.log(JSON.stringify({metric:'metadata-registration',initialReads:1,metadataExtraReads:0,semanticReads:2}));});
test('registration reuse requires same session, schema, sampling context and current CAS; explicit validate stays fresh',async t=>{const store=new RuntimeStore(':memory:');t.after(()=>store.close());let calls=0,current=structuredClone(descriptor);const runtime:PresentationRuntime={describe:()=>current,invoke:async request=>{calls++;return {status:'ok',invocationId:request.invocationId,traceId:request.traceId,data:{items:[{id:'1'}]}};}},library=new DataSourceLibrary({store,runtime});let previous=await library.register({definition},source);const renamed=()=>({definition:{...definition,title:'Label edit'},expectedRevision:previous.revision});previous=await library.register(renamed(),{...source,sessionId:'B'});assert.equal(calls,2);current={...current,version:'1.1.0'};previous=await library.register(renamed(),{...source,sessionId:'B'});assert.equal(calls,3);previous=await library.register({...renamed(),context:{storeId:'B'}},{...source,sessionId:'B'});assert.equal(calls,4);const validation=await library.validateRegistration({...renamed(),context:{storeId:'B'}},{...source,sessionId:'B'});assert.equal(calls,4);current={...current,version:'1.2.0'};assert.throws(()=>library.commit(renamed(),validation),{code:'DATA_SOURCE_VALIDATION_CHANGED'});current={...current,version:'1.1.0'};await library.validate({...renamed(),context:{storeId:'B'}},{...source,sessionId:'B'});assert.equal(calls,5);assert.throws(()=>library.commit({...renamed(),expectedRevision:previous.revision-1},validation),{code:'DATA_SOURCE_CONFLICT'});});
test('reused build receipts retain original execution provenance and every ancestor; later tampering fails revalidation',async t=>{
  const root=fixture(t),store=new RuntimeStore(':memory:');t.after(()=>store.close());const sources=new SourceComponentStore(join(root,'sources')),runner=new AuthoringEvidenceRunner(join(root,'evidence')),runtime={describe:()=>undefined,invoke:async()=>({status:'failed'} as never)},presentation=new AppsPresentationService({store,sources,runtime}),authoring=new AppsAuthoringService({store,sources,presentation,evidenceRoot:runner.root,validateBuildEvidence:reference=>runner.verifyBuild(reference,sources,{allowFailure:true})});
  const first=authoring.begin('A',{mode:'new'}),workspace=first.draft.workspacePath;writeFileSync(join(workspace,'package-lock.json'),'{}');writeFileSync(join(workspace,'build.mjs'),"import{mkdirSync,writeFileSync}from'node:fs';mkdirSync('dist',{recursive:true});writeFileSync('dist/index.html','<main>reuse</main>');");
  const input=(begin:typeof first)=>({attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,sourceRevision:begin.attempt.sourceRevision,workspacePath:workspace,command:[process.execPath,'build.mjs'],sources});
  const original=await runner.build(input(first));await authoring.recordBuild('A',{attemptId:first.attempt.attemptId,epoch:first.attempt.epoch,reportRef:original.reportRef});
  let prior=original,latest:BuildReceipt|undefined,current=first;
  for(let i=0;i<2;i++){current=authoring.begin('A',{mode:'edit',viewId:first.view.viewId});authoring.markBuilding('A',{attemptId:current.attempt.attemptId,epoch:current.attempt.epoch});prior=runner.reuseBuild(prior.reportRef,input(current));latest=await authoring.recordBuild('A',{attemptId:current.attempt.attemptId,epoch:current.attempt.epoch,reportRef:prior.reportRef});assert.equal(latest.executionKind,'reuse');assert.equal(latest.executionId,original.report.executionId);assert.equal(latest.startedAt,original.report.startedAt);assert.equal(latest.finishedAt,original.report.finishedAt);assert.deepEqual(compileSchema(AUTHORING_BUILD_RECEIPT_SCHEMA)(latest),[]);}
  const refs=store.query<{file:FileEvidenceRef}>('artifact_refs',{ownerKind:'build_receipt',ownerId:latest!.receiptId,targetKind:'file'});assert.ok(refs.some(ref=>ref.file.sha256===original.reportRef.sha256));assert.ok(refs.some(ref=>ref.file.sha256===latest!.reusedFrom!.sha256));
  const verify=()=>{(authoring as unknown as {verifyReceiptFiles(a:AuthoringAttempt,b:BuildReceipt,p:PreviewReceipt):void}).verifyReceiptFiles(store.get<AuthoringAttempt>('authoring_attempts',current.attempt.attemptId)!,latest!,{viewportResults:[],assertionResults:[]} as unknown as PreviewReceipt);};verify();writeFileSync(original.reportRef.path,'tampered original signed report');assert.throws(verify,{code:'EVIDENCE_HASH_MISMATCH'});
});
test('backend rejects draft diagnostics before any formal preview fields can claim PASS',t=>{const root=fixture(t),store=new RuntimeStore(':memory:');t.after(()=>store.close());const service=new AppsAuthoringService({store,sources:new SourceComponentStore(join(root,'sources')),presentation:{} as never});assert.throws(()=>(service as unknown as {validatePreview(value:unknown,context:unknown,build:unknown):void}).validatePreview({validationProfile:'draft',verdict:'PASS'},{},{}),{code:'PREVIEW_INCOMPLETE'});});
test('collection version is stable on reads and advances for writes, deletes, rollbacks and external commits',t=>{
  const root=mkdtempSync(join(tmpdir(),'backend-performance-')),path=join(root,'runtime.db'),store=new RuntimeStore(path),other=new RuntimeStore(path);t.after(()=>{other.close();store.close();assert.ok(resolve(root).startsWith(resolve(tmpdir())));rmSync(root,{recursive:true,force:true});});
  const empty=store.collectionVersion('views');store.list('views');store.get('views','missing');assert.equal(store.collectionVersion('views'),empty);assert.notEqual(other.collectionVersion('views'),empty);
  store.put('views','view',{ownerSessionId:'A',title:'first'});const written=store.collectionVersion('views');assert.notEqual(written,empty);assert.equal(store.delete('views','missing'),false);assert.equal(store.collectionVersion('views'),written);
  assert.throws(()=>store.transaction(()=>{store.put('views','view',{ownerSessionId:'A',title:'rolled back'});throw new Error('rollback');}),/rollback/);assert.notEqual(store.collectionVersion('views'),written);assert.equal(store.get<{title:string}>('views','view')!.title,'first');
  const beforeExternal=store.collectionVersion('views');other.put('views','other',{ownerSessionId:'B'});assert.notEqual(store.collectionVersion('views'),beforeExternal);const beforeDelete=store.collectionVersion('views');assert.equal(store.delete('views','view'),true);assert.notEqual(store.collectionVersion('views'),beforeDelete);assert.throws(()=>store.collectionVersion('invalid'),/UNKNOWN_RUNTIME_COLLECTION/);
});
