import test from 'node:test';
import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {existsSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {canonicalJson} from '../../packages/app-contracts/src/index.ts';
import {composeAppsRuntime} from '../../packages/service/src/apps-main.ts';
import {createAppsServer} from '../../packages/service/src/apps-server.ts';
import type {AuthoringDraft,AuthoringAttempt,AuthoringView,BuildReceipt,PreviewReceipt,StartMountInput,ViewPublication} from '../../packages/app-presentation/src/authoring-types.ts';
// @ts-expect-error Actual isolated browser runner is also exported by the standalone CLI.
import {runAuthoringPreview} from '../../scripts/apps-authoring-preview.mjs';

const browser=process.env.DSH_PREVIEW_BROWSER_PATH??'C:/Program Files/Google/Chrome/Application/chrome.exe';
async function setup(){
 const directory=mkdtempSync(join(tmpdir(),'apps-authoring-http-')),instance=composeAppsRuntime(directory,{connections:[]}),token='a'.repeat(64),server=createAppsServer({...instance,token});
 await new Promise<void>(accept=>server.listen(0,'127.0.0.1',accept));const url=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
 const call=async(path:string,input?:unknown)=>{const response=await fetch(url+path,{method:input===undefined?'GET':'POST',headers:{authorization:'Bearer '+token,...(input===undefined?{}:{'content-type':'application/json'})},...(input===undefined?{}:{body:JSON.stringify(input)})});return {status:response.status,body:await response.json()};};
 const action=async(capabilityId:string,input:unknown,requestId=randomUUID())=>{const result=await call('/v1/presentation-actions',{sessionId:'original',capabilityId,input,requestId});assert.equal(result.status,200);return result.body;};
 const begin=async(input:unknown)=>{const result=await action('apps.authoring.begin',input);assert.equal(result.status,'ok',JSON.stringify(result));return result.data as {draft:AuthoringDraft;attempt:AuthoringAttempt;view:AuthoringView};};
 return {...instance,directory,url,token,call,action,begin,async cleanup(){server.closeAllConnections();await new Promise<void>(accept=>server.close(()=>accept()));await instance.close();assert.ok(resolve(directory).startsWith(resolve(tmpdir())));rmSync(directory,{recursive:true,force:true,maxRetries:5,retryDelay:200});}};
}
function project(workspace:string,title:string){
 const html=`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><h1>${title}</h1><button id="toggle">Select</button><output id="result">unselected</output><script>window.addEventListener('message',e=>{if(e.source!==parent||e.origin!==location.origin)return;const m=e.data;if(m.type==='hello')parent.postMessage({channel:m.channel,protocolVersion:'2.0',sessionId:m.sessionId,viewId:m.viewId,buildId:m.buildId,frameInstanceId:m.frameInstanceId,requestId:'data',method:'getData',params:null},location.origin);});parent.postMessage({channel:'dsh.apps.component.v2',type:'hello',protocolVersion:'2.0',requestId:'hello',documentNonce:'document'},location.origin);document.querySelector('#toggle').onclick=()=>document.querySelector('#result').textContent='selected';</script>`;
 writeFileSync(join(workspace,'package-lock.json'),'{}');writeFileSync(join(workspace,'input.html'),html);writeFileSync(join(workspace,'build.mjs'),"import{mkdirSync,copyFileSync}from'node:fs';mkdirSync('dist',{recursive:true});copyFileSync('input.html','dist/index.html');");
}
function openInput(publication:ViewPublication):StartMountInput{return {viewId:publication.viewId,publicationId:publication.publicationId,attemptId:publication.attemptId,attemptEpoch:publication.attemptEpoch,buildId:publication.candidateBuildId,expectedViewRevision:publication.expectedViewRevision};}
test('HTTP authoring validates real receipt schemas, authorizes candidate document, commits once and keeps fixed historical publications',{skip:!existsSync(browser),timeout:60000},async()=>{
 const f=await setup();try{
  const prepare=async(mode:'new'|'edit',viewId?:string,title='First')=>{
   const begin=await f.begin({mode,...(viewId?{viewId}:{})});project(begin.draft.workspacePath,title);
   const build=await f.evidenceRunner.build({attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,sourceRevision:begin.draft.sourceRevision,workspacePath:begin.draft.workspacePath,command:[process.execPath,'build.mjs'],sources:f.presentation.sources!,onStart:async()=>{const marked=await f.call('/v1/authoring/markBuilding',{sessionId:'original',params:{attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch}});assert.equal(marked.body.state,'building');}});
   const built=await f.action('apps.authoring.record_build',{attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,reportRef:build.reportRef});assert.equal(built.status,'ok',JSON.stringify(built));const receipt=built.data as BuildReceipt;
   const tested=await runAuthoringPreview({attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,buildReceiptId:receipt.receiptId,buildReportRef:build.reportRef,mode:'fixture',runner:f.evidenceRunner,sources:f.presentation.sources,browserExecutable:browser,data:{viewId:begin.view.viewId,bindings:[]},assertions:[{id:'select',action:'click',selector:'#toggle',checkSelector:'#result',check:'text',expected:'selected'}]});assert.equal(tested.report.verdict,'PASS',JSON.stringify(tested.report));
   const recorded=await f.action('apps.authoring.record_preview',{attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,buildReceiptId:receipt.receiptId,reportRef:tested.reportRef});assert.equal(recorded.status,'ok',JSON.stringify(recorded));const preview=recorded.data as PreviewReceipt;
   assert.deepEqual(Object.keys(preview.viewportResults[0]).sort(),['id','contentWidthCssPx','heightCssPx','deviceScaleFactor','screenshot','pageErrors','unhandledRejections','failedRequests','bridgeReady','assertionIds'].sort());
   const published=await f.action('apps.authoring.publish',{attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,viewId:begin.view.viewId,expectedViewRevision:begin.attempt.expectedViewRevision,buildId:receipt.archiveBuildId,buildReceiptId:receipt.receiptId,previewReceiptId:preview.receiptId});assert.equal(published.status,'ok',JSON.stringify(published));const publication=published.data as ViewPublication;
   const params={publicationId:publication.publicationId,attemptId:begin.attempt.attemptId,attemptEpoch:begin.attempt.epoch,viewId:begin.view.viewId,buildId:receipt.archiveBuildId,frameInstanceId:randomUUID(),documentNonce:randomUUID(),clientFeatures:['renderReadyV1','uiStateV1']};
   const identity={protocolVersion:'2.0',sessionId:'original',viewId:params.viewId,buildId:params.buildId,frameInstanceId:params.frameInstanceId};
   return {begin,build,preview,publication,params,identity};
  };
  const first=await prepare('new'),viewId=first.begin.view.viewId;
  const fixed=(value:typeof first)=>`/v1/views/${viewId}?${new URLSearchParams({sessionId:'original',publicationId:value.publication.publicationId,buildId:value.publication.candidateBuildId})}`;
  const pending=await f.call(fixed(first));assert.equal(pending.status,200);assert.equal(pending.body.source,undefined);assert.equal(pending.body.publication.source.buildId,first.publication.candidateBuildId);assert.equal(pending.body.activeBuildId,null);assert.equal(pending.body.publication.state,'prepared');assert.equal(pending.body.publication.readyDeadlineAt,null);assert.equal(pending.body.publication.mountStartedAt,null);assert.equal(f.presentation.getView(viewId)?.source,undefined);
  const unauthorized=await f.call('/v1/component-extension',{...first.identity,channel:'dsh.apps.component.v2',type:'extension',feature:'renderReadyV1',action:'ready',requestId:'not-granted',params:{}});assert.equal(unauthorized.status,400);
  assert.equal((await f.call('/v1/authoring/authorizeFrame',{sessionId:'foreign',params:first.params})).status,400);
  const notOpened=await f.call('/v1/authoring/authorizeFrame',{sessionId:'original',params:first.params});assert.equal(notOpened.status,400);assert.equal(notOpened.body.error.code,'ATTEMPT_SUPERSEDED');
  const target=openInput(first.publication);
  for(const params of [{...target,unexpected:true},{...target,expectedViewRevision:undefined}])assert.equal((await f.call('/v1/authoring/startMount',{sessionId:'original',params})).status,400);
  const foreign=await f.call('/v1/authoring/startMount',{sessionId:'foreign',params:target});assert.equal(foreign.status,400);assert.equal(foreign.body.error.code,'VIEW_NOT_OWNED');
  const mismatched=await f.call('/v1/authoring/startMount',{sessionId:'original',params:{...target,buildId:'f'.repeat(64)}});assert.equal(mismatched.status,400);assert.equal(mismatched.body.error.code,'PUBLICATION_TARGET_MISMATCH');
  assert.deepEqual((await f.call(fixed(first))).body,pending.body);assert.equal(f.store.list('view_publications').length,1);assert.equal(f.store.list<{namespace:string}>('provider_records').filter(value=>value.namespace==='frame_grants').length,0);
  const opened=await f.call('/v1/authoring/startMount',{sessionId:'original',params:target});assert.equal(opened.status,200);assert.equal(opened.body.state,'mounting');assert.equal(Date.parse(opened.body.readyDeadlineAt)-Date.parse(opened.body.mountStartedAt),15000);
  const repeated=await Promise.all([f.call('/v1/authoring/startMount',{sessionId:'original',params:target}),f.call('/v1/authoring/startMount',{sessionId:'original',params:target})]);for(const result of repeated){assert.equal(result.status,200);assert.deepEqual(result.body,opened.body);}assert.equal(f.store.list('view_publications').length,1);const mounting=await f.call(fixed(first));assert.equal(mounting.body.publication.state,'mounting');assert.equal(mounting.body.source.buildId,first.publication.candidateBuildId);assert.equal(mounting.body.activeBuildId,null);assert.equal(f.presentation.getView(viewId)?.source,undefined);
  const grant=await f.call('/v1/authoring/authorizeFrame',{sessionId:'original',params:first.params});assert.deepEqual(grant.body.features,['renderReadyV1','uiStateV1']);
  const extension={...first.identity,channel:'dsh.apps.component.v2',type:'extension',feature:'renderReadyV1',action:'ready',requestId:'ready',params:{documentNonce:first.params.documentNonce,checks:{rendered:true,bridgeReady:true,dataRead:true,unhandledErrors:[],assertionResults:first.preview.assertionResults}}};
  const beforeForeignNonce=canonicalJson({views:f.store.list('views'),publications:f.store.list('view_publications'),records:f.store.list('provider_records')});const foreignNonce=await f.call('/v1/component-extension',{...extension,params:{...extension.params,documentNonce:'foreign-document'}});assert.equal(foreignNonce.status,400);assert.equal(foreignNonce.body.error.code,'BRIDGE_IDENTITY_STALE');assert.equal(canonicalJson({views:f.store.list('views'),publications:f.store.list('view_publications'),records:f.store.list('provider_records')}),beforeForeignNonce);
  const bad=await f.call('/v1/component-extension',{...extension,params:{...extension.params,checks:{...extension.params.checks,dataRead:false}}});assert.equal(bad.body.error.code,'FRAME_RUNTIME_ERROR');assert.equal(f.presentation.getView(viewId)?.source,undefined);
  const ready=await f.call('/v1/component-extension',extension);assert.equal(ready.body.result.publication.state,'mounted');const revision=ready.body.result.view.viewRevision;
  assert.equal((await f.call(fixed(first))).body.viewRevision,revision);
  const ui=await f.call('/v1/component-extension',{...extension,feature:'uiStateV1',action:'write',params:{uiStateSchemaVersion:1,expectedStateRevision:0,value:{search:'saved'},selectionEvidence:[]}});assert.equal(ui.body.result.stateRevision,1);
  const second=await prepare('edit',viewId,'Second');assert.equal(f.presentation.getView(viewId)?.source?.buildId,first.publication.candidateBuildId);
  const secondPending=await f.call(fixed(second));assert.equal(secondPending.status,200);assert.equal(secondPending.body.publication.state,'prepared');assert.equal(secondPending.body.publication.source.buildId,second.publication.candidateBuildId);assert.equal(secondPending.body.source.buildId,first.publication.candidateBuildId);assert.equal(secondPending.body.activeBuildId,first.publication.candidateBuildId);assert.equal(secondPending.body.lastGoodBuildId,first.publication.candidateBuildId);assert.deepEqual(secondPending.body.source,f.presentation.getView(viewId)?.source);
  assert.equal((await f.call('/v1/authoring/startMount',{sessionId:'original',params:openInput(first.publication)})).status,400);assert.equal(f.store.list('view_publications').length,2);assert.equal((await f.call('/v1/authoring/startMount',{sessionId:'original',params:openInput(second.publication)})).body.state,'mounting');
  assert.equal((await f.call('/v1/authoring/authorizeFrame',{sessionId:'original',params:second.params})).status,200);
  const ready2=await f.call('/v1/component-extension',{...extension,...second.identity,params:{documentNonce:second.params.documentNonce,checks:{...extension.params.checks,assertionResults:second.preview.assertionResults}}});assert.equal(ready2.body.result.view.viewRevision,revision+1);
  const historical=await f.call(fixed(first));assert.equal(historical.body.source.buildId,first.publication.candidateBuildId);assert.equal(historical.body.viewRevision,revision);assert.equal(f.presentation.getView(viewId)?.source?.buildId,second.publication.candidateBuildId);
  const retired=await f.call('/v1/authoring/retireFrame',{sessionId:'original',params:{viewId,buildId:second.params.buildId,frameInstanceId:second.params.frameInstanceId,documentNonce:second.params.documentNonce}});assert.equal(retired.body.retired,true);
  assert.equal((await f.call('/v1/component-bridge',{...second.identity,channel:'dsh.apps.component.v2',method:'getData',requestId:'late',params:null})).body.error.code,'BRIDGE_IDENTITY_STALE');
  assert.equal((await f.call('/v1/authoring/negotiateFrame',{sessionId:'original',params:{viewId,buildId:second.params.buildId,frameInstanceId:second.params.frameInstanceId,documentNonce:randomUUID(),clientFeatures:['uiStateV1']}})).status,400);
  assert.equal((await f.call(fixed(first).replace('original','foreign'))).status,400);
 }finally{await f.cleanup();}
});

test('HTTP display opens the previewed archive, rejects invalid grants atomically and reopens after an inspectable actual-load error',{skip:!existsSync(browser),timeout:60000},async()=>{
 const f=await setup();try{
  f.runtime.addConnection({appId:'notes',connectionId:'notes-display',displayName:'Isolated display notes',config:{},configRevision:1,enabled:true});f.runtime.bind({sessionId:'original',appId:'notes',connectionId:'notes-display',enabled:true,boundAt:new Date().toISOString()});
  const at=new Date().toISOString(),recordId=canonicalJson(['notes','notes-display','notes','note-a']);f.store.put('provider_records',recordId,{appId:'notes',connectionId:'notes-display',namespace:'notes',recordId:'note-a',value:{id:'note-a',title:'Original data',content:'P1 fixture',revision:'1',createdAt:at,updatedAt:at}});
  const prepare=async(begin:Awaited<ReturnType<typeof f.begin>>,title:string)=>{
   project(begin.draft.workspacePath,title);const build=await f.evidenceRunner.build({attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,sourceRevision:begin.draft.sourceRevision,workspacePath:begin.draft.workspacePath,command:[process.execPath,'build.mjs'],sources:f.presentation.sources!});const built=await f.action('apps.authoring.record_build',{attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,reportRef:build.reportRef});assert.equal(built.status,'ok');const receipt=built.data as BuildReceipt;
   const tested=await runAuthoringPreview({attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,buildReceiptId:receipt.receiptId,buildReportRef:build.reportRef,mode:'fixture',runner:f.evidenceRunner,sources:f.presentation.sources,browserExecutable:browser,data:f.presentation.getData('original',begin.view.viewId),assertions:[{id:'select',action:'click',selector:'#toggle',checkSelector:'#result',check:'text',expected:'selected'}]});assert.equal(tested.report.verdict,'PASS');const recorded=await f.action('apps.authoring.record_preview',{attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,buildReceiptId:receipt.receiptId,reportRef:tested.reportRef});assert.equal(recorded.status,'ok');const preview=recorded.data as PreviewReceipt;
   const published=await f.action('apps.authoring.publish',{attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,viewId:begin.view.viewId,expectedViewRevision:begin.attempt.expectedViewRevision,buildId:receipt.archiveBuildId,buildReceiptId:receipt.receiptId,previewReceiptId:preview.receiptId});assert.equal(published.status,'ok');return {publication:published.data as ViewPublication,preview,receipt};
  };
  const begin=await f.begin({mode:'new',title:'Display P1',bindings:[{bindingId:'notes',appId:'notes',connectionId:'notes-display',capabilityId:'notes.notes.list',capabilityMajor:1,input:{},projection:[],refresh:{mode:'manual'}}]});await f.presentation.refreshView('original',begin.view.viewId,{kind:'agent',sessionId:'original',nativeCallId:'fixture-read'});const first=await prepare(begin,'P1'),target=openInput(first.publication),viewId=target.viewId;
  const state=()=>canonicalJson({views:f.store.list('views'),publications:f.store.list('view_publications'),records:f.store.list('provider_records')});
  const callOpen=(publication:ViewPublication,displayId:string)=>f.call('/v1/authoring/openDisplay',{sessionId:'original',params:{...openInput(publication),displayId}});
  const opened=await callOpen(first.publication,'http-display-one');assert.equal(opened.status,200,JSON.stringify(opened));assert.equal(opened.body.publication.state,'prepared');assert.equal(opened.body.publication.readyDeadlineAt,null);assert.equal(opened.body.source.buildId,target.buildId);assert.equal(opened.body.data.bindings[0].resources[0].resourceId,'note-a');
  const params={...target,displayId:opened.body.display.displayId,displayGeneration:opened.body.display.generation,frameInstanceId:randomUUID(),documentNonce:randomUUID(),clientFeatures:['renderReadyV1','uiStateV1']};const {expectedViewRevision:_unused,...frameParams}=params;
  for(const bad of [{...frameParams,viewId:'foreign-view'},{...frameParams,clientFeatures:[123]},{...frameParams,buildId:'f'.repeat(64)}]){const before=state(),result=await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:bad});assert.equal(result.status,400);assert.equal(state(),before);}
  f.runtime.bind({sessionId:'original',appId:'notes',connectionId:'notes-display',enabled:false,boundAt:new Date().toISOString()});const beforeUnbound=state(),unbound=await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:frameParams});assert.equal(unbound.body.error.code,'CONNECTION_NOT_BOUND');assert.equal(state(),beforeUnbound);f.runtime.bind({sessionId:'original',appId:'notes',connectionId:'notes-display',enabled:true,boundAt:new Date().toISOString()});
  const authorized=await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:frameParams});assert.equal(authorized.status,200);assert.deepEqual(authorized.body.features,['renderReadyV1','uiStateV1']);
  const identity={protocolVersion:'2.0',sessionId:'original',viewId,buildId:target.buildId,frameInstanceId:frameParams.frameInstanceId},extension={...identity,channel:'dsh.apps.component.v2',type:'extension',feature:'renderReadyV1',action:'ready',requestId:'display-ready',params:{documentNonce:frameParams.documentNonce,checks:{rendered:true,bridgeReady:true,dataRead:true,unhandledErrors:[],assertionResults:first.preview.assertionResults}}};
  const beforeNonce=state(),nonce=await f.call('/v1/component-extension',{...extension,params:{...extension.params,documentNonce:'foreign-nonce'}});assert.equal(nonce.status,400);assert.equal(nonce.body.error.code,'BRIDGE_IDENTITY_STALE');assert.equal(state(),beforeNonce);
  const failed=await f.call('/v1/authoring/reportDisplayError',{sessionId:'original',params:{viewId,publicationId:target.publicationId,buildId:target.buildId,displayId:params.displayId,displayGeneration:params.displayGeneration,error:{phase:'script',code:'COMPONENT_SCRIPT_ERROR',message:'Actual iframe script failure fixture'}}});assert.equal(failed.body.state,'failed');
  const inspected=await f.call('/v1/authoring/inspect',{sessionId:'original',params:{publicationId:target.publicationId}});assert.equal(inspected.body.latestDisplay.errors[0].code,'COMPONENT_SCRIPT_ERROR');assert.equal(inspected.body.attempt.state,'publish_ready');assert.equal(inspected.body.view.viewRevision,1);
  const reopened=await callOpen(first.publication,'http-display-two');assert.equal(reopened.status,200);assert.equal(reopened.body.display.generation,2);const secondParams={...frameParams,displayId:reopened.body.display.displayId,displayGeneration:2,frameInstanceId:randomUUID(),documentNonce:randomUUID()};assert.equal((await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:secondParams})).status,200);
  assert.equal((await f.call('/v1/component-extension',extension)).body.error.code,'BRIDGE_IDENTITY_STALE');assert.equal((await f.call('/v1/component-bridge',{...identity,channel:'dsh.apps.component.v2',method:'getData',requestId:'old-frame',params:null})).body.error.code,'BRIDGE_IDENTITY_STALE');
  const ready2={...extension,frameInstanceId:secondParams.frameInstanceId,params:{...extension.params,documentNonce:secondParams.documentNonce}},ready=await f.call('/v1/component-extension',ready2);assert.equal(ready.body.result.display.state,'ready');assert.equal(ready.body.result.view.viewRevision,2);assert.equal((await f.call('/v1/component-extension',ready2)).body.result.view.viewRevision,2);
  const oldSdkUi={...ready2,feature:'uiStateV1',action:'write',params:{uiStateSchemaVersion:1,expectedStateRevision:0,value:{search:'SDK16-compatible'},selectionEvidence:[]}},uiBeforeMissingNonce=state(),missingUiNonce=await f.call('/v1/component-extension',oldSdkUi);assert.equal(missingUiNonce.body.error.code,'BRIDGE_IDENTITY_STALE');assert.equal(state(),uiBeforeMissingNonce);const writtenUi=await f.call('/v1/component-extension',{...oldSdkUi,params:{...oldSdkUi.params,documentNonce:secondParams.documentNonce}});assert.equal(writtenUi.status,200);assert.equal(writtenUi.body.result.stateRevision,1);const readUi=await f.call('/v1/component-extension',{...oldSdkUi,action:'read',params:{uiStateSchemaVersion:1,documentNonce:secondParams.documentNonce}});assert.deepEqual(readUi.body.result.snapshot.value,{search:'SDK16-compatible'});const uiBeforeNonce=state(),wrongUiNonce=await f.call('/v1/component-extension',{...oldSdkUi,params:{...oldSdkUi.params,documentNonce:'wrong-old-ui-document'}});assert.equal(wrongUiNonce.body.error.code,'BRIDGE_IDENTITY_STALE');assert.equal(state(),uiBeforeNonce);
  const directUiBefore=canonicalJson(f.store.list('view_ui_states'));for(const [operation,params] of [['exportUiState',{viewId,sourceBuildId:target.buildId,uiStateSchemaVersion:1,expectedStateRevision:0,value:{search:'bypass'},selectionEvidence:[]}],['restoreUiState',{viewId,targetBuildId:target.buildId,uiStateSchemaVersion:1}]] as const){const bypass=await f.call('/v1/authoring/'+operation,{sessionId:'original',params});assert.equal(bypass.body.error.code,'BRIDGE_IDENTITY_STALE');assert.equal(canonicalJson(f.store.list('view_ui_states')),directUiBefore);}
  const next=await f.begin({mode:'edit',viewId});f.presentation.createView('original',{viewId,title:'P2',bindings:[]});const second=await prepare(next,'P2'),p2=await callOpen(second.publication,'http-P2'),p2Params={...secondParams,...openInput(second.publication),displayId:p2.body.display.displayId,displayGeneration:p2.body.display.generation,frameInstanceId:randomUUID(),documentNonce:randomUUID()};const {expectedViewRevision:_p2Revision,...p2Frame}=p2Params;assert.equal((await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:p2Frame})).status,200);const p2Ready={...ready2,buildId:second.publication.candidateBuildId,frameInstanceId:p2Frame.frameInstanceId,params:{...extension.params,documentNonce:p2Frame.documentNonce}};assert.equal((await f.call('/v1/component-extension',p2Ready)).body.result.view.viewRevision,3);
  const historical=await callOpen(first.publication,'http-P1-history');assert.equal(historical.status,200);assert.equal(historical.body.view.source.buildId,first.publication.candidateBuildId);assert.equal(historical.body.data.bindings[0].resources[0].resourceId,'note-a');const historicalData=await f.call(`/v1/views/${viewId}/data?`+new URLSearchParams({sessionId:'original',publicationId:target.publicationId,buildId:target.buildId,displayId:historical.body.display.displayId,displayGeneration:String(historical.body.display.generation)}));assert.equal(historicalData.status,200);assert.equal(historicalData.body.bindings[0].bindingId,'notes');assert.equal((await f.call(`/v1/views/${viewId}/data?sessionId=original`)).body.bindings.length,0);
  const historyFrame={...secondParams,displayId:historical.body.display.displayId,displayGeneration:historical.body.display.generation,frameInstanceId:randomUUID(),documentNonce:randomUUID()};assert.equal((await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:historyFrame})).status,200);const historyReady={...ready2,frameInstanceId:historyFrame.frameInstanceId,params:{...extension.params,documentNonce:historyFrame.documentNonce}},historyResult=await f.call('/v1/component-extension',historyReady);assert.equal(historyResult.body.result.view.source.buildId,first.publication.candidateBuildId);assert.equal(f.presentation.getView(viewId)?.source?.buildId,second.publication.candidateBuildId);assert.equal(f.presentation.getView(viewId)?.viewRevision,3);
  const retireHistory=(frame:typeof historyFrame)=>f.call('/v1/authoring/retireFrame',{sessionId:'original',params:{viewId,buildId:frame.buildId,frameInstanceId:frame.frameInstanceId,documentNonce:frame.documentNonce}});
  const remountFrame={...historyFrame,frameInstanceId:randomUUID(),documentNonce:randomUUID()},historyBridge=(frame:{frameInstanceId:string},requestId:string)=>f.call('/v1/component-bridge',{protocolVersion:'2.0',sessionId:'original',viewId,buildId:historyFrame.buildId,frameInstanceId:frame.frameInstanceId,channel:'dsh.apps.component.v2',method:'getData',requestId,params:null});
  const liveHolds=await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:remountFrame});assert.equal(liveHolds.body.error.code,'BRIDGE_IDENTITY_STALE');
  assert.equal((await historyBridge(historyFrame,'live-document')).status,200);
  const closed=await retireHistory(historyFrame);assert.equal(closed.status,200);assert.equal(closed.body.retired,true);
  assert.equal((await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:remountFrame})).status,200);
  assert.equal((await historyBridge(historyFrame,'retired-document')).body.error.code,'BRIDGE_IDENTITY_STALE');assert.equal((await historyBridge(remountFrame,'remounted-document')).status,200);
  const anotherDocument={...remountFrame,frameInstanceId:randomUUID(),documentNonce:randomUUID()};assert.equal((await f.call('/v1/authoring/authorizeDisplayFrame',{sessionId:'original',params:anotherDocument})).body.error.code,'BRIDGE_IDENTITY_STALE');
  const remountedReady=await f.call('/v1/component-extension',{...historyReady,frameInstanceId:remountFrame.frameInstanceId,requestId:'remount-ready',params:{...historyReady.params,documentNonce:remountFrame.documentNonce}});assert.equal(remountedReady.body.result.display.state,'ready');assert.equal(remountedReady.body.result.view.source.buildId,first.publication.candidateBuildId);
  assert.equal(f.store.list('build_receipts').length,2);assert.equal(f.store.list('preview_receipts').length,2);assert.equal(f.store.list('components').length,0);
 }finally{await f.cleanup();}
});

test('original command CLI marks building before dispatch; cancellation stops that process and rejects a late completion',{timeout:30000},async()=>{
 const f=await setup();try{
  const begin=await f.begin({mode:'new'});project(begin.draft.workspacePath,'Cancel');writeFileSync(join(begin.draft.workspacePath,'hang.mjs'),"console.log('started owned build');setInterval(()=>{},1000);");writeFileSync(join(f.directory,'service-key'),f.token);
  const input=join(f.directory,'build-request.json');writeFileSync(input,JSON.stringify({sessionId:'original',attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,sourceRevision:begin.attempt.sourceRevision,workspacePath:begin.draft.workspacePath,command:[process.execPath,'hang.mjs'],evidenceRoot:f.evidenceRunner.root,archiveRoot:f.presentation.sources!.directory,runtime:{url:f.url,keyFile:join(f.directory,'service-key')}}));
  const child=spawn(process.execPath,[resolve('scripts/apps-authoring-build.mjs'),input],{stdio:['ignore','pipe','pipe'],windowsHide:true});let output='',errors='';child.stdout.on('data',value=>{output+=value});child.stderr.on('data',value=>{errors+=value});
  const completed=new Promise<number|null>((accept,reject)=>{child.once('error',reject);child.once('close',accept);});
  for(let n=0;n<100&&f.store.get<AuthoringAttempt>('authoring_attempts',begin.attempt.attemptId)?.state!=='building';n++)await new Promise(accept=>setTimeout(accept,20));assert.equal(f.store.get<AuthoringAttempt>('authoring_attempts',begin.attempt.attemptId)?.state,'building');
  const cancelled=await f.action('apps.authoring.cancel',{attemptId:begin.attempt.attemptId,expectedEpoch:begin.attempt.epoch,reason:'Explicit test cancellation'});assert.equal(cancelled.status,'ok');assert.equal(cancelled.data.status,'cancelled');assert.equal(await completed,1,errors);
  const report=JSON.parse(output.trim());assert.equal(report.verdict,'FAIL');const late=await f.action('apps.authoring.record_build',{attemptId:begin.attempt.attemptId,epoch:begin.attempt.epoch,reportRef:report.reportRef});assert.equal(late.status,'failed');assert.equal(late.error.code,'ATTEMPT_SUPERSEDED');assert.equal(f.store.list('build_receipts').length,0);
 }finally{await f.cleanup();}
});


test('active source reopens after another build has display history',async()=>{
 const f=await setup();try{
  const view=f.presentation.createView('original',{title:'Existing product table'}),buildId='active-build';
  f.store.put('views',view.viewId,{...view,source:{buildId,directory:f.directory,entry:'index.html',files:['index.html']},activeBuildId:buildId,validationStatus:'legacy_unverified'});
  f.store.put('provider_records','component-display:newer',{appId:'apps',connectionId:'presentation',namespace:'component_displays',recordId:'component-display:newer',value:{displayId:'newer',ownerSessionId:'original',viewId:view.viewId,buildId:'new-build',state:'opening'}});
  const identity={protocolVersion:'2.0',sessionId:'original',viewId:view.viewId,buildId,frameInstanceId:randomUUID()},documentNonce=randomUUID();
  const params={viewId:view.viewId,buildId,frameInstanceId:identity.frameInstanceId,documentNonce,clientFeatures:['renderReadyV1']};
  const granted=await f.call('/v1/authoring/negotiateFrame',{sessionId:'original',params});
  assert.equal(granted.status,200,JSON.stringify(granted.body));
  const request={...identity,channel:'dsh.apps.component.v2',method:'getData',requestId:randomUUID(),params:null};
  const data=await f.call('/v1/component-bridge',request);assert.equal(data.status,200,JSON.stringify(data.body));assert.equal(data.body.result.viewId,view.viewId);
  await f.call('/v1/authoring/retireFrame',{sessionId:'original',params:{viewId:view.viewId,buildId,frameInstanceId:identity.frameInstanceId,documentNonce}});
  assert.equal((await f.call('/v1/component-bridge',{...request,requestId:randomUUID()})).body.error.code,'BRIDGE_IDENTITY_STALE');
 }finally{await f.cleanup();}
});
