import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import {AppRegistryPage,HallmarkToolView,SessionComponentsButton,SessionComponentsPane} from '../../packages/dsh-plugin/client/index.tsx';
import {ownedWorkspaceIntent} from '../../packages/dsh-plugin/client/workspace-intent.ts';
import {COMPONENTS_SIDEBAR_KIND} from '../../packages/dsh-plugin/client/sidebar-contract.ts';
import {INITIAL_TEMPLATES} from '../../packages/presentation/src/design.ts';
import type {ViewSpec} from '../../packages/presentation/src/types.ts';
import type {OverviewDto} from '../../packages/contracts/src/overview.ts';
const populatedOverview:OverviewDto={fetchedAt:'2026-10-06T08:30:00Z',collected:{status:'ok',count:86},products:{status:'ok',count:128,lastSuccessAt:'2026-10-06T08:20:00Z'},stores:{status:'ok',count:2,rows:[{id:'fixture-shop-a',name:'合成店铺 A',productCount:84,lastSuccessAt:'2026-10-06T08:20:00Z',status:'ok'},{id:'fixture-shop-b',name:'合成店铺 B',productCount:44,lastSuccessAt:'2026-10-06T08:25:00Z',status:'ok'}]}};
const emptyOverview:OverviewDto={fetchedAt:'2026-10-06T08:30:00Z',collected:{status:'unavailable',count:null},products:{status:'unavailable',count:null,lastSuccessAt:null},stores:{status:'unavailable',count:null,rows:[]}};
let currentOverview=populatedOverview;
let firstVisit=false;
const saved={components:[] as any[],entries:[] as any[],templates:[] as any[]};
const views=new Map<string,ViewSpec>();const calls:any[]=[];const navigation:string[]=[];let active=false;const assertions:string[]=[];let reopen=()=>{};
const chatView:ViewSpec={id:'fixture-owned-chat-view',title:'会话文本组件（合成）',layout:{type:'column',children:['explain']},widgets:[{id:'explain',type:'text',text:'隔离测试组件，不包含用户业务数据。'}],bindings:[]};views.set(chatView.id,chatView);
let mountedSession='fixture-session';let openSidebar:((params:Record<string,unknown>)=>void)|undefined;let nativeOpens=0;
const sidebarRight={mounted:{getSnapshot:()=>mountedSession},openTab:(kind:string,options?:{params?:{viewId?:string}})=>{if(kind!==COMPONENTS_SIDEBAR_KIND)throw new Error('Fixture unknown native tab kind');nativeOpens++;openSidebar?.(options?.params??{});}};
const errors:string[]=[];window.addEventListener('error',event=>errors.push(event.message));window.addEventListener('unhandledrejection',event=>errors.push(String(event.reason)));
(globalThis as any).fetch=async(url:string,init:RequestInit={})=>{
 if(!String(url).startsWith('/api/hallmark-app'))throw new Error('Fixture blocked non-app network');
 const input=init.body?JSON.parse(String(init.body)):Object.fromEntries(new URL(String(url),'http://fixture.test').searchParams);
 calls.push(input);let value:any;
 switch(input.resource??input.action){
  case 'state':value={sessionId:'fixture-session',appId:'hallmark',active};break;
  case 'health':value={serviceStatus:'ok',hallmarkStatus:firstVisit?'ok':'unavailable',sourceConnected:firstVisit};break;
  case 'overview':value=structuredClone(currentOverview);break;
   case 'sessionViews':value={sessionId:input.sessionId,views:input.sessionId==='fixture-session'?[{viewId:chatView.id,title:chatView.title,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-01T00:00:00Z',state:'ready'}]:[]};break;
   case 'sessionView':case 'sessionViewData':if(input.sessionId!=='fixture-session'||input.viewId!==chatView.id)return new Response(JSON.stringify({status:'failed',error:{code:'SESSION_VIEW_NOT_FOUND',message:'Synthetic scoped rejection',retryable:false}}),{status:404});value=input.resource==='sessionView'?chatView:{status:'ok',data:{viewId:chatView.id,bindings:[],missing:[]}};break;
  case 'saved':value=firstVisit?{components:[],entries:[],templates:[]}:saved;break;
  case 'templates':value=INITIAL_TEMPLATES;break;
  case 'datasets':value=[];break;
  case 'view':value=views.get(input.viewId);break;
  case 'viewData':value={status:'ok',data:{viewId:input.viewId,bindings:[],missing:[]}};break;
  case 'preview':views.set(input.spec.id,input.spec);value=input.spec;break;
  case 'saveComponent':{const spec=views.get(input.viewId)!;const component={id:spec.id,title:input.title,spec};saved.components.push(component);saved.entries.push({id:'fixture-entry',viewId:spec.id,kind:'component',title:input.title,order:0,pinned:false});value={component};break;}
  case 'openComponent':{const component=saved.components.find(c=>c.id===input.componentId)!;const spec={...structuredClone(component.spec),id:crypto.randomUUID()};views.set(spec.id,spec);value={spec,sourceComponentId:component.id,baseRevision:component.revision??1};break;}
  case 'manage':{const entry=saved.entries.find(e=>e.id===input.id);if(input.operation==='pin'&&entry)entry.pinned=input.pinned;value=entry;break;}
  case 'saveTemplate':value={id:'fixture-template'};break;
  case 'activate':active=true;value={sessionId:'fixture-session',appId:'hallmark',active};break;
  case 'close':active=false;value={sessionId:'fixture-session',appId:'hallmark',active};break;
  case 'openEntry':value=views.get(saved.entries.find(entry=>entry.id===input.entryId)?.viewId??input.entryId);break;
  default:throw new Error(`Fixture unhandled resource ${JSON.stringify(input)}`);
 }
 return new Response(JSON.stringify(value),{status:200,headers:{'content-type':'application/json'}});
};
const delay=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const wait=async(predicate:()=>unknown,label:string)=>{for(let i=0;i<100;i++){if(predicate())return;await delay(30);}throw new Error(`Timeout: ${label}`);};
const visible=(element:Element)=>!element.closest('[hidden]')&&element.getClientRects().length>0;
const button=(text:string)=>{const buttons=Array.from(document.querySelectorAll<HTMLButtonElement>('button')).filter(visible);return buttons.find(button=>button.textContent?.trim()===text)??buttons.find(button=>button.textContent?.includes(text));};
const ariaButton=(label:string)=>Array.from(document.querySelectorAll<HTMLButtonElement>('button')).find(button=>visible(button)&&button.getAttribute('aria-label')===label);
const dockTabs=()=>Array.from(document.querySelectorAll<HTMLButtonElement>('.hm-workspace-dock [role="tab"]')).filter(visible);
const dockTab=(title:string)=>dockTabs().find(tab=>tab.textContent?.trim()===title);
const workbenchTab=(title:string)=>Array.from(document.querySelectorAll<HTMLButtonElement>('[role="tablist"][aria-label="Hallmark 工作台功能"] [role="tab"]')).find(tab=>visible(tab)&&tab.textContent?.startsWith(title));
const card=()=>document.querySelector<HTMLElement>('.hm-application-card');
const openButton=()=>document.querySelector<HTMLButtonElement>('[aria-label^="进入 Hallmark 工作台"]');
const check=(condition:unknown,label:string)=>{if(!condition)throw new Error(label);assertions.push(label);};
function FixtureShell(){
 const [panel,setPanel]=useState('apps');const [side,setSide]=useState<{params:Record<string,unknown>;revision:number}>();reopen=()=>setPanel('apps');(window as any).__UI_CHAT_PANEL__=()=>setPanel('chat');openSidebar=params=>setSide(previous=>({params,revision:(previous?.revision??0)+1}));
  const sidebarSignal=React.useMemo(()=>new AbortController().signal,[]);
  const tabActions=React.useMemo(()=>({openTab:sidebarRight.openTab}),[]);
  const useTabInfo=()=>({tab:{navigation:{params:side?.params??{},revision:side?.revision??0},signal:sidebarSignal,visible:true,actions:tabActions}});
 return <div style={{height:'100vh',display:'flex',overflow:'hidden'}}><aside className="fixture-sidebar" style={{width:210,flexShrink:0,padding:20,borderRight:'1px solid var(--dsw-alias-border-l1)',background:'var(--dsw-alias-bg-layer-1)'}}><strong style={{fontSize:16}}>DSH 页面测试</strong><p style={{fontSize:12,marginTop:8}}>隔离合成预览<br/>非用户业务数据</p><nav style={{display:'grid',gap:10,marginTop:30}}><span>原有聊天</span><span>插件</span><strong style={{borderRadius:8,padding:10,background:'var(--dsw-alias-bg-layer-2)'}}>▦ 应用</strong><span>工作区</span></nav></aside><main style={{flex:1,minWidth:0,minHeight:0}}>{panel==='apps'?<AppRegistryPage currentSessionId="fixture-session" onReturn={sessionId=>{if(!sessionId)throw new Error('Fixture navigation requires exact selected session');navigation.push(sessionId);setPanel('chat');}}/>:<section data-fixture-chat="true" className="fixture-chat-grid" style={{height:'100%',display:'flex',overflow:'auto'}}><div style={{flex:1,minWidth:0,padding:20}}><h2>原聊天：fixture-session</h2><p>隔离原生入口模拟，不是另一套聊天实现。</p><SessionComponentsButton sessionId="fixture-session" sidebarRight={sidebarRight}/><HallmarkToolView sessionId="fixture-session" phase="result" block={{meta:{hallmark:{viewId:chatView.id,status:'ok'}}}} sidebarRight={sidebarRight}/></div>{side?<aside data-fixture-rightbar="true" style={{width:420,minWidth:0,borderLeft:'1px solid var(--dsw-alias-border-l1)',overflow:'auto'}}><SessionComponentsPane sessionId="fixture-session" useTabInfo={useTabInfo} onOpenWorkspace={view=>{ownedWorkspaceIntent.open(view);setPanel('apps');}}/></aside>:null}</section>}</main><style>{'@media(max-width:600px){.fixture-sidebar{display:none}}'}</style></div>;
}
createRoot(document.getElementById('root')!).render(<FixtureShell/>);
(async()=>{
 try{
  await wait(openButton,'initial application catalog');
  check(!document.querySelector('dialog')&&!workbenchTab('组件设计'),'initial main page is application catalog, not popup or default workbench');
  check(document.querySelectorAll('.hm-application-card').length===1,'catalog lists only real installed application metadata');
  openButton()!.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,detail:1}));
  await wait(()=>workbenchTab('组件设计'),'single-click workbench controls');await wait(()=>calls.some(call=>call.resource==='datasets'),'local workbench loaded');
  check(!calls.some(call=>call.action==='activate'),'pointer single click opens workbench without activating chat');
  check(!!document.querySelector('.hm-app-rail')&&!document.querySelector('dialog'),'workbench is a permanent two-column page, not a modal');
  await wait(()=>Array.from(document.querySelectorAll('.hm-metric-value')).map(value=>value.textContent).join(',')==='86,128,2','populated overview cards');
  check(document.querySelectorAll('.hm-metric-card').length===3,'workbench renders three business overview cards from the mocked overview DTO');
  check(document.querySelectorAll('.hm-store-table tbody tr').length===2&&document.querySelector('.hm-store-table')?.textContent?.includes('84')&&document.querySelector('.hm-store-table')?.textContent?.includes('44'),'store overview shows the two synthetic stores and exact source counts');
  const primary=getComputedStyle(document.querySelector('.hm-header-actions .hm-action-primary')!);const secondary=getComputedStyle(document.querySelector('.hm-header-actions .hm-action-secondary')!);const muted=getComputedStyle(document.querySelector('.hm-metric-label')!);
  check(getComputedStyle(document.documentElement).getPropertyValue('--dsw-alias-brand-primary').trim()==='#0f1115'&&primary.backgroundColor==='rgb(37, 99, 235)'&&primary.color==='rgb(255, 255, 255)','primary action stays product blue under actual monochrome DSH brand tokens');
  check(secondary.backgroundColor==='rgb(255, 255, 255)'&&muted.color==='rgb(97, 102, 107)','secondary action and supporting text use the real light DSH surface and label colors');
  const readsBefore=calls.filter(call=>call.resource==='overview').length,refreshStart=calls.length;document.querySelector<HTMLButtonElement>('.hm-header-actions .hm-action-secondary')!.click();await wait(()=>calls.filter(call=>call.resource==='overview').length>readsBefore,'overview refreshed');
  check(calls.slice(refreshStart).every(call=>!call.action)&&calls.slice(refreshStart).some(call=>call.resource==='overview'),'header refresh rereads overview and local configuration without any business write');
  workbenchTab('组件设计')!.click();await wait(()=>button('预览'),'builder form');
  check(document.querySelectorAll('input,select,textarea').length>5,'builder has real layout/widget/binding/theme form controls');
  button('预览')!.click();await wait(()=>calls.some(call=>call.action==='preview'),'temporary preview');await delay(80);
  check(saved.components.length===0&&!calls.some(call=>call.action==='saveComponent'),'preview never saves implicitly');
  button('明确保存为组件')!.click();await wait(()=>saved.components.length===1,'explicit save');
  check(calls.filter(call=>call.action==='saveComponent').length===1,'explicit save creates one saved component');
  await wait(()=>button('更新原组件'),'saved origin available');const previousPreviewCount=calls.filter(call=>call.action==='preview').length;button('生成临时预览')!.click();await wait(()=>calls.filter(call=>call.action==='preview').length>previousPreviewCount,'fresh editable draft preview');check(calls.filter(call=>call.action==='preview').at(-1).spec.id!==saved.components[0].id,'continuing after first save uses a distinct draft ID and cannot shadow the saved view');
   check(dockTabs().length===1&&!!dockTab('工作台')&&!ariaButton('关闭 工作台 标签'),'workspace dock has a pinned non-closable workbench');
   workbenchTab('组件库')!.click();await wait(()=>button(saved.entries[0].title),'saved entry available');
   button('置顶常用')!.click();await wait(()=>button('取消置顶'),'pin response reflected in UI');workbenchTab('工作台')!.click();await wait(()=>workbenchTab('工作台')?.getAttribute('aria-selected')==='true'&&button(saved.entries[0].title),'pinned component visible');check(!!button(saved.entries[0].title),'pin action makes saved component available in common entries');
   workbenchTab('组件设计')!.click();await wait(()=>button('更新原组件'),'saved builder draft retained');check(!!button('另存为新组件'),'builder survives inner workbench tab switches and offers update or save-as');
   workbenchTab('组件库')!.click();await wait(()=>button(saved.entries[0].title),'saved entry available');button(saved.entries[0].title)!.click();await wait(()=>dockTabs().length===2,'saved component opens dock tab');
   const savedTitle=saved.entries[0].title;check(dockTabs().some(tab=>tab.getAttribute('aria-selected')==='true'&&tab.textContent===savedTitle),'saved component opens as a real selected view tab');
   dockTab('工作台')!.click();await wait(()=>button(savedTitle),'return to saved entries');button(savedTitle)!.click();await delay(100);check(dockTabs().length===2,'opening the same saved component reuses its existing tab');
   ariaButton(`关闭 ${savedTitle} 标签`)!.click();await delay(80);check(dockTabs().length===1&&dockTab('工作台')!.getAttribute('aria-selected')==='true','closing selected view returns to the pinned workbench');
   ariaButton('新建组件设计标签')!.click();await wait(()=>dockTabs().length===2&&button('预览'),'draft tab created');const draftTab=dockTabs().find(tab=>tab.getAttribute('aria-selected')==='true')!;const draftTitle=draftTab.querySelector('.hm-dock-label')!.textContent!.trim();
   const titleInput=Array.from(document.querySelectorAll<HTMLLabelElement>('.hm-form label')).find(label=>visible(label)&&label.textContent?.startsWith('组件标题'))!.querySelector<HTMLInputElement>('input')!;
   Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(titleInput,'切换后保留的临时设计');titleInput.dispatchEvent(new Event('input',{bubbles:true}));await delay(60);
   dockTab('工作台')!.click();await delay(60);draftTab.click();await delay(60);check(Array.from(document.querySelectorAll<HTMLInputElement>('.hm-form input')).some(input=>visible(input)&&input.value==='切换后保留的临时设计'),'inactive draft remains mounted and retains unsaved edits');
   draftTab.focus();draftTab.dispatchEvent(new KeyboardEvent('keydown',{key:'Home',bubbles:true}));await delay(60);check(dockTab('工作台')!.getAttribute('aria-selected')==='true','workspace tabs support keyboard Home navigation');
   ariaButton(`关闭 ${draftTitle} 标签`)!.click();await delay(60);check(dockTabs().length===1&&saved.components.length===1&&calls.filter(call=>call.action==='saveComponent').length===1,'closing a draft does not save or alter business data');
  button('应用列表')!.click();await wait(card,'back to catalog');
  check(!workbenchTab('组件设计'),'back action restores full catalog before selecting an app');
  card()!.dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,cancelable:true}));await wait(()=>document.querySelector('[role="menuitem"]'),'context menu');
  button('启动聊天')!.click();await wait(()=>document.querySelector('[data-fixture-chat]'),'returns to original chat');
  check(active&&calls.filter(call=>call.action==='activate').length===1&&navigation[0]==='fixture-session','context-menu start chat activates and navigates exact original session');
  check(!calls.some(call=>call.action==='close'),'leaving application page does not close chat capability');
   await wait(()=>ariaButton('查看本会话组件'),'native input component entry');ariaButton('查看本会话组件')!.click();await wait(()=>button(chatView.title),'owned component sidebar list');
   check(!!document.querySelector('[data-fixture-rightbar] .hm-session-view-list'),'native sidebar entry lists only the exact session-owned component');
   button(chatView.title)!.click();await wait(()=>button('在标签页打开'),'owned component detail');check(calls.some(call=>call.resource==='sessionViewData'&&call.viewId===chatView.id),'sidebar detail uses owned snapshot resources');
   const before=nativeOpens;mountedSession='another-session';button('侧栏查看')!.click();await delay(80);check(nativeOpens===before,'tool card cannot open its component into another mounted session');mountedSession='fixture-session';
   sidebarRight.openTab(COMPONENTS_SIDEBAR_KIND,{params:{viewId:'foreign-view'}});await wait(()=>document.body.innerText.includes('此组件不存在或不属于此会话'),'foreign view rejected');check(!calls.some(call=>call.resource==='sessionView'&&call.viewId==='foreign-view'),'foreign navigation never reads a global or non-member view');
   sidebarRight.openTab(COMPONENTS_SIDEBAR_KIND,{params:{viewId:chatView.id}});await wait(()=>button('在标签页打开'),'restore owned sidebar detail');button('在标签页打开')!.click();await wait(()=>dockTab(chatView.title),'owned workspace tab opened');
   check(dockTab(chatView.title)!.getAttribute('aria-selected')==='true'&&!calls.some(call=>['view','viewData'].includes(call.resource)&&call.viewId===chatView.id),'sidebar opens the same owned component in a workspace tab without global fallback');
   check(calls.filter(call=>call.action==='saveComponent').length===1,'viewing chat components never implicitly saves them');
  reopen();await wait(openButton,'double-click catalog');const doubleTarget=openButton()!;
  doubleTarget.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,detail:1}));doubleTarget.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,detail:2}));doubleTarget.dispatchEvent(new MouseEvent('dblclick',{bubbles:true,cancelable:true,detail:2}));
  await wait(()=>calls.filter(call=>call.action==='activate').length===2,'double-click starts chat');await wait(()=>document.querySelector('[data-fixture-chat]'),'double-click returns to chat');await delay(550);
  check(!workbenchTab('组件设计')&&navigation[1]==='fixture-session','double-click cancels pending workbench and restores exact original chat');
  reopen();await wait(openButton,'reopen catalog');openButton()!.click();await wait(()=>workbenchTab('组件设计'),'reopen workbench');workbenchTab('组件设计')!.click();await wait(()=>button('预览'),'new builder');button('预览')!.click();await delay(100);
  check(errors.length===0,'no browser runtime errors');
  (window as any).__UI_SHOW_CATALOG__=()=>button('应用列表')?.click();
  (window as any).__UI_SHOW_OVERVIEW__=async()=>{if(!dockTab('工作台')){openButton()?.click();await wait(()=>dockTab('工作台'),'overview app selected');}dockTab('工作台')?.click();await delay(40);workbenchTab('工作台')?.click();await wait(()=>document.querySelector('.hm-overview-grid'),'overview visible');};
  (window as any).__UI_SET_OVERVIEW__=async(populated:boolean)=>{currentOverview=populated?populatedOverview:emptyOverview;window.dispatchEvent(new CustomEvent('hallmark:workspace-refresh'));await wait(()=>Array.from(document.querySelectorAll('.hm-metric-value')).filter(visible).map(value=>value.textContent).join(',')===(populated?'86,128,2':'—,—,—'),'overview snapshot scenario');};
  (window as any).__UI_SET_FIRST_VISIT__=async(enabled:boolean)=>{
    firstVisit=enabled;currentOverview=populatedOverview;
    await (window as any).__UI_SHOW_OVERVIEW__();
    const previousReads=calls.filter(call=>call.resource==='saved').length;
    const refresh=document.querySelector<HTMLButtonElement>('.hm-header-actions .hm-action-secondary')!;
    await wait(()=>!refresh.disabled,'first-visit refresh available');refresh.click();
    await wait(()=>calls.filter(call=>call.resource==='saved').length>previousReads,'first-visit saved state read');
    await wait(()=>enabled?document.querySelector('.hm-component-welcome')?.textContent?.includes('把常用工作，变成你的组件')&&document.querySelector('.hm-connection-state')?.getAttribute('data-status')==='connected':Array.from(document.querySelectorAll('.hm-entry-open')).some(item=>visible(item)&&item.textContent?.includes(saved.entries[0].title)),'first-visit scenario visible');
    await wait(()=>Array.from(document.querySelectorAll('.hm-metric-value')).filter(visible).map(value=>value.textContent).join(',')==='86,128,2','first-visit overview data');
  };
  (window as any).__UI_SHOW_LIBRARY__=async()=>{await (window as any).__UI_SHOW_OVERVIEW__();workbenchTab('组件库')?.click();await wait(()=>document.querySelector('.hm-library-content .hm-entry-row .hm-actions'),'saved library action controls');};
  (window as any).__UI_SHOW_BUILDER__=()=>workbenchTab('组件设计')?.click();
   (window as any).__UI_SHOW_COMPONENT_TABS__=async()=>{if(!dockTab('工作台')){openButton()?.click();await wait(()=>dockTab('工作台'),'screenshot workbench');}dockTab('工作台')?.click();await delay(60);workbenchTab('组件库')?.click();await wait(()=>button(saved.entries[0].title),'screenshot saved entry');button(saved.entries[0].title)?.click();await delay(80);ariaButton('新建组件设计标签')?.click();await delay(80);};
   (window as any).__UI_SHOW_CHAT_SIDEBAR__=()=>{(window as any).__UI_CHAT_PANEL__?.();sidebarRight.openTab(COMPONENTS_SIDEBAR_KIND,{params:{viewId:chatView.id}});};
  (window as any).__UI_SMOKE_RESULT__={ok:true,fixtureOnly:true,assertions,navigation,calls:calls.map(({resource,action})=>({resource,action})),errors};
 }catch(error){(window as any).__UI_SMOKE_RESULT__={ok:false,fixtureOnly:true,message:String(error),assertions,errors,body:document.body.innerText.slice(0,5000)};}
})();
