import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,mkdirSync,writeFileSync,rmSync,readFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {AppsRuntime,RuntimeStore} from '../../packages/app-runtime/src/index.ts';
import {NotesProvider,resolveNotesResources} from '../../packages/app-notes/src/index.ts';
import {AppsPresentationService} from '../../packages/app-presentation/src/index.ts';
import {SourceComponentStore} from '../../packages/source-components/src/index.ts';
import {createLegacyPresentationAdapter,normalizeLegacyPresentationInput} from '../../packages/service/src/apps-legacy-presentation.ts';
import type {AppProvider,CapabilityDescriptor,CapabilityResult,InvocationRequest,JsonValue} from '../../packages/app-contracts/src/index.ts';
import type {Template,ViewSpec} from '../../packages/presentation/src/types.ts';
import {COMPONENT_CHANNEL} from '../../packages/component-runtime/src/apps-client.ts';
import {INITIAL_TEMPLATES} from '../../packages/presentation/src/design.ts';

async function setup(t:{after:(action:()=>unknown)=>void}) {
  const directory=mkdtempSync(join(tmpdir(),'apps-legacy-components-')),store=new RuntimeStore(':memory:'),runtime=new AppsRuntime(store),sources=new SourceComponentStore(join(directory,'sources'));
  t.after(async()=>{await runtime.dispose();store.close();rmSync(directory,{recursive:true,force:true});});
  runtime.register(new NotesProvider({store}));
  const descriptor:CapabilityDescriptor={capabilityId:'hallmark.collected.search',version:'1.0.0',title:'Fixture products',description:'Isolated read fixture',effect:'query',inputSchema:{type:'object',additionalProperties:false},outputSchema:{type:'object',properties:{items:{type:'array',items:{type:'object'}},total:{type:'integer'}},required:['items','total'],additionalProperties:false},execution:{mode:'sync',timeoutMs:1000,concurrency:'declared_safe',lockScope:'connection',idempotency:'not_applicable',completionEvidence:'response'},discovery:{defaultVisible:false,keywords:[]},aliases:['hallmark_search_collected_items']};
  const provider:AppProvider={manifest:{manifestVersion:1,appId:'hallmark',displayName:'Fixture Hallmark',providerPackage:'fixture',providerVersion:'1.0.0',runtimeProtocolMajor:1,resourceTypes:['collected-item']},descriptors:[descriptor],execute:async context=>({invocationId:context.request.invocationId,traceId:context.request.traceId,status:'ok',data:{items:[{id:'item-a',title:'Product fixture'}],total:1},provenance:[{appId:'hallmark',connectionId:context.request.connectionId,sourceKind:'application',sourceRef:'/api/items',fetchedAt:new Date().toISOString(),sourceDataTime:null,freshness:'unknown'}]}),dispose:async()=>{}};
  runtime.register(provider);
  const presentation=new AppsPresentationService({store,runtime,sources,resources:(binding,result)=>binding.appId==='notes'?resolveNotesResources(binding,result):[{appId:'hallmark',connectionId:binding.connectionId,resourceType:'collected-item',resourceId:'item-a'}]});
  runtime.register(presentation.provider());
  for(const [appId,connectionId] of [['apps','presentation'],['notes','n'],['hallmark','h']]){runtime.addConnection({appId,connectionId,displayName:appId,config:{},configRevision:1,enabled:true});runtime.bind({sessionId:'s',appId,connectionId,enabled:true,boundAt:new Date().toISOString()});}
  store.put('legacy_aliases','connection:default',{appId:'hallmark',connectionId:'h',status:'resolved'});
  const adapter=createLegacyPresentationAdapter(presentation,runtime),tool=(name:string,args:Record<string,unknown>)=>adapter.handle(`/tools/${name}`,'POST',{arguments:args,sessionId:'s'}) as Promise<{status:string;data:any;error?:{code:string;message:string}}>;
  return {directory,store,runtime,sources,presentation,adapter,tool};
}
const spec=():ViewSpec=>({id:'legacy-input-id',title:'Product table',layout:{type:'column',children:['table']},widgets:[{id:'table',type:'table',bindingId:'products',columns:[{field:'title',label:'Title'}]}],bindings:[{id:'products',query:{tool:'hallmark_search_collected_items',params:{}},fieldMap:{title:'名称',id:'商品标识'}}]});

test('all nine old presentation aliases normalize into the shared Runtime with JSON Patch, asset entries and histories',async t=>{
  const f=await setup(t),rendered=await f.tool('hallmark_render_view',{spec:spec()});assert.equal(rendered.status,'ok',rendered.error?.message);const id=rendered.data.viewId;assert.equal(rendered.data.spec.widgets[0].columns[0].label,'Title');
  const updated=await f.tool('hallmark_update_view',{viewId:id,patch:[{op:'replace',path:'/title',value:'Patched table'},{op:'add',path:'/widgets/0/columns/-',value:{field:'id',label:'ID'}}]});assert.equal(updated.status,'ok',updated.error?.message);assert.equal(updated.data.spec.widgets[0].columns.length,2);
  const failed=await f.tool('hallmark_update_view',{viewId:id,patch:[{op:'replace',path:'/title',value:'Should not persist'},{op:'test',path:'/title',value:'Other'}]});assert.equal(failed.status,'failed');assert.equal(f.presentation.getView(id)?.title,'Patched table');
  const saved=await f.tool('hallmark_save_component',{viewId:id,title:'Saved title',userRequest:'Save this design'});assert.equal(saved.status,'ok',saved.error?.message);const componentId=saved.data.component.id;assert.equal(componentId,id);assert.equal(saved.data.entry.viewId,componentId);assert.equal(saved.data.entry.appId,'hallmark');assert.notEqual(saved.data.entry.id,componentId);
  const opened=await f.tool('hallmark_open_component',{componentId});assert.equal(opened.status,'ok');assert.equal(opened.data.sourceComponentId,componentId);assert.equal(opened.data.baseRevision,1);assert.notEqual(opened.data.viewId,id);
  const savedAgain=await f.tool('hallmark_save_component',{viewId:opened.data.viewId,mode:'update',componentId,expectedRevision:1,userRequest:'Update this design'});assert.equal(savedAgain.status,'ok',savedAgain.error?.message);
  const entry=await f.tool('hallmark_save_entry',{title:'Data entry',binding:spec().bindings[0],userRequest:'Save query'});assert.equal(entry.status,'ok',entry.error?.message);assert.equal(entry.data.kind,'data');assert.equal(entry.data.appId,'hallmark');assert.deepEqual(entry.data.binding,spec().bindings[0]);assert.equal(entry.data.order,1);
  const template=await f.tool('hallmark_save_template',{viewId:id,name:'Reusable design',description:'Exact columns',userRequest:'Save template'});assert.equal(template.status,'ok',template.error?.message);assert.equal(template.data.widgetStyles[0].columns.length,2);assert.equal(template.data.name,'Reusable design');
  const renamed=await f.tool('hallmark_manage_saved',{kind:'component',id:componentId,action:'rename',name:'Renamed design'});assert.equal(renamed.status,'ok',renamed.error?.message);assert.equal(renamed.data.id,componentId);assert.equal(renamed.data.spec.title,'Renamed design');assert.equal(renamed.data.revision,3);
  const listed=await f.tool('hallmark_list_saved',{});assert.equal(listed.status,'ok',listed.error?.message);assert.equal(listed.data.components[0].revisions.length,3);assert.equal(listed.data.entries.length,2);assert.equal(listed.data.entries.find((item:{id:string})=>item.id===entry.data.id).userRequest,'Save query');assert.equal(listed.data.templates[0].description,'Exact columns');assert.equal(listed.data.templates[0].userRequest,'Save template');assert.ok(Date.parse(listed.data.templates[0].savedAt));
  const project=join(f.directory,'project');mkdirSync(join(project,'dist'),{recursive:true});writeFileSync(join(project,'package-lock.json'),'{}');writeFileSync(join(project,'component.json'),JSON.stringify({title:'Source fixture',bindings:spec().bindings}));writeFileSync(join(project,'dist','index.html'),'<button>Local source component</button>');
  const source=await f.tool('hallmark_open_source_component',{directory:project});assert.equal(source.status,'ok',source.error?.message);assert.equal(source.data.spec.kind,'source');assert.equal(source.data.spec.bindings.length,1);assert.deepEqual(source.data.spec.bindings[0].fieldMap,spec().bindings[0].fieldMap);assert.deepEqual(source.data.spec.bindings[0].query,spec().bindings[0].query);assert.equal(source.data.initialData[0].status,'ok');assert.equal(source.data.initialData[0].datasetKey,source.data.spec.bindings[0].datasetKey);assert.equal(f.runtime.store.list('invocations').length,11);
});

test('legacy entries retain imported identity, pin, order and labels through save, manage and UI opening',async t=>{
  const f=await setup(t),rendered=await f.tool('hallmark_render_view',{spec:spec()}),viewId=rendered.data.viewId,saved=await f.tool('hallmark_save_component',{viewId,userRequest:'Save component'}),componentId=saved.data.component.id;
  // Existing library exports can use a separate entry ID; it must remain stable.
  const original=f.store.get<Record<string,JsonValue>>('saved_assets',`entry:${saved.data.entry.id}`)!;
  f.store.delete('saved_assets',`entry:${saved.data.entry.id}`);f.store.put('saved_assets','entry:imported-component-entry',{...original,assetId:'imported-component-entry',pinned:true,order:9});
  const updated=await f.tool('hallmark_save_component',{viewId,userRequest:'Save updated component'});assert.equal(updated.status,'ok',updated.error?.message);assert.equal(updated.data.component.id,componentId);assert.equal(updated.data.entry.id,'imported-component-entry');assert.equal(updated.data.entry.pinned,true);assert.equal(updated.data.entry.order,9);assert.equal(f.store.list<Record<string,JsonValue>>('saved_assets').filter(asset=>asset.componentId===componentId).length,1);
  const entry=await f.tool('hallmark_save_entry',{title:'Mapped data',binding:spec().bindings[0],userRequest:'Save fields'});assert.equal(entry.status,'ok',entry.error?.message);assert.deepEqual(entry.data.binding,spec().bindings[0]);
  const reordered=await f.tool('hallmark_manage_saved',{kind:'entry',id:entry.data.id,action:'reorder',order:-1});assert.equal(reordered.data.id,entry.data.id);assert.equal(reordered.data.kind,'data');assert.equal(reordered.data.order,-1);assert.deepEqual(reordered.data.binding,spec().bindings[0]);assert.equal(reordered.data.userRequest,'Save fields');
  const listed=await f.tool('hallmark_list_saved',{});assert.deepEqual(listed.data.entries.map((item:{id:string})=>item.id),[entry.data.id,'imported-component-entry']);
  const uiListed=await f.adapter.handle('/ui/saved','GET') as {entries:{id:string}[]};assert.deepEqual(uiListed.entries.map(item=>item.id),[entry.data.id,'imported-component-entry']);
  const dataView=await f.adapter.handle('/ui/open-entry','POST',{entryId:entry.data.id}) as ViewSpec;assert.deepEqual(dataView.widgets[0].columns,[{field:'title',label:'名称'},{field:'id',label:'商品标识'}]);assert.deepEqual(dataView.bindings[0].query,spec().bindings[0].query);
  const renamed=await f.adapter.handle('/ui/manage','POST',{kind:'component',id:componentId,action:'rename',name:'Renamed imported'}) as {id:string;spec:ViewSpec};assert.equal(renamed.id,componentId);assert.equal(renamed.spec.title,'Renamed imported');assert.equal(f.store.get<Record<string,JsonValue>>('saved_assets','entry:imported-component-entry')!.title,'Renamed imported');
  const explicitCopy=await f.tool('hallmark_save_component',{viewId,mode:'save_as',userRequest:'Save a separate copy'});assert.equal(explicitCopy.status,'ok',explicitCopy.error?.message);assert.notEqual(explicitCopy.data.component.id,componentId);
  assert.throws(()=>f.presentation.saveComponent('s',viewId,'Invalid target',{mode:'save_as',legacyComponentId:'another-target'}),{code:'INVALID_INPUT'});
  const deleted=await f.tool('hallmark_manage_saved',{kind:'component',id:componentId,action:'delete'});assert.deepEqual(deleted.data,{deleted:true,id:componentId});assert.equal(f.store.get('saved_assets','entry:imported-component-entry'),undefined);
  const template=await f.tool('hallmark_save_template',{viewId,name:'Original template',userRequest:'Save reusable template'}),renamedTemplate=await f.tool('hallmark_manage_saved',{kind:'template',id:template.data.id,action:'rename',name:'Renamed template'});assert.equal(renamedTemplate.data.id,template.data.id);assert.equal(renamedTemplate.data.name,'Renamed template');assert.ok(renamedTemplate.data.widgetStyles);
});

test('legacy explicit spec identity, title precedence and saved template binding rules match the original interface',async t=>{
  const f=await setup(t),first=await f.tool('hallmark_render_view',{spec:spec(),title:'Ignored top-level title'});assert.equal(first.status,'ok',first.error?.message);assert.equal(first.data.viewId,spec().id);assert.equal(first.data.spec.title,spec().title);
  const repeated=await f.tool('hallmark_render_view',{spec:{...spec(),title:'Re-rendered same draft'}});assert.equal(repeated.status,'ok',repeated.error?.message);assert.equal(repeated.data.viewId,first.data.viewId);assert.equal(f.presentation.getView(first.data.viewId)?.title,'Re-rendered same draft');
  for(const [appId,connectionId] of [['apps','presentation'],['hallmark','h']])f.runtime.bind({sessionId:'other',appId,connectionId,enabled:true,boundAt:new Date().toISOString()});
  const foreign=await f.adapter.handle('/tools/hallmark_render_view','POST',{sessionId:'other',arguments:{spec:spec()}}) as {status:string;error:{code:string}};assert.equal(foreign.status,'failed');assert.equal(foreign.error.code,'VIEW_NOT_OWNED');assert.equal(f.presentation.getView(first.data.viewId)?.title,'Re-rendered same draft');
  const absent=await f.tool('hallmark_render_view',{});assert.equal(absent.status,'needs_clarification');assert.deepEqual(absent.data,undefined);
  const missingIntent=await f.tool('hallmark_save_component',{viewId:first.data.viewId});assert.equal(missingIntent.status,'failed');assert.equal(missingIntent.error?.code,'SAVE_NOT_REQUESTED');
  const missingVersion=await f.tool('hallmark_save_component',{viewId:first.data.viewId,mode:'update',userRequest:'Update saved design'}) as unknown as {status:string;clarification:{missing:string[]}};assert.equal(missingVersion.status,'needs_clarification');assert.deepEqual(missingVersion.clarification.missing,['componentId','expectedRevision']);
  const base=INITIAL_TEMPLATES.find(template=>(template.contentRules.bindingIds as string[]).length===1)!;
  const themed=await f.tool('hallmark_render_view',{spec:{...spec(),templateId:base.id,theme:{primary:'#112233'}}});assert.equal(themed.status,'ok',themed.error?.message);assert.equal(themed.data.spec.theme.primary,'#112233');assert.equal(themed.data.spec.theme.background,base.theme.background);
  const template=await f.tool('hallmark_save_template',{viewId:first.data.viewId,name:'Mapped reusable design',userRequest:'Save this template'});assert.equal(template.status,'ok',template.error?.message);
  const supplied={...spec().bindings[0],id:'caller-binding'},fromTemplate=await f.tool('hallmark_render_view',{templateId:template.data.id,bindings:[supplied]});assert.equal(fromTemplate.status,'ok',fromTemplate.error?.message);assert.equal(fromTemplate.data.spec.title,'Hallmark');assert.equal(fromTemplate.data.spec.templateId,template.data.id);assert.equal(fromTemplate.data.spec.bindings[0].id,'products');assert.deepEqual(fromTemplate.data.spec.bindings[0].fieldMap,supplied.fieldMap);
  const before=f.store.list('views').length,badCount=await f.tool('hallmark_render_view',{templateId:template.data.id,bindings:[]});assert.equal(badCount.status,'failed');assert.equal(badCount.error?.code,'INVALID_SPEC');assert.equal(f.store.list('views').length,before);
  const unknownTemplate=await f.tool('hallmark_render_view',{spec:{...spec(),templateId:'missing-template'}});assert.equal(unknownTemplate.status,'failed');assert.equal(unknownTemplate.error?.code,'TEMPLATE_NOT_FOUND');
  const saved=await f.tool('hallmark_save_component',{viewId:fromTemplate.data.viewId,userRequest:'Save design with its template snapshot'});assert.equal(saved.status,'ok',saved.error?.message);assert.equal(saved.data.component.template.id,template.data.id);assert.equal(saved.data.component.template.theme.primary,'#112233');
  const deleted=await f.tool('hallmark_manage_saved',{kind:'template',id:template.data.id,action:'delete'});assert.deepEqual(deleted.data,{deleted:true,id:template.data.id});const reopened=await f.tool('hallmark_open_component',{componentId:saved.data.component.id});assert.equal(reopened.status,'ok',reopened.error?.message);assert.equal(reopened.data.spec.templateId,undefined);assert.equal(reopened.data.spec.theme.primary,'#112233');
});

test('legacy source templates, explicit source revisions and first-load receipts preserve their original public fields',async t=>{
  const f=await setup(t),project=join(f.directory,'source-branches');mkdirSync(join(project,'dist'),{recursive:true});writeFileSync(join(project,'package-lock.json'),'Exact fixture lock');writeFileSync(join(project,'component.json'),JSON.stringify({name:'Metadata source title',bindings:spec().bindings}));writeFileSync(join(project,'dist','index.html'),'Build A');
  const opened=await f.tool('hallmark_open_source_component',{directory:project});assert.equal(opened.status,'ok',opened.error?.message);assert.equal(opened.data.spec.title,'Metadata source title');assert.equal(opened.data.initialData[0].status,'ok');assert.equal(typeof opened.data.initialData[0].datasetKey,'string');assert.equal(opened.data.initialData[0].datasetId,undefined);
  const saved=await f.tool('hallmark_save_component',{viewId:opened.data.viewId,userRequest:'Save source A'});assert.equal(saved.status,'ok',saved.error?.message);const componentId=saved.data.component.id,buildA=saved.data.component.spec.source.buildId;assert.deepEqual(saved.data.component.revisions.map((version:{revision:number})=>version.revision),[1]);assert.equal(saved.data.component.revisions[0].buildId,buildA);
  writeFileSync(join(project,'dist','index.html'),'Build B');const updated=await f.tool('hallmark_open_source_component',{directory:project,viewId:opened.data.viewId,title:'Explicit source B title'});assert.equal(updated.status,'ok',updated.error?.message);assert.equal(updated.data.viewId,opened.data.viewId);assert.equal(updated.data.spec.title,'Explicit source B title');assert.deepEqual(updated.data.spec.bindings[0].fieldMap,spec().bindings[0].fieldMap);
  const savedB=await f.tool('hallmark_save_component',{viewId:updated.data.viewId,mode:'update',componentId,expectedRevision:1,userRequest:'Update source to B'});assert.equal(savedB.status,'ok',savedB.error?.message);assert.equal(savedB.data.component.revision,2);assert.deepEqual(savedB.data.component.revisions.map((version:{revision:number})=>version.revision),[1,2]);
  const target=join(f.directory,'revision-A-checkout'),historical=await f.tool('hallmark_open_component',{componentId,revision:1,directory:target});assert.equal(historical.status,'ok',historical.error?.message);assert.equal(historical.data.baseRevision,2);assert.equal(historical.data.spec.source.buildId,buildA);assert.equal(historical.data.spec.source.directory,target);assert.equal(readFileSync(join(target,'dist','index.html'),'utf8'),'Build A');assert.equal(readFileSync(join(target,'package-lock.json'),'utf8'),'Exact fixture lock');
  const template=await f.tool('hallmark_save_template',{viewId:updated.data.viewId,name:'Reusable source B',description:'Preserved source project',userRequest:'Save reusable source'});assert.equal(template.status,'ok',template.error?.message);assert.equal(template.data.kind,'source');assert.equal(template.data.bindings[0].query.tool,'hallmark_search_collected_items');
  const templated=await f.tool('hallmark_render_view',{templateId:template.data.id});assert.equal(templated.status,'ok',templated.error?.message);assert.equal(templated.data.spec.templateId,template.data.id);assert.equal(templated.data.spec.title,'Hallmark');assert.notEqual(templated.data.spec.source.directory,project);assert.equal(readFileSync(join(templated.data.spec.source.directory,'dist','index.html'),'utf8'),'Build B');assert.deepEqual(templated.data.spec.bindings[0].fieldMap,spec().bindings[0].fieldMap);
  const generic=f.presentation.getView(updated.data.viewId)!,dataset=generic.bindings[0].datasetId!;f.store.delete('datasets',dataset);const reopened=await f.tool('hallmark_open_component',{componentId});assert.equal(reopened.status,'ok',reopened.error?.message);assert.equal(reopened.data.initialData[0].status,'ok');assert.equal(reopened.data.initialData[0].datasetKey,reopened.data.spec.bindings[0].datasetKey);
  const stale=await f.tool('hallmark_save_component',{viewId:reopened.data.viewId,mode:'update',componentId,expectedRevision:1,userRequest:'Try stale revision'});assert.equal(stale.status,'failed');assert.equal(stale.error?.code,'COMPONENT_CONFLICT');
});
test('old session/global view routes, source template library and unowned drafts remain usable without claiming a session',async t=>{
  const f=await setup(t),rendered=await f.tool('hallmark_render_view',{spec:spec()}),id=rendered.data.viewId;
  await f.presentation.refreshView('s',id,{kind:'agent',sessionId:'s',nativeCallId:'refresh'});
  const data=await f.adapter.handle(`/sessions/s/views/${id}/data`,'GET') as {data:{bindings:any[]}};assert.equal(data.data.bindings[0].payload.items[0].id,'item-a');assert.equal(data.data.bindings[0].provenance.endpoint,'/api/items');
  await assert.rejects(f.adapter.handle(`/sessions/other/views/${id}`,'GET'),{code:'VIEW_NOT_OWNED'});
  const renamed=await f.adapter.handle(`/sessions/s/views/${id}`,'POST',{action:'rename',title:'Session title'}) as {title:string};assert.equal(renamed.title,'Session title');
  const saved=await f.adapter.handle('/ui/save','POST',{viewId:id,title:'Library title',action:'save-component'}) as {component:{id:string}};
  const library=await f.adapter.handle(`/ui/views/${saved.component.id}`,'GET') as ViewSpec;assert.equal(library.title,'Library title');assert.equal(library.id,saved.component.id);
  const draft=await f.adapter.handle('/ui/open-component','POST',{componentId:saved.component.id}) as {spec:ViewSpec};assert.equal(f.presentation.getView(draft.spec.id)?.ownerSessionId,null);
  await assert.rejects(f.adapter.handle(`/sessions/s/views/${draft.spec.id}`,'GET'),{code:'VIEW_NOT_OWNED'});
  const template=await f.adapter.handle('/ui/save-template','POST',{viewId:draft.spec.id,name:'Library template',action:'save-template'}) as Template;
  const fromTemplate=await f.adapter.handle('/ui/open-template','POST',{templateId:template.id,bindings:spec().bindings}) as {spec:ViewSpec};assert.equal(f.presentation.getView(fromTemplate.spec.id)?.ownerSessionId,null);assert.equal(fromTemplate.spec.widgets[0].columns?.length,1);
  await f.adapter.handle(`/sessions/s/views/${id}`,'POST',{action:'remove'});const session=await f.adapter.handle('/sessions/s/views','GET') as {views:{viewId:string}[]};assert.ok(!session.views.some(view=>view.viewId===id));
  const sources=join(f.directory,'source-template');mkdirSync(join(sources,'dist'),{recursive:true});writeFileSync(join(sources,'package-lock.json'),'{}');writeFileSync(join(sources,'dist','index.html'),'<button>Source design</button>');
  const source=f.presentation.openSource(null,sources,{title:'Offline template'}),sourceAsset=await f.adapter.handle('/ui/save-template','POST',{viewId:source.viewId,name:'Offline source',action:'save-template'}) as Template;
  const restored=await f.adapter.handle('/ui/open-template','POST',{templateId:sourceAsset.id}) as {spec:ViewSpec};assert.notEqual(restored.spec.source?.directory,sources);assert.equal(readFileSync(join(restored.spec.source!.directory,'package-lock.json'),'utf8'),'{}');
});
test('unknown legacy datasets are marked needs_migration and JSON Patch cannot swap an immutable source build',async t=>{
  const f=await setup(t);
  assert.throws(()=>normalizeLegacyPresentationInput('hallmark_render_view',{spec:{...spec(),bindings:[{id:'products',datasetKey:'old:unmapped',fieldMap:{}}]}},'s',f.runtime),{code:'LEGACY_BINDING_NEEDS_MIGRATION'});
  const project=join(f.directory,'source');mkdirSync(join(project,'dist'),{recursive:true});writeFileSync(join(project,'dist','index.html'),'Source');const opened=await f.tool('hallmark_open_source_component',{directory:project});
  const update=await f.tool('hallmark_update_view',{viewId:opened.data.viewId,patch:[{op:'replace',path:'/source/buildId',value:'invented'}]});assert.equal(update.status,'failed');assert.equal(update.error?.code,'INVALID_SPEC');
  await assert.rejects(f.adapter.handle('/ui/open-component','POST',{componentId:'missing',revision:'1'}),{code:'INVALID_UI_INPUT'});
  await assert.rejects(f.adapter.handle('/ui/render','POST',{spec:spec(),unexpected:true}),{code:'INVALID_UI_INPUT'});
  await assert.rejects(f.adapter.handle(`/sessions/s/views/${opened.data.viewId}`,'POST',{action:'remove',title:'ignored'}),{code:'INVALID_UI_INPUT'});
});
test('generic component bridge executes the real Notes Provider and produces a recorded Runtime invocation',async t=>{
  const f=await setup(t),create=f.runtime.describe('notes.notes.create')!,request:InvocationRequest={protocolVersion:'1.0',appId:'notes',connectionId:'n',invocationId:'create-note',traceId:'trace-note',capabilityId:create.capabilityId,capabilityVersion:create.version,input:{id:'note-a',title:'Actual Note fixture',content:'Local test record'},source:{kind:'agent',sessionId:'s',nativeCallId:'create'},deadlineAt:new Date(Date.now()+10000).toISOString(),idempotencyKey:'create-note'};
  const result=await f.runtime.invoke(request);assert.equal(result.status,'ok');
  const current=f.presentation.createView('s',{title:'Notes interaction',bindings:[{bindingId:'notes',appId:'notes',connectionId:'n',capabilityId:'notes.notes.list',capabilityMajor:1,input:{},projection:[],refresh:{mode:'manual'}}]});await f.presentation.refreshView('s',current.viewId,{kind:'agent',sessionId:'s',nativeCallId:'list'});
  const identity={protocolVersion:'2.0' as const,sessionId:'s',viewId:current.viewId,buildId:'fixture-build',frameInstanceId:'actual-frame'},host=f.presentation.createHost(identity),before=f.store.list('invocations').length;
  const reply=await host.handle({...identity,channel:COMPONENT_CHANNEL,requestId:'read-note',method:'invokeCapability',params:{appId:'notes',connectionId:'n',capabilityId:'notes.notes.get',capabilityVersion:'1.0.0',input:{id:'note-a'},deadlineAt:new Date(Date.now()+10000).toISOString()}}) as unknown as {result:CapabilityResult};
  assert.equal(reply.result.status,'ok');assert.equal((reply.result as {data:JsonValue}).data&&recordNote(reply.result),'Actual Note fixture');assert.equal(f.store.list('invocations').length,before+1);
  const selection=f.presentation.getData('s',current.viewId).bindings[0];assert.equal(f.presentation.validateSelection('s',current.viewId,{bindingId:'notes',datasetRevision:selection.revision!,resources:selection.resources}).resources[0].resourceId,'note-a');
});
function recordNote(result:CapabilityResult):unknown {return ('data' in result?result.data as {note?:{title?:string}}:undefined)?.note?.title;}
