import type {CapabilityDescriptor,JsonSchema} from '../../app-contracts/src/index.ts';

const text:JsonSchema={type:'string',minLength:1};
const strings:JsonSchema={type:'array',items:text,minItems:1};
const object:JsonSchema={type:'object',additionalProperties:true};
const selection:JsonSchema={type:'object',properties:{id:text,skuIds:strings,cursor:text,revision:text},required:['id'],additionalProperties:false};
const component:JsonSchema={type:'object',properties:{itemId:text,sourceSkuId:text,quantity:{type:'integer',minimum:1}},required:['itemId','sourceSkuId','quantity'],additionalProperties:false};
const schemas:Record<string,JsonSchema>={
 search:{type:'object',properties:{query:{type:'string'},source:text,category:text,price:{type:'object',properties:{meaning:{enum:['purchase_cost','source_display_price']},currency:text,min:{type:'number'},max:{type:'number'}},required:['meaning','currency'],additionalProperties:false},store:{type:'object',properties:{id:text,listingRecord:{enum:['found','not_found','unavailable'],description:'推荐选品条件：found=本店有记录（含草稿、失败、归档）；not_found=已完成记录查询但未找到，可作上品候选，不证明历史从未上架；unavailable=记录暂不可查。'},status:{enum:['listed','partial','not_listed','unknown']},saleState:{enum:['on_sale','out_of_stock','pending','archived','failed','not_sellable','unknown']},association:{enum:['linked','none','unknown']}},required:['id'],additionalProperties:false},limit:{type:'integer',minimum:1,maximum:100},cursor:text,refresh:{type:'boolean'}},additionalProperties:false},
 read:{type:'object',properties:{id:text,ids:strings,skuIds:strings,selections:{type:'array',items:selection,minItems:1},cursor:text,revision:text,limit:{type:'integer',minimum:1,maximum:40},maxBytes:{type:'integer',minimum:1024,maximum:65536},refresh:{type:'boolean'}},additionalProperties:false},
 'resource.read':{type:'object',properties:{id:text,kind:{enum:['raw','description','images','image']},path:{type:'string'},assetId:text,role:{enum:['main','sku','detail']},skuIds:strings,cursor:text,revision:text,limit:{type:'integer',minimum:1,maximum:100},maxBytes:{type:'integer',minimum:1024,maximum:65536}},required:['id'],additionalProperties:false},
};
const descriptions:Record<string,string>={
 search:'搜索采集商品事实，默认每页30张精简卡片；关键词不匹配旧任务文本。价格明确采购价或来源展示售价。用户找未上商品时推荐 store.listingRecord=not_found；found含保存的上品草稿及失败/归档记录，unavailable表示读取未完成，不能当无记录。recordLookup解释查询口径与失败原因；新记录筛选无法确定总数时total=null，knownMatches仅为已知匹配。不要轮流试旧status和association来猜未上。旧store.status仅兼容历史成功铺货覆盖度，store.saleState筛当前在售/无库存/归档等，store.association筛采购关联，条件在分页统计前组合。店铺saleStates按去重销售商品offer计数，不是来源SKU数；过期或缺失观察为unknown。返回全量匹配统计与续页。',
 read:'默认返回可用于上品的精简事实：公共属性、真实包装、采购价含义、SKU差异表和主图。SKU每页最多40行，描述首1500字，批量受响应预算限制；未知与可继续读取分开。无需先搜索已知商品ID。',
 'resource.read':'按短素材编号下载图片并返回当前执行环境可查看的文件，或展开SKU/详情图片、描述、原始资料指定路径。太大时给目录或续页，不截断JSON。完整原始资料仅用于具体追查。',
};
export const COLLECTION_DESCRIPTORS:CapabilityDescriptor[]=Object.entries(schemas).map(([name,inputSchema])=>({capabilityId:`hallmark.collection.${name}`,version:'1.0.0',title:({'search':'搜索采集商品','read':'读取精简采集资料','resource.read':'查看素材与依据'} as Record<string,string>)[name],description:descriptions[name],effect:'query',inputSchema,outputSchema:object,execution:{mode:'sync',timeoutMs:90000,concurrency:'declared_safe',lockScope:'resources',idempotency:'not_applicable',completionEvidence:'response'},discovery:{defaultVisible:true,keywords:['采集箱','商品','sku','上品','图片',name]},aliases:[]}));
export const LISTING_PREPARE_DESCRIPTOR:CapabilityDescriptor={capabilityId:'hallmark.listing.prepare',version:'1.0.0',title:'准备上品资料',description:'给目标店铺与已选商品/SKU，程序一次组合精简采集资料、采购组成、包装结果、经营规则、已有商品关联和类目候选/模板。支持多SKU组合销售；已有资料版本可复用。整个响应受字节预算限制，续页仅传 continuation.input，无需重读已返回资料；类目默认给必填约束，其余字段可按需展开。只准备数据，不审核、不生成检查声明；Agent接着制作标题、属性和图片，再保存草稿。',effect:'query',inputSchema:{type:'object',properties:{storeId:text,selections:{type:'array',items:selection,minItems:1,maxItems:30},compositions:{type:'array',minItems:1,maxItems:200,items:{type:'object',properties:{id:text,members:{type:'array',items:component,minItems:1,maxItems:100}},required:['id','members'],additionalProperties:false}},knownRevisions:{type:'object',additionalProperties:text},categoryQuery:text,categories:{type:'object',additionalProperties:{type:'object',properties:{descriptionCategoryId:text,typeId:text},required:['descriptionCategoryId','typeId'],additionalProperties:false}},maxBytes:{type:'integer',minimum:2048,maximum:65536},salesLimit:{type:'integer',minimum:1,maximum:100},cursor:text,refresh:{type:'boolean'},includeOptionalAttributes:{type:'boolean'}},required:['storeId'],oneOf:[{required:['selections']},{required:['cursor']}],additionalProperties:false},outputSchema:object,execution:{mode:'sync',timeoutMs:120000,concurrency:'declared_safe',lockScope:'resources',idempotency:'not_applicable',completionEvidence:'response'},discovery:{defaultVisible:true,keywords:['上品','准备','批量','组合','采购']},aliases:[]};
