import type {DataSourceDraft,DataSourceField} from '../../app-presentation/src/types.ts';

const field=(role:string,path:string,extra:Partial<DataSourceField>={}):DataSourceField=>({role,path,confirmed:true,...extra});
const loaded={search:{scope:'loaded' as const},sort:{scope:'loaded' as const}};
// StoreProduct.status and products-board pLabels in the source app define these six values.
// not_returned belongs to presence, not status, and cannot be used by this exact filter.
const productStatusChoices=[{label:'在售',value:'on_sale'},{label:'已归档',value:'archived'},{label:'审核中',value:'pending'},{label:'审核未通过',value:'rejected'},{label:'暂不可售',value:'not_sellable'},{label:'状态待确认',value:'unknown'}];
const skuFields=[field('product.id','productId'),field('product.name','title'),field('sku.id','sku'),field('sku.specification','spec'),field('price.current','price',{currencyPath:'currency'}),field('price.currency','currency'),field('product.image','image')];
/** Provider-owned meanings verified against structured Hallmark responses, never inferred by UI. */
export function hallmarkProductSources(connectionId:string,_store?:{id:string;name:string},_sampleProductId?:string):DataSourceDraft[]{
 const base={appId:'hallmark',connectionId,capabilityMajor:1,storeScoped:true};
 const result:DataSourceDraft[]=[{...base,id:`hallmark:${connectionId}:products`,title:'Ozon 店铺商品快照',description:'店铺商品快照；当前售价按源分单位换算，不计算利润。',capabilityId:'hallmark.products.list',input:{limit:10,fields:['title','imageUrl','sku','currency','pricing','status']},parameters:[{name:'cursor',label:'分页位置',type:'string'},{name:'storeId',label:'店铺编号',type:'string',required:true,editable:false},{name:'query',label:'搜索商品',type:'string'},{name:'status',label:'商品状态',type:'string',choices:productStatusChoices},{name:'limit',label:'每页条数',type:'integer',default:10}],rowsPath:'products',fields:[field('product.id','productId'),field('product.name','title'),field('product.image','imageUrl'),field('price.current','pricing.sellerMinor',{currencyPath:'currency',numericScale:0.01,description:'平台当前卖家价；原始单位为分，展示时除以100。'}),field('price.currency','currency'),field('sku.id','sku')],operations:{pagination:{cursorParam:'cursor',limitParam:'limit'},search:{scope:'server',param:'query'},sort:{scope:'loaded'}}}];
 result.push({...base,id:`hallmark:${connectionId}:sku`,title:'Ozon 商品 SKU 明细',description:'精确商品对应的SKU；规格仅来自已匹配的源SKU，不推测其他规格。',capabilityId:'hallmark.products.skus',input:{},parameters:[{name:'storeId',label:'店铺编号',type:'string',required:true,editable:false},{name:'productId',label:'商品编号',type:'string',required:true,linked:true}],rowsPath:'items',fields:skuFields,operations:loaded});
 result.push({...base,id:`hallmark:${connectionId}:procurement`,title:'Ozon 商品采购与利润对照',description:'在售商品与精确采购来源对照，读取真实物流渠道并匹配库存仓；补充明确渠道费用后计算参考利润，非实际结算利润。',capabilityId:'hallmark.products.procurement',input:{loadAll:true,planMode:'delivery'},parameters:[{name:'loadAll',label:'读取全部在售商品',type:'boolean',editable:false},{name:'storeId',label:'店铺编号',type:'string',required:true,editable:false},{name:'cursor',label:'分页位置',type:'string'},{name:'query',label:'搜索名称、SKU或规格',type:'string'},{name:'limit',label:'每页条数',type:'integer'},{name:'planMode',label:'物流费用方案',type:'string',default:'delivery',choices:[{label:'接口物流方案',value:'delivery'},{label:'平台统一费率试算',value:'platform'},{label:'自定义试算',value:'custom'}]},{name:'deliveryMethodId',label:'接口物流渠道编号',type:'string'},{name:'fixedFeeYuan',label:'固定费用（元/件）',type:'number'},{name:'logisticsYuanPerKg',label:'运费（元/kg）',type:'number'},{name:'commissionPercent',label:'佣金比例（%）',type:'number'}],rowsPath:'products',fields:[field('product.id','productId'),field('product.name','title'),field('product.image','imageUrl'),field('sku.id','sku'),field('sku.specification','salesSpecification',{label:'销售规格'}),field('purchase.specification','purchaseSpecification'),field('logistics.plan','logisticsMatch.label'),field('product.url','productUrl'),field('purchase.url','purchaseLinks'),field('price.current','sellerMinor',{currencyPath:'currency',numericScale:0.01,description:'已核实的实际卖家售价；原始单位为分。'}),field('purchase.price','purchaseMinor',{currency:'CNY',numericScale:0.01,description:'平台核实的人民币采购成本；原始单位为分，不按来源顺序猜测。'}),field('price.currency','currency'),field('logistics.weight','packageGrams'),field('metric.margin','referenceProfit.margin',{percentScale:'fraction',description:'售价减采购价、物流、佣金及固定费用后的参考比例，非结算净利润率。'})],operations:loaded});
 return result;
}
export function hallmarkCollectedSources(connectionId:string,sampleItemId?:string):DataSourceDraft[]{
 const base={appId:'hallmark',connectionId,capabilityMajor:1};
 const result:DataSourceDraft[]=[{...base,id:`hallmark:${connectionId}:collected`,title:'采集箱 · 商品信息',description:'已有采集商品、规格数量和最低采集价格，仅展示，不作选品评估。',capabilityId:'hallmark.collected.search',input:{limit:10},parameters:[{name:'cursor',label:'分页位置',type:'string'},{name:'limit',label:'每页条数',type:'integer',default:10}],rowsPath:'items',fields:[field('product.id','id'),field('product.name','title'),field('product.image','mainImage'),field('price.current','minPrice',{currencyPath:'currency',label:'最低采集价格',description:'采集商品的最低SKU价格，不代表店铺售价。'}),field('price.currency','currency')],operations:{...loaded,pagination:{cursorParam:'cursor',limitParam:'limit'}}}];
 if(sampleItemId)result.push({...base,id:`hallmark:${connectionId}:collected-sku`,title:'采集箱 · SKU 规格与价格',description:'结构化采集SKU明细；仅规格和价格。',capabilityId:'hallmark.collected.skus',input:{itemId:sampleItemId},parameters:[{name:'itemId',label:'采集商品编号',type:'string',required:true,linked:true,default:sampleItemId}],rowsPath:'items',fields:skuFields.map(item=>item.role==='price.current'?{...item,label:'SKU 采集价格',description:'采集来源提供的该规格价格，不代表店铺售价。'}:item),operations:loaded});
 return result;
}
