import { build } from 'esbuild';
import { mkdir, readFile } from 'node:fs/promises';
import { HOST_PLUGIN_VERSION } from '../packages/dsh-plugin/server/version.ts';
import { TOOL_DEFINITIONS } from '../packages/contracts/src/index.ts';
import { assertJsonCompatible } from '../packages/contracts/src/json.ts';
import { Config } from '../packages/dsh-plugin/server/config.ts';
assertJsonCompatible(Config.toJSON());
assertJsonCompatible(TOOL_DEFINITIONS);
const packageDirectory='packages/dsh-plugin';
const manifest=JSON.parse(await readFile(`${packageDirectory}/package.json`,'utf8'));
if(manifest.version!==HOST_PLUGIN_VERSION)throw new Error('HOST_CODE_VERSION_MISMATCH');
await mkdir(`${packageDirectory}/lib`,{recursive:true});
await mkdir(`${packageDirectory}/client`,{recursive:true});
await build({entryPoints:[`${packageDirectory}/server/index.ts`],outfile:`${packageDirectory}/lib/index.js`,bundle:true,platform:'node',format:'esm',target:'node22',sourcemap:true,packages:'external'});
const client=await build({entryPoints:[`${packageDirectory}/client/index.tsx`],bundle:true,write:false,platform:'browser',format:'cjs',target:'es2022',jsx:'automatic',external:['react','react/jsx-runtime','react-dom','react-dom/client','@deepseek-ai/*'],define:{'process.env.NODE_ENV':'"production"'},minify:false});
const {writeFile}=await import('node:fs/promises');
const javascript=client.outputFiles.find(file=>file.path.endsWith('.js'))??client.outputFiles[0];
const wrapped=`window.__ModuleLoader__.load({id:'dsh-plugin-hallmark',factory:function(require){var module={exports:{}};var exports=module.exports;\n${javascript.text}\nreturn module.exports;}});\n`;
await writeFile(`${packageDirectory}/client/client.js`,wrapped);
console.log('Prebuilt Host and Client plugin artifacts');
