// A.2 maintenance acceptance: isolated Runtime fixture and byte-verified reuse of actual frozen runs.
// Never opens the user's live Runtime or changes a desktop profile, process or candidate archive.
import assert from 'node:assert/strict';
import {spawn,spawnSync} from 'node:child_process';
import {createHash,randomUUID} from 'node:crypto';
import {existsSync,mkdirSync,readFileSync,readdirSync,renameSync,writeFileSync} from 'node:fs';
import {createServer} from 'node:net';
import {createServer as createHttpServer} from 'node:http';
import {join,relative,resolve} from 'node:path';
import {pathToFileURL,fileURLToPath} from 'node:url';
import {DatabaseSync} from 'node:sqlite';
import {RuntimeStore,RUNTIME_COLLECTIONS} from '../../packages/app-runtime/src/store.ts';
import {AppsPresentationService} from '../../packages/app-presentation/src/index.ts';
import {SourceComponentStore} from '../../packages/source-components/src/index.ts';
import {AuthoringEvidenceRunner,evidenceFile} from '../../packages/source-components/src/authoring-evidence.ts';
import {EvidencePathResolver} from '../../packages/source-components/src/evidence-relocation.ts';
import {startAuthoringPreview} from '../../packages/source-components/src/authoring-preview.ts';
import {gcDryRun,applyGC} from '../../packages/app-migration/src/maintenance.ts';
import {backupRuntime,restoreRuntimeBackup,verifyRuntimeBackup} from '../../packages/app-migration/src/runtime-backup.ts';
import {verifyA2ReleaseEvidence,parseEvidenceCsv,loadFrozenBaseline} from '../../scripts/verify-a2-release-evidence.mjs';

const repository=resolve(fileURLToPath(new URL('../..',import.meta.url)));
process.chdir(repository);
const args=process.argv.slice(2);if(args.length)throw Error('NO_ARGUMENTS: creates a fresh private evidence run directory.');
const runId=`maintenance-${new Date().toISOString().replace(/[:.]/g,'-')}-${randomUUID()}`;
const directory=resolve('evidence/apps-a2-20261007/formal-maintenance',runId);mkdirSync(directory,{recursive:true});
const startedAt=new Date().toISOString(),candidate='1.0.0-candidate.10';
const executedCommit=spawnSync('git',['rev-parse','HEAD'],{encoding:'utf8',windowsHide:true}).stdout.trim();assert.match(executedCommit,/^[a-f0-9]{40}$/);
const trackedProductDiff=spawnSync('git',['diff','HEAD','--name-only','--','packages','scripts',':(exclude)scripts/verify-a2-release-evidence.mjs'],{encoding:'utf8',windowsHide:true});assert.equal(trackedProductDiff.status,0);assert.equal(trackedProductDiff.stdout.trim(),'','Existing tracked product sources must match HEAD; new checker is separately hash-bound.');
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const ref=path=>{const full=resolve(path),bytes=readFileSync(full);return {path:full,sha256:sha(bytes),bytes:bytes.length};};
const json=(name,value)=>{const path=join(directory,name);mkdirSync(resolve(path,'..'),{recursive:true});writeFileSync(path,JSON.stringify(value,null,2)+'\n',{flag:'wx',mode:0o600});return ref(path);};
const copy=(name,path)=>{const dest=join(directory,name);mkdirSync(resolve(dest,'..'),{recursive:true});writeFileSync(dest,readFileSync(path),{flag:'wx',mode:0o600});return ref(dest);};
const assertions=[];
const check=(id,expected,actual)=>{assert.deepEqual(actual,expected,id);const item={id,expected:expected===null?'null (observed empty value)':expected,actual:actual===null?'null (observed empty value)':actual,status:'PASS'};assertions.push(item);return item;};
const provenance={runId,startedAt,executedCommit,node:process.version,platform:process.platform,workingTreeAtStart:spawnSync('git',['status','--short'],{encoding:'utf8',windowsHide:true}).stdout.trim(),trackedProductDiffCommand:'git diff HEAD --name-only -- packages scripts :(exclude)scripts/verify-a2-release-evidence.mjs',trackedProductDiff:trackedProductDiff.stdout.trim(),executedSourceState:'HEAD identifies tracked product sources (verified zero diff), not the entire worktree. New uncommitted maintenance harness, checker and narrow tests have separate SHA identities; no candidate rebuild.',harness:ref(fileURLToPath(import.meta.url)),releaseEvidenceVerifier:ref('scripts/verify-a2-release-evidence.mjs'),acceptance:ref('docs/requirements/A2/docs/03_ACCEPTANCE.md'),candidateManifest:ref(`evidence/apps-a2-20261007/candidates/${candidate}/build-manifest.json`),environment:'Fresh fixture paths and owned headless Chrome only; no live Runtime/desktop/API/process access.',releaseApproved:false};
const productionPaths=['packages/app-migration/src/maintenance.ts','packages/app-migration/src/runtime-backup.ts','packages/app-runtime/src/store.ts','packages/source-components/src/index.ts','packages/source-components/src/authoring-evidence.ts','packages/source-components/src/evidence-relocation.ts','packages/app-presentation/src/authoring.ts','packages/app-presentation/src/index.ts'];
const productionHashes=Object.fromEntries(productionPaths.map(path=>[path,ref(path).sha256]));
const packedInputs=JSON.parse(readFileSync(provenance.candidateManifest.path,'utf8')).sourceInputs;
const inputSnapshot=()=>Object.entries(packedInputs).map(([path,expectedSha256])=>({path,expectedSha256,actualSha256:ref(path).sha256}));
const packedInputBefore=inputSnapshot();check('candidate10:source-input-count',143,packedInputBefore.length);check('candidate10:source-inputs-before',[],packedInputBefore.filter(row=>row.expectedSha256!==row.actualSha256));
const records=[];
function record(testId,scope,items,artifacts,metrics=[]){const row={schemaVersion:1,recordKind:'ACCEPTANCE_EXECUTION',testId,runId,candidate,executedCommit,scope,modelClass:'NONE',executionKind:'FIXTURE_EXECUTION',status:'PASS',assertions:items,artifacts:artifacts.map(item=>({...item,kind:'result'})),metrics};const file=json(`${testId}/result.json`,row);records.push(file);return file;}
const pause=milliseconds=>new Promise(accept=>setTimeout(accept,milliseconds));

async function browserFixture(action){
  const executable=['C:/Program Files/Google/Chrome/Application/chrome.exe','C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'].find(existsSync);if(!executable)throw Error('OWNED_FIXTURE_BROWSER_UNAVAILABLE');
  const portServer=createServer();await new Promise(accept=>portServer.listen(0,'127.0.0.1',accept));const port=portServer.address().port;await new Promise(accept=>portServer.close(accept));
  const profile=join(directory,`.browser-profile-${randomUUID()}`),child=spawn(executable,['--headless=new','--disable-gpu','--disable-background-networking','--disable-component-update','--disable-extensions','--no-first-run','--no-default-browser-check',`--remote-debugging-port=${port}`,`--user-data-dir=${profile}`,'about:blank'],{windowsHide:true,stdio:['ignore','ignore','ignore']});
  let socket,sequence=0;const pending=new Map();
  const command=(method,params={})=>new Promise((accept,reject)=>{const id=++sequence,timer=setTimeout(()=>{pending.delete(id);reject(Error(`Owned fixture browser timed out: ${method}`));},10000);pending.set(id,{accept:value=>{clearTimeout(timer);accept(value);},reject:error=>{clearTimeout(timer);reject(error);}});socket.send(JSON.stringify({id,method,params}));});
  const evaluate=async expression=>{const value=await command('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(value.exceptionDetails)throw Error(value.exceptionDetails.text);return value.result?.value;};
  const open=async(path,condition)=>{const navigation=await command('Page.navigate',{url:path.startsWith('http://127.0.0.1:')?path:pathToFileURL(path).href});if(navigation.errorText)throw Error('Owned fixture navigation failed: '+navigation.errorText);for(let index=0;index<100;index++){if(await evaluate(condition))return;await pause(50);}throw Error('Owned fixture did not render '+path);};
  const screenshot=async path=>{const result=await command('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(path,Buffer.from(result.data,'base64'),{flag:'wx'});return ref(path);};
  try{
    let pages;for(let index=0;index<100;index++){try{pages=await fetch(`http://127.0.0.1:${port}/json/list`).then(response=>response.json());if(pages.length)break;}catch{}await pause(50);}if(!pages?.length)throw Error('OWNED_FIXTURE_BROWSER_UNAVAILABLE');
    socket=new WebSocket(pages.find(page=>page.type==='page').webSocketDebuggerUrl);await new Promise((accept,reject)=>{socket.addEventListener('open',accept,{once:true});socket.addEventListener('error',reject,{once:true});});
    socket.addEventListener('message',event=>{const value=JSON.parse(event.data),request=pending.get(value.id);if(request){pending.delete(value.id);value.error?request.reject(Error(value.error.message)):request.accept(value.result);}});
    await command('Page.enable');await command('Runtime.enable');await command('Emulation.setDeviceMetricsOverride',{width:720,height:420,deviceScaleFactor:1,mobile:false});
    return await action({open,evaluate,screenshot,executable});
  }finally{if(socket?.readyState===WebSocket.OPEN){try{await command('Browser.close');}catch{}socket.close();}if(child.exitCode===null){await Promise.race([new Promise(accept=>child.once('close',accept)),pause(3000)]);if(child.exitCode===null)child.kill();}for(const request of pending.values())request.reject(Error('Owned fixture browser closed'));}
}

async function tst073(){
  const start=assertions.length,root=join(directory,'TST-073'),runtime=join(root,'fixture-runtime'),backupDirectory=join(root,'full-backup'),target=join(root,'restored-runtime');mkdirSync(runtime,{recursive:true});
  const sources=new SourceComponentStore(join(runtime,'source-components')),runner=new AuthoringEvidenceRunner(join(runtime,'authoring-evidence')),builds=[];
  const owner='maintenance-fixture-owner',old='2000-01-01T00:00:00.000Z';
  for(const [index,name]of ['history','last-good','pending','new-reference','orphan'].entries()){
    const workspace=join(runtime,'component-workspace',name);mkdirSync(workspace,{recursive:true});
    writeFileSync(join(workspace,'package.json'),JSON.stringify({name:'maintenance-'+name,version:'1.0.0',private:true}));writeFileSync(join(workspace,'package-lock.json'),JSON.stringify({lockfileVersion:3,name:'maintenance-'+name,version:'1.0.0',packages:{}}));
    writeFileSync(join(workspace,'source.html'),`<!doctype html><html><meta charset="utf-8"><style>body{font:20px sans-serif;margin:28px;color:#17325d}article{padding:24px;border:1px solid #bbceeb;border-radius:12px}</style><article><h1>A.2 ${name}</h1><p>Isolated maintenance fixture · ${index+1}</p></article></html>`);
    writeFileSync(join(workspace,'build.mjs'),"import{mkdirSync,copyFileSync}from'node:fs';mkdirSync('dist',{recursive:true});copyFileSync('source.html','dist/index.html');console.log('actual maintenance fixture built');");
    if(index<3){const built=await runner.build({attemptId:name,epoch:index+1,sourceRevision:index+1,workspacePath:workspace,command:[process.execPath,'build.mjs'],sources});check(`073:${name}:actual-build`,'PASS',built.report.verdict);builds.push({name,workspace,buildId:built.report.archiveBuildId,built});}
    else{mkdirSync(join(workspace,'dist'));writeFileSync(join(workspace,'dist','index.html'),readFileSync(join(workspace,'source.html')));builds.push({name,workspace,buildId:sources.capture(workspace).source.buildId});}
  }
  const [history,lastGood,pending,newReference,orphan]=builds;
  const historicalScreenshot=join(runner.root,'historical-preview.png');
  const originalPreview=await startAuthoringPreview({sources,buildId:history.buildId,mode:'fixture',data:{viewId:'fixture',bindings:[]}});let originalRender;
  try{originalRender=await browserFixture(async browser=>{await browser.open(originalPreview.url,"document.querySelector('iframe')?.contentDocument?.querySelector('h1')?.textContent==='A.2 history'");return {text:await browser.evaluate("document.querySelector('iframe').contentDocument.body.innerText"),screenshot:await browser.screenshot(historicalScreenshot),browser:browser.executable};});}finally{await originalPreview.close();}
  check('073:history-real-render',true,originalRender.text.includes('A.2 history'));
  const screenshotRef=evidenceFile(historicalScreenshot),preview={schemaVersion:1,attemptId:'history',epoch:1,buildReceiptId:'build-history',buildId:history.buildId,protocol:'dsh.apps.component.v2',mode:'fixture',runnerVersion:'maintenance-direct-archive-browser/1',verdict:'PASS',viewportResults:[{contentWidthCssPx:720,screenshot:screenshotRef}],assertionResults:[{id:'historical-visible',required:true,expected:'A.2 history',actual:originalRender.text,status:'PASS',evidenceRefs:[screenshotRef]}]};
  const previewRef=runner.writeReport('preview',preview),store=new RuntimeStore(join(runtime,'apps.db'));
  try{
    for(const build of builds)store.put('builds',build.buildId,{...sources.manifest(build.buildId),createdAt:old});
    store.put('datasets','dataset:v1:maintenance',{datasetId:'dataset:v1:maintenance',revision:'1',status:'ready',payload:{items:[{id:'fixture'}]},fetchedAt:old});
    store.put('views','view-main',{viewId:'view-main',ownerSessionId:owner,title:'Maintenance last-good',design:{kind:'source'},bindings:[],createdAt:old,updatedAt:old,viewRevision:4,activeBuildId:lastGood.buildId,lastGoodBuildId:lastGood.buildId,previousGoodBuildId:history.buildId,pendingPublicationId:null,validationStatus:'verified',source:{buildId:lastGood.buildId,directory:lastGood.workspace,entry:'index.html',files:['index.html']}});
    for(const [index,build]of [history,lastGood,pending].entries()){
      const draftId='draft-'+build.name;store.put('authoring_drafts',draftId,{schemaVersion:1,draftId,ownerSessionId:owner,viewId:'view-main',workspacePath:build.workspace,sourceRevision:index+1,epoch:index+1,status:build===pending?'previewing':'closed',createdAt:old,updatedAt:old});
      store.put('build_receipts','build-'+build.name,{receiptId:'build-'+build.name,...build.built.report});
    }
    store.put('authoring_attempts','pending',{attemptId:'pending',draftId:'draft-pending',epoch:3,sourceRevision:3,state:'previewing',startedAt:old,expectedViewRevision:4,invocationRefs:[],evidenceRefs:[pending.built.reportRef],terminalReason:null,buildReceiptId:'build-pending'});
    store.put('authoring_attempts','history',{attemptId:'history',draftId:'draft-history',epoch:1,sourceRevision:1,state:'mounted',startedAt:old,expectedViewRevision:4,invocationRefs:[],evidenceRefs:[history.built.reportRef,previewRef],terminalReason:null,buildReceiptId:'build-history',previewReceiptId:'preview-history'});
    store.put('preview_receipts','preview-history',{receiptId:'preview-history',...preview});
    store.put('view_ui_states','historical-ui',{sessionId:owner,viewId:'view-main',sourceBuildId:history.buildId,value:{query:'old filter'},stateRevision:1});
    store.put('component_contexts','historical-context',{snapshotId:'historical-context',buildId:history.buildId,datasetId:'dataset:v1:maintenance'});
    store.put('artifact_refs','historic-preview-file',{ownerKind:'preview_receipt',ownerId:'preview-history',targetKind:'file',targetId:screenshotRef.sha256,file:screenshotRef});
    const first=gcDryRun(store,runtime,{now:new Date('2026-10-07T00:00:00Z')});
    check('073:initial-only-unreferenced',[newReference.buildId,orphan.buildId].sort(),first.candidates.map(item=>item.id).sort());
    for(const build of [history,lastGood,pending])check(`073:retention:${build.name}`,true,first.retained.some(item=>item.id===build.buildId&&item.reason==='asset_reference'));
    const firstRef=json('TST-073/gc-plan-before-reference.json',first),beforeRows=rows(store.db);
    store.put('artifact_refs','added-after-plan',{ownerKind:'context',ownerId:'new-visible-context',targetKind:'build',targetId:newReference.buildId});
    let staleError;try{applyGC(store,first);}catch(error){staleError=error.message;}check('073:stale-plan-refused','GC_PLAN_STALE',staleError);
    const afterStale=rows(store.db);check('073:stale-does-not-remove-builds',beforeRows.builds,afterStale.builds);
    const next=gcDryRun(store,runtime,{now:new Date('2026-10-07T00:00:00Z')});check('073:fresh-only-true-orphan',[orphan.buildId],next.candidates.map(item=>item.id));
    const applied=applyGC(store,next);check('073:deleted-only-orphan',[{collection:'builds',id:orphan.buildId}],applied.deleted);check('073:orphan-file-removed',false,existsSync(join(sources.directory,'builds',orphan.buildId)));
    for(const build of [history,lastGood,pending,newReference])check(`073:kept:${build.name}`,true,sources.verify(build.buildId).valid);
    json('TST-073/gc-plan-after-reference.json',next);json('TST-073/gc-transaction-diff.json',{firstPlan:firstRef,staleError,rowsBefore:beforeRows,rowsAfterNewReferenceAndStale:afterStale,rowsAfterApply:rows(store.db),applied,referenceInventory:store.list('artifact_refs'),newReference:newReference.buildId,orphan:orphan.buildId});
  }finally{store.close();}
  const db=new DatabaseSync(join(runtime,'apps.db'),{readOnly:true});let originalRows;try{originalRows=rows(db);}finally{db.close();}
  const manifest=await backupRuntime({sourceDirectory:runtime,backupDirectory,offlineConfirmed:true});check('073:backup-all25-collections',25,Object.keys(manifest.counts).length);check('073:backup-verifies',manifest.backupId,verifyRuntimeBackup(backupDirectory).backupId);
  const restored=restoreRuntimeBackup({backupDirectory,targetDirectory:target});check('073:restore-original-evidence-unchanged',true,restored.originalEvidenceUnchanged);
  json('TST-073/backup-manifest.json',manifest);json('TST-073/restore-report.json',restored);
  renameSync(runtime,join(root,'original-runtime-hidden'));
  const restoredStore=new RuntimeStore(join(target,'apps.db'));let inspection,rendered;
  try{
    const actual=rows(restoredStore.db);for(const table of RUNTIME_COLLECTIONS)check(`073:restored-rows:${table}`,originalRows[table],actual[table].filter(row=>table!=='provider_records'||!row.id.startsWith('evidence_relocations:')));
    const resolver=new EvidencePathResolver({root:target,store:restoredStore}),mapped=resolver.resolve.bind(resolver),restoredSources=new SourceComponentStore(join(target,'source-components'));
    const restoredRunner=new AuthoringEvidenceRunner(join(target,'authoring-evidence'),{resolvePath:mapped});
    check('073:historic-receipt-signature-preserved',history.buildId,restoredRunner.readReport(previewRef).buildId);
    check('073:history-image-exact-sha',screenshotRef.sha256,sha(readFileSync(mapped(screenshotRef.path))));check('073:history-image-exact-bytes',screenshotRef.bytes,readFileSync(mapped(screenshotRef.path)).length);
    for(const build of [history,lastGood,pending,newReference])check(`073:restored-build:${build.name}`,true,restoredSources.verify(build.buildId).valid);
    const service=new AppsPresentationService({store:restoredStore,sources:restoredSources,runtime:{describe:()=>undefined,invoke:async()=>{throw Error('NO_RUNTIME_OR_BUSINESS_CALLS');}}}),authoring=service.configureAuthoring({evidenceRoot:restoredRunner.root,resolveEvidencePath:mapped,validateBuildEvidence:reference=>restoredRunner.verifyBuild(reference,restoredSources,{allowFailure:true}),validatePreviewEvidence:reference=>restoredRunner.readReport(reference)});
    const beforeInspection=rows(restoredStore.db);inspection=authoring.inspect(owner,{attemptId:'pending'});check('073:pending-explained-state','previewing',inspection.attempt.state);check('073:pending-workspace-recoverable',true,inspection.workspaceAvailable);check('073:pending-missing-preview-explicit',['PreviewReceipt'],inspection.missingEvidence);check('073:inspect-no-logical-write',beforeInspection,rows(restoredStore.db));
    const currentPreview=await startAuthoringPreview({sources:restoredSources,buildId:lastGood.buildId,mode:'fixture',data:{viewId:'fixture',bindings:[]}}),imageServer=createHttpServer((request,response)=>{if(request.method!=='GET'||request.url!=='/historical.png'){response.writeHead(404);response.end();return;}response.writeHead(200,{'content-type':'image/png','cache-control':'no-store'});response.end(readFileSync(mapped(screenshotRef.path)));});
    await new Promise(accept=>imageServer.listen(0,'127.0.0.1',accept));
    try{rendered=await browserFixture(async browser=>{await browser.open(currentPreview.url,"document.querySelector('iframe')?.contentDocument?.querySelector('h1')?.textContent==='A.2 last-good'");const text=await browser.evaluate("document.querySelector('iframe').contentDocument.body.innerText"),lastGoodScreenshot=await browser.screenshot(join(root,'restored-last-good-opened.png'));await browser.open(`http://127.0.0.1:${imageServer.address().port}/historical.png`,'document.images[0]?.complete&&document.images[0]?.naturalWidth>0');const image=await browser.evaluate('({width:document.images[0].naturalWidth,height:document.images[0].naturalHeight,complete:document.images[0].complete})');return {lastGoodText:text,lastGoodScreenshot,historicalImage:image,historicalImageOpenedScreenshot:await browser.screenshot(join(root,'restored-history-screenshot-opened.png')),browser:browser.executable};});}finally{await currentPreview.close();imageServer.closeAllConnections();await new Promise(accept=>imageServer.close(accept));}
    check('073:restored-last-good-opened',true,rendered.lastGoodText.includes('A.2 last-good'));check('073:restored-historical-screenshot-opened',{width:720,height:420,complete:true},rendered.historicalImage);
  }finally{restoredStore.close();}
  const details=json('TST-073/details.json',{productionHashes,fixtureVersions:{databaseSchema:4,sourceBuilds:builds.map(({name,buildId})=>({name,buildId})),bridge:'2.0 declared only; direct archive browser opening tests backup, not bridge or native mount'},manifest:ref(join(backupDirectory,'manifest.json')),restored,inspection,originalRender,rendered,originalRootsUnavailable:true,liveHost:'NOT_RUN',liveModel:'NOT_RUN',businessCalls:0});
  return record('TST-073',['FIXTURE'],assertions.slice(start),[details,ref(join(root,'gc-plan-before-reference.json')),ref(join(root,'gc-plan-after-reference.json')),ref(join(root,'gc-transaction-diff.json')),ref(join(root,'backup-manifest.json')),ref(join(root,'restore-report.json')),rendered.lastGoodScreenshot,rendered.historicalImageOpenedScreenshot]);
}
function rows(db){return Object.fromEntries(RUNTIME_COLLECTIONS.map(table=>[table,db.prepare(`SELECT * FROM ${table} ORDER BY id`).all()]));}

const schedulerCases=[
 ['worker-crud','plans require a live worker, registered read schema, timezone and CAS; next run is explicit UTC'],
 ['independent-bindings','actual worker refreshes two closed-UI datasets independently, preserves failed data and never builds or saves'],
 ['restart-missed-once','persisted nextRun survives SQLite restart and missed days coalesce to one read per dataset'],
 ['single-flight-disable','same-dataset plans and overlapping manual refresh are single-flight; disabled plans/connections stop new reads'],
 ['timezone-dst','timezone search skips nonexistent DST minutes and does not dispatch a repeated wall-clock slot twice'],
 ['interrupted-reservation','an interrupted read reservation recovers once even when nextRun was already persisted in the future'],
 ['changed-plan-inflight','changing a plan during its in-flight read cannot attach the old result to the new binding'],
];
const configCases=[
 ['mock-a-to-b','controlled configuration drains Mock A, refuses new dispatch, then records new Mock B revision'],
 ['provider-cache-generations','backend generations exclude old persisted product/task caches while preserving original operation evidence'],
 ['actual-execution-idle','timeout and aborted caller do not release actual execution or commit a new configuration'],
 ['unknown-and-inspect','unresolved business outcome blocks configuration switch and inspect remains pinned until actually idle'],
 ['queued-and-rollback','queued calls never migrate generations and failed invalidation rolls the configuration transaction back'],
 ['intent-original-revision','a duplicate successful intent after a configuration change retains the original operation and revision without execution'],
 ['file-seed-composition','real composition treats the persisted database as authoritative, reports changed seed file and invalidates its actual clients'],
];
function frozenCases(testId,prefix,mapping){
  const oldSummary=JSON.parse(readFileSync('evidence/apps-a2-20261007/runtime-refresh-config/final-scope.json','utf8')),frozen=JSON.parse(readFileSync('evidence/apps-a2-20261007/verification/frozen-candidate10.json','utf8'));
  const log='evidence/apps-a2-20261007/verification/full-test-candidate10.txt';check(`${testId}:frozen-log-hash`,frozen.logs['full-test-candidate10.txt'],ref(log).sha256);
  const text=readFileSync(log,'utf8'),testPath=prefix==='scheduler'?'test/service/apps-scheduler.test.ts':'test/apps-runtime/connection-config.test.ts';check(`${testId}:exact-tested-harness`,oldSummary.sourceHashes[testPath],ref(testPath).sha256);
  const sourceText=readFileSync(testPath,'utf8'),cases=[];
  for(const [name,title]of mapping){
    const path=`evidence/apps-a2-20261007/runtime-refresh-config/${prefix}-${name}.json`,value=JSON.parse(readFileSync(path,'utf8'));
    check(`${testId}:${name}:status`,'PASS',value.status);check(`${testId}:${name}:scope`,prefix==='scheduler'?'FIXTURE+CLOCK_CONTROL':'FIXTURE',value.scope);
    check(`${testId}:${name}:candidate10-run-time`,true,value.executedAt.startsWith('2026-10-07T08:24:'));check(`${testId}:${name}:test-trace`,true,sourceText.includes(`test('${title}'`));
    check(`${testId}:${name}:frozen-log-success`,1,text.split('\n').filter(line=>line.startsWith('✔ '+title+' (')).length);
    const differences=Object.entries(value.sourceHashes).filter(([path,hash])=>ref(path).sha256!==hash);check(`${testId}:${name}:source-hashes`,[],differences);
    cases.push({name,title,original:ref(path),frozenCopy:copy(`${testId}/original-cases/${prefix}-${name}.json`,path),sourceFile:testPath,sourceLine:sourceText.slice(0,sourceText.indexOf(`test('${title}'`)).split('\n').length,executedAt:value.executedAt,facts:value.facts,sourceHashes:value.sourceHashes});
  }
  const staleSources=Object.entries(oldSummary.sourceHashes).filter(([path,hash])=>ref(path).sha256!==hash).map(([path,oldHash])=>({path,oldHash,currentHash:ref(path).sha256}));
  check(`${testId}:old-summary-excluded-as-current`,true,staleSources.length>0);
  return {cases,originalExecutionCommit:'NOT_RECORDED: uncommitted working tree; not reconstructed',verifiedAgainstCommit:executedCommit,reuseNotFreshProductExecution:true,revalidatedAt:new Date().toISOString(),oldSummary:ref('evidence/apps-a2-20261007/runtime-refresh-config/final-scope.json'),oldSummaryStaleSources:staleSources,oldSummaryNotOverwritten:true,frozenLog:copy(`${testId}/full-test-candidate10.txt`,log),frozenVerification:copy(`${testId}/frozen-candidate10.json`,'evidence/apps-a2-20261007/verification/frozen-candidate10.json'),testSource:copy(`${testId}/tested-harness.ts`,testPath),executionMode:'Revalidate original actual 08:24 frozen production execution against current exact source hashes and per-test success trace; no rerun and no promotion to native/model/business scope. executedCommit on the current card identifies this revalidation harness, not the original 08:24 execution.'};
}
function tst075(){
  const start=assertions.length,proof=frozenCases('TST-075','scheduler',schedulerCases),facts=Object.fromEntries(proof.cases.map(row=>[row.name,row.facts]));
  const crud=facts['worker-crud'],closed=facts['independent-bindings'],restart=facts['restart-missed-once'],disabled=facts['single-flight-disable'],interrupted=facts['interrupted-reservation'],changed=facts['changed-plan-inflight'],dst=facts['timezone-dst'];
  check('075:worker-observable',true,Boolean(crud.workerId&&closed.workerId&&crud.workerState==='running'));check('075:explicit-next-run','2026-10-07T01:00:00.000Z',crud.initialNextRunAt);check('075:closed-ui',true,closed.allUiClosed);check('075:only-read-capabilities',true,closed.queries.length===6&&closed.queries.every(query=>query.source.kind==='scheduler'&&query.capabilityId.endsWith('.rows.list')));check('075:build-save-business-counts-zero-delta',closed.beforeCounts,closed.afterCounts);
  check('075:at-most-one-missed-read-per-dataset',2,restart.readCount);check('075:real-sqlite-restart',true,restart.sqliteRestart&&restart.firstWorkerId!==restart.newWorkerId);check('075:nextRun-after-catchup',true,restart.plans.length===2&&restart.plans.every(plan=>plan.nextRunAt==='2026-10-16T01:00:00.000Z'&&plan.misfirePolicy==='coalesce_once'));check('075:repeat-catchup-count',0,restart.repeatTickAdditionalReads);check('075:single-dataset-single-flight',1,disabled.physicalReads);check('075:disabled-no-new-reads',0,disabled.disabledPlansAdditionalReads);check('075:disabled-connection-explicit','CONNECTION_DISABLED',disabled.disabledConnectionResult.code);check('075:worker-absent-explicit',true,crud.absentWorkerRejected&&disabled.absentWorkerRejectsExecution);check('075:interrupted-read-coalesced-once',1,interrupted.readCount);check('075:interrupted-repeat-count',0,interrupted.repeatTickAdditionalReads);check('075:interrupted-no-business',0,interrupted.businessMutationCalls);check('075:changed-inflight-not-reattached',false,changed.oldResultAttachedToNewBinding);check('075:changed-plan-next-read',['hallmark','notes'],changed.nextReadApps);check('075:DST-no-duplicate',true,dst.sameWallClockSlotDispatchedAtMostOnce);
  const store=new RuntimeStore(':memory:');try{const service=new AppsPresentationService({store,runtime:{describe:()=>undefined,invoke:async()=>{throw Error('UNEXPECTED_QUERY');}}});let error;try{service.createView('fixture',{title:'Absent worker',design:{},bindings:[{bindingId:'h',appId:'hallmark',connectionId:'fixture',capabilityId:'hallmark.rows.list',capabilityMajor:1,input:{},projection:[],refresh:{mode:'scheduled',scheduleId:'unsupported'}}]});}catch(problem){error=problem.code;}check('075:scheduled-view-without-worker-unsupported','SCHEDULER_UNAVAILABLE',error);check('075:unsupported-no-view-records',0,store.list('views').length);proof.absentWorkerDirectProductionCheck={actualError:error,views:store.list('views').length,datasets:store.list('datasets').length,source:ref('packages/app-presentation/src/index.ts'),isUserInterfaceExecution:false};}finally{store.close();}
  const detail=json('TST-075/details.json',{...proof,scope:'FIXTURE+CLOCK_CONTROL',stepMapping:{1:['worker-crud','independent-bindings'],2:['restart-missed-once','single-flight-disable','interrupted-reservation'],3:['single-flight-disable','worker-crud','absentWorkerDirectProductionCheck']},clockTrace:['2026-10-07T00:59:00.000Z','2026-10-07T01:00:00.000Z','2026-10-07T13:00:00.000Z','2026-10-15T14:00:00.000Z'],unsupportedCode:'SCHEDULER_UNAVAILABLE; no fabricated freshness SLA',liveHost:'NOT_RUN',liveModel:'NOT_RUN',realBusiness:'NOT_RUN'});
  return record('TST-075',['FIXTURE','CLOCK_CONTROL'],assertions.slice(start),[detail,proof.frozenLog,proof.frozenVerification,proof.testSource,...proof.cases.map(row=>row.frozenCopy)],[{name:'physicalQueryCountSingleFlight',value:disabled.physicalReads,unit:'count'}]);
}
function tst076(){
  const start=assertions.length,proof=frozenCases('TST-076','config',configCases),facts=Object.fromEntries(proof.cases.map(row=>[row.name,row.facts])),seed=facts['file-seed-composition'],move=facts['mock-a-to-b'],cache=facts['provider-cache-generations'],idle=facts['actual-execution-idle'],unknown=facts['unknown-and-inspect'],queued=facts['queued-and-rollback'],intent=facts['intent-original-revision'];
  check('076:database-authority','database',seed.reportedDifference.authority);check('076:seed-change-not-applied',false,seed.fileChangeApplied);check('076:seed-active-old-backend','A',seed.oldCallBackend);check('076:controlled-new-backend','B',seed.controlledUpdateBackend);check('076:CAS-new-revision',2,move.afterRevision);check('076:old-call-revision',1,move.oldInvocationRevision);check('076:new-call-revision',2,move.newInvocationRevision);check('076:cache-generation',1,move.cacheGeneration);check('076:drain-no-dispatch',0,move.newDispatchDuringDrain);check('076:MockA-trace',['/api/health','/api/stores'],move.mockARequests);check('076:MockB-trace',['/api/health','/api/stores'],move.mockBRequests);check('076:old-CAS-rejected',true,move.oldExpectedRevisionRejected);
  check('076:old-cache-A','A',cache.oldProductOrigin);check('076:new-cache-B','B',cache.newProductOrigin);check('076:new-task-cache-cleared',null,cache.newGenerationTaskMapping);check('076:original-operation-retained',true,cache.originalOperationPreserved);check('076:one-new-B-product-read',1,cache.mockBProductReads);check('076:abort-does-not-mean-idle',1,idle.actualExecutionActiveAfterCallerAbort);check('076:drain-timeout-keeps-revision',1,idle.revisionAfterFailedUpdate);check('076:update-only-after-actual-idle',2,idle.revisionAfterActualIdleUpdate);check('076:unknown-blocks-switch',true,unknown.unknownPreventsSwitch);check('076:inspect-active-until-real-idle',true,unknown.inspectAbortedCallerStillActualActive===1&&unknown.disposeWaitsForActualInspect);check('076:unknown-keeps-revision',1,unknown.configRevision);check('076:old-queued-no-dispatch',0,queued.oldQueuedRequestDispatches);check('076:failed-invalidation-keeps-revision',2,queued.preservedRevision);check('076:admission-resumed',true,queued.admissionResumed);check('076:duplicate-no-execution',1,intent.executions);check('076:duplicate-original-operation',intent.operationId,intent.duplicateOperationId);check('076:rollback-is-new-revision',3,intent.activeRevisionAfterRollback);
  const detail=json('TST-076/details.json',{...proof,scope:'FIXTURE',stepMapping:{1:['file-seed-composition'],2:['mock-a-to-b','actual-execution-idle','unknown-and-inspect','queued-and-rollback'],3:['mock-a-to-b','provider-cache-generations','intent-original-revision']},databaseAuthority:true,nativeUiAddressDisplay:'NOT_RUN: scope is configuration authority/client requests, not actual desktop UI',realBusiness:'NOT_RUN'});
  return record('TST-076',['FIXTURE'],assertions.slice(start),[detail,proof.frozenLog,proof.frozenVerification,proof.testSource,...proof.cases.map(row=>row.frozenCopy)]);
}

function tst077(){
  const start=assertions.length,root=join(directory,'TST-077');mkdirSync(root,{recursive:true});
  const csvPath='docs/requirements/traceability.csv',originalCsv=ref(csvPath),importedCsv=copy('TST-077/legacy-traceability.csv',csvPath),parsed=parseEvidenceCsv(readFileSync(csvPath,'utf8'));check('077:legacy48rows',48,parsed.rows.length);check('077:legacy-exact-bytes',originalCsv.sha256,importedCsv.sha256);check('077:legacy42real-not-run',42,parsed.rows.filter(row=>row.remainingRealStatus==='NOT_RUN').length);
  const artifact=json('TST-077/synthetic-original-trace.json',{scope:'LOCAL_MODEL',candidate:'1.0.0-candidate.5',synthetic:true,note:'Explicit negative-case fixture; not imported or claimed as a historical model execution.'});
  const fixtureRecord={schemaVersion:1,recordKind:'ACCEPTANCE_EXECUTION',testId:'TST-020',runId:'negative-fixture',candidate:'1.0.0-candidate.5',executedCommit,scope:['LOCAL_MODEL'],modelClass:'LOCAL_MODEL',executionKind:'MODEL_EXECUTION',status:'PASS',assertions:[{id:'fixture-only',expected:true,actual:true,status:'PASS'}],artifacts:[{...artifact,kind:'trace'}],metrics:[{name:'modelInputBytes',value:100,unit:'bytes'}]};
  const recordRef=json('TST-077/synthetic-local-candidate5-record.json',fixtureRecord);
  const base={schemaVersion:1,target:{candidate:'1.0.0-candidate.6',executedCommit,releaseScope:'DECLARED_TEST_SET'},required:[{testId:'TST-020',scope:['LIVE_MODEL'],modelClass:'LIVE_MODEL'}],records:[recordRef],legacyCsv:{original:originalCsv,imported:importedCsv,expectedRows:48}};
  const negative=[];
  const run=(name,manifest,expectedCode)=>{const manifestRef=json(`TST-077/${name}-manifest.json`,manifest),result=verifyA2ReleaseEvidence(manifest),resultRef=json(`TST-077/${name}-result.json`,result);check(`077:${name}:rejected`,false,result.eligibleForCardReview);check(`077:${name}:reason:${expectedCode}`,true,result.issues.some(item=>item.code===expectedCode));negative.push({name,expectedCode,manifest:manifestRef,result:resultRef,actualCodes:result.issues.map(item=>item.code)});};
  run('candidate5-local-to-candidate6-live',base,'VERSION_OR_COMMIT_MISMATCH');
  const sameVersion={...fixtureRecord,candidate:'1.0.0-candidate.6'};run('same-candidate-wrong-model',{...base,records:[json('TST-077/same-candidate-local-record.json',sameVersion)]},'REQUIRED_SCOPE_MISMATCH');
  const notRun={...sameVersion,scope:['LIVE_MODEL'],modelClass:'LIVE_MODEL',status:'NOT_RUN'};run('not-run-under-required-scope',{...base,records:[json('TST-077/not-run-record.json',notRun)]},'REQUIRED_RECORD_NOT_PASS');
  run('all-48-missing-records',{...base,required:parsed.rows.map(row=>({testId:row.testId,scope:['LIVE_HOST'],modelClass:'NONE'})),records:[]},'RECORD_MISSING');
  const good={...sameVersion,scope:['FIXTURE'],modelClass:'NONE',executionKind:'FIXTURE_EXECUTION'},goodRef=json('TST-077/intact-fixture-record.json',good),fixtureManifest={...base,target:{...base.target,releaseScope:'DECLARED_TEST_SET'},required:[{testId:'TST-020',scope:['FIXTURE'],modelClass:'NONE'}],records:[goodRef]};
  const positive=verifyA2ReleaseEvidence(fixtureManifest);check('077:intact-only-declared-fixture-eligible',true,positive.eligibleForCardReview);check('077:no-release-signature',false,positive.releaseApproved);check('077:historical-not-run-preserved',42,positive.legacy.remainingRealNotRun);check('077:legacy-not-current-acceptance',false,positive.legacy.countsAsCurrentAcceptance);json('TST-077/intact-fixture-result.json',positive);
  check('077:declared-card-never-release-eligible',false,positive.eligibleForReleaseReview);
  for(const releaseScope of ['CORE','AUTHORING','BUSINESS-WRITE','DATA-CUTOVER'])run(`mandatory-${releaseScope.toLowerCase()}`,{...fixtureManifest,target:{...fixtureManifest.target,releaseScope}},'RECORD_MISSING');
  const cliInput=json('TST-077/intact-cli-manifest.json',fixtureManifest),cliOutput=join(root,'actual-cli-positive-result.json'),cli=spawnSync(process.execPath,['scripts/verify-a2-release-evidence.mjs','--manifest',cliInput.path,'--output',cliOutput],{encoding:'utf8',windowsHide:true});writeFileSync(join(root,'actual-cli-positive.log'),cli.stdout+cli.stderr,{flag:'wx'});check('077:actual-delivered-cli-positive-exit',0,cli.status);check('077:actual-delivered-cli-positive-card-eligible',true,JSON.parse(readFileSync(cliOutput,'utf8')).eligibleForCardReview);
  const cliNegativeOutput=join(root,'actual-cli-negative-result.json'),cliNegative=spawnSync(process.execPath,['scripts/verify-a2-release-evidence.mjs','--manifest',join(root,'candidate5-local-to-candidate6-live-manifest.json'),'--output',cliNegativeOutput],{encoding:'utf8',windowsHide:true});writeFileSync(join(root,'actual-cli-negative.log'),cliNegative.stdout+cliNegative.stderr,{flag:'wx'});check('077:actual-delivered-cli-negative-exit',2,cliNegative.status);check('077:actual-delivered-cli-negative-release-eligible',false,JSON.parse(readFileSync(cliNegativeOutput,'utf8')).eligibleForReleaseReview);
  const missingRef={...artifact,path:join(root,'does-not-exist.json')};run('missing-original-artifact',{...fixtureManifest,records:[json('TST-077/missing-artifact-record.json',{...good,artifacts:[{...missingRef,kind:'trace'}]})]},'EVIDENCE_GAP');
  const tampered=copy('TST-077/tampered-artifact.json',artifact.path);writeFileSync(tampered.path,Buffer.concat([readFileSync(tampered.path),Buffer.from(' ')]));run('changed-original-artifact',{...fixtureManifest,records:[json('TST-077/tampered-artifact-record.json',{...good,artifacts:[{...tampered,kind:'trace'}]})]},'EVIDENCE_INVALID');
  run('bytes-labelled-token',{...fixtureManifest,records:[json('TST-077/bytes-as-token-record.json',{...good,metrics:[{name:'modelInputTokens',value:100,unit:'bytes'}]})]},'TOKEN_UNIT_MISMATCH');
  run('syntax-as-host',{...fixtureManifest,required:[{testId:'TST-020',scope:['LIVE_HOST'],modelClass:'NONE'}],records:[json('TST-077/static-as-host-record.json',{...good,scope:['LIVE_HOST'],executionKind:'STATIC_CHECK'})]},'EXECUTION_SCOPE_MISMATCH');
  const alteredCsv=copy('TST-077/changed-legacy.csv',csvPath);writeFileSync(alteredCsv.path,readFileSync(alteredCsv.path,'utf8').replace('NOT_RUN','PASS'));run('altered-old-csv',{...fixtureManifest,legacyCsv:{...base.legacyCsv,imported:alteredCsv}},'EVIDENCE_INVALID');
  const bothChanged=readFileSync(csvPath,'utf8').replace('NOT_RUN','PASS'),bothOriginal=join(root,'both-changed-original.csv'),bothImported=join(root,'both-changed-imported.csv');writeFileSync(bothOriginal,bothChanged,{flag:'wx'});writeFileSync(bothImported,bothChanged,{flag:'wx'});run('both-original-and-import-rehashed',{...fixtureManifest,legacyCsv:{original:ref(bothOriginal),imported:ref(bothImported),expectedRows:48}},'LEGACY_BASELINE_MISMATCH');
  run('wrong-expected-row-count',{...fixtureManifest,legacyCsv:{...base.legacyCsv,expectedRows:47}},'LEGACY_CSV_INVALID');
  const wrongColumns=join(root,'bad-columns.csv');writeFileSync(wrongColumns,readFileSync(csvPath,'utf8').replace('remainingRealStatus','remainingRealRenamed'),{flag:'wx'});run('wrong-legacy-columns-rehashed',{...fixtureManifest,legacyCsv:{original:ref(wrongColumns),imported:ref(wrongColumns),expectedRows:48}},'LEGACY_CSV_INVALID');
  const baseline=loadFrozenBaseline();check('077:frozen-derived-observation48-not-run',48,baseline.derivedCurrentNotRun);check('077:frozen-original-real42-not-run',42,baseline.remainingRealNotRun);
  const gitBlob=spawnSync('git',['show','HEAD:docs/requirements/traceability.csv'],{windowsHide:true});check('077:actual-git-blob-read-exit',0,gitBlob.status);const lfOriginal=join(root,'frozen-git-original.csv'),lfImported=join(root,'frozen-git-import.csv');writeFileSync(lfOriginal,gitBlob.stdout,{flag:'wx'});writeFileSync(lfImported,gitBlob.stdout,{flag:'wx'});const lfBaseline=loadFrozenBaseline(lfOriginal);check('077:LF-original-audited-hash','5885e2375bc5711a36d90a635647966b27b850ebfe8b7ff0e95a7a342575c779',lfBaseline.original.sha256);check('077:LF-original-serialization','LF_git_blob',lfBaseline.serialization);const lfManifest={...fixtureManifest,legacyCsv:{original:ref(lfOriginal),imported:ref(lfImported),expectedRows:48}},lfManifestRef=json('TST-077/lf-import-manifest.json',lfManifest),lfResult=verifyA2ReleaseEvidence(lfManifest),lfResultRef=json('TST-077/lf-import-result.json',lfResult);check('077:LF-byte-exact-import-qualified',true,lfResult.eligibleForCardReview);check('077:LF-original-not-normalized',ref(lfOriginal).sha256,ref(lfImported).sha256);
  check('077:original-input-still-exact',originalCsv.sha256,ref(csvPath).sha256);
  const gateTests=spawnSync(process.execPath,['--test','test/acceptance/release-evidence-gate.test.ts'],{encoding:'utf8',windowsHide:true});writeFileSync(join(root,'gate-tests.txt'),gateTests.stdout+gateTests.stderr,{flag:'wx'});check('077:delivered-gate-tests-exit',0,gateTests.status);check('077:gate-test-count',true,/tests 12/.test(gateTests.stdout)&&/pass 12/.test(gateTests.stdout)&&/fail 0/.test(gateTests.stdout));
  const scopesById={'TST-073':'FIXTURE','TST-075':'FIXTURE+CLOCK_CONTROL','TST-076':'FIXTURE','TST-077':'DOC+FIXTURE'},traceRows=Array.from({length:80},(_,index)=>{const id=`TST-${String(index+1).padStart(3,'0')}`,scope=scopesById[id],reuse=['TST-075','TST-076'].includes(id);return [id,`REQ-${id.slice(4)}`,candidate,executedCommit,scope??'',scope?'PASS':'NOT_RUN',scope?runId:'',scope?executedCommit:'',scope?join(directory,id,'result.json'):'',reuse?'FROZEN_PRODUCT_EVIDENCE_REVALIDATION':scope?'CURRENT_ISOLATED_FIXTURE_EXECUTION':'',reuse?'NOT_RECORDED: original 08:24 uncommitted worktree':''];});
  const currentCsv=join(root,'current-card-traceability.csv');writeFileSync(currentCsv,['testId,requirementId,targetCandidate,targetCommit,scope,status,runId,executedCommit,resultPath,executionMode,originalExecutionCommit',...traceRows.map(row=>row.map(value=>'"'+String(value).replaceAll('"','""')+'"').join(','))].join('\r\n')+'\r\n',{flag:'wx'});const trace=parseEvidenceCsv(readFileSync(currentCsv,'utf8'));check('077:current-trace80cards',80,trace.rows.length);check('077:only-four-complete-card-scopes',4,trace.rows.filter(row=>row.status==='PASS').length);check('077:remaining-current76-not-run',76,trace.rows.filter(row=>row.status==='NOT_RUN').length);
  const detail=json('TST-077/details.json',{legacyOriginal:originalCsv,legacyImported:importedCsv,frozenBaseline:baseline,gitBlobSerialization:{baseline:lfBaseline,original:ref(lfOriginal),imported:ref(lfImported),manifest:lfManifestRef,result:lfResultRef},currentTraceability:ref(currentCsv),legacyRows:48,remainingRealNotRun:42,originalValuesPreserved:true,negativeCases:negative,actualCli:{positiveInput:cliInput,positiveOutput:ref(cliOutput),negativeOutput:ref(cliNegativeOutput),positiveExit:cli.status,negativeExit:cliNegative.status},deliveredExecutable:ref('scripts/verify-a2-release-evidence.mjs'),narrowTests:ref('test/acceptance/release-evidence-gate.test.ts'),syntaxAndUiSeparated:true,modelInputUnitSeparated:true,syntheticCaseRecords:true,eligibleScope:'DOC+FIXTURE verification of an offline review aid; no native/model execution claims',allReleaseGates:'NOT_ACCEPTED',humanReleaseApproval:false});
  const row={schemaVersion:1,recordKind:'ACCEPTANCE_EXECUTION',testId:'TST-077',runId,candidate,executedCommit,scope:['DOC','FIXTURE'],modelClass:'NONE',executionKind:'FIXTURE_EXECUTION',status:'PASS',assertions:assertions.slice(start),artifacts:[{...detail,kind:'result'},{...ref(currentCsv),kind:'trace'},{...importedCsv,kind:'input'},{...ref(join(root,'gate-tests.txt')),kind:'log'},{...ref(cliOutput),kind:'result'},{...ref(cliNegativeOutput),kind:'result'}],metrics:[]};
  // DOC means offline source/legacy review as part of a fixture execution; it is not a native execution.
  const result=json('TST-077/result.json',row);records.push(result);return result;
}

try{
  await tst073();tst075();tst076();tst077();
  check('production-source-unchanged',productionHashes,Object.fromEntries(productionPaths.map(path=>[path,ref(path).sha256])));
  const packedInputAfter=inputSnapshot();check('candidate10:source-inputs-after',[],packedInputAfter.filter(row=>row.expectedSha256!==row.actualSha256));check('candidate10:source-inputs-no-change-during-run',packedInputBefore,packedInputAfter);const sourceVerification=json('candidate10-source-verification.json',{candidate,candidateManifest:provenance.candidateManifest,checked:143,before:packedInputBefore,after:packedInputAfter,mismatches:[],candidateRebuilt:false,newFilesSeparatelyBound:[ref(fileURLToPath(import.meta.url)),ref('scripts/verify-a2-release-evidence.mjs'),ref('test/acceptance/release-evidence-gate.test.ts')]});
  const typecheckStartedAt=new Date().toISOString(),typecheck=spawnSync(process.execPath,['node_modules/typescript/bin/tsc','--noEmit'],{encoding:'utf8',windowsHide:true});writeFileSync(join(directory,'typecheck.log'),typecheck.stdout+typecheck.stderr,{flag:'wx'});check('final-typecheck-exit',0,typecheck.status);const typecheckRef=json('typecheck-run.json',{command:[process.execPath,'node_modules/typescript/bin/tsc','--noEmit'],startedAt:typecheckStartedAt,finishedAt:new Date().toISOString(),exitCode:typecheck.status,status:'PASS',log:ref(join(directory,'typecheck.log')),testSource:ref('test/acceptance/release-evidence-gate.test.ts')});
  const required=records.map(reference=>{const row=JSON.parse(readFileSync(reference.path,'utf8'));return {testId:row.testId,scope:row.scope,modelClass:row.modelClass};}),baseline=loadFrozenBaseline(),cardManifest={schemaVersion:1,target:{candidate,executedCommit,releaseScope:'DECLARED_TEST_SET'},required,records,legacyCsv:{original:baseline.original,imported:ref(join(directory,'TST-077','legacy-traceability.csv')),expectedRows:48}},cardManifestRef=json('card-integrity-manifest.json',cardManifest),cardReview=verifyA2ReleaseEvidence(cardManifest);check('current-four-card-integrity',true,cardReview.eligibleForCardReview);check('current-four-cards-do-not-release',false,cardReview.eligibleForReleaseReview);const cardReviewRef=json('card-integrity-result.json',cardReview);
  const gates=[];for(const releaseScope of ['CORE','AUTHORING','BUSINESS-WRITE','DATA-CUTOVER']){const manifestRef=json(`release-sets/${releaseScope.toLowerCase()}-manifest.json`,{...cardManifest,target:{...cardManifest.target,releaseScope}}),result=verifyA2ReleaseEvidence({...cardManifest,target:{...cardManifest.target,releaseScope}});check(`${releaseScope}:incomplete-release-blocked`,false,result.eligibleForReleaseReview);gates.push({releaseScope,status:'NOT_ACCEPTED',mandatoryTestCount:result.releasePolicy.mandatoryTestCount,manifest:manifestRef,result:json(`release-sets/${releaseScope.toLowerCase()}-result.json`,result)});}
  const result=json('summary.json',{...provenance,finishedAt:new Date().toISOString(),status:'PASS',productionHashes,sourceVerification,typecheck:typecheckRef,records,totalAssertions:assertions.length,assertions,cardIntegrity:{manifest:cardManifestRef,result:cardReviewRef},releaseSets:gates,scopeByCard:{'TST-073':'FIXTURE','TST-075':'FIXTURE+CLOCK_CONTROL','TST-076':'FIXTURE','TST-077':'DOC+FIXTURE'},liveHost:'NOT_RUN',liveModel:'NOT_RUN',realBusiness:'NOT_RUN',dataCutover:'NOT_RUN',allReleaseGates:'NOT_ACCEPTED',reviewer:null});
  console.log(JSON.stringify({runId,directory,summary:result,cardCount:4,assertions:assertions.length,scope:'Offline maintenance fixtures and frozen source-identical test revalidation only',releaseApproved:false},null,2));
}catch(error){json('failure.json',{...provenance,finishedAt:new Date().toISOString(),status:'FAIL',error:{message:error.message,stack:error.stack},completedAssertions:assertions,partialRecords:records});throw error;}
