import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {mkdirSync,mkdtempSync,readFileSync,rmSync,writeFileSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
// The delivered artifact is an executable MJS CLI, outside the TypeScript compilation tree.
// Keep this test's inspected output contract explicit instead of suppressing strict typing.
interface GateReview {eligibleForCardReview:boolean;eligibleForReleaseReview:boolean;releaseApproved:boolean;classification:string;fullReleaseGatesEvaluated:boolean;namedReleaseScopeEvaluated:string|null;verifiedFiles:unknown[];issues:{code:string}[];requiredResults:{testId:string;scope:string[];status:string}[];legacy:{remainingRealNotRun:number;countsAsCurrentAcceptance:boolean}|null}
const gateModule=await import(new URL('../../scripts/verify-a2-release-evidence.mjs',import.meta.url).href);
const verifyA2ReleaseEvidence:(manifest:unknown)=>GateReview=gateModule.verifyA2ReleaseEvidence;
const parseEvidenceCsv:(source:string)=>{columns:string[];rows:Record<string,string>[]}=gateModule.parseEvidenceCsv;
interface PolicyCard {testId:string;scope:string[];modelClass:string}
const loadA2ReleasePolicy:()=>{minimum:Record<string,PolicyCard>;requiredByRelease:Record<string,PolicyCard[]>}=gateModule.loadA2ReleasePolicy;
const loadFrozenBaseline:(path?:string)=>{original:{path:string;sha256:string;bytes:number};serialization:string;derived:{path:string;sha256:string;bytes:number};originalRows:number;remainingRealNotRun:number;derivedCurrentNotRun:number}=gateModule.loadFrozenBaseline;

const commit='e53fd18a0bedb011db69dd2b87e159c5bb67cf75';
function fixture(){
  const directory=mkdtempSync(join(tmpdir(),'a2-release-evidence-'));mkdirSync(join(directory,'records'));
  const ref=(name:string,value:unknown)=>{const path=join(directory,name);writeFileSync(path,typeof value==='string'||Buffer.isBuffer(value)?value:JSON.stringify(value));const bytes=readFileSync(path);return {path,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length};};
  const artifact={...ref('log.txt','actual fixture execution trace'),kind:'log'};
  const record={schemaVersion:1,recordKind:'ACCEPTANCE_EXECUTION',testId:'TST-077',runId:'fixture',candidate:'1.0.0-candidate.6',executedCommit:commit,scope:['FIXTURE'],modelClass:'NONE',executionKind:'FIXTURE_EXECUTION',status:'PASS',assertions:[{id:'fixture',expected:true,actual:true,status:'PASS'}],artifacts:[artifact],metrics:[{name:'queryCount',value:0,unit:'count'}]};
  const manifest=(row:unknown=record)=>({schemaVersion:1,target:{candidate:'1.0.0-candidate.6',executedCommit:commit,releaseScope:'DECLARED_TEST_SET'},required:[{testId:'TST-077',scope:['FIXTURE'],modelClass:'NONE'}],records:[ref('records/run.json',row)]});
  return {directory,ref,record,artifact,manifest,close(){rmSync(directory,{recursive:true,force:true});}};
}
test('evidence gate verifies original identity and bytes but never grants release approval',()=>{const f=fixture();try{const result=verifyA2ReleaseEvidence(f.manifest());assert.equal(result.eligibleForCardReview,true);assert.equal(result.releaseApproved,false);assert.equal(result.verifiedFiles.length,2);}finally{f.close();}});
test('named release scopes force frozen A2 mandatory cards instead of trusting a caller single-card plan',()=>{const f=fixture();try{const policy=loadA2ReleasePolicy();assert.equal(Object.keys(policy.minimum).length,80);assert.deepEqual(Object.fromEntries(Object.entries(policy.requiredByRelease).map(([name,rows])=>[name,rows.length])),{CORE:51,AUTHORING:78,'BUSINESS-WRITE':52,'DATA-CUTOVER':53});assert.deepEqual(policy.minimum['TST-058'].scope,['SOURCE_EXEC','LIVE_MODEL']);assert.deepEqual(policy.minimum['TST-080'].scope,['DOC','LIVE_HOST']);for(const releaseScope of ['CORE','AUTHORING','BUSINESS-WRITE','DATA-CUTOVER']){const manifest=f.manifest();manifest.target.releaseScope=releaseScope;const result=verifyA2ReleaseEvidence(manifest);assert.equal(result.eligibleForReleaseReview,false);assert.equal(result.releaseApproved,false);assert.equal(result.namedReleaseScopeEvaluated,releaseScope);assert.ok(result.issues.some(item=>item.code==='RECORD_MISSING'));assert.ok(result.requiredResults.some(item=>item.testId==='TST-080'&&item.scope.includes('LIVE_HOST')));}}finally{f.close();}});
test('candidate5 local-model evidence cannot qualify candidate6 external-model scope',()=>{const f=fixture();try{const local={...f.record,candidate:'1.0.0-candidate.5',scope:['LOCAL_MODEL'],modelClass:'LOCAL_MODEL',executionKind:'MODEL_EXECUTION'};const manifest=f.manifest(local);manifest.required=[{testId:'TST-077',scope:['LIVE_MODEL'],modelClass:'LIVE_MODEL'}];const result=verifyA2ReleaseEvidence(manifest);assert.equal(result.eligibleForCardReview,false);assert.ok(result.issues.some(item=>item.code==='VERSION_OR_COMMIT_MISMATCH'));local.candidate='1.0.0-candidate.6';const sameVersion=verifyA2ReleaseEvidence({...manifest,records:[f.ref('records/local.json',local)]});assert.ok(sameVersion.issues.some(item=>item.code==='REQUIRED_SCOPE_MISMATCH'));}finally{f.close();}});
test('NOT_RUN, missing record, unknown status and a non-PASS assertion cannot be hidden by a top-level PASS',()=>{const f=fixture();try{for(const row of [{...f.record,status:'NOT_RUN'},{...f.record,status:'INVENTED'},{...f.record,assertions:[{id:'unfinished',expected:true,actual:null,status:'NOT_RUN'}]}])assert.equal(verifyA2ReleaseEvidence(f.manifest(row)).eligibleForCardReview,false);assert.equal(verifyA2ReleaseEvidence({...f.manifest(),records:[]}).eligibleForCardReview,false);assert.equal(verifyA2ReleaseEvidence({...f.manifest(),overallStatus:'PASS'}).eligibleForCardReview,false);}finally{f.close();}});
test('missing or changed artifact bytes are evidence gaps even while a record says PASS',()=>{const f=fixture();try{const manifest=f.manifest();writeFileSync(f.artifact.path,'changed');let result=verifyA2ReleaseEvidence(manifest);assert.ok(result.issues.some(item=>item.code==='EVIDENCE_INVALID'));rmSync(f.artifact.path);result=verifyA2ReleaseEvidence(manifest);assert.ok(result.issues.some(item=>item.code==='EVIDENCE_GAP'));}finally{f.close();}});
test('static syntax checks cannot claim Host UI execution and UTF8 bytes cannot be labelled token counts',()=>{const f=fixture();try{const staticRow={...f.record,scope:['LIVE_HOST'],executionKind:'STATIC_CHECK'};const manifest=f.manifest(staticRow);manifest.required=[{testId:'TST-077',scope:['LIVE_HOST'],modelClass:'NONE'}];assert.ok(verifyA2ReleaseEvidence(manifest).issues.some(item=>item.code==='EXECUTION_SCOPE_MISMATCH'));const bytes={...f.record,metrics:[{name:'modelInputTokens',value:128,unit:'bytes'}]};assert.ok(verifyA2ReleaseEvidence(f.manifest(bytes)).issues.some(item=>item.code==='TOKEN_UNIT_MISMATCH'));}finally{f.close();}});
test('legacy CSV is anchored to both frozen 48-row inputs and retains NOT_RUN without converting history',()=>{const f=fixture();try{const baseline=loadFrozenBaseline(),csv=readFileSync(baseline.original.path,'utf8');assert.equal(baseline.originalRows,48);assert.equal(baseline.remainingRealNotRun,42);assert.equal(baseline.derivedCurrentNotRun,48);const manifest={...f.manifest(),legacyCsv:{original:f.ref('original.csv',csv),imported:f.ref('imported.csv',csv),expectedRows:48}};const result=verifyA2ReleaseEvidence(manifest);assert.equal(result.legacy?.remainingRealNotRun,42);assert.equal(result.legacy?.countsAsCurrentAcceptance,false);assert.equal(result.eligibleForCardReview,true);writeFileSync(manifest.legacyCsv.imported.path,csv.replace('NOT_RUN','PASS'));assert.equal(verifyA2ReleaseEvidence(manifest).eligibleForCardReview,false);assert.deepEqual(parseEvidenceCsv('a,b\r\n"x,y","z ""q"""\r\n').rows,[{a:'x,y',b:'z "q"'}]);assert.throws(()=>parseEvidenceCsv('a,b\n1\n'),/LEGACY_CSV_INVALID/);}finally{f.close();}});
test('malformed required entries and unknown scope are structured blockers rather than crashes',()=>{const f=fixture();try{for(const required of [[null],['TST-077'],[{testId:'TST-077',scope:['INVENTED'],modelClass:'NONE'}],[{testId:'TST-077',scope:['LIVE_MODEL'],modelClass:'NONE'}]]){const result=verifyA2ReleaseEvidence({...f.manifest(),required});assert.equal(result.eligibleForReleaseReview,false);assert.ok(result.issues.some(item=>item.code==='REQUIRED_SET_INVALID'));}}finally{f.close();}});
test('conflicting record identity and competing target FAIL or NOT_RUN cannot be hidden by a PASS',()=>{const f=fixture();try{for(const status of ['FAIL','NOT_RUN']){const manifest=f.manifest();const other=f.ref('records/other.json',{...f.record,status});let result=verifyA2ReleaseEvidence({...manifest,records:[...manifest.records,other]});assert.ok(result.issues.some(item=>item.code==='RECORD_IDENTITY_CONFLICT'));assert.equal(result.eligibleForCardReview,false);const distinct=f.ref('records/new-run.json',{...f.record,runId:'second-run',status});result=verifyA2ReleaseEvidence({...manifest,records:[...manifest.records,distinct]});assert.ok(result.issues.some(item=>item.code==='REQUIRED_RECORD_NOT_PASS'));assert.equal(result.eligibleForCardReview,false);}}finally{f.close();}});
test('complete named-scope metadata can qualify for review while a removed mandatory Host scope blocks',()=>{const f=fixture();try{const policy=loadA2ReleasePolicy(),baseline=loadFrozenBaseline();for(const [releaseScope,required]of Object.entries(policy.requiredByRelease)){const records=required.map(item=>{const executionKind=item.scope.includes('LIVE_MODEL')?'MODEL_EXECUTION':item.scope.includes('REAL_BUSINESS')?'REAL_BUSINESS_EXECUTION':item.scope.includes('DATA_CUTOVER')?'CUTOVER_EXECUTION':item.scope.includes('LIVE_HOST')?'HOST_EXECUTION':item.scope.includes('SOURCE_EXEC')?'SOURCE_EXECUTION':'FIXTURE_EXECUTION';return f.ref(`records/${releaseScope}-${item.testId}.json`,{...f.record,testId:item.testId,runId:'synthetic-metadata-fixture-only',scope:item.scope,modelClass:item.modelClass,executionKind,assertions:[{id:'metadata-only',expected:'synthetic qualification fixture, no actual Host/model/business claim',actual:'synthetic qualification fixture, no actual Host/model/business claim',status:'PASS'}]});});const manifest={...f.manifest(),target:{candidate:f.record.candidate,executedCommit:commit,releaseScope},required:[required[0]],records,legacyCsv:{original:baseline.original,imported:baseline.original,expectedRows:48}};const result=verifyA2ReleaseEvidence(manifest);assert.equal(result.eligibleForReleaseReview,true);assert.equal(result.releaseApproved,false);const weak=f.ref(`records/${releaseScope}-weakened-host.json`,{...f.record,testId:'TST-001',scope:['FIXTURE']});const rejected=verifyA2ReleaseEvidence({...manifest,records:[weak,...records.slice(1)]});assert.equal(rejected.eligibleForReleaseReview,false);assert.ok(rejected.requiredResults.some(item=>item.testId==='TST-001'&&item.status==='BLOCKED'));}}finally{f.close();}});
test('rehashed alterations to both historical CSV copies, bad columns and wrong row counts cannot replace the frozen baseline',()=>{const f=fixture();try{const baseline=loadFrozenBaseline(),csv=readFileSync(baseline.original.path,'utf8'),changed=csv.replace('NOT_RUN','PASS');for(const source of [changed,csv.replace('remainingRealStatus','renamedRemainingStatus')]){const manifest={...f.manifest(),legacyCsv:{original:f.ref('rewritten-original.csv',source),imported:f.ref('rewritten-imported.csv',source),expectedRows:48}};const result=verifyA2ReleaseEvidence(manifest);assert.equal(result.eligibleForCardReview,false);assert.ok(result.issues.some(item=>item.code==='LEGACY_BASELINE_MISMATCH'));}const wrongCount=verifyA2ReleaseEvidence({...f.manifest(),legacyCsv:{original:baseline.original,imported:baseline.original,expectedRows:47}});assert.ok(wrongCount.issues.some(item=>item.code==='LEGACY_CSV_INVALID'));}finally{f.close();}});
test('audited Git LF bytes and current Windows CRLF bytes import without normalization or cross-serialization substitution',()=>{const f=fixture();try{const blob=spawnSync('git',['show','HEAD:docs/requirements/traceability.csv'],{windowsHide:true});assert.equal(blob.status,0);const gitOriginal=f.ref('git-original.csv',blob.stdout),gitImported=f.ref('git-imported.csv',blob.stdout);assert.equal(gitOriginal.sha256,'5885e2375bc5711a36d90a635647966b27b850ebfe8b7ff0e95a7a342575c779');const selected=loadFrozenBaseline(gitOriginal.path);assert.equal(selected.serialization,'LF_git_blob');const lf=verifyA2ReleaseEvidence({...f.manifest(),legacyCsv:{original:gitOriginal,imported:gitImported,expectedRows:48}});assert.equal(lf.eligibleForCardReview,true);const current=loadFrozenBaseline(),workOriginal=f.ref('work-original.csv',readFileSync(current.original.path)),workImported=f.ref('work-imported.csv',readFileSync(current.original.path));assert.equal(verifyA2ReleaseEvidence({...f.manifest(),legacyCsv:{original:workOriginal,imported:workImported,expectedRows:48}}).eligibleForCardReview,true);if(workOriginal.sha256!==gitOriginal.sha256)assert.ok(verifyA2ReleaseEvidence({...f.manifest(),legacyCsv:{original:gitOriginal,imported:workImported,expectedRows:48}}).issues.some(item=>item.code==='LEGACY_CSV_CHANGED'));}finally{f.close();}});
