import React,{useState} from 'react';
import {templates,columns,fields,format} from './data';
import type {Dataset,Product,TemplateId} from './data';
import './style.css';
const value=(p:Product,k:string)=>p[k as keyof Product];
export function Workbench({id,dataset,loading=false,error,onRefresh,demo=false}:{id:TemplateId;dataset:Dataset;loading?:boolean;error?:string;onRefresh?:()=>void;demo?:boolean}) {
 const [query,setQuery]=useState(''),[sort,setSort]=useState(id==='profit'?'profit':'default'),[filter,setFilter]=useState('all'),[page,setPage]=useState(0),[detail,setDetail]=useState<Product|null>(null),[picked,setPicked]=useState<string[]>([]),[view,setView]=useState('grid');
 const template=templates.find(t=>t[0]===id)!; const matches=dataset.items.filter(p=>`${p.name} ${p.sku} ${p.spec}`.toLowerCase().includes(query.toLowerCase())).filter(p=>filter==='all'||(filter==='campaign'?!!p.campaign&&p.campaign!=='未参加':(p.margin??Infinity)<15));
 const rows=[...matches].sort((a,b)=>sort==='default'?0:Number(value(b,sort)??-Infinity)-Number(value(a,sort)??-Infinity)); const pages=Math.max(1,Math.ceil(rows.length/8)),current=Math.min(page,pages-1),visible=rows.slice(current*8,current*8+8);
 const sum=(key:string)=>rows.reduce((n,p)=>n+(typeof value(p,key)==='number'?Number(value(p,key)):0),0);
 const metric=(key:string)=>rows.some(p=>typeof value(p,key)==='number')?format(key,sum(key),dataset.currency):'—';
 const stats=id==='collection'?[['已读取商品',String(dataset.items.length)],['SKU 记录',String(new Set(dataset.items.map(p=>p.sku)).size)],['来源',String(new Set(dataset.items.map(p=>p.source).filter(Boolean)).size)]]:id==='campaigns'?[['当前候选',String(rows.length)],['活动预估利润率 > 0',String(rows.filter(p=>(p.activityMargin??0)>0).length)],['活动预估利润率 ≤ 0',String(rows.filter(p=>p.activityMargin!==undefined&&p.activityMargin<=0).length)]]:[['筛选后销量',metric('sales')],['筛选后浏览量',metric('views')],['筛选后贡献利润',metric('profit')]];
 const toggle=(p:Product)=>setPicked(a=>a.includes(p.id)?a.filter(x=>x!==p.id):[...a,p.id]);
 return <main className="workbench" data-app-component data-ready={!loading&&!error}>
  <header className="page-head"><div><div className="eyebrow">COMMERCE / {id.toUpperCase()} <span>{demo?'示例数据':'已绑定数据'}</span></div><h1>{template[1]}</h1><p>{template[2]}</p></div><button className="refresh" onClick={onRefresh} disabled={loading}>↻ {loading?'读取中':'刷新数据'}</button></header>
  <div className="period"><span>◷ {dataset.period||'未提供统计时间'}</span>{dataset.comparisonPeriod&&['pricing','review'].includes(id)&&<span>对比：{dataset.comparisonPeriod}</span>}<span>{dataset.currency} · 已读取 {dataset.items.length} / {dataset.total} 条</span></div>
  <section className="metrics">{stats.map(([label,number],i)=><article key={label}><span>{label}</span><strong>{number}</strong><small>{id==='collection'?'当前采集结果':i===2?'按已读取且匹配的商品汇总':'当前筛选范围'}</small></article>)}</section>
  {['profit','traffic','pricing','review'].includes(id)&&<section className="insight"><div><div className="eyebrow">{id==='profit'?'PROFIT CONTRIBUTION':id==='traffic'?'ATTENTION → ORDERS':'PERIOD COMPARISON'}</div><h2>{id==='profit'?'利润贡献 · 商品分布':id==='traffic'?'浏览与订单 · 商品对照':id==='pricing'?'调整前后 · 价格对照':'活动前后 · 利润对照'}</h2><p>{id==='traffic'?'条形为浏览量，右侧为订单数。':id==='profit'?'展示当前排序的前 5 件商品。':'灰色为对比期，绿色为当前期。'}</p></div><div className="bars">{rows.slice(0,5).map(p=>{const key=id==='traffic'?'views':id==='pricing'?'price':'profit',before=id==='pricing'?'beforePrice':'beforeProfit';const max=Math.max(1,...rows.slice(0,5).flatMap(r=>[Number(value(r,key)??0),Number(value(r,before)??0)]));return <button className="bar-row" key={p.id} onClick={()=>setDetail(p)}><span>{p.name}</span><span className="bar-track">{['pricing','review'].includes(id)&&<i className="bar-before" style={{width:`${Math.max(0,Number(value(p,before)??0))/max*100}%`}}/>}<i style={{width:`${Math.max(0,Number(value(p,key)??0))/max*100}%`}}/></span><b>{format(id==='traffic'?'orders':key,value(p,id==='traffic'?'orders':key),dataset.currency)}</b></button>;})}</div></section>}
  {id==='campaigns'&&<section className="campaign-banner"><span className="campaign-symbol">%</span><div><h2>活动商品候选清单</h2><p>查看活动价、预估利润率与库存；勾选商品进行本地比较。</p></div><span className="badge">仅评估 · 未提交报名</span></section>}
  <section className="data-panel"><div className="toolbar"><label className="search"><span>⌕</span><input aria-label="搜索商品" placeholder="搜索商品名称、SKU、规格" value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label>{id!=='collection'&&<select aria-label="筛选商品" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0);}}><option value="all">全部商品</option><option value="campaign">参加促销</option><option value="low">利润率低于 15%</option></select>}<select aria-label="排序" value={sort} onChange={e=>{setSort(e.target.value);setPage(0);}}><option value="default">默认排序</option>{columns[id].filter(k=>fields[k]?.type||['views','sales','orders','stock'].includes(k)).map(k=><option key={k} value={k}>{fields[k].label} ↓</option>)}</select>{id==='collection'&&<button onClick={()=>setView(v=>v==='grid'?'table':'grid')}>{view==='grid'?'列表视图':'卡片视图'}</button>}</div>
   {error?<div className="empty" role="alert">{error}<button onClick={onRefresh}>重新读取</button></div>:loading?<div className="empty">正在读取数据…</div>:!rows.length?<div className="empty">没有匹配的商品<button onClick={()=>{setQuery('');setFilter('all');}}>清除筛选</button></div>:id==='collection'&&view==='grid'?<div className="collection-grid">{visible.map(p=><button className="product-card" key={p.id} onClick={()=>setDetail(p)}><ProductImage p={p}/><div className="card-body"><small>{p.source||'来源未提供'}</small><h3>{p.name}</h3><p>{p.spec}</p><div className="card-end"><code>{p.sku}</code><strong>{format('price',p.price,dataset.currency)}</strong></div></div></button>)}</div>:<div className="table-scroll"><table><thead><tr>{id==='campaigns'&&<th>选择</th>}<th>商品 / SKU</th>{columns[id].map(k=><th key={k}>{id==='collection'&&k==='price'?'采集价格':fields[k].label}</th>)}<th/></tr></thead><tbody>{visible.map((p,i)=><tr key={p.id}>{id==='campaigns'&&<td><input type="checkbox" aria-label={`选择 ${p.sku}`} checked={picked.includes(p.id)} onChange={()=>toggle(p)}/></td>}<td><button className="product-cell" onClick={()=>setDetail(p)}>{id==='profit'?<span className="rank">{current*8+i+1}</span>:<ProductImage p={p}/>}<span><b>{p.name}</b><small>{p.sku} · {p.spec}</small></span></button></td>{columns[id].map(k=><td key={k} className={`${fields[k]?.type==='percent'?'accent':''} ${typeof value(p,k)==='number'&&Number(value(p,k))<0?'negative':''}`}>{k==='campaign'?<span className="badge">{p.campaign||'—'}</span>:format(k,value(p,k),dataset.currency)}</td>)}<td><button className="detail-button" onClick={()=>setDetail(p)}>详情 ↗</button></td></tr>)}</tbody></table></div>}
   <footer className="pagination"><span>{id==='campaigns'?`已选 ${picked.length} 件 · `:''}筛选 {rows.length} 条{dataset.total>dataset.items.length?'（仅已读取数据）':''}</span><div><button aria-label="上一页" disabled={current===0} onClick={()=>setPage(current-1)}>←</button><span>{current+1} / {pages}</span><button aria-label="下一页" disabled={current+1>=pages} onClick={()=>setPage(current+1)}>→</button></div></footer>
  </section><p className="footnote">{id==='collection'?'采集商品信息按 SKU 展示，价格保留原始币种口径。':dataset.note||'未提供利润口径；缺失字段显示为 —。'}{demo?' · 本页为模板交互预览，无真实业务写入。':''}</p>
  {detail&&<div className="dialog-backdrop" onClick={()=>setDetail(null)}><section role="dialog" aria-modal="true" aria-label="商品详情" className="detail-panel" onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setDetail(null);}}><button className="close" autoFocus onClick={()=>setDetail(null)}>关闭 ×</button><div className="eyebrow">PRODUCT DETAILS</div><h2>{detail.name}</h2><p>{detail.sku}</p><ProductImage p={detail}/><dl>{['spec',...columns[id]].filter((k,i,a)=>a.indexOf(k)===i).map(k=><div key={k}><dt>{id==='collection'&&k==='price'?'采集价格':fields[k].label}</dt><dd>{format(k,value(detail,k),dataset.currency)}</dd></div>)}</dl></section></div>}
 </main>;
}
function ProductImage({p}:{p:Product}){const [failed,setFailed]=useState(false);return <span className="product-image">{p.image&&!failed?<img src={p.image} alt={p.name} loading="lazy" decoding="async" onError={()=>setFailed(true)}/>:<span className="image-placeholder">◇<small>暂无图片</small></span>}</span>;}
