import React,{useEffect,useRef,useState} from 'react';
import type {AppsComponent,AppsView} from '../../app-presentation/src/types.ts';
import type {JsonValue} from '../../app-contracts/src/index.ts';
import {appsResource} from './api.ts';
import {PresentationRecovery,usePresentationRecovery} from './presentation-recovery.tsx';
import {AppsIcon,appsDisplayTime} from './ui.tsx';
type ComponentSummary=Pick<AppsComponent,'componentId'|'title'|'revision'|'savedAt'>;
interface SavedAsset {assetId:string;kind:'entry'|'template';title:string;componentId?:string;binding?:JsonValue}
/** The existing shared Presentation library is authoritative; this view owns no asset copies. */
export function AppsLibrary({sessionId,onOpenView,refreshKey=0}:{sessionId?:string;onOpenView?:(view:AppsView)=>void;refreshKey?:number}) {
  const recovery=usePresentationRecovery();
  const [components,setComponents]=useState<ComponentSummary[]>([]),[assets,setAssets]=useState<SavedAsset[]>([]),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[loading,setLoading]=useState(true),[readFailed,setReadFailed]=useState(false),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),[renaming,setRenaming]=useState<string>(),[name,setName]=useState('');const inFlight=useRef(false),owner=useRef(sessionId);owner.current=sessionId;
  useEffect(()=>{const controller=new AbortController();setLoading(true);setReadFailed(false);appsResource<{components:ComponentSummary[];assets:SavedAsset[]}>('saved',{},controller.signal).then(value=>{if(!controller.signal.aborted){setComponents(value.components??[]);setAssets((value.assets??[]).filter(asset=>!asset.componentId||!(value.components??[]).some(component=>component.componentId===asset.componentId)));}}).catch(error=>{if(!controller.signal.aborted){setReadFailed(true);setNotice(error instanceof Error?error.message:String(error));}}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[revision,refreshKey]);
  useEffect(()=>{const refresh=()=>setRevision(value=>value+1);window.addEventListener('apps-library-changed',refresh);return()=>window.removeEventListener('apps-library-changed',refresh);},[]);
  const perform=async<T,>(capability:string,input:JsonValue,next?:(value:T)=>void)=>{if(!sessionId||inFlight.current||recovery.pending)return;const target=sessionId;inFlight.current=true;setBusy(true);setNotice('');try{await recovery.run<T>(target,capability,input,value=>{if(owner.current===target){next?.(value);}});}catch(error){if(owner.current===target)setNotice(error instanceof Error?error.message:String(error));}finally{inFlight.current=false;setBusy(false);}};
  const open=(componentId:string,revision?:number)=>void perform<AppsView>('apps.presentation.open_component',{componentId,...(revision?{revision}:{})},view=>onOpenView?.(view));
  const edit=(componentId:string,revision?:number)=>void perform<{view:AppsView}>('apps.authoring.begin',{mode:'open_saved',componentId,...(revision?{revision}:{})},result=>onOpenView?.(result.view));
  const manage=(kind:string,id:string,action:'rename'|'delete')=>void perform('apps.presentation.manage_saved',{kind,id,action,...(kind==='component'?{expectedRevision:components.find(component=>component.componentId===id)!.revision}:{}),...(action==='rename'?{name:name.trim()}:{})},()=>{window.dispatchEvent(new CustomEvent('apps-library-changed'));setRenaming(undefined);setName('');setNotice(action==='delete'?'库项已移除，已有工作副本与历史构建继续保留。':'名称已更新为新的元数据版本。');});
  const matches=(title:string)=>title.normalize('NFKC').toLocaleLowerCase().includes(query.normalize('NFKC').toLocaleLowerCase());
  const visibleComponents=components.filter(component=>matches(component.title)),visibleAssets=assets.filter(asset=>matches(asset.title));
  const disabled=!sessionId||busy||!!recovery.pending;
  return <section className="apps-library" aria-label="共享组件库" aria-busy={loading}>
    <header className="apps-library-heading"><div><h3>已保存组件 <span className="apps-count">{(loading||readFailed)&&!components.length&&!assets.length?'—':components.length+assets.length}</span></h3><p>{readFailed&&components.length+assets.length?'读取未更新，当前保留上次成功读取的库项。':'只有明确保存的组件和模板才会出现在这里。'}</p></div><button type="button" disabled={loading} onClick={()=>setRevision(value=>value+1)}>{loading?'刷新中…':'刷新'}</button><label className="apps-search"><AppsIcon name="search"/><input aria-label="搜索组件库" value={query} onChange={event=>setQuery(event.target.value)} placeholder="搜索组件与模板"/></label></header>
    {notice?<p className="apps-notice" role="status">{notice}</p>:null}<PresentationRecovery pending={recovery.pending} inspecting={recovery.inspecting} onInspect={()=>void recovery.inspect().then(known=>{if(!known)setNotice('原调用仍未确认；继续只读检查，不会自动重发。');}).catch(error=>setNotice(error instanceof Error?error.message:String(error)))}/>
    {loading&&!components.length&&!assets.length?<div className="apps-empty" role="status"><span className="apps-loading-dot"/>正在读取组件库…</div>:visibleComponents.length||visibleAssets.length?<div className="apps-library-grid">
      {visibleComponents.map(component=><article key={component.componentId} className="apps-library-card"><div className="apps-card-visual"><AppsIcon name="component"/><span>已保存组件</span><span className="apps-badge">版本 {component.revision}</span></div><div className="apps-card-content"><strong className="apps-card-title">{component.title}</strong><p className="apps-card-meta">保存于 <time dateTime={component.savedAt} title={component.savedAt}>{appsDisplayTime(component.savedAt)}</time></p><div className="apps-card-actions"><button className="apps-primary" disabled={disabled} onClick={()=>open(component.componentId)}>在当前会话打开</button><button disabled={disabled} onClick={()=>edit(component.componentId)}>重开编辑</button></div><details className="apps-card-management"><summary>组件管理</summary><div className="apps-card-actions"><button disabled={disabled} onClick={()=>{setRenaming(component.componentId);setName(component.title);}}>重命名</button><button className="apps-danger-text" disabled={disabled} onClick={()=>manage('component',component.componentId,'delete')}>从组件库移除</button></div></details>{renaming===component.componentId?<form className="apps-rename-form" onSubmit={event=>{event.preventDefault();manage('component',component.componentId,'rename');}}><input autoFocus aria-label="组件新名称" value={name} onChange={event=>setName(event.target.value)}/><button className="apps-primary" disabled={busy||!!recovery.pending||!name.trim()}>保存名称</button><button type="button" onClick={()=>setRenaming(undefined)}>取消</button></form>:null}<ComponentHistory key={`${component.componentId}:${component.revision}`} componentId={component.componentId} disabled={disabled} open={open} edit={edit}/></div></article>)}
      {visibleAssets.map(asset=><article key={`${asset.kind}:${asset.assetId}`} className="apps-library-card"><div className="apps-card-visual is-template"><AppsIcon name={asset.kind==='template'?'grid':'component'}/><span>{asset.kind==='template'?'可复用模板':'快捷入口'}</span></div><div className="apps-card-content"><strong className="apps-card-title">{asset.title}</strong><p className="apps-card-meta">{asset.kind==='template'?'打开后在当前会话继续创作':'在当前会话打开保存的展示'}</p><div className="apps-card-actions"><button className="apps-primary" disabled={disabled} onClick={()=>{if(asset.componentId)open(asset.componentId);else void perform<AppsView>('apps.presentation.render_view',{title:asset.title,...(asset.kind==='template'?{templateId:asset.assetId}:asset.binding?{bindings:[asset.binding]}:{})},view=>onOpenView?.(view));}}>明确打开</button><button disabled={disabled} onClick={()=>manage(asset.kind,asset.assetId,'delete')}>移除库入口</button></div></div></article>)}
    </div>:<div className="apps-empty"><span className="apps-empty-icon"><AppsIcon name="component"/></span><h3>{readFailed?'组件库暂时无法读取':query?'没有匹配的组件':'还没有保存的组件'}</h3><p>{readFailed?'请刷新重试。组件与工作副本没有删除。':query?'换个关键词试试，或清空搜索查看全部组件。':'在任意原聊天 @ 应用，让 Agent 创建或编辑组件；满意后明确保存到这里。'}</p>{query?<button onClick={()=>setQuery('')}>清空搜索</button>:null}</div>}
    {!sessionId?<p className="apps-muted apps-library-footnote">请先打开已有聊天，再打开或编辑组件。</p>:null}
  </section>;
}

function ComponentHistory({componentId,disabled,open,edit}:{componentId:string;disabled:boolean;open:(id:string,revision:number)=>void;edit:(id:string,revision:number)=>void}) {
  const [expanded,setExpanded]=useState(false),[versions,setVersions]=useState<ComponentSummary[]>(),[error,setError]=useState('');
  useEffect(()=>{if(!expanded||versions)return;const controller=new AbortController();setError('');appsResource<{revisions:ComponentSummary[]}>('componentHistory',{componentId},controller.signal).then(value=>{if(!controller.signal.aborted)setVersions(value.revisions);}).catch(reason=>{if(!controller.signal.aborted)setError(String(reason.message??reason));});return()=>controller.abort();},[expanded,componentId,versions]);
  return <details className="apps-card-history" onToggle={event=>setExpanded(event.currentTarget.open)}><summary>历史版本</summary>{expanded?<div className="apps-history-list">{error?<p role="status">{error}，收起后展开可重试。</p>:!versions?<p>正在读取历史…</p>:versions.map(version=><div key={version.revision}><div><span>版本 {version.revision} · {version.title}</span><small>{appsDisplayTime(version.savedAt)}</small></div><div className="apps-card-actions"><button disabled={disabled} onClick={()=>open(componentId,version.revision)}>打开此版本</button><button disabled={disabled} onClick={()=>edit(componentId,version.revision)}>从此版本编辑</button></div></div>)}</div>:null}</details>;
}
