/** Version-bound, public DSH 0.2.0-rc.2 inputTriggers adapter. No editor or send implementation. */
export const APPS_REFERENCE_SOURCE='dsh-apps';
export interface NativeOccurrence {occurrenceId:string;source:string;ref:string;label?:string}
export interface NativeAppsInputState {phase:string;draftRev:number;occurrences:readonly NativeOccurrence[];attachmentIds:readonly string[];draft:string}
export interface NativeAppRow {appId:string;displayName:string;runtimeState?:string}
export interface NativeConnectionChoice {connectionId:string;displayName:string}
export interface NativeBindingRequest {sessionId:string;appId:string;connectionId?:string;bindRequestId:string;epoch:number;enabled:boolean;referenceId:string}
export interface NativeBindingReceipt extends NativeBindingRequest {status:'bound'|'needs_connection'|'failed'|'cancelled';connections?:NativeConnectionChoice[];error?:{code:string;message:string}}
export interface NativeReference {kind:'dsh-apps-native-reference';version:1;sessionId:string;appId:string;bindRequestId:string;epoch:number}
export interface NativeReferenceState {referenceId:string;reference:NativeReference;label:string;status:'pending'|'binding'|'bound'|'needs_connection'|'failed'|'removed';epoch:number;connectionId?:string;connections?:NativeConnectionChoice[];message?:string;manualSubmission?:boolean}
export interface NativeAppsTransport {apps(signal:AbortSignal):Promise<NativeAppRow[]>;bind(input:NativeBindingRequest,signal:AbortSignal):Promise<NativeBindingReceipt>;inspect?(sessionId:string,bindRequestId:string,referenceId:string,signal:AbortSignal):Promise<NativeBindingReceipt|null>;serialize(referenceId:string,signal:AbortSignal):Promise<{text:string}>}
export interface NativeCandidate {name:string;label:string;description:string;value:string;section:string}
export interface AppsTriggerSource {trigger:'@';name:string;order:number;candidates(session:{sessionId:string},request:{query:string;signal:AbortSignal}):Promise<NativeCandidate[]>;onPick(input:{candidate:NativeCandidate;session:{sessionId:string};action:'pick'|'drill'}):{insert:{source:string;ref:string;label:string;clipboardText:string}}|undefined;codec:{serialize(referenceId:string,signal:AbortSignal):Promise<string>}}
const nonce=()=>globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random().toString(36).slice(2)}`;
export function parseNativeReference(value:string):NativeReference|undefined {try{const ref=JSON.parse(value);if(ref?.kind==='dsh-apps-native-reference'&&ref.version===1&&typeof ref.sessionId==='string'&&typeof ref.appId==='string'&&typeof ref.bindRequestId==='string'&&Number.isSafeInteger(ref.epoch)&&ref.epoch>=0&&Object.keys(ref).every(key=>['kind','version','sessionId','appId','bindRequestId','epoch'].includes(key)))return ref;}catch{}return;}
/** Pending intent exists before pick; only a published native occurrence permits Host binding. */
export class NativeAppsReferences {
  readonly source:AppsTriggerSource;
  private transport:NativeAppsTransport;private records=new Map<string,NativeReferenceState>();private inputs=new Map<string,{state:NativeAppsInputState;token:object}>();private requests=new Map<string,AbortController>();private hydrating=new Set<string>();private removedWhileHydrating=new Set<string>();private lifetime=new AbortController();private listeners=new Set<()=>void>();private revision=0;
  constructor(transport:NativeAppsTransport){this.transport=transport;this.source={trigger:'@',name:APPS_REFERENCE_SOURCE,order:20,candidates:async(session,request)=>{if(this.lifetime.signal.aborted)return [];const signal=AbortSignal.any([this.lifetime.signal,request.signal]);const apps=await transport.apps(signal);signal.throwIfAborted();const query=request.query.normalize('NFKC').toLocaleLowerCase();return apps.filter(app=>app.runtimeState!=='unavailable'&&`${app.appId} ${app.displayName}`.normalize('NFKC').toLocaleLowerCase().includes(query)).map(app=>({name:app.appId,label:app.displayName,description:'在本聊天启用应用',section:'Apps',value:JSON.stringify({appId:app.appId,displayName:app.displayName,sessionId:session.sessionId})}));},onPick:({candidate,session,action})=>{if(action!=='pick'||this.lifetime.signal.aborted)return;let value:Record<string,unknown>;try{value=JSON.parse(candidate.value);}catch{return;}if(value.sessionId!==session.sessionId||typeof value.appId!=='string'||typeof value.displayName!=='string')return;const reference:NativeReference={kind:'dsh-apps-native-reference',version:1,sessionId:session.sessionId,appId:value.appId,bindRequestId:nonce(),epoch:0},referenceId=JSON.stringify(reference);this.records.set(referenceId,{referenceId,reference,label:value.displayName,status:'pending',epoch:0});this.changed();return {insert:{source:APPS_REFERENCE_SOURCE,ref:referenceId,label:value.displayName,clipboardText:`@${value.displayName}`}};},codec:{serialize:async(referenceId,signal)=>{const ref=parseNativeReference(referenceId);if(!ref)throw new Error('Apps引用身份无效，未发送。');const entry=this.records.get(referenceId);if(entry){if(entry.status!=='bound')throw new Error('Apps绑定尚未确认，请选择连接后再手动发送。');entry.manualSubmission=true;this.changed();}try{const receipt=await transport.serialize(referenceId,AbortSignal.any([signal,this.lifetime.signal]));if(typeof receipt.text!=='string'||!receipt.text)throw new Error('Apps引用序列化未确认，未发送。');return receipt.text;}catch(error){if(entry){entry.manualSubmission=false;this.changed();}throw error;}}}};}
  subscribe=(listener:()=>void)=>{this.listeners.add(listener);return()=>{this.listeners.delete(listener);};};getSnapshot=()=>this.revision;
  private changed(){this.revision++;for(const listener of this.listeners)listener();}
  states(sessionId:string){return [...this.records.values()].filter(entry=>entry.reference.sessionId===sessionId&&entry.status!=='removed');}
  observe(sessionId:string,state:NativeAppsInputState,token:object,disabledReason?:string){
    if(this.lifetime.signal.aborted||disabledReason||!Array.isArray(state.occurrences)||!Number.isSafeInteger(state.draftRev))return;
    const previous=this.inputs.get(sessionId);this.inputs.set(sessionId,{state,token});const present=new Set(state.occurrences.filter(occ=>occ.source===APPS_REFERENCE_SOURCE).map(occ=>occ.ref));
    for(const referenceId of present){const parsed=parseNativeReference(referenceId);if(!parsed||parsed.sessionId!==sessionId)continue;let entry=this.records.get(referenceId);if(!entry){entry={referenceId,reference:parsed,label:state.occurrences.find(occ=>occ.ref===referenceId)?.label??parsed.appId,status:'binding',epoch:parsed.epoch};this.records.set(referenceId,entry);void this.restore(entry);}if(entry.status==='removed'){entry.status='failed';entry.message='原Apps绑定已解除；请重新明确选择应用后再手动发送。';this.changed();}if(entry.manualSubmission&&previous&&!previous.state.occurrences.some(occ=>occ.ref===referenceId))entry.manualSubmission=false;if(entry.status==='pending')void this.bind(entry,true);}
    if(previous?.token!==token||previous.state.draftRev===state.draftRev)return;
    for(const occ of previous.state.occurrences){if(occ.source!==APPS_REFERENCE_SOURCE||present.has(occ.ref))continue;const entry=this.records.get(occ.ref);if(!entry||entry.manualSubmission||entry.status==='removed')continue;if(state.phase==='adjudicating'||state.phase==='submitting')continue;void this.remove(occ.ref);}
  }
  release(sessionId:string,token:object){if(this.inputs.get(sessionId)?.token===token)this.inputs.delete(sessionId);}
  async choose(referenceId:string,connectionId:string){const entry=this.records.get(referenceId);if(!entry||entry.status!=='needs_connection'||!entry.connections?.some(item=>item.connectionId===connectionId))return;entry.epoch++;entry.connectionId=connectionId;await this.bind(entry,true);}
  async remove(referenceId:string){const entry=this.records.get(referenceId);if(!entry||entry.status==='removed')return;if(this.hydrating.has(referenceId)){entry.status='removed';this.removedWhileHydrating.add(referenceId);this.changed();return;}entry.epoch++;entry.status='removed';this.requests.get(referenceId)?.abort();this.changed();await this.bind(entry,false);}
  private async restore(entry:NativeReferenceState){
    this.hydrating.add(entry.referenceId);this.changed();try{const receipt=await this.transport.inspect?.(entry.reference.sessionId,entry.reference.bindRequestId,entry.referenceId,this.lifetime.signal);if(this.lifetime.signal.aborted)return;if(!receipt||receipt.referenceId!==entry.referenceId||receipt.sessionId!==entry.reference.sessionId||receipt.appId!==entry.reference.appId||receipt.bindRequestId!==entry.reference.bindRequestId||!Number.isSafeInteger(receipt.epoch)||receipt.epoch<entry.reference.epoch)throw new Error('原Apps引用未找到有效绑定记录；请重新明确选择应用。');entry.epoch=receipt.epoch;entry.connectionId=receipt.connectionId;entry.connections=receipt.connections;entry.status=receipt.status==='bound'&&receipt.enabled&&receipt.connectionId?'bound':receipt.status==='needs_connection'?'needs_connection':'failed';entry.message=receipt.status==='cancelled'?'原Apps绑定已解除；请重新明确选择应用后再手动发送。':receipt.error?.message;}catch(error){if(!this.lifetime.signal.aborted){entry.status='failed';entry.message=error instanceof Error?error.message:String(error);}}finally{this.hydrating.delete(entry.referenceId);const removed=this.removedWhileHydrating.delete(entry.referenceId);if(removed&&entry.status!=='failed'&&entry.status!=='removed'&&!this.lifetime.signal.aborted)void this.remove(entry.referenceId);this.changed();}
  }
  private async bind(entry:NativeReferenceState,enabled:boolean){
    const epoch=entry.epoch,controller=new AbortController();this.requests.get(entry.referenceId)?.abort();this.requests.set(entry.referenceId,controller);if(enabled){entry.status='binding';entry.message=undefined;this.changed();}
    const request:NativeBindingRequest={sessionId:entry.reference.sessionId,appId:entry.reference.appId,bindRequestId:entry.reference.bindRequestId,epoch,enabled,referenceId:entry.referenceId,...(entry.connectionId?{connectionId:entry.connectionId}:{})};
    try{const receipt=await this.transport.bind(request,AbortSignal.any([controller.signal,this.lifetime.signal]));if(controller.signal.aborted||this.lifetime.signal.aborted||entry.epoch!==epoch)return;if(receipt.sessionId!==request.sessionId||receipt.appId!==request.appId||receipt.bindRequestId!==request.bindRequestId||receipt.epoch!==epoch||receipt.referenceId!==request.referenceId||receipt.status==='bound'&&(!receipt.connectionId||receipt.enabled!==enabled))throw new Error('Apps绑定回执身份不一致。');if(!enabled){entry.status='removed';return;}entry.status=receipt.status==='bound'?'bound':receipt.status==='needs_connection'?'needs_connection':'failed';entry.connectionId=receipt.connectionId;entry.connections=receipt.connections;entry.message=receipt.error?.message;}
    catch(error){if(entry.epoch!==epoch||this.lifetime.signal.aborted)return;entry.status=enabled?'failed':'removed';entry.message=error instanceof Error?error.message:String(error);}
    finally{if(this.requests.get(entry.referenceId)===controller)this.requests.delete(entry.referenceId);this.changed();}
  }
  dispose(){if(this.lifetime.signal.aborted)return;this.lifetime.abort();for(const request of this.requests.values())request.abort();this.requests.clear();this.inputs.clear();this.records.clear();this.listeners.clear();}
}
export const browserNativeAppsTransport:NativeAppsTransport={
  async apps(signal){const response=await fetch('/api/dsh-apps?resource=apps',{credentials:'same-origin',signal});const value=await response.json() as {apps?:NativeAppRow[]};if(!response.ok||!Array.isArray(value.apps))throw new Error('Apps目录暂不可用。');return value.apps;},
  async bind(input,signal){const response=await fetch('/api/dsh-apps',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'nativeBinding',...input}),signal});const value=await response.json();if(!response.ok)throw new Error(value?.error?.message??'Apps绑定未确认。');return value;},
  async serialize(referenceId,signal){const response=await fetch('/api/dsh-apps',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'serializeNativeReference',referenceId}),signal});const value=await response.json();if(!response.ok)throw new Error(value?.error?.message??'Apps引用尚未可调用。');return value;},
  async inspect(sessionId,bindRequestId,referenceId,signal){const query=new URLSearchParams({resource:'nativeBinding',sessionId,bindRequestId,referenceId}),response=await fetch(`/api/dsh-apps?${query}`,{credentials:'same-origin',signal}),value=await response.json();if(!response.ok)throw new Error(value?.error?.message??'原Apps引用记录暂不可读。');return value;},
};
