import React,{useEffect,useRef,useState} from 'react';
import type {AuthoringView} from '../../app-presentation/src/authoring-types.ts';
import type {AppsComponent,AppsView} from '../../app-presentation/src/types.ts';
import {appsResource} from './api.ts';
import {PresentationRecovery,usePresentationRecovery} from './presentation-recovery.tsx';
/** Save pins the displayed revision and advances this working copy's target only after a confirmed save. */
export function AppsSaveControls({sessionId,viewId,onOpenView,refreshKey=0}:{sessionId:string;viewId:string;onOpenView?:(view:AppsView)=>void;refreshKey?:number}){
  const recovery=usePresentationRecovery();
  const [view,setView]=useState<AuthoringView&{baseRevisionAtOpen?:number;selectedSourceRevision?:number}>(),[title,setTitle]=useState(''),[request,setRequest]=useState(''),[mode,setMode]=useState<'save_as'|'update'>('save_as'),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[conflict,setConflict]=useState(false),[revision,setRevision]=useState(0);const inFlight=useRef(false),owner=useRef(`${sessionId}:${viewId}`),formOwner=useRef('');owner.current=`${sessionId}:${viewId}`;
  useEffect(()=>{const controller=new AbortController();setView(current=>current?.viewId===viewId&&current.ownerSessionId===sessionId?current:undefined);appsResource<AuthoringView>('view',{sessionId,viewId},controller.signal).then(value=>{if(!controller.signal.aborted){setView(value);if(formOwner.current!==`${sessionId}:${viewId}`){formOwner.current=`${sessionId}:${viewId}`;setTitle(value.title);setMode(value.sourceComponentId?'update':'save_as');}}}).catch(error=>{if(!controller.signal.aborted)setNotice(error instanceof Error?error.message:String(error));});return()=>controller.abort();},[sessionId,viewId,revision,refreshKey]);
  useEffect(()=>{const receive=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.sessionId===sessionId&&detail?.viewId===viewId){if(event.type==='apps-publication-discovered')setView(value=>value?{...value,pendingPublicationId:detail.publicationId}:value);setRevision(value=>value+1);}};window.addEventListener('apps-authoring-published',receive);window.addEventListener('apps-display-ready',receive);window.addEventListener('apps-publication-discovered',receive);return()=>{window.removeEventListener('apps-authoring-published',receive);window.removeEventListener('apps-display-ready',receive);window.removeEventListener('apps-publication-discovered',receive);};},[sessionId,viewId]);
  const saveable=view?.validationStatus==='verified'&&!view.pendingPublicationId;
  const save=async()=>{if(!view||!saveable||inFlight.current||recovery.pending||!title.trim())return;const target=owner.current;inFlight.current=true;setBusy(true);setNotice('');try{await recovery.run<AppsComponent>(sessionId,'apps.authoring.save_component',{viewId,expectedViewRevision:view.viewRevision,userRequest:request.trim()||`明确保存组件“${title.trim()}”`,title:title.trim(),mode,...(mode==='update'?{componentId:view.sourceComponentId!,expectedRevision:view.baseRevision??view.baseRevisionAtOpen!}:{})},saved=>{window.dispatchEvent(new CustomEvent('apps-library-changed',{detail:{sessionId,viewId,component:saved}}));if(owner.current===target){setView(current=>({...current??saved.view,title:saved.view.title,sourceComponentId:saved.view.sourceComponentId,baseRevision:saved.view.baseRevision,baseRevisionAtOpen:saved.view.baseRevisionAtOpen,selectedSourceRevision:saved.view.selectedSourceRevision}) as AuthoringView);setMode('update');setNotice(`已明确保存“${saved.title}”版本 ${saved.revision}。`);setConflict(false);}});}catch(error){if(owner.current===target){setNotice(error instanceof Error?error.message:String(error));setConflict(['COMPONENT_CONFLICT','VIEW_CONFLICT'].includes(String((error as {code?:string}).code)));}}finally{inFlight.current=false;setBusy(false);}};
  const latest=async()=>{if(!view?.sourceComponentId||inFlight.current||recovery.pending)return;const target=owner.current;inFlight.current=true;setBusy(true);try{await recovery.run<AppsView>(sessionId,'apps.presentation.open_component',{componentId:view.sourceComponentId},latest=>{if(owner.current===target){onOpenView?.(latest);setNotice('最新版已单独打开，当前工作副本和更新基线继续保留。');}});}catch(error){if(owner.current===target)setNotice(error instanceof Error?error.message:String(error));}finally{inFlight.current=false;setBusy(false);}};
  return <section aria-label="明确保存组件" style={{borderTop:'1px solid #bfd2e9',paddingTop:16,marginTop:16}}><h3>保存组件</h3><p>满意后保存到组件库，之后可以重新打开和继续编辑。</p>{notice?<p role="status">{notice}</p>:null}<PresentationRecovery pending={recovery.pending} inspecting={recovery.inspecting} onInspect={()=>void recovery.inspect().then(known=>{if(!known)setNotice('原调用仍未确认；继续只读检查，不会自动重发。');}).catch(error=>setNotice(error instanceof Error?error.message:String(error)))}/><form className="apps-save-form" onSubmit={event=>{event.preventDefault();void save();}} style={{display:'flex',flexWrap:'wrap',gap:8}}><input aria-label="保存组件名称" placeholder="组件名称" value={title} onChange={event=>setTitle(event.target.value)}/><input aria-label="明确保存要求" placeholder="保存备注（可选）" value={request} onChange={event=>setRequest(event.target.value)}/><select aria-label="保存方式" value={mode} onChange={event=>setMode(event.target.value as 'save_as'|'update')}><option value="save_as">另存为组件</option>{view?.sourceComponentId?<option value="update">更新原组件</option>:null}</select><button className="apps-primary" disabled={busy||!!recovery.pending||!saveable||!title.trim()}>{busy?'正在保存…':'保存到组件库'}</button></form>{view?.pendingPublicationId?<p>新设计正在加载，确认展示后才能保存。</p>:view?.validationStatus!=='verified'?<p>此工作副本尚未通过正式预览和发布，暂时不能保存。</p>:null}{conflict?<div className="apps-save-conflict"><p>已有组件或当前展示已经更新。你的工作副本仍保留，请选择如何继续。</p><button onClick={()=>setNotice('工作副本已保留，更新基线未自动修改。')}>保留工作副本</button><button disabled={busy||!!recovery.pending||!view?.sourceComponentId} onClick={()=>void latest()}>查看原组件最新版</button><button onClick={()=>{setMode('save_as');setConflict(false);setNotice('选择另存，原组件历史继续保留。');}}>改为另存</button></div>:null}<details className="apps-save-version"><summary>保存版本信息</summary><p>来源版本 {view?.selectedSourceRevision??'工作副本'} · 更新基线 {view?.baseRevision??view?.baseRevisionAtOpen??'新组件'} · 视图版本 {view?.viewRevision??'—'}</p></details></section>;
}
