import React,{useEffect,useRef,useState} from 'react';
import {AppsDirectory} from './directory.tsx';
import {AppsLibrary} from './library.tsx';
import {AppsNativeView} from './view.tsx';
import {AppsSaveControls} from './save-controls.tsx';
import {appsAuthoring,appsResource} from './api.ts';
import {PresentationRecovery,usePresentationRecovery} from './presentation-recovery.tsx';
import type {AppsView} from '../../app-presentation/src/types.ts';
import {observeCurrentSession,type SessionSnapshot} from '../../dsh-plugin/client/session-selection.ts';
import {ownedWorkspaceIntent} from '../../dsh-plugin/client/workspace-intent.ts';
import {announceAppsPublication,publicationKey,readOwnedPendingPublication,useOwnedAppsViews} from './native-publication.tsx';
/** Views live in the Apps plugin area; original chat selection and Composer stay authoritative. */
export function AppsWorkspace(props:{useSessions?:(selector:(state:SessionSnapshot)=>string|undefined)=>string|undefined;usePanelInfo?:(selector:(state:{activePanelId:string|null})=>string|null)=>string|null;currentSessionId?:string;onReturn?:(sessionId:string)=>void}) {
  const recovery=usePresentationRecovery();
  const sessionId=props.useSessions?props.useSessions(observeCurrentSession):props.currentSessionId;
  const pageVisible=props.usePanelInfo?props.usePanelInfo(state=>state.activePanelId)==='hallmark-apps':true;
  const [views,setViews]=useState<AppsView[]>([]),[selected,setSelected]=useState<string>(),[hidden,setHidden]=useState<string[]>([]),[closing,setClosing]=useState<string>(),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),inFlight=useRef(false),owner=useRef(sessionId),visiblePage=useRef(pageVisible);owner.current=sessionId;visiblePage.current=pageVisible;
  const [summaryRevision,setSummaryRevision]=useState(0);
  const open=(view:AppsView)=>{if(view.ownerSessionId!==owner.current){setNotice('此组件属于其他聊天，请切回原会话。');return;}setViews(rows=>[...rows.filter(row=>row.viewId!==view.viewId),view]);setHidden(rows=>rows.filter(id=>id!==view.viewId));setSelected(view.viewId);setNotice('');setSummaryRevision(value=>value+1);};
  const consumed=useRef(new Set<string>()),pending=useRef<{sessionId:string;viewId:string;publicationId:string}>();
  useEffect(()=>{setViews([]);setSelected(undefined);setHidden([]);setClosing(undefined);},[sessionId]);
  useOwnedAppsViews(sessionId,async(views,signal)=>{setViews(views);if(pending.current?.sessionId===sessionId&&views.some(view=>view.viewId===pending.current?.viewId&&view.pendingPublicationId===pending.current.publicationId))return;pending.current=undefined;
    for(const view of views){if(!sessionId||!view.pendingPublicationId)continue;const key=publicationKey(sessionId,view.viewId,view.pendingPublicationId);if(consumed.current.has(key))continue;
      const publication=await readOwnedPendingPublication(sessionId,view,signal);if(signal.aborted||owner.current!==sessionId)return;consumed.current.add(key);if(!publication)continue;
      pending.current={sessionId,viewId:view.viewId,publicationId:view.pendingPublicationId};announceAppsPublication(sessionId,view.viewId,view.pendingPublicationId);return;
    }
  },error=>setNotice(error instanceof Error?error.message:String(error)),revision,pageVisible);
  useEffect(()=>{const controller=new AbortController();const receive=()=>{const intent=ownedWorkspaceIntent.take();if(!intent)return;if(intent.sessionId!==owner.current){setNotice('会话已切换，请切回组件所属聊天后重新打开。');return;}appsResource<AppsView>('view',{sessionId:intent.sessionId,viewId:intent.viewId},controller.signal).then(view=>{if(!controller.signal.aborted&&owner.current===intent.sessionId)open(view);}).catch(error=>{if(!controller.signal.aborted&&owner.current===intent.sessionId)setNotice(error instanceof Error?error.message:String(error));});};const off=ownedWorkspaceIntent.subscribe(receive);receive();return()=>{controller.abort();off();};},[sessionId]);
  const create=async(mode:'new'|'edit'='new',viewId?:string)=>{if(!sessionId||inFlight.current||recovery.pending)return;const target=sessionId;inFlight.current=true;setBusy(true);try{await recovery.run<{view:AppsView;draft:{workspacePath:string};attempt:{attemptId:string;epoch:number}}>(target,'apps.authoring.begin',{mode,...(mode==='edit'?{viewId:viewId!}:{title:'新组件'})},value=>{if(owner.current===target){open(value.view);setNotice(`工作副本已${mode==='edit'?'重开':'新建'}。返回原聊天，让 Agent 继续设计、构建和预览；满意后再明确保存。`);}});}catch(error){if(owner.current===target)setNotice(error instanceof Error?error.message:String(error));}finally{inFlight.current=false;setBusy(false);}};
  const close=async(view:AppsView,action:'keep'|'discard')=>{if(!sessionId||inFlight.current)return;const target=sessionId;inFlight.current=true;setBusy(true);try{await appsAuthoring(target,'closeDraft',{viewId:view.viewId,action});if(owner.current===target){setHidden(ids=>[...ids,view.viewId]);if(selected===view.viewId)setSelected(undefined);setClosing(undefined);setNotice(action==='keep'?'工作副本已关闭并保留，可从当前会话视图重开。':'工作副本已丢弃，组件库和既有成功构建仍保留。');}}catch(error){if(owner.current===target)setNotice(error instanceof Error?error.message:String(error));}finally{inFlight.current=false;setBusy(false);}};
  const current=views.find(view=>view.viewId===selected&&view.ownerSessionId===sessionId);
  const visible=views.filter(view=>!hidden.includes(view.viewId));
  const navigation=<nav aria-label="当前会话组件视图" className="apps-local-tabs"><button className="apps-library-tab" aria-pressed={!current} onClick={()=>setSelected(undefined)}>组件库</button>{visible.map(view=><span key={view.viewId} className={`apps-local-tab${selected===view.viewId?' is-active':''}`}><button aria-pressed={selected===view.viewId} title={view.title} onClick={()=>setSelected(view.viewId)}>{view.title}</button><button className="apps-tab-close" aria-label={`关闭${view.title}`} onClick={()=>setClosing(view.viewId)}>×</button></span>)}<button className="apps-tab-add" aria-label="新建组件工作副本" title="新建组件工作副本" disabled={!sessionId||busy||!!recovery.pending} onClick={()=>void create()}>+</button></nav>;
  return <AppsDirectory currentSessionId={sessionId} onReturn={props.onReturn} onOpenView={open} onCreate={()=>void create()} creationDisabled={!sessionId||busy||!!recovery.pending} onRefreshViews={()=>setRevision(value=>value+1)} summaryRefreshKey={summaryRevision} navigation={navigation}>
    {notice?<p className="apps-notice" role="status">{notice}</p>:null}<PresentationRecovery pending={recovery.pending} inspecting={recovery.inspecting} onInspect={()=>void recovery.inspect().then(known=>{if(!known)setNotice('原调用仍未确认；继续只读检查，不会自动重发。');}).catch(error=>setNotice(error instanceof Error?error.message:String(error)))}/>
    {closing?<section className="apps-close-prompt apps-panel" aria-label="关闭工作副本"><h3>关闭工作副本</h3><p>关闭视图不删除组件库。选择保留或丢弃此工作副本。</p><div className="apps-card-actions"><button className="apps-primary" disabled={busy||!!recovery.pending} onClick={()=>{const view=views.find(view=>view.viewId===closing);if(view)void close(view,'keep');}}>关闭并保留</button><button className="apps-danger-text" disabled={busy||!!recovery.pending} onClick={()=>{const view=views.find(view=>view.viewId===closing);if(view)void close(view,'discard');}}>丢弃工作副本</button><button onClick={()=>setClosing(undefined)}>取消</button><button onClick={()=>{setHidden(ids=>[...ids,closing]);if(selected===closing)setSelected(undefined);setClosing(undefined);}}>只隐藏展示视图</button></div></section>:null}
    <section hidden={!!current} className="apps-library-pane"><div className="apps-workbench-intro"><div><h2>组件库</h2><p>保存常用组件，随时在当前聊天打开和继续编辑。</p></div><button className="apps-primary" disabled={!sessionId||busy||!!recovery.pending} onClick={()=>void create()}>新建组件工作副本</button></div><AppsLibrary sessionId={sessionId} onOpenView={open} refreshKey={revision}/></section>
    {current&&sessionId&&pageVisible?<section className="apps-open-component"><AppsNativeView key={`${sessionId}:${current.viewId}`} sessionId={sessionId} viewId={current.viewId} isCurrentOwner={()=>owner.current===sessionId&&visiblePage.current}/><div className="apps-editor-actions"><p>在原聊天继续描述修改，Agent 会构建并预览新的设计。</p><button disabled={busy||!!recovery.pending} onClick={()=>void create('edit',current.viewId)}>重开此工作副本编辑</button></div><div className="apps-save-panel"><AppsSaveControls sessionId={sessionId} viewId={current.viewId} onOpenView={open}/></div></section>:null}
    {hidden.length?<details className="apps-closed-views"><summary>已关闭展示视图（{hidden.length}）</summary><div className="apps-card-actions">{views.filter(view=>hidden.includes(view.viewId)).map(view=><button key={view.viewId} onClick={()=>open(view)}>{view.title}</button>)}</div></details>:null}
  </AppsDirectory>;
}
