import React,{useEffect,useRef,useState} from 'react';
import {AppsDirectory} from './directory.tsx';
import {AppsLibrary} from './library.tsx';
import {AppsNativeView} from './view.tsx';
import {AppsSaveControls} from './save-controls.tsx';
import {WorkbenchBoard} from './workbench-board.tsx';
import {MaterialLibrary} from './material-library.tsx';
import {appsAuthoring,appsResource} from './api.ts';
import {PresentationRecovery,usePresentationRecovery} from './presentation-recovery.tsx';
import type {AppsView,Workbench,WorkbenchInstance,WorkbenchSavedComponent} from '../../app-presentation/src/types.ts';
import {observeCurrentSession,type SessionSnapshot} from '../../dsh-plugin/client/session-selection.ts';
import {ownedWorkspaceIntent} from '../../dsh-plugin/client/workspace-intent.ts';
import {announceAppsPublication,publicationKey,readOwnedPendingPublication,updateOwnedAppsView,useOwnedAppsViews} from './native-publication.tsx';
import {APPS_WORKSPACE_TABS_STYLES} from './workspace-tabs.css.ts';
import {CurrentComponentWorkbenchAction} from './workbench-component-actions.tsx';
/** Views live in the Apps plugin area; original chat selection and Composer stay authoritative. */
export function AppsWorkspace(props:{useSessions?:(selector:(state:SessionSnapshot)=>string|undefined)=>string|undefined;usePanelInfo?:(selector:(state:{activePanelId:string|null})=>string|null)=>string|null;currentSessionId?:string;onReturn?:(sessionId:string)=>void;onPrepareDataSource?:(sessionId:string,text:string)=>void|Promise<void>}) {
  const recovery=usePresentationRecovery();
  const sessionId=props.useSessions?props.useSessions(observeCurrentSession):props.currentSessionId;
  const pageVisible=props.usePanelInfo?props.usePanelInfo(state=>state.activePanelId)==='hallmark-apps':true;
  const [views,setViews]=useState<AppsView[]>([]),[selected,setSelected]=useState<string>(),[closing,setClosing]=useState<string>(),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[revision,setRevision]=useState(0),inFlight=useRef(false),owner=useRef(sessionId),visiblePage=useRef(pageVisible);owner.current=sessionId;visiblePage.current=pageVisible;
  const [summaryRevision,setSummaryRevision]=useState(0);
  const [currentWorkbench,setCurrentWorkbench]=useState<Workbench>();
  const [appId,setAppId]=useState('hallmark'),[localTab,setLocalTab]=useState<'workbench'|'materials'|'saved'|'view'|'instance'>('workbench'),[materialsOpen,setMaterialsOpen]=useState(false),[editingInstance,setEditingInstance]=useState<WorkbenchInstance>(),[workbenchRevision,setWorkbenchRevision]=useState(0),[highlightId,setHighlightId]=useState<string>();
  const [instanceTabs,setInstanceTabs]=useState<WorkbenchInstance[]>([]),[selectedInstance,setSelectedInstance]=useState<string>();
  const boardRef=useRef(currentWorkbench),appOwner=useRef(appId);appOwner.current=appId;
  const acceptWorkbench=(next:Workbench)=>{if(next.appId!==appOwner.current)return;const previous=boardRef.current;if(previous?.appId===next.appId&&previous.revision>next.revision)return;boardRef.current=next;setCurrentWorkbench(next);};
  const [savedOpen,setSavedOpen]=useState(false);
  const tabState=useRef({keys:[] as string[],active:'workbench'});
  tabState.current={keys:['workbench',...(materialsOpen?['materials']:[]),...(savedOpen?['saved']:[]),...instanceTabs.map(instance=>'instance:'+instance.instanceId),...views.filter(view=>view.panelState!=='closed').map(view=>'view:'+view.viewId)],active:localTab==='view'&&selected?'view:'+selected:localTab==='instance'&&selectedInstance?'instance:'+selectedInstance:localTab};
  const activateTab=(key:string)=>{if(key.startsWith('view:')){setSelected(key.slice(5));setLocalTab('view');}else if(key.startsWith('instance:')){setSelected(undefined);setSelectedInstance(key.slice(9));setLocalTab('instance');}else{setSelected(undefined);setLocalTab(key==='materials'?'materials':key==='saved'?'saved':'workbench');}};
  const selectAdjacentTab=(key:string)=>{const {keys,active}=tabState.current;if(active!==key)return;const index=keys.indexOf(key);activateTab(keys[index+1]??keys[index-1]??'workbench');};
  const closeLocalTab=(key:'materials'|'saved')=>{selectAdjacentTab(key);if(key==='materials'){setMaterialsOpen(false);setEditingInstance(undefined);}else setSavedOpen(false);};
  const openSaved=()=>{setSavedOpen(true);setSelected(undefined);setLocalTab('saved');};
  const openInstance=(instance:WorkbenchInstance)=>{setInstanceTabs(tabs=>tabs.some(tab=>tab.instanceId===instance.instanceId)?tabs.map(tab=>tab.instanceId===instance.instanceId?instance:tab):[...tabs,instance]);activateTab('instance:'+instance.instanceId);};
  const closeInstance=(instanceId:string)=>{selectAdjacentTab('instance:'+instanceId);setInstanceTabs(tabs=>tabs.filter(tab=>tab.instanceId!==instanceId));};
  const openMaterials=(instance?:WorkbenchInstance)=>{setEditingInstance(instance);setMaterialsOpen(true);setLocalTab('materials');setSelected(undefined);setNotice('');};
  const open=(view:AppsView)=>{if(view.ownerSessionId!==owner.current){setNotice('此组件属于其他聊天，请切回原会话。');return;}if(view.panelState==='closed'){void restore(view);return;}setViews(rows=>rows.some(row=>row.viewId===view.viewId)?rows.map(row=>row.viewId===view.viewId?view:row):[...rows,view]);updateOwnedAppsView(view);setSelected(view.viewId);setLocalTab('view');setNotice('');setSummaryRevision(value=>value+1);};
  const restore=async(view:AppsView)=>{if(!sessionId||view.ownerSessionId!==sessionId||inFlight.current)return;const target=sessionId;inFlight.current=true;setBusy(true);try{const restored=await appsAuthoring<AppsView>(target,'restoreView',{viewId:view.viewId});if(restored.ownerSessionId!==target||restored.viewId!==view.viewId||restored.panelState==='closed')throw new Error('工作副本恢复状态尚未确认。');if(owner.current===target)open(restored);}catch(error){if(owner.current===target)setNotice(error instanceof Error?error.message:String(error));}finally{inFlight.current=false;setBusy(false);}};
  const consumed=useRef(new Set<string>()),pending=useRef<{sessionId:string;viewId:string;publicationId:string}>();
  useEffect(()=>{setViews([]);setSelected(undefined);setClosing(undefined);setLocalTab(tab=>tab==='view'?'workbench':tab);},[sessionId]);
  useEffect(()=>{setEditingInstance(undefined);setHighlightId(undefined);setLocalTab('workbench');setInstanceTabs([]);setSelectedInstance(undefined);setCurrentWorkbench(undefined);boardRef.current=undefined;},[appId]);
  useEffect(()=>{const changed=(event:Event)=>{const detail=(event as CustomEvent).detail;if(detail?.appId===appId&&detail.board)acceptWorkbench(detail.board);};window.addEventListener('apps-workbench-changed',changed);return()=>window.removeEventListener('apps-workbench-changed',changed);},[appId]);
  useOwnedAppsViews(sessionId,async(views,signal)=>{setViews(views);setSelected(current=>views.some(view=>view.viewId===current&&view.panelState==='closed')?undefined:current);if(pending.current?.sessionId===sessionId&&views.some(view=>view.panelState!=='closed'&&view.viewId===pending.current?.viewId&&view.pendingPublicationId===pending.current.publicationId))return;pending.current=undefined;
    for(const view of views){if(!sessionId||view.panelState==='closed'||!view.pendingPublicationId)continue;const key=publicationKey(sessionId,view.viewId,view.pendingPublicationId);if(consumed.current.has(key))continue;
      const publication=await readOwnedPendingPublication(sessionId,view,signal);if(signal.aborted||owner.current!==sessionId)return;consumed.current.add(key);if(!publication)continue;
      pending.current={sessionId,viewId:view.viewId,publicationId:view.pendingPublicationId};announceAppsPublication(sessionId,view.viewId,view.pendingPublicationId);return;
    }
  },error=>setNotice(error instanceof Error?error.message:String(error)),revision,pageVisible);
  useEffect(()=>{const controller=new AbortController();const receive=()=>{const intent=ownedWorkspaceIntent.take();if(!intent)return;if(intent.sessionId!==owner.current){setNotice('会话已切换，请切回组件所属聊天后重新打开。');return;}appsResource<AppsView>('view',{sessionId:intent.sessionId,viewId:intent.viewId},controller.signal).then(view=>{if(!controller.signal.aborted&&owner.current===intent.sessionId)open(view);}).catch(error=>{if(!controller.signal.aborted&&owner.current===intent.sessionId)setNotice(error instanceof Error?error.message:String(error));});};const off=ownedWorkspaceIntent.subscribe(receive);receive();return()=>{controller.abort();off();};},[sessionId]);
  const create=async(mode:'new'|'edit'='new',viewId?:string)=>{if(!sessionId||inFlight.current||recovery.pending)return;const target=sessionId;inFlight.current=true;setBusy(true);try{await recovery.run<{view:AppsView;draft:{workspacePath:string};attempt:{attemptId:string;epoch:number}}>(target,'apps.authoring.begin',{mode,...(mode==='edit'?{viewId:viewId!}:{title:'新组件'})},value=>{if(owner.current===target){open(value.view);setNotice(`工作副本已${mode==='edit'?'重开':'新建'}。返回原聊天，让 Agent 继续设计、构建和预览；满意后再明确保存。`);}});}catch(error){if(owner.current===target)setNotice(error instanceof Error?error.message:String(error));}finally{inFlight.current=false;setBusy(false);}};
  const close=async(view:AppsView)=>{if(!sessionId||inFlight.current||recovery.pending)return;const target=sessionId;inFlight.current=true;setBusy(true);setClosing(view.viewId);setNotice('');try{await appsAuthoring(target,'closeDraft',{viewId:view.viewId,action:'keep'});if(owner.current===target){const closed={...view,panelState:'closed' as const,closedAt:new Date().toISOString()};selectAdjacentTab('view:'+view.viewId);setViews(rows=>rows.map(row=>row.viewId===view.viewId?closed:row));updateOwnedAppsView(closed);setNotice('工作副本已关闭并保留，可从“已关闭工作副本”恢复。');}}catch(error){if(owner.current===target)setNotice(`未能关闭“${view.title}”，标签和内容已保留。${error instanceof Error?error.message:String(error)}`);}finally{inFlight.current=false;setBusy(false);setClosing(current=>current===view.viewId?undefined:current);}};
  const openPinned=async(component:WorkbenchSavedComponent)=>{if(!sessionId){setNotice('请先选择一个聊天，再打开组件。');return;}if(inFlight.current||recovery.pending)return;const target=sessionId,targetApp=appId;inFlight.current=true;setBusy(true);setNotice('');try{await recovery.run<AppsView>(target,'apps.presentation.open_component',{componentId:component.componentId,revision:component.revision,...(currentWorkbench?.context?{context:{storeId:currentWorkbench.context.storeId}}:{})},view=>{if(owner.current===target&&appOwner.current===targetApp)open(view);});}catch(error){if(owner.current===target&&appOwner.current===targetApp)setNotice(error instanceof Error?error.message:String(error));}finally{inFlight.current=false;setBusy(false);}};
  const current=localTab==='view'?views.find(view=>view.viewId===selected&&view.ownerSessionId===sessionId&&view.panelState!=='closed'):undefined;
  const visible=views.filter(view=>view.panelState!=='closed'),closed=views.filter(view=>view.panelState==='closed');
  const navigation=<nav aria-label="应用工作台与组件标签" className="apps-local-tabs"><style>{APPS_WORKSPACE_TABS_STYLES}</style><div className="apps-tabs-scroll"><button className="apps-library-tab" aria-pressed={localTab==='workbench'||localTab==='view'&&!current} onClick={()=>activateTab('workbench')}>工作台</button>{materialsOpen?<span className={`apps-local-tab${localTab==='materials'?' is-active':''}`}><button aria-pressed={localTab==='materials'} onClick={()=>activateTab('materials')}>素材库</button><button className="apps-tab-close" aria-label="关闭素材库" title="关闭素材库" onClick={()=>closeLocalTab('materials')}>×</button></span>:null}{savedOpen?<span className={`apps-local-tab${localTab==='saved'?' is-active':''}`}><button aria-pressed={localTab==='saved'} onClick={openSaved}>我的组件与模板</button><button className="apps-tab-close" aria-label="关闭我的组件与模板" title="关闭我的组件与模板" onClick={()=>closeLocalTab('saved')}>×</button></span>:null}{instanceTabs.map(instance=><span key={instance.instanceId} className={`apps-local-tab${localTab==='instance'&&selectedInstance===instance.instanceId?' is-active':''}`}><button aria-pressed={localTab==='instance'&&selectedInstance===instance.instanceId} title={instance.title} onClick={()=>activateTab('instance:'+instance.instanceId)}>{currentWorkbench?.instances.find(item=>item.instanceId===instance.instanceId)?.title??instance.title}</button><button className="apps-tab-close" aria-label={`关闭${instance.title}`} title="关闭标签页" onClick={()=>closeInstance(instance.instanceId)}>×</button></span>)}{visible.map(view=><span key={view.viewId} className={`apps-local-tab${localTab==='view'&&selected===view.viewId?' is-active':''}`} aria-busy={closing===view.viewId}><button aria-pressed={localTab==='view'&&selected===view.viewId} title={view.title} onClick={()=>activateTab('view:'+view.viewId)}>{view.title}</button><button className="apps-tab-close" aria-label={`关闭${view.title}`} title={closing===view.viewId?'正在关闭…':'关闭并保留工作副本'} disabled={busy||!!recovery.pending} onClick={()=>void close(view)}>{closing===view.viewId?'…':'×'}</button></span>)}</div><button className="apps-tab-add" aria-label="新建组件工作副本" title="新建组件工作副本" disabled={!sessionId||busy||!!recovery.pending} onClick={()=>void create()}>+</button></nav>;
  return <AppsDirectory currentSessionId={sessionId} onAppChange={setAppId} onReturn={props.onReturn} onOpenView={open} onCreate={()=>void create()} creationDisabled={!sessionId||busy||!!recovery.pending} onRefreshViews={()=>{setRevision(value=>value+1);setWorkbenchRevision(value=>value+1);}} summaryRefreshKey={summaryRevision} navigation={navigation}>
    {notice?<p className="apps-notice" role="status">{notice}</p>:null}<PresentationRecovery pending={recovery.pending} inspecting={recovery.inspecting} onInspect={()=>void recovery.inspect().then(known=>{if(!known)setNotice('原调用仍未确认；继续只读检查，不会自动重发。');}).catch(error=>setNotice(error instanceof Error?error.message:String(error)))}/>
    <section hidden={localTab!=='workbench'&&!(localTab==='view'&&!current)} className="apps-library-pane"><WorkbenchBoard key={appId} appId={appId} snapshot={currentWorkbench} active={localTab==='workbench'&&pageVisible} onAdd={()=>openMaterials()} onOpenSaved={openSaved} onOpenInstance={openInstance} onOpenComponent={component=>void openPinned(component)} onConfigure={openMaterials} highlightId={highlightId} revision={workbenchRevision} onChange={acceptWorkbench}/></section>
    {localTab==='instance'&&selectedInstance?<section className="apps-open-component"><WorkbenchBoard key={`${appId}:${selectedInstance}`} appId={appId} snapshot={currentWorkbench} detailInstanceId={selectedInstance} active={pageVisible} onAdd={()=>openMaterials()} onOpenSaved={openSaved} onConfigure={openMaterials} onReturn={()=>activateTab('workbench')} revision={workbenchRevision} onChange={acceptWorkbench}/></section>:null}
    {localTab==='saved'?<section className="apps-library-pane"><div className="apps-workbench-intro"><h2>我的组件</h2><button onClick={()=>activateTab('workbench')}>返回工作台</button></div><AppsLibrary appId={appId} sessionId={sessionId} onOpenView={open} refreshKey={revision} context={currentWorkbench?.context} pinnedComponents={currentWorkbench?.savedComponents} onAdded={acceptWorkbench}/></section>:null}
    {materialsOpen?<section hidden={localTab!=='materials'}><MaterialLibrary key={`${appId}:${editingInstance?.instanceId??'new'}`} appId={appId} sessionId={sessionId} initial={editingInstance} onOpenSaved={openSaved} currentWorkbench={currentWorkbench} onContextChange={board=>{setCurrentWorkbench(board);setWorkbenchRevision(value=>value+1);}} active={localTab==='materials'&&pageVisible} onReturn={props.onReturn} onPrepareDataSource={props.onPrepareDataSource} onComplete={(instance,board)=>{setCurrentWorkbench(board);setHighlightId(instance.instanceId);setWorkbenchRevision(value=>value+1);setLocalTab('workbench');setNotice(editingInstance?'组件配置已保存。':'组件已添加到工作台。');}}/></section>:null}
    {current&&sessionId&&pageVisible?<section className="apps-open-component"><CurrentComponentWorkbenchAction key={`${appId}:${sessionId}:${current.viewId}`} appId={appId} sessionId={sessionId} view={current} onAdded={acceptWorkbench} onShowWorkbench={()=>activateTab('workbench')}/><AppsNativeView key={`${sessionId}:${current.viewId}`} sessionId={sessionId} viewId={current.viewId} isCurrentOwner={()=>owner.current===sessionId&&visiblePage.current}/><details className="apps-component-edit-options"><summary>编辑与另存为</summary><div className="apps-editor-actions"><p>在原聊天继续描述修改，Agent 会构建并预览新的设计。</p><button disabled={busy||!!recovery.pending} onClick={()=>void create('edit',current.viewId)}>重开此工作副本编辑</button></div><div className="apps-save-panel"><AppsSaveControls sessionId={sessionId} viewId={current.viewId} onOpenView={open} refreshKey={summaryRevision}/></div></details></section>:null}
    {closed.length?<details className="apps-closed-views"><summary>已关闭工作副本（{closed.length}）</summary><div className="apps-card-actions">{closed.map(view=><button key={view.viewId} disabled={busy||!!recovery.pending} aria-label={`恢复${view.title}`} onClick={()=>void restore(view)}>{view.title}</button>)}</div></details>:null}
  </AppsDirectory>;
}
